"""
Export endpoints: JSON, YAML, SDK config, character sheet (text).
"""

import json
import yaml
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import PlainTextResponse, JSONResponse
from sqlalchemy.orm import Session

from api.db import get_db, CustomPersona, WorkspaceMember, User
from api.personas import _persona_to_vector, _get_persona_or_404, _jsonify
from api.auth import get_current_user

from persona_math.compiler import compile_all_platforms, compile_all_tiers, SUPPORTED_PLATFORMS
from persona_math.ceid import ceid_full_diagnostic

router = APIRouter(prefix="/workspaces/{workspace_id}/personas", tags=["export"])


@router.get("/{persona_id}/export")
def export_persona(
    workspace_id: str, persona_id: str,
    format: str = "json",
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    _assert_member(db, workspace_id, user.id)
    p = _get_persona_or_404(db, workspace_id, persona_id)
    P = _persona_to_vector(p)

    if format == "json":
        payload = _jsonify(_build_export_payload(p, P))
        return JSONResponse(content=payload)

    elif format == "yaml":
        payload = _jsonify(_build_export_payload(p, P))
        content = yaml.dump(payload, allow_unicode=True, sort_keys=False)
        return PlainTextResponse(content=content, media_type="application/x-yaml")

    elif format == "sdk":
        by_platform = compile_all_platforms(P, persona_id=persona_id)
        lines = [
            f'"""',
            f'HPEP Studio — SDK export for persona: {p.name}',
            f'CEID Score: {p.ceid_score}',
            f'"""',
            f'import hpep',
            f'',
            f'# Re-create persona from block spec',
            f'persona = hpep.Persona(',
            f'    name={p.name!r},',
            f'    blocks={json.dumps(p.get_blocks(), indent=8)},',
            f')',
            f'',
            f'# Ready-to-use system prompts:',
        ]
        for platform, data in by_platform.items():
            snippet = data.get("standard", {}).get("system_instruction", "")[:120]
            lines.append(f'# {platform}: {snippet!r}...')
        content = "\n".join(lines)
        return PlainTextResponse(content=content, media_type="text/x-python")

    elif format == "character-sheet":
        sheet = _build_character_sheet(p, P)
        return {"character_sheet": sheet, "persona_id": p.id, "name": p.name}

    else:
        raise HTTPException(400, f"Unknown format '{format}'. Choose: json, yaml, sdk, character-sheet")


def _build_export_payload(p: CustomPersona, P) -> dict:
    try:
        diag = ceid_full_diagnostic(P)
    except Exception:
        diag = {}
    compiled = compile_all_platforms(P, persona_id=p.id)
    return {
        "schema": "hpep-studio-v1",
        "persona": {
            "id":          p.id,
            "name":        p.name,
            "description": p.description,
            "blocks":      p.get_blocks(),
            "k_overrides": p.get_k_overrides(),
            "ceid":        diag,
            "version":     p.version,
            "is_public":   p.is_public,
        },
        "compiled": compiled,
    }


def _build_character_sheet(p: CustomPersona, P) -> str:
    blocks = p.get_blocks()
    block_names = {
        1: "Power / Instrumental Rationality",
        2: "Strategic Planning",
        3: "Realist Epistemology",
        4: "Rhetoric / Persuasion",
        5: "Psychological Depth",
        6: "Temporal Reasoning",
        7: "Systemic Analysis",
        8: "Cognitive Flexibility",
        9: "Ethics / Prosociality",
        10: "Meta-cognition / Self-model",
    }
    bar = lambda v: "█" * int(v * 20) + "░" * (20 - int(v * 20))

    lines = [
        "╔══════════════════════════════════════════════════════╗",
        f"║  HPEP-100 CHARACTER SHEET                            ║",
        f"║  {p.name:<52}║",
        "╚══════════════════════════════════════════════════════╝",
        "",
        f"  CEID Score: {p.ceid_score:.3f}" if p.ceid_score else "  CEID Score: N/A",
        f"  Version:    {p.version}",
        "",
        "  BLOCK ACTIVATION PROFILE",
        "  " + "─" * 52,
    ]
    for b, name in block_names.items():
        val = blocks.get(b, 0.5)
        lines.append(f"  B{b:02d} {name:<32} {bar(val)} {val:.2f}")

    k_overrides = p.get_k_overrides()
    if k_overrides:
        lines += ["", "  K-LAYER OVERRIDES"]
        for k, v in sorted(k_overrides.items(), key=lambda x: int(x[0])):
            lines.append(f"    K{int(k):03d}: {v:.3f}")

    lines += [
        "",
        "  Generated by HPEP Studio — hpep.studio",
        "  Framework: HPEP-100 v2 + CEID Protocol v4",
    ]
    return "\n".join(lines)


def _assert_member(db: Session, workspace_id: str, user_id: str) -> None:
    member = db.query(WorkspaceMember).filter(
        WorkspaceMember.workspace_id == workspace_id,
        WorkspaceMember.user_id == user_id,
    ).first()
    if not member:
        raise HTTPException(404, "Workspace not found or access denied.")
