"""
Auto-generated API contract tests from OpenAPI schema.

These tests validate that:
1. All endpoints are documented
2. Response schemas match OpenAPI specification
3. Request validation works correctly
4. Error responses are properly formatted

Generated by: scripts/generate_contract_tests.py
"""

import pytest
import os

os.environ["DATABASE_URL"] = "sqlite:///:memory:"
os.environ["STRIPE_SECRET_KEY"] = "sk_test_mock"

from fastapi.testclient import TestClient
from api.db import create_user, grant_free_persona
from api.main import app, get_db


@pytest.fixture
def client(test_db):
    """Create test client with test database."""
    def override_get_db():
        yield test_db

    app.dependency_overrides[get_db] = override_get_db
    yield TestClient(app)
    app.dependency_overrides.clear()


@pytest.fixture
def authenticated_user(test_db):
    """Create authenticated user for tests."""
    user, api_key = create_user(test_db, "contract_test@example.com")
    grant_free_persona(test_db, user.id, "persona_socrates")
    return {"user": user, "api_key": api_key}


class TestGeneratedContracts:
    """Auto-generated endpoint contract tests."""


    def test_refund_purchase_admin_refund__purchase_id__post(self, client, authenticated_user):
        """Contract test: POST /admin/refund/{purchase_id}"""
        # Endpoint: Refund Purchase
        response = client.post(
            "/admin/refund/{purchase_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_dashboard_analytics_dashboard_get(self, client, authenticated_user):
        """Contract test: GET /analytics/dashboard"""
        # Endpoint: Platform dashboard summary
        response = client.get(
            "/analytics/dashboard",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_daily_active_users_analytics_dau_get(self, client, authenticated_user):
        """Contract test: GET /analytics/dau"""
        # Endpoint: Daily active users time series
        response = client.get(
            "/analytics/dau",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_export_csv_analytics_export_csv_get(self, client, authenticated_user):
        """Contract test: GET /analytics/export/csv"""
        # Endpoint: Download analytics as CSV
        response = client.get(
            "/analytics/export/csv",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_top_personas_analytics_personas_top_get(self, client, authenticated_user):
        """Contract test: GET /analytics/personas/top"""
        # Endpoint: Top personas by usage
        response = client.get(
            "/analytics/personas/top",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_persona_stats_analytics_personas__persona_id__get(self, client, authenticated_user):
        """Contract test: GET /analytics/personas/{persona_id}"""
        # Endpoint: Single persona usage stats
        response = client.get(
            "/analytics/personas/{persona_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_cohort_retention_analytics_retention_get(self, client, authenticated_user):
        """Contract test: GET /analytics/retention"""
        # Endpoint: Cohort retention analysis
        response = client.get(
            "/analytics/retention",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_revenue_report_analytics_revenue_get(self, client, authenticated_user):
        """Contract test: GET /analytics/revenue"""
        # Endpoint: Revenue report
        response = client.get(
            "/analytics/revenue",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_user_engagement_analytics_users__user_id__get(self, client, authenticated_user):
        """Contract test: GET /analytics/users/{user_id}"""
        # Endpoint: User engagement statistics
        response = client.get(
            "/analytics/users/{user_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_personas_api_v1_personas__get(self, client, authenticated_user):
        """Contract test: GET /api/v1/personas/"""
        # Endpoint: List Personas
        response = client.get(
            "/api/v1/personas/",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_post_ceid_api_v1_personas__persona_id__ceid_post(self, client, authenticated_user):
        """Contract test: POST /api/v1/personas/{persona_id}/ceid"""
        # Endpoint: Post Ceid
        response = client.post(
            "/api/v1/personas/{persona_id}/ceid",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_post_drift_api_v1_personas__persona_id__drift_post(self, client, authenticated_user):
        """Contract test: POST /api/v1/personas/{persona_id}/drift"""
        # Endpoint: Post Drift
        response = client.post(
            "/api/v1/personas/{persona_id}/drift",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_persona_history_api_v1_personas__persona_id__history_get(self, client, authenticated_user):
        """Contract test: GET /api/v1/personas/{persona_id}/history"""
        # Endpoint: Get Persona History
        response = client.get(
            "/api/v1/personas/{persona_id}/history",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_persona_image_api_v1_personas__persona_id__image_get(self, client, authenticated_user):
        """Contract test: GET /api/v1/personas/{persona_id}/image"""
        # Endpoint: Get Persona Image
        response = client.get(
            "/api/v1/personas/{persona_id}/image",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_persona_profile_api_v1_personas__persona_id__profile_get(self, client, authenticated_user):
        """Contract test: GET /api/v1/personas/{persona_id}/profile"""
        # Endpoint: Get Persona Profile
        response = client.get(
            "/api/v1/personas/{persona_id}/profile",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_post_voice_api_v1_personas__persona_id__voice_post(self, client, authenticated_user):
        """Contract test: POST /api/v1/personas/{persona_id}/voice"""
        # Endpoint: Post Voice
        response = client.post(
            "/api/v1/personas/{persona_id}/voice",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_login_auth_login_post(self, client, authenticated_user):
        """Contract test: POST /auth/login"""
        # Endpoint: Login
        response = client.post(
            "/auth/login",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_logout_auth_logout_post(self, client, authenticated_user):
        """Contract test: POST /auth/logout"""
        # Endpoint: Logout
        response = client.post(
            "/auth/logout",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_logout_all_auth_logout_all_post(self, client, authenticated_user):
        """Contract test: POST /auth/logout/all"""
        # Endpoint: Logout All
        response = client.post(
            "/auth/logout/all",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_current_user_profile_auth_me_get(self, client, authenticated_user):
        """Contract test: GET /auth/me"""
        # Endpoint: Get Current User Profile
        response = client.get(
            "/auth/me",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_change_password_auth_me_password_patch(self, client, authenticated_user):
        """Contract test: PATCH /auth/me/password"""
        # Endpoint: Change Password
        response = client.patch(
            "/auth/me/password",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_start_github_oauth_auth_oauth_github_get(self, client, authenticated_user):
        """Contract test: GET /auth/oauth/github"""
        # Endpoint: Start Github Oauth
        response = client.get(
            "/auth/oauth/github",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_github_oauth_callback_auth_oauth_github_callback_get(self, client, authenticated_user):
        """Contract test: GET /auth/oauth/github/callback"""
        # Endpoint: Github Oauth Callback
        response = client.get(
            "/auth/oauth/github/callback",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_start_google_oauth_auth_oauth_google_get(self, client, authenticated_user):
        """Contract test: GET /auth/oauth/google"""
        # Endpoint: Start Google Oauth
        response = client.get(
            "/auth/oauth/google",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_google_oauth_callback_auth_oauth_google_callback_get(self, client, authenticated_user):
        """Contract test: GET /auth/oauth/google/callback"""
        # Endpoint: Google Oauth Callback
        response = client.get(
            "/auth/oauth/google/callback",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_refresh_access_token_auth_oauth_token_post(self, client, authenticated_user):
        """Contract test: POST /auth/oauth/token"""
        # Endpoint: Refresh Access Token
        response = client.post(
            "/auth/oauth/token",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_user_permissions_auth_permissions_get(self, client, authenticated_user):
        """Contract test: GET /auth/permissions"""
        # Endpoint: Get User Permissions
        response = client.get(
            "/auth/permissions",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_register_auth_register_post(self, client, authenticated_user):
        """Contract test: POST /auth/register"""
        # Endpoint: Register
        response = client.post(
            "/auth/register",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_request_verification_auth_request_verification_post(self, client, authenticated_user):
        """Contract test: POST /auth/request-verification"""
        # Endpoint: Request Verification
        response = client.post(
            "/auth/request-verification",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_roles_auth_roles_get(self, client, authenticated_user):
        """Contract test: GET /auth/roles"""
        # Endpoint: List Roles
        response = client.get(
            "/auth/roles",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_user_profile_auth_users__user_id__get(self, client, authenticated_user):
        """Contract test: GET /auth/users/{user_id}"""
        # Endpoint: Get User Profile
        response = client.get(
            "/auth/users/{user_id}",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_delete_user_auth_users__user_id__delete(self, client, authenticated_user):
        """Contract test: DELETE /auth/users/{user_id}"""
        # Endpoint: Delete User
        response = client.delete(
            "/auth/users/{user_id}",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_update_user_role_auth_users__user_id__role_patch(self, client, authenticated_user):
        """Contract test: PATCH /auth/users/{user_id}/role"""
        # Endpoint: Update User Role
        response = client.patch(
            "/auth/users/{user_id}/role",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_verify_email_auth_verify_email_post(self, client, authenticated_user):
        """Contract test: POST /auth/verify-email"""
        # Endpoint: Verify Email
        response = client.post(
            "/auth/verify-email",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_create_billing_portal_session_billing_portal_post(self, client, authenticated_user):
        """Contract test: POST /billing/portal"""
        # Endpoint: Create Billing Portal Session
        response = client.post(
            "/billing/portal",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_flush_all_cache_cache_flush_delete(self, client, authenticated_user):
        """Contract test: DELETE /cache/flush"""
        # Endpoint: Flush All Cache
        response = client.delete(
            "/cache/flush",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_cache_health_cache_health_get(self, client, authenticated_user):
        """Contract test: GET /cache/health"""
        # Endpoint: Cache Health
        response = client.get(
            "/cache/health",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_flush_persona_cache_cache_personas_delete(self, client, authenticated_user):
        """Contract test: DELETE /cache/personas"""
        # Endpoint: Flush Persona Cache
        response = client.delete(
            "/cache/personas",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_cache_stats_cache_stats_get(self, client, authenticated_user):
        """Contract test: GET /cache/stats"""
        # Endpoint: Cache Stats
        response = client.get(
            "/cache/stats",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_checkout_bundle_checkout_bundle__bundle_id__post(self, client, authenticated_user):
        """Contract test: POST /checkout/bundle/{bundle_id}"""
        # Endpoint: Checkout Bundle
        response = client.post(
            "/checkout/bundle/{bundle_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_checkout_checkout__persona_id__post(self, client, authenticated_user):
        """Contract test: POST /checkout/{persona_id}"""
        # Endpoint: Checkout
        response = client.post(
            "/checkout/{persona_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_checkout_mock_checkout__persona_id__mock_post(self, client, authenticated_user):
        """Contract test: POST /checkout/{persona_id}/mock"""
        # Endpoint: Checkout Mock
        response = client.post(
            "/checkout/{persona_id}/mock",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_flags_flags__get(self, client, authenticated_user):
        """Contract test: GET /flags/"""
        # Endpoint: List Flags
        response = client.get(
            "/flags/",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_create_flag_flags__post(self, client, authenticated_user):
        """Contract test: POST /flags/"""
        # Endpoint: Create Flag
        response = client.post(
            "/flags/",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_flag_flags__flag_name__get(self, client, authenticated_user):
        """Contract test: GET /flags/{flag_name}"""
        # Endpoint: Get Flag
        response = client.get(
            "/flags/{flag_name}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_update_flag_flags__flag_name__patch(self, client, authenticated_user):
        """Contract test: PATCH /flags/{flag_name}"""
        # Endpoint: Update Flag
        response = client.patch(
            "/flags/{flag_name}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_delete_flag_flags__flag_name__delete(self, client, authenticated_user):
        """Contract test: DELETE /flags/{flag_name}"""
        # Endpoint: Delete Flag
        response = client.delete(
            "/flags/{flag_name}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_evaluate_flag_flags__flag_name__evaluate_post(self, client, authenticated_user):
        """Contract test: POST /flags/{flag_name}/evaluate"""
        # Endpoint: Evaluate Flag
        response = client.post(
            "/flags/{flag_name}/evaluate",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_flag_statistics_flags__flag_name__stats_get(self, client, authenticated_user):
        """Contract test: GET /flags/{flag_name}/stats"""
        # Endpoint: Get Flag Statistics
        response = client.get(
            "/flags/{flag_name}/stats",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_health_health_get(self, client, authenticated_user):
        """Contract test: GET /health"""
        # Endpoint: Health
        response = client.get(
            "/health",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_me_me_get(self, client, authenticated_user):
        """Contract test: GET /me"""
        # Endpoint: Get Me
        response = client.get(
            "/me",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_api_keys_me_api_keys_get(self, client, authenticated_user):
        """Contract test: GET /me/api-keys"""
        # Endpoint: List Api Keys
        response = client.get(
            "/me/api-keys",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_rotate_api_key_me_api_keys_rotate_post(self, client, authenticated_user):
        """Contract test: POST /me/api-keys/rotate"""
        # Endpoint: Rotate Api Key
        response = client.post(
            "/me/api-keys/rotate",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_revoke_api_key_me_api_keys__key_id__delete(self, client, authenticated_user):
        """Contract test: DELETE /me/api-keys/{key_id}"""
        # Endpoint: Revoke Api Key
        response = client.delete(
            "/me/api-keys/{key_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_my_invoices_me_invoices_get(self, client, authenticated_user):
        """Contract test: GET /me/invoices"""
        # Endpoint: Get My Invoices
        response = client.get(
            "/me/invoices",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_purchases_me_purchases_get(self, client, authenticated_user):
        """Contract test: GET /me/purchases"""
        # Endpoint: Get Purchases
        response = client.get(
            "/me/purchases",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_my_referral_code_me_referral_code_post(self, client, authenticated_user):
        """Contract test: POST /me/referral-code"""
        # Endpoint: Get My Referral Code
        response = client.post(
            "/me/referral-code",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_my_subscription_me_subscription_get(self, client, authenticated_user):
        """Contract test: GET /me/subscription"""
        # Endpoint: Get My Subscription
        response = client.get(
            "/me/subscription",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_cancel_my_subscription_me_subscription_delete(self, client, authenticated_user):
        """Contract test: DELETE /me/subscription"""
        # Endpoint: Cancel My Subscription
        response = client.delete(
            "/me/subscription",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_wallet_balance_me_wallet_get(self, client, authenticated_user):
        """Contract test: GET /me/wallet"""
        # Endpoint: Get Wallet Balance
        response = client.get(
            "/me/wallet",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_deep_health_check_observability_health_deep_get(self, client, authenticated_user):
        """Contract test: GET /observability/health/deep"""
        # Endpoint: Deep Health Check
        response = client.get(
            "/observability/health/deep",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_liveness_check_observability_health_liveness_get(self, client, authenticated_user):
        """Contract test: GET /observability/health/liveness"""
        # Endpoint: Liveness Check
        response = client.get(
            "/observability/health/liveness",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_readiness_check_observability_health_readiness_get(self, client, authenticated_user):
        """Contract test: GET /observability/health/readiness"""
        # Endpoint: Readiness Check
        response = client.get(
            "/observability/health/readiness",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_collect_logs_observability_logs_collect_post(self, client, authenticated_user):
        """Contract test: POST /observability/logs/collect"""
        # Endpoint: Collect Logs
        response = client.post(
            "/observability/logs/collect",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_metrics_observability_metrics_get(self, client, authenticated_user):
        """Contract test: GET /observability/metrics"""
        # Endpoint: Get Metrics
        response = client.get(
            "/observability/metrics",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_record_metric_observability_metrics_record_post(self, client, authenticated_user):
        """Contract test: POST /observability/metrics/record"""
        # Endpoint: Record Metric
        response = client.post(
            "/observability/metrics/record",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_metrics_summary_observability_metrics_summary_get(self, client, authenticated_user):
        """Contract test: GET /observability/metrics/summary"""
        # Endpoint: Get Metrics Summary
        response = client.get(
            "/observability/metrics/summary",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_prometheus_metrics_observability_prometheus_metrics_get(self, client, authenticated_user):
        """Contract test: GET /observability/prometheus/metrics"""
        # Endpoint: Prometheus Metrics
        response = client.get(
            "/observability/prometheus/metrics",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_record_trace_observability_traces_record_post(self, client, authenticated_user):
        """Contract test: POST /observability/traces/record"""
        # Endpoint: Record Trace
        response = client.post(
            "/observability/traces/record",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_trace_observability_traces__trace_id__get(self, client, authenticated_user):
        """Contract test: GET /observability/traces/{trace_id}"""
        # Endpoint: Get Trace
        response = client.get(
            "/observability/traces/{trace_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_baselines_performance_baselines_get(self, client, authenticated_user):
        """Contract test: GET /performance/baselines"""
        # Endpoint: List Baselines
        response = client.get(
            "/performance/baselines",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_create_performance_baseline_performance_baselines_create_pos(self, client, authenticated_user):
        """Contract test: POST /performance/baselines/create"""
        # Endpoint: Create Performance Baseline
        response = client.post(
            "/performance/baselines/create",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_performance_dashboard_performance_dashboard_summary_get(self, client, authenticated_user):
        """Contract test: GET /performance/dashboard/summary"""
        # Endpoint: Get Performance Dashboard
        response = client.get(
            "/performance/dashboard/summary",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_metrics_performance_metrics_get(self, client, authenticated_user):
        """Contract test: GET /performance/metrics"""
        # Endpoint: List Metrics
        response = client.get(
            "/performance/metrics",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_record_performance_metric_performance_metrics_record_post(self, client, authenticated_user):
        """Contract test: POST /performance/metrics/record"""
        # Endpoint: Record Performance Metric
        response = client.post(
            "/performance/metrics/record",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_check_for_regressions_performance_regressions_check_get(self, client, authenticated_user):
        """Contract test: GET /performance/regressions/check"""
        # Endpoint: Check For Regressions
        response = client.get(
            "/performance/regressions/check",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_detect_endpoint_regression_performance_regressions_detect_po(self, client, authenticated_user):
        """Contract test: POST /performance/regressions/detect"""
        # Endpoint: Detect Endpoint Regression
        response = client.post(
            "/performance/regressions/detect",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_catalog_personas_get(self, client, authenticated_user):
        """Contract test: GET /personas"""
        # Endpoint: Get Catalog
        response = client.get(
            "/personas",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_library_stats_personas_stats_library_get(self, client, authenticated_user):
        """Contract test: GET /personas/stats/library"""
        # Endpoint: Get Library Stats
        response = client.get(
            "/personas/stats/library",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_persona_detail_personas__persona_id__get(self, client, authenticated_user):
        """Contract test: GET /personas/{persona_id}"""
        # Endpoint: Get Persona Detail
        response = client.get(
            "/personas/{persona_id}",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_evaluate_rollback_rollback_evaluate_post(self, client, authenticated_user):
        """Contract test: POST /rollback/evaluate"""
        # Endpoint: Evaluate Rollback
        response = client.post(
            "/rollback/evaluate",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_execute_rollback_rollback_execute_post(self, client, authenticated_user):
        """Contract test: POST /rollback/execute"""
        # Endpoint: Execute Rollback
        response = client.post(
            "/rollback/execute",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_record_rollback_completion_rollback_history_post(self, client, authenticated_user):
        """Contract test: POST /rollback/history"""
        # Endpoint: Record Rollback Completion
        response = client.post(
            "/rollback/history",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_rollback_history_endpoint_rollback_history_get(self, client, authenticated_user):
        """Contract test: GET /rollback/history"""
        # Endpoint: Get Rollback History Endpoint
        response = client.get(
            "/rollback/history",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_get_rollback_policy_rollback_policy_get(self, client, authenticated_user):
        """Contract test: GET /rollback/policy"""
        # Endpoint: Get Rollback Policy
        response = client.get(
            "/rollback/policy",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_update_rollback_policy_rollback_policy_patch(self, client, authenticated_user):
        """Contract test: PATCH /rollback/policy"""
        # Endpoint: Update Rollback Policy
        response = client.patch(
            "/rollback/policy",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_approve_rollback_rollback__rollback_id__approve_post(self, client, authenticated_user):
        """Contract test: POST /rollback/{rollback_id}/approve"""
        # Endpoint: Approve Rollback
        response = client.post(
            "/rollback/{rollback_id}/approve",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_subscribe_subscribe__tier__post(self, client, authenticated_user):
        """Contract test: POST /subscribe/{tier}"""
        # Endpoint: Subscribe
        response = client.post(
            "/subscribe/{tier}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_list_subscription_tiers_subscription_tiers_get(self, client, authenticated_user):
        """Contract test: GET /subscription/tiers"""
        # Endpoint: List Subscription Tiers
        response = client.get(
            "/subscription/tiers",
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_compile_v1_compile__persona_id__post(self, client, authenticated_user):
        """Contract test: POST /v1/compile/{persona_id}"""
        # Endpoint: Compile
        response = client.post(
            "/v1/compile/{persona_id}",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_compile_platforms_v1_compile__persona_id__all_platforms_post(self, client, authenticated_user):
        """Contract test: POST /v1/compile/{persona_id}/all-platforms"""
        # Endpoint: Compile Platforms
        response = client.post(
            "/v1/compile/{persona_id}/all-platforms",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_compile_tiers_v1_compile__persona_id__all_tiers_post(self, client, authenticated_user):
        """Contract test: POST /v1/compile/{persona_id}/all-tiers"""
        # Endpoint: Compile Tiers
        response = client.post(
            "/v1/compile/{persona_id}/all-tiers",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")


    def test_compile_voice_v1_compile__persona_id__voice_post(self, client, authenticated_user):
        """Contract test: POST /v1/compile/{persona_id}/voice"""
        # Endpoint: Compile Voice
        response = client.post(
            "/v1/compile/{persona_id}/voice",
            headers={"X-API-Key": authenticated_user["api_key"]},
        )

        # Verify response status
        assert response.status_code in [200, 201, 204, 400, 401, 403, 404, 500]

        # Verify response is valid JSON (if not 204 No Content)
        if response.status_code != 204:
            try:
                data = response.json()
            except ValueError:
                pytest.skip(f"Response is not JSON: {response.text}")



class TestGeneratedErrorContracts:
    """Auto-generated error response contract tests."""

    def test_404_not_found(self, client):
        """Verify 404 responses have proper schema."""
        response = client.get("/nonexistent")
        assert response.status_code == 404
        data = response.json()
        # Error responses should have detail or message
        assert "detail" in data or "message" in data

    def test_401_unauthorized(self, client):
        """Verify 401 responses require authentication."""
        response = client.get("/me")
        assert response.status_code in [401, 403]
        if response.status_code == 401:
            data = response.json()
            assert "detail" in data or "message" in data

    def test_422_validation_error(self, client):
        """Verify 422 responses for invalid requests."""
        response = client.post(
            "/auth/register",
            json={"email": "invalid"},  # Missing password
        )
        assert response.status_code == 422
        data = response.json()
        assert "detail" in data or "message" in data
