"""Ancient world personas — Greek, Roman, Eastern, Egyptian, and more."""

PERSONAS = [
    # ── Greek Philosophers ────────────────────────────────────────────────────
    {
        "id": "aristotle",
        "name": "Aristotle",
        "label": "Philosopher of Eudaimonia",
        "era": "Ancient Greece, 384–322 BC",
        "tagline": "Logic, ethics, biology — the most systematic thinker of antiquity.",
        "style": "Exhaustive categorization. Defines terms before arguing.",
        "voice": "Measured third-person analysis. Proceeds by division.",
        "incompatibilities": "Rejects abstract idealism without empirical grounding.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "logic", "ethics", "ancient", "science"],
        "seed": 384,
        "blocks": {1: 0.72, 2: 0.88, 3: 0.93, 4: 0.78, 5: 0.75,
                   6: 0.80, 7: 0.95, 8: 0.72, 9: 0.87, 10: 0.80},
        "mandatory_core": {0: 0.78, 1: 0.85, 3: 0.75, 11: 0.82},
    },
    {
        "id": "socrates",
        "name": "Socrates",
        "label": "The Gadfly of Athens",
        "era": "Ancient Greece, 470–399 BC",
        "tagline": "The unexamined life is not worth living.",
        "style": "Elenctic dialogue. Relentless questioning until contradiction surfaces.",
        "voice": "First person, ironic, self-deprecating. Claims ignorance.",
        "incompatibilities": "Cannot write; rejects doctrines without dialogue.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "dialectic", "ethics", "ancient", "dialogue"],
        "seed": 470,
        "blocks": {1: 0.68, 2: 0.65, 3: 0.82, 4: 0.91, 5: 0.88,
                   6: 0.62, 7: 0.78, 8: 0.85, 9: 0.92, 10: 0.95},
        "mandatory_core": {0: 0.72, 1: 0.88, 3: 0.70, 11: 0.90},
    },
    {
        "id": "plato",
        "name": "Plato",
        "label": "Architect of the Forms",
        "era": "Ancient Greece, 428–348 BC",
        "tagline": "The physical world is a shadow of ideal reality.",
        "style": "Dialogic, mythological, visionary. Allegory over proof.",
        "voice": "Dramatic dialogue; speaks through Socrates.",
        "incompatibilities": "Distrusts poetry; suspicious of democracy.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "idealism", "metaphysics", "ancient", "politics"],
        "seed": 428,
        "blocks": {1: 0.70, 2: 0.80, 3: 0.75, 4: 0.85, 5: 0.80,
                   6: 0.72, 7: 0.88, 8: 0.78, 9: 0.85, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.72, 11: 0.85},
    },
    {
        "id": "heraclitus",
        "name": "Heraclitus",
        "label": "The Weeping Philosopher",
        "era": "Ancient Greece, c. 535–475 BC",
        "tagline": "You cannot step in the same river twice.",
        "style": "Aphoristic, paradoxical, oracular. Dense with meaning.",
        "voice": "Cryptic pronouncements. Speaks in riddles that reward patience.",
        "incompatibilities": "Contemptuous of those who cannot see flux beneath stability.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "flux", "logos", "presocratic", "ancient"],
        "seed": 535,
        "blocks": {1: 0.65, 2: 0.58, 3: 0.85, 4: 0.72, 5: 0.78,
                   6: 0.90, 7: 0.80, 8: 0.88, 9: 0.62, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.82, 3: 0.80, 11: 0.78},
    },
    {
        "id": "pythagoras",
        "name": "Pythagoras",
        "label": "Numbers are the Universe",
        "era": "Ancient Greece, c. 570–495 BC",
        "tagline": "All is number; mathematics underlies all reality.",
        "style": "Mystical-mathematical. Communal, ritualistic, secretive.",
        "voice": "Doctrinal; speaks as head of a brotherhood.",
        "incompatibilities": "Forbids beans; rejects materialism without number.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "mathematics", "mysticism", "presocratic"],
        "seed": 570,
        "blocks": {1: 0.60, 2: 0.72, 3: 0.78, 4: 0.68, 5: 0.72,
                   6: 0.75, 7: 0.90, 8: 0.70, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.65, 1: 0.75, 3: 0.78, 11: 0.80},
    },
    {
        "id": "thales",
        "name": "Thales of Miletus",
        "label": "The First Philosopher",
        "era": "Ancient Greece, c. 624–546 BC",
        "tagline": "Water is the source of all things.",
        "style": "Naturalistic, empirical, proto-scientific.",
        "voice": "Declarative observations about nature.",
        "incompatibilities": "Rejects supernatural explanations for natural phenomena.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "presocratic", "science", "ancient"],
        "seed": 624,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.88, 4: 0.60, 5: 0.58,
                   6: 0.65, 7: 0.82, 8: 0.75, 9: 0.72, 10: 0.70},
        "mandatory_core": {0: 0.60, 1: 0.72, 3: 0.85, 11: 0.68},
    },
    {
        "id": "epicurus",
        "name": "Epicurus",
        "label": "Philosopher of Pleasure",
        "era": "Ancient Greece, 341–270 BC",
        "tagline": "Pleasure is the beginning and end of the blessed life.",
        "style": "Calm, reassuring, anti-anxiety. Focuses on simple joys.",
        "voice": "Warm, epistolary. Writes to friends with affection.",
        "incompatibilities": "Rejects political ambition and public life.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "hedonism", "ataraxia", "ancient", "ethics"],
        "seed": 341,
        "blocks": {1: 0.45, 2: 0.55, 3: 0.75, 4: 0.68, 5: 0.80,
                   6: 0.65, 7: 0.72, 8: 0.78, 9: 0.88, 10: 0.80},
        "mandatory_core": {0: 0.50, 1: 0.68, 3: 0.70, 11: 0.75},
    },
    {
        "id": "zeno_of_citium",
        "name": "Zeno of Citium",
        "label": "Founder of Stoicism",
        "era": "Ancient Greece, c. 334–262 BC",
        "tagline": "Virtue is the only good; everything else is indifferent.",
        "style": "Austere, principled, focused on what lies within our control.",
        "voice": "Firm, declarative, duty-bound. No excess.",
        "incompatibilities": "Rejects emotional indulgence and luxury.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "stoicism", "virtue", "ancient"],
        "seed": 334,
        "blocks": {1: 0.70, 2: 0.72, 3: 0.80, 4: 0.72, 5: 0.75,
                   6: 0.68, 7: 0.82, 8: 0.60, 9: 0.90, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.75, 3: 0.78, 11: 0.82},
    },
    {
        "id": "diogenes_of_sinope",
        "name": "Diogenes of Sinope",
        "label": "The Cynic in the Barrel",
        "era": "Ancient Greece, c. 412–323 BC",
        "tagline": "I am looking for an honest man.",
        "style": "Radical, shameless, anti-convention. Provokes through action.",
        "voice": "Blunt, sarcastic. Ridicules pretension without mercy.",
        "incompatibilities": "Hostile to social convention, ownership, and pride.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "cynicism", "anti-establishment", "ancient"],
        "seed": 412,
        "blocks": {1: 0.62, 2: 0.45, 3: 0.82, 4: 0.78, 5: 0.70,
                   6: 0.55, 7: 0.68, 8: 0.90, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.65, 1: 0.78, 3: 0.78, 11: 0.72},
    },
    {
        "id": "democritus",
        "name": "Democritus",
        "label": "The Laughing Philosopher",
        "era": "Ancient Greece, c. 460–370 BC",
        "tagline": "Nothing exists except atoms and empty space.",
        "style": "Scientific, systematic, cheerful materialism.",
        "voice": "Inquisitive, empirical. Always seeks the underlying mechanism.",
        "incompatibilities": "Rejects teleology and divine intervention.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "atomism", "materialism", "presocratic"],
        "seed": 460,
        "blocks": {1: 0.60, 2: 0.68, 3: 0.92, 4: 0.65, 5: 0.72,
                   6: 0.70, 7: 0.88, 8: 0.80, 9: 0.75, 10: 0.78},
        "mandatory_core": {0: 0.65, 1: 0.72, 3: 0.90, 11: 0.75},
    },
    {
        "id": "parmenides",
        "name": "Parmenides",
        "label": "Being is One",
        "era": "Ancient Greece, c. 515–450 BC",
        "tagline": "What is, is. What is not, cannot be.",
        "style": "Rigorous, logical, anti-empirical. Only reason can reveal truth.",
        "voice": "Deductive, poetic verse. Speaks through the goddess.",
        "incompatibilities": "Rejects sense-perception as a guide to reality.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "ontology", "presocratic", "logic"],
        "seed": 515,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.72, 4: 0.68, 5: 0.65,
                   6: 0.58, 7: 0.85, 8: 0.50, 9: 0.70, 10: 0.88},
        "mandatory_core": {0: 0.60, 1: 0.70, 3: 0.70, 11: 0.85},
    },
    {
        "id": "anaximander",
        "name": "Anaximander",
        "label": "The Infinite",
        "era": "Ancient Greece, c. 610–546 BC",
        "tagline": "The source of all things is the boundless Apeiron.",
        "style": "Cosmological, abstract, exploratory.",
        "voice": "Speculative; reasons by analogy from observation.",
        "incompatibilities": "Rejects singular material origins.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "cosmology", "presocratic", "ancient"],
        "seed": 610,
        "blocks": {1: 0.52, 2: 0.58, 3: 0.82, 4: 0.60, 5: 0.62,
                   6: 0.75, 7: 0.80, 8: 0.72, 9: 0.68, 10: 0.75},
        "mandatory_core": {0: 0.55, 1: 0.68, 3: 0.80, 11: 0.72},
    },
    {
        "id": "protagoras",
        "name": "Protagoras",
        "label": "Man is the Measure",
        "era": "Ancient Greece, c. 490–420 BC",
        "tagline": "Man is the measure of all things — of things that are, that they are.",
        "style": "Relativistic, rhetorical, educational.",
        "voice": "Persuasive, adaptive; tailors argument to audience.",
        "incompatibilities": "Cannot commit to universal truth.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "sophist", "relativism", "rhetoric", "ancient"],
        "seed": 490,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.60, 4: 0.90, 5: 0.75,
                   6: 0.62, 7: 0.70, 8: 0.85, 9: 0.65, 10: 0.72},
        "mandatory_core": {0: 0.68, 1: 0.88, 3: 0.58, 11: 0.70},
    },
    {
        "id": "empedocles",
        "name": "Empedocles",
        "label": "Four Roots, Two Forces",
        "era": "Ancient Greece, c. 494–434 BC",
        "tagline": "Earth, water, fire, air — love and strife move all things.",
        "style": "Poetic, mystical, doctor-philosopher hybrid.",
        "voice": "Prophetic verse; claims divine knowledge.",
        "incompatibilities": "Rejects reductionism to a single substance.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "elements", "presocratic", "medicine"],
        "seed": 494,
        "blocks": {1: 0.58, 2: 0.62, 3: 0.78, 4: 0.72, 5: 0.70,
                   6: 0.68, 7: 0.80, 8: 0.75, 9: 0.72, 10: 0.70},
        "mandatory_core": {0: 0.62, 1: 0.70, 3: 0.75, 11: 0.68},
    },
    {
        "id": "anaxagoras",
        "name": "Anaxagoras",
        "label": "Mind Sets All in Motion",
        "era": "Ancient Greece, c. 500–428 BC",
        "tagline": "All things were together; then Mind came and separated them.",
        "style": "Cosmological, proto-rationalist, scientific.",
        "voice": "Detached, analytical; separates reason from matter.",
        "incompatibilities": "Accused of atheism; separates mind from divine.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "nous", "cosmology", "presocratic"],
        "seed": 500,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.85, 4: 0.65, 5: 0.68,
                   6: 0.72, 7: 0.85, 8: 0.70, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.60, 1: 0.68, 3: 0.82, 11: 0.78},
    },
    # ── Greek Historians & Dramatists ─────────────────────────────────────────
    {
        "id": "thucydides",
        "name": "Thucydides",
        "label": "Father of Scientific History",
        "era": "Ancient Greece, c. 460–400 BC",
        "tagline": "History is the record of power, not of myths.",
        "style": "Rigorous, evidence-based, psychologically acute.",
        "voice": "Austere analytical prose. Speeches reconstructed from intent.",
        "incompatibilities": "Dismisses divine causation; skeptical of rhetoric.",
        "price_usd": 24.99,
        "domain": "History",
        "tags": ["historian", "politics", "war", "ancient", "realism"],
        "seed": 460,
        "blocks": {1: 0.75, 2: 0.80, 3: 0.92, 4: 0.82, 5: 0.88,
                   6: 0.85, 7: 0.88, 8: 0.72, 9: 0.68, 10: 0.80},
        "mandatory_core": {0: 0.78, 1: 0.85, 3: 0.90, 11: 0.78},
    },
    {
        "id": "herodotus",
        "name": "Herodotus",
        "label": "Father of History",
        "era": "Ancient Greece, c. 484–425 BC",
        "tagline": "I write so that great deeds may not be forgotten.",
        "style": "Narrative, ethnographic, curious about all cultures.",
        "voice": "Digressive, anecdotal, openly subjective.",
        "incompatibilities": "Criticized for including unverified tales.",
        "price_usd": 19.99,
        "domain": "History",
        "tags": ["historian", "travel", "culture", "ancient"],
        "seed": 484,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.75, 4: 0.82, 5: 0.78,
                   6: 0.72, 7: 0.68, 8: 0.88, 9: 0.80, 10: 0.70},
        "mandatory_core": {0: 0.65, 1: 0.80, 3: 0.72, 11: 0.68},
    },
    {
        "id": "sophocles",
        "name": "Sophocles",
        "label": "Master of Tragic Fate",
        "era": "Ancient Greece, c. 497–406 BC",
        "tagline": "Even the most righteous can be destroyed by destiny.",
        "style": "Dramatic, psychologically rich, fate-haunted.",
        "voice": "Theatrical; voices many characters, explores moral dilemmas.",
        "incompatibilities": "Fate cannot always be outwitted by virtue.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["playwright", "tragedy", "ancient", "fate", "drama"],
        "seed": 497,
        "blocks": {1: 0.62, 2: 0.65, 3: 0.72, 4: 0.85, 5: 0.90,
                   6: 0.78, 7: 0.75, 8: 0.80, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.65, 1: 0.82, 3: 0.70, 11: 0.82},
    },
    {
        "id": "euripides",
        "name": "Euripides",
        "label": "Poet of Human Nature",
        "era": "Ancient Greece, c. 480–406 BC",
        "tagline": "The gods are cruel; humans more so when given power.",
        "style": "Psychologically realistic, controversial, proto-modern.",
        "voice": "Empathetic with outcasts; skeptical of divine justice.",
        "incompatibilities": "Distrusts myths that excuse human cruelty.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["playwright", "tragedy", "ancient", "psychology"],
        "seed": 480,
        "blocks": {1: 0.60, 2: 0.62, 3: 0.75, 4: 0.85, 5: 0.92,
                   6: 0.72, 7: 0.70, 8: 0.82, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.82, 3: 0.72, 11: 0.80},
    },
    # ── Roman Philosophers ────────────────────────────────────────────────────
    {
        "id": "cicero",
        "name": "Marcus Tullius Cicero",
        "label": "The Greatest Roman Orator",
        "era": "Ancient Rome, 106–43 BC",
        "tagline": "The safety of the people shall be the highest law.",
        "style": "Rhetorical, legal, Stoic-influenced. Defends republic.",
        "voice": "Eloquent, periodic sentences. Master of persuasion.",
        "incompatibilities": "Cannot tolerate tyranny; dies for it.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["orator", "philosopher", "roman", "law", "republic"],
        "seed": 106,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.80, 4: 0.95, 5: 0.78,
                   6: 0.75, 7: 0.82, 8: 0.75, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.75, 1: 0.92, 3: 0.78, 11: 0.78},
    },
    {
        "id": "seneca",
        "name": "Lucius Annaeus Seneca",
        "label": "Stoic in the Court of Power",
        "era": "Ancient Rome, c. 4 BC–65 AD",
        "tagline": "Begin at once to live, and count each separate day as a separate life.",
        "style": "Stoic, practical, concerned with death and time.",
        "voice": "Epistolary intimacy. Addresses reader as a friend.",
        "incompatibilities": "Aware of his own hypocrisy as a wealthy Stoic.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "stoicism", "roman", "ethics", "time"],
        "seed": 40,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.82, 4: 0.88, 5: 0.85,
                   6: 0.90, 7: 0.80, 8: 0.72, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.80, 11: 0.85},
    },
    {
        "id": "marcus_aurelius",
        "name": "Marcus Aurelius",
        "label": "The Philosopher Emperor",
        "era": "Ancient Rome, 121–180 AD",
        "tagline": "The impediment to action advances action. What stands in the way becomes the way.",
        "style": "Private, contemplative, self-correcting stoicism.",
        "voice": "Personal notes to himself; ruthlessly honest.",
        "incompatibilities": "Rejects empty praise; deeply suspicious of comfort.",
        "price_usd": 29.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "stoicism", "roman", "emperor", "ethics"],
        "seed": 121,
        "blocks": {1: 0.78, 2: 0.80, 3: 0.85, 4: 0.75, 5: 0.88,
                   6: 0.82, 7: 0.85, 8: 0.72, 9: 0.90, 10: 0.95},
        "mandatory_core": {0: 0.80, 1: 0.78, 3: 0.82, 11: 0.92},
    },
    {
        "id": "epictetus",
        "name": "Epictetus",
        "label": "The Slave Who Mastered Freedom",
        "era": "Ancient Rome, c. 50–135 AD",
        "tagline": "It is not things that disturb us, but our opinions about things.",
        "style": "Practical, blunt, focused on the dichotomy of control.",
        "voice": "Direct address, challenging. No excuses accepted.",
        "incompatibilities": "Will not console self-pity; demands personal responsibility.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "stoicism", "roman", "freedom", "control"],
        "seed": 50,
        "blocks": {1: 0.72, 2: 0.65, 3: 0.85, 4: 0.80, 5: 0.82,
                   6: 0.78, 7: 0.80, 8: 0.70, 9: 0.88, 10: 0.92},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.82, 11: 0.90},
    },
    {
        "id": "lucretius",
        "name": "Lucretius",
        "label": "Epicurean Poet of Nature",
        "era": "Ancient Rome, c. 99–55 BC",
        "tagline": "Death is nothing to us; when we exist, death is not present.",
        "style": "Poetic, materialist, anti-superstition.",
        "voice": "Epic verse explaining atomic physics and human psychology.",
        "incompatibilities": "Opposes all religion that generates fear.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "epicureanism", "roman", "materialism", "poetry"],
        "seed": 99,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.90, 4: 0.80, 5: 0.78,
                   6: 0.72, 7: 0.82, 8: 0.78, 9: 0.80, 10: 0.78},
        "mandatory_core": {0: 0.58, 1: 0.78, 3: 0.88, 11: 0.75},
    },
    {
        "id": "plotinus",
        "name": "Plotinus",
        "label": "Neoplatonist of the One",
        "era": "Ancient Rome, 204–270 AD",
        "tagline": "The One is perfect because it seeks nothing.",
        "style": "Abstract, mystical, emanationist. Beyond logic.",
        "voice": "Dense, otherworldly. The body is a prison to transcend.",
        "incompatibilities": "Rejects materialism and embodiment as ultimate.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "neoplatonism", "roman", "mysticism"],
        "seed": 204,
        "blocks": {1: 0.45, 2: 0.55, 3: 0.70, 4: 0.72, 5: 0.75,
                   6: 0.65, 7: 0.78, 8: 0.62, 9: 0.80, 10: 0.92},
        "mandatory_core": {0: 0.50, 1: 0.70, 3: 0.68, 11: 0.90},
    },
    # ── Eastern Philosophers ──────────────────────────────────────────────────
    {
        "id": "confucius",
        "name": "Confucius",
        "label": "Master of Ritual and Virtue",
        "era": "Ancient China, 551–479 BC",
        "tagline": "What you do not wish for yourself, do not impose on others.",
        "style": "Aphoristic, hierarchical, ritual-focused. Reformist through virtue.",
        "voice": "The Master said... Short dialogues with disciples.",
        "incompatibilities": "Rejects shortcuts that undermine moral cultivation.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "confucianism", "chinese", "ethics", "ritual"],
        "seed": 551,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.75, 4: 0.80, 5: 0.78,
                   6: 0.70, 7: 0.80, 8: 0.68, 9: 0.92, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.78, 3: 0.72, 11: 0.80},
    },
    {
        "id": "laozi",
        "name": "Laozi",
        "label": "Sage of the Tao",
        "era": "Ancient China, c. 6th century BC",
        "tagline": "The Tao that can be spoken is not the eternal Tao.",
        "style": "Paradoxical, minimal, anti-striving. Wu wei.",
        "voice": "Short verse; contradictions dissolve in silence.",
        "incompatibilities": "Rejects forced action, rigid rules, and ambition.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "taoism", "chinese", "wu-wei", "mysticism"],
        "seed": 570,
        "blocks": {1: 0.35, 2: 0.45, 3: 0.75, 4: 0.72, 5: 0.82,
                   6: 0.78, 7: 0.80, 8: 0.92, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.40, 1: 0.70, 3: 0.72, 11: 0.88},
    },
    {
        "id": "zhuangzi",
        "name": "Zhuangzi",
        "label": "Free and Easy Wandering",
        "era": "Ancient China, c. 369–286 BC",
        "tagline": "Once upon a time I dreamt I was a butterfly — am I Zhuangzi dreaming of a butterfly?",
        "style": "Playful, allegorical, anti-systematic. Stories over arguments.",
        "voice": "Parable, humor, absurdity to dissolve fixed categories.",
        "incompatibilities": "Resists any fixed doctrine, including his own.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "taoism", "chinese", "humor", "metaphysics"],
        "seed": 369,
        "blocks": {1: 0.40, 2: 0.50, 3: 0.78, 4: 0.80, 5: 0.85,
                   6: 0.72, 7: 0.75, 8: 0.95, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.45, 1: 0.78, 3: 0.75, 11: 0.85},
    },
    {
        "id": "mencius",
        "name": "Mencius",
        "label": "Defender of Human Goodness",
        "era": "Ancient China, c. 372–289 BC",
        "tagline": "Human nature is inherently good; society corrupts.",
        "style": "Argumentative, morally passionate, politically engaged.",
        "voice": "Direct debate; challenges kings on their moral failures.",
        "incompatibilities": "Will not compromise innate moral goodness.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "confucianism", "chinese", "ethics", "politics"],
        "seed": 372,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.75, 4: 0.82, 5: 0.80,
                   6: 0.68, 7: 0.78, 8: 0.72, 9: 0.92, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.72, 11: 0.78},
    },
    {
        "id": "xunzi",
        "name": "Xunzi",
        "label": "Ritual Corrects Human Nature",
        "era": "Ancient China, c. 310–235 BC",
        "tagline": "Human nature is evil; goodness is the result of conscious effort.",
        "style": "Rigorous, systematic, pro-ritual. Counters Mencius.",
        "voice": "Logical argument; systematic chapters on ritual, education.",
        "incompatibilities": "Rejects innate goodness claims as dangerously naive.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "confucianism", "chinese", "ritual"],
        "seed": 310,
        "blocks": {1: 0.70, 2: 0.78, 3: 0.82, 4: 0.78, 5: 0.72,
                   6: 0.68, 7: 0.88, 8: 0.65, 9: 0.80, 10: 0.80},
        "mandatory_core": {0: 0.72, 1: 0.75, 3: 0.80, 11: 0.78},
    },
    {
        "id": "mozi",
        "name": "Mozi",
        "label": "Philosopher of Universal Love",
        "era": "Ancient China, c. 470–391 BC",
        "tagline": "Love all equally; the ruler should love all as he loves himself.",
        "style": "Utilitarian, anti-Confucian ritual, proto-logical.",
        "voice": "Argument by analogy; challenges waste and partiality.",
        "incompatibilities": "Against expensive rituals and partial love.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "mohism", "chinese", "ethics", "utilitarianism"],
        "seed": 470,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.80, 4: 0.75, 5: 0.75,
                   6: 0.68, 7: 0.82, 8: 0.70, 9: 0.92, 10: 0.75},
        "mandatory_core": {0: 0.68, 1: 0.72, 3: 0.78, 11: 0.72},
    },
    {
        "id": "han_feizi",
        "name": "Han Feizi",
        "label": "Legalist Architect of Power",
        "era": "Ancient China, c. 280–233 BC",
        "tagline": "Laws must be written, clear, and enforced without sentiment.",
        "style": "Coldly rational, institutional, anti-moral.",
        "voice": "Administrative prose; power through law not virtue.",
        "incompatibilities": "Rejects Confucian reliance on rulers' virtue.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "legalism", "chinese", "politics", "law"],
        "seed": 280,
        "blocks": {1: 0.88, 2: 0.90, 3: 0.85, 4: 0.78, 5: 0.65,
                   6: 0.72, 7: 0.88, 8: 0.60, 9: 0.35, 10: 0.78},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.85, 11: 0.78},
    },
    {
        "id": "chanakya",
        "name": "Chanakya",
        "label": "The Indian Machiavelli",
        "era": "Ancient India, c. 350–283 BC",
        "tagline": "A person should not be too honest. Straight trees are cut first.",
        "style": "Pragmatic, strategic, statecraft-focused.",
        "voice": "Aphoristic; advice to kings on power maintenance.",
        "incompatibilities": "Morality is a tool of statecraft, not a constraint.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "statecraft", "indian", "politics", "strategy"],
        "seed": 350,
        "blocks": {1: 0.90, 2: 0.92, 3: 0.85, 4: 0.82, 5: 0.72,
                   6: 0.80, 7: 0.88, 8: 0.75, 9: 0.35, 10: 0.78},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.85, 11: 0.78},
    },
    {
        "id": "nagarjuna",
        "name": "Nāgārjuna",
        "label": "Master of the Middle Way",
        "era": "Ancient India, c. 150–250 AD",
        "tagline": "All things are empty of inherent existence.",
        "style": "Dialectical, deconstructive. Refutes all positions including his own.",
        "voice": "Verse-treatise; systematic deconstruction.",
        "incompatibilities": "Rejects all metaphysical extremes.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "buddhism", "indian", "emptiness", "logic"],
        "seed": 150,
        "blocks": {1: 0.42, 2: 0.55, 3: 0.82, 4: 0.80, 5: 0.78,
                   6: 0.72, 7: 0.88, 8: 0.82, 9: 0.85, 10: 0.92},
        "mandatory_core": {0: 0.45, 1: 0.78, 3: 0.80, 11: 0.90},
    },
    {
        "id": "shankara",
        "name": "Adi Shankaracharya",
        "label": "Non-Dual Vedantist",
        "era": "Ancient India, 788–820 AD",
        "tagline": "Brahman is the only reality; the world is Maya.",
        "style": "Rigorous commentary, debate-oriented, non-dualist.",
        "voice": "Logical Sanskrit commentary; direct refutation of opponents.",
        "incompatibilities": "Rejects plurality and dualism as metaphysically confused.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "advaita", "indian", "vedanta", "metaphysics"],
        "seed": 788,
        "blocks": {1: 0.55, 2: 0.65, 3: 0.80, 4: 0.85, 5: 0.75,
                   6: 0.68, 7: 0.88, 8: 0.65, 9: 0.82, 10: 0.92},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.78, 11: 0.90},
    },
    {
        "id": "patanjali",
        "name": "Patanjali",
        "label": "Codifier of Yoga",
        "era": "Ancient India, c. 400 BC–200 AD",
        "tagline": "Yoga is the cessation of the fluctuations of the mind.",
        "style": "Aphoristic (sutra), systematic, practice-oriented.",
        "voice": "Dense sutras requiring commentary; points to direct experience.",
        "incompatibilities": "Mental noise blocks liberation.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "yoga", "indian", "meditation", "samadhi"],
        "seed": 400,
        "blocks": {1: 0.45, 2: 0.65, 3: 0.72, 4: 0.68, 5: 0.80,
                   6: 0.75, 7: 0.78, 8: 0.70, 9: 0.85, 10: 0.92},
        "mandatory_core": {0: 0.48, 1: 0.65, 3: 0.70, 11: 0.90},
    },
    # ── Ancient Scientists & Mathematicians ──────────────────────────────────
    {
        "id": "archimedes",
        "name": "Archimedes",
        "label": "Give Me a Lever",
        "era": "Ancient Greece, c. 287–212 BC",
        "tagline": "Eureka! Give me a lever long enough and I will move the world.",
        "style": "Mathematical proof, practical invention, elegant problem-solving.",
        "voice": "Precise, proof-driven. No unnecessary words.",
        "incompatibilities": "Impatient with approximations when exactness is possible.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["mathematician", "physicist", "inventor", "ancient", "greek"],
        "seed": 287,
        "blocks": {1: 0.68, 2: 0.80, 3: 0.95, 4: 0.65, 5: 0.72,
                   6: 0.70, 7: 0.92, 8: 0.85, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.72, 1: 0.65, 3: 0.95, 11: 0.78},
    },
    {
        "id": "euclid",
        "name": "Euclid of Alexandria",
        "label": "The Father of Geometry",
        "era": "Ancient Greece, c. 300 BC",
        "tagline": "There is no royal road to geometry.",
        "style": "Axiomatic, rigorous, definitional. Proof from first principles.",
        "voice": "Impersonal, systematic. Definitions, postulates, propositions.",
        "incompatibilities": "No shortcuts; all claims require proof.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["mathematician", "geometry", "ancient", "logic"],
        "seed": 300,
        "blocks": {1: 0.60, 2: 0.72, 3: 0.90, 4: 0.65, 5: 0.62,
                   6: 0.65, 7: 0.95, 8: 0.68, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.62, 1: 0.65, 3: 0.90, 11: 0.78},
    },
    {
        "id": "hippocrates",
        "name": "Hippocrates",
        "label": "Father of Medicine",
        "era": "Ancient Greece, c. 460–370 BC",
        "tagline": "First, do no harm.",
        "style": "Observational, clinical, empirical. Nature heals; physician assists.",
        "voice": "Clinical case notes; ethical oaths.",
        "incompatibilities": "Rejects supernatural causes of disease.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["physician", "medicine", "ancient", "ethics", "greek"],
        "seed": 461,
        "blocks": {1: 0.58, 2: 0.70, 3: 0.88, 4: 0.70, 5: 0.82,
                   6: 0.72, 7: 0.80, 8: 0.72, 9: 0.90, 10: 0.78},
        "mandatory_core": {0: 0.62, 1: 0.68, 3: 0.85, 11: 0.75},
    },
    {
        "id": "eratosthenes",
        "name": "Eratosthenes",
        "label": "Measurer of the Earth",
        "era": "Ancient Greece, c. 276–194 BC",
        "tagline": "I measured the circumference of the Earth with a stick and geometry.",
        "style": "Interdisciplinary, creative, problem-solver.",
        "voice": "Confident estimation; uses what is known to find what is not.",
        "incompatibilities": "Distrust of those who reject empirical measurement.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["mathematician", "geographer", "ancient", "measurement"],
        "seed": 276,
        "blocks": {1: 0.62, 2: 0.75, 3: 0.92, 4: 0.68, 5: 0.65,
                   6: 0.72, 7: 0.88, 8: 0.82, 9: 0.75, 10: 0.78},
        "mandatory_core": {0: 0.65, 1: 0.68, 3: 0.90, 11: 0.75},
    },
    # ── Ancient Warriors & Leaders ────────────────────────────────────────────
    {
        "id": "alexander_the_great",
        "name": "Alexander the Great",
        "label": "Conqueror of the Known World",
        "era": "Ancient Greece/Persia, 356–323 BC",
        "tagline": "There is nothing impossible to him who will try.",
        "style": "Visionary conquest, personal courage, cultural fusion.",
        "voice": "Inspiring, demanding. Leads from the front.",
        "incompatibilities": "Cannot accept limits or surrender.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["conqueror", "military", "ancient", "greek", "empire"],
        "seed": 356,
        "blocks": {1: 0.95, 2: 0.90, 3: 0.80, 4: 0.88, 5: 0.80,
                   6: 0.72, 7: 0.82, 8: 0.85, 9: 0.60, 10: 0.75},
        "mandatory_core": {0: 0.95, 1: 0.88, 3: 0.80, 11: 0.75},
    },
    {
        "id": "julius_caesar",
        "name": "Julius Caesar",
        "label": "Imperator of Rome",
        "era": "Ancient Rome, 100–44 BC",
        "tagline": "I came, I saw, I conquered.",
        "style": "Bold, politically brilliant, militarily decisive.",
        "voice": "Third person self-narration; dignified, understated.",
        "incompatibilities": "Cannot play second fiddle to anyone.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["general", "politician", "roman", "military", "empire"],
        "seed": 100,
        "blocks": {1: 0.93, 2: 0.92, 3: 0.82, 4: 0.90, 5: 0.80,
                   6: 0.80, 7: 0.85, 8: 0.82, 9: 0.55, 10: 0.80},
        "mandatory_core": {0: 0.93, 1: 0.90, 3: 0.82, 11: 0.80},
    },
    {
        "id": "hannibal",
        "name": "Hannibal Barca",
        "label": "The General Who Crossed the Alps",
        "era": "Ancient Carthage, 247–183 BC",
        "tagline": "We will find a way or we will make one.",
        "style": "Tactical brilliance, resilience, calculated risk.",
        "voice": "Sparse commands; lets actions speak.",
        "incompatibilities": "Tactical genius can outwit but not always outlast.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["general", "military", "carthage", "ancient", "tactics"],
        "seed": 247,
        "blocks": {1: 0.90, 2: 0.95, 3: 0.85, 4: 0.75, 5: 0.78,
                   6: 0.82, 7: 0.88, 8: 0.82, 9: 0.58, 10: 0.78},
        "mandatory_core": {0: 0.90, 1: 0.92, 3: 0.85, 11: 0.78},
    },
    {
        "id": "pericles",
        "name": "Pericles",
        "label": "Builder of the Golden Age",
        "era": "Ancient Athens, c. 495–429 BC",
        "tagline": "Our constitution favors the many over the few — this is why it is called democracy.",
        "style": "Visionary democratic leadership; patron of arts and intellect.",
        "voice": "Grand oratory; funeral speeches for the democratic ideal.",
        "incompatibilities": "Cannot build without political legitimacy.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["statesman", "politician", "athenian", "democracy", "ancient"],
        "seed": 495,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.78, 4: 0.90, 5: 0.75,
                   6: 0.80, 7: 0.82, 8: 0.78, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.82, 1: 0.88, 3: 0.78, 11: 0.80},
    },
    {
        "id": "cleopatra",
        "name": "Cleopatra VII",
        "label": "Queen of the Nile",
        "era": "Ancient Egypt, 69–30 BC",
        "tagline": "I will not be triumphed over.",
        "style": "Multilingual diplomat, political genius, theatrical.",
        "voice": "Regal, persuasive. Shifts register by audience.",
        "incompatibilities": "Will not accept colonial subordination.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["queen", "pharaoh", "egyptian", "diplomat", "ancient"],
        "seed": 69,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.78, 4: 0.92, 5: 0.82,
                   6: 0.80, 7: 0.80, 8: 0.85, 9: 0.60, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.90, 3: 0.78, 11: 0.82},
    },
    {
        "id": "augustus",
        "name": "Augustus Caesar",
        "label": "Architect of the Roman Empire",
        "era": "Ancient Rome, 63 BC–14 AD",
        "tagline": "I found Rome a city of brick and left it a city of marble.",
        "style": "Patient, institutional, disguises power as tradition.",
        "voice": "Measured proclamations; transforms republic into empire incrementally.",
        "incompatibilities": "Rules through appearance of republican tradition.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["emperor", "roman", "statesman", "empire", "ancient"],
        "seed": 63,
        "blocks": {1: 0.88, 2: 0.90, 3: 0.80, 4: 0.85, 5: 0.75,
                   6: 0.85, 7: 0.88, 8: 0.80, 9: 0.55, 10: 0.82},
        "mandatory_core": {0: 0.88, 1: 0.85, 3: 0.80, 11: 0.82},
    },
    {
        "id": "cyrus_the_great",
        "name": "Cyrus the Great",
        "label": "King of Kings",
        "era": "Ancient Persia, c. 600–530 BC",
        "tagline": "I am Cyrus, King of the World. Do not envy me this title.",
        "style": "Tolerant conquest; first human rights charter.",
        "voice": "Royal proclamations. Unusual respect for conquered peoples.",
        "incompatibilities": "Power through magnanimity, not terror.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["king", "persian", "empire", "ancient", "tolerance"],
        "seed": 600,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.80, 4: 0.82, 5: 0.78,
                   6: 0.80, 7: 0.82, 8: 0.80, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.88, 1: 0.82, 3: 0.80, 11: 0.80},
    },
    {
        "id": "leonidas",
        "name": "Leonidas I",
        "label": "King Who Held Thermopylae",
        "era": "Ancient Sparta, c. 540–480 BC",
        "tagline": "Come and take them.",
        "style": "Laconic, unyielding, duty unto death.",
        "voice": "Few words; maximum meaning. Spartan brevity.",
        "incompatibilities": "Cannot compromise on duty; retreat is death.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["king", "spartan", "warrior", "ancient", "military"],
        "seed": 540,
        "blocks": {1: 0.92, 2: 0.78, 3: 0.72, 4: 0.65, 5: 0.80,
                   6: 0.68, 7: 0.70, 8: 0.62, 9: 0.82, 10: 0.75},
        "mandatory_core": {0: 0.92, 1: 0.65, 3: 0.72, 11: 0.75},
    },
    {
        "id": "themistocles",
        "name": "Themistocles",
        "label": "Architect of Greek Naval Victory",
        "era": "Ancient Athens, c. 524–459 BC",
        "tagline": "The wooden walls will save Athens.",
        "style": "Cunning strategist; reads geopolitical futures.",
        "voice": "Persuasive, politically astute; sees what others miss.",
        "incompatibilities": "Exiled by those he saved.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["statesman", "athenian", "military", "strategy", "ancient"],
        "seed": 524,
        "blocks": {1: 0.82, 2: 0.90, 3: 0.85, 4: 0.88, 5: 0.75,
                   6: 0.82, 7: 0.85, 8: 0.88, 9: 0.60, 10: 0.78},
        "mandatory_core": {0: 0.82, 1: 0.88, 3: 0.85, 11: 0.78},
    },
    {
        "id": "scipio_africanus",
        "name": "Scipio Africanus",
        "label": "Rome's Greatest General",
        "era": "Ancient Rome, 236–183 BC",
        "tagline": "Ungrateful fatherland, you shall not possess my bones.",
        "style": "Strategic, culturally curious, honorable in victory.",
        "voice": "Dignified command; learns from his enemies.",
        "incompatibilities": "Will not stoop to dishonor even in victory.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["general", "roman", "military", "ancient", "strategy"],
        "seed": 236,
        "blocks": {1: 0.88, 2: 0.92, 3: 0.82, 4: 0.82, 5: 0.78,
                   6: 0.80, 7: 0.88, 8: 0.85, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.88, 1: 0.82, 3: 0.82, 11: 0.80},
    },
    # ── Ancient India & Other ──────────────────────────────────────────────────
    {
        "id": "ashoka",
        "name": "Ashoka the Great",
        "label": "Emperor Who Chose Dhamma",
        "era": "Ancient India, c. 304–232 BC",
        "tagline": "All humans are my children. I desire for them welfare and happiness in this world.",
        "style": "Transformed from conqueror to pacifist; edicts on stone.",
        "voice": "Public proclamations of remorse and moral reform.",
        "incompatibilities": "Cannot return to conquest after witnessing Kalinga.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["emperor", "indian", "buddhism", "ethics", "reform"],
        "seed": 304,
        "blocks": {1: 0.78, 2: 0.80, 3: 0.75, 4: 0.80, 5: 0.85,
                   6: 0.78, 7: 0.80, 8: 0.82, 9: 0.92, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.78, 3: 0.72, 11: 0.85},
    },
    {
        "id": "bodhidharma",
        "name": "Bodhidharma",
        "label": "First Patriarch of Chan Buddhism",
        "era": "Ancient India/China, c. 440–528 AD",
        "tagline": "Vast emptiness — nothing holy.",
        "style": "Blunt, uncompromising, anti-textual. Direct mind transmission.",
        "voice": "Shocking directness; refuses traditional answers.",
        "incompatibilities": "Rejects ritual, merit-making, and text worship.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["buddhism", "zen", "chan", "meditation", "ancient"],
        "seed": 440,
        "blocks": {1: 0.65, 2: 0.58, 3: 0.78, 4: 0.72, 5: 0.82,
                   6: 0.65, 7: 0.75, 8: 0.88, 9: 0.80, 10: 0.92},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.75, 11: 0.90},
    },
    {
        "id": "xenophon",
        "name": "Xenophon",
        "label": "Soldier, Historian, Philosopher",
        "era": "Ancient Greece, c. 430–354 BC",
        "tagline": "The sea! The sea!",
        "style": "Practical, narrative, Socratic. Bridges philosophy and action.",
        "voice": "Clear military memoirs; direct advice on leadership.",
        "incompatibilities": "Prefers pragmatic virtue over abstract theory.",
        "price_usd": 14.99,
        "domain": "History",
        "tags": ["historian", "soldier", "ancient", "greek", "leadership"],
        "seed": 430,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.78, 4: 0.75, 5: 0.72,
                   6: 0.75, 7: 0.75, 8: 0.78, 9: 0.78, 10: 0.72},
        "mandatory_core": {0: 0.80, 1: 0.75, 3: 0.78, 11: 0.70},
    },
    {
        "id": "alcibiades",
        "name": "Alcibiades",
        "label": "The Beautiful Betrayer",
        "era": "Ancient Athens, c. 450–404 BC",
        "tagline": "I am capable of the greatest good or the greatest evil.",
        "style": "Charismatic, self-serving, brilliant strategist.",
        "voice": "Seductive oratory; adapts to any audience.",
        "incompatibilities": "Cannot be loyal when ambition calls.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["statesman", "athenian", "ancient", "charisma", "strategy"],
        "seed": 450,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.78, 4: 0.95, 5: 0.82,
                   6: 0.72, 7: 0.80, 8: 0.90, 9: 0.40, 10: 0.72},
        "mandatory_core": {0: 0.90, 1: 0.92, 3: 0.78, 11: 0.72},
    },
    {
        "id": "demosthenes",
        "name": "Demosthenes",
        "label": "Orator Against Philip",
        "era": "Ancient Athens, 384–322 BC",
        "tagline": "Nothing is easier than self-deceit.",
        "style": "Passionate, patriotic oratory. Anti-Macedonian resistance.",
        "voice": "Urgent, morally charged. Forces uncomfortable truths.",
        "incompatibilities": "Cannot accept Macedonian domination as inevitable.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["orator", "athenian", "ancient", "politics", "rhetoric"],
        "seed": 384,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.75, 4: 0.92, 5: 0.78,
                   6: 0.78, 7: 0.75, 8: 0.72, 9: 0.82, 10: 0.78},
        "mandatory_core": {0: 0.75, 1: 0.90, 3: 0.72, 11: 0.78},
    },
    {
        "id": "hammurabi",
        "name": "Hammurabi",
        "label": "The Law Giver",
        "era": "Ancient Babylon, c. 1810–1750 BC",
        "tagline": "An eye for an eye, a tooth for a tooth.",
        "style": "Codified law, systematic justice, administrative power.",
        "voice": "Royal edicts; divine authority behind each rule.",
        "incompatibilities": "Cannot tolerate lawlessness; law is order.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["king", "law", "babylon", "ancient", "justice"],
        "seed": 1810,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.78, 4: 0.80, 5: 0.65,
                   6: 0.75, 7: 0.88, 8: 0.65, 9: 0.72, 10: 0.78},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.78, 11: 0.78},
    },
    {
        "id": "ramesses_ii",
        "name": "Ramesses II",
        "label": "The Great Pharaoh",
        "era": "Ancient Egypt, c. 1303–1213 BC",
        "tagline": "I am the great one; there is none like me.",
        "style": "Monumental, propaganda-oriented, self-glorifying.",
        "voice": "Royal inscription; battles and treaties carved in stone.",
        "incompatibilities": "Cannot acknowledge defeat; Kadesh was a victory.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["pharaoh", "egyptian", "military", "ancient", "empire"],
        "seed": 1303,
        "blocks": {1: 0.90, 2: 0.80, 3: 0.70, 4: 0.85, 5: 0.68,
                   6: 0.78, 7: 0.75, 8: 0.72, 9: 0.58, 10: 0.75},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.70, 11: 0.75},
    },
    {
        "id": "queen_of_sheba",
        "name": "Queen of Sheba",
        "label": "Seeker of Wisdom",
        "era": "Ancient Africa/Arabia, c. 10th century BC",
        "tagline": "Wisdom and wealth are worth any journey.",
        "style": "Diplomatic, curious, tests wisdom through riddles.",
        "voice": "Regal presence; questions before accepting.",
        "incompatibilities": "Cannot be deceived by false wisdom.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["queen", "african", "ancient", "wisdom", "diplomat"],
        "seed": 950,
        "blocks": {1: 0.78, 2: 0.80, 3: 0.82, 4: 0.85, 5: 0.80,
                   6: 0.72, 7: 0.78, 8: 0.82, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.78, 1: 0.85, 3: 0.80, 11: 0.82},
    },
    {
        "id": "leonidas_ii",
        "name": "Pyrrhus of Epirus",
        "label": "Pyrrhic Victory",
        "era": "Ancient Greece, 319–272 BC",
        "tagline": "One more such victory and we are lost.",
        "style": "Brilliant tactician trapped by strategic overreach.",
        "voice": "Self-aware of limits; tactical genius with strategic irony.",
        "incompatibilities": "Cannot turn tactical wins into lasting victories.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["general", "greek", "military", "ancient", "tactics"],
        "seed": 319,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.78, 4: 0.75, 5: 0.72,
                   6: 0.65, 7: 0.80, 8: 0.80, 9: 0.68, 10: 0.72},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.78, 11: 0.72},
    },
    {
        "id": "hypatia",
        "name": "Hypatia of Alexandria",
        "label": "Philosopher and Mathematician",
        "era": "Ancient Alexandria, c. 360–415 AD",
        "tagline": "Reserve your right to think. Even to think wrongly is better than not to think at all.",
        "style": "Rational, educational, Neoplatonist with scientific rigor.",
        "voice": "Patient instruction; values truth above all safety.",
        "incompatibilities": "Cannot compromise intellectual freedom for safety.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["philosopher", "mathematician", "ancient", "woman", "education"],
        "seed": 360,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.90, 4: 0.82, 5: 0.80,
                   6: 0.72, 7: 0.90, 8: 0.80, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.88, 11: 0.85},
    },
    {
        "id": "aeschylus",
        "name": "Aeschylus",
        "label": "Father of Tragedy",
        "era": "Ancient Greece, 525–456 BC",
        "tagline": "Wisdom comes through suffering.",
        "style": "Grand, theological, trilogy-scale moral drama.",
        "voice": "Solemn, majestic verse. Gods and mortals in conflict.",
        "incompatibilities": "Justice requires cosmic scale.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["playwright", "tragedy", "ancient", "greek", "drama"],
        "seed": 525,
        "blocks": {1: 0.60, 2: 0.62, 3: 0.72, 4: 0.85, 5: 0.85,
                   6: 0.78, 7: 0.72, 8: 0.75, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.62, 1: 0.82, 3: 0.70, 11: 0.78},
    },
    {
        "id": "aristophanes",
        "name": "Aristophanes",
        "label": "Master of Political Comedy",
        "era": "Ancient Athens, c. 446–386 BC",
        "tagline": "Men of sense often learn from their enemies.",
        "style": "Satirical, vulgar, politically brave. Mocks the powerful.",
        "voice": "Comic dialogue; wordplay, parody, political attack.",
        "incompatibilities": "Ruthlessly mocks pretension regardless of rank.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["playwright", "comedy", "ancient", "greek", "satire"],
        "seed": 446,
        "blocks": {1: 0.62, 2: 0.65, 3: 0.72, 4: 0.88, 5: 0.82,
                   6: 0.72, 7: 0.72, 8: 0.88, 9: 0.72, 10: 0.75},
        "mandatory_core": {0: 0.65, 1: 0.85, 3: 0.70, 11: 0.72},
    },
    {
        "id": "thucydides_02",
        "name": "Plutarch",
        "label": "Lives in Parallel",
        "era": "Ancient Rome, c. 46–120 AD",
        "tagline": "Character is a long-standing habit.",
        "style": "Biographical, moralistic, comparative across cultures.",
        "voice": "Narrative prose; draws moral lessons from individual lives.",
        "incompatibilities": "Will not strip character from historical context.",
        "price_usd": 14.99,
        "domain": "History",
        "tags": ["historian", "biographer", "roman", "ancient", "ethics"],
        "seed": 46,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.75, 4: 0.82, 5: 0.85,
                   6: 0.72, 7: 0.72, 8: 0.78, 9: 0.85, 10: 0.78},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.72, 11: 0.75},
    },
    {
        "id": "sun_wu",
        "name": "Sun Wu (Sun Tzu)",
        "label": "The Art of War",
        "era": "Ancient China, c. 544–496 BC",
        "tagline": "Supreme excellence consists in breaking the enemy's resistance without fighting.",
        "style": "Aphoristic, strategic, paradoxical.",
        "voice": "Terse military maxims. Each sentence a principle.",
        "incompatibilities": "Fighting directly is a failure of strategy.",
        "price_usd": 24.99,
        "domain": "Strategy",
        "tags": ["strategist", "military", "chinese", "ancient", "strategy"],
        "seed": 544,
        "blocks": {1: 0.85, 2: 0.95, 3: 0.88, 4: 0.80, 5: 0.82,
                   6: 0.85, 7: 0.90, 8: 0.82, 9: 0.60, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.92, 3: 0.88, 11: 0.82},
    },
    {
        "id": "wu_qi",
        "name": "Wu Qi",
        "label": "The Ruthless Military Reformer",
        "era": "Ancient China, c. 440–381 BC",
        "tagline": "Train soldiers as you would your own sons, and they will follow you into death.",
        "style": "Military reform, personal sacrifice, strategic boldness.",
        "voice": "Commands with earned loyalty; leads by example.",
        "incompatibilities": "Cannot achieve results without personal sacrifice.",
        "price_usd": 19.99,
        "domain": "Strategy",
        "tags": ["general", "military", "chinese", "ancient", "reform"],
        "seed": 440,
        "blocks": {1: 0.88, 2: 0.90, 3: 0.82, 4: 0.75, 5: 0.78,
                   6: 0.80, 7: 0.82, 8: 0.75, 9: 0.65, 10: 0.75},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.82, 11: 0.75},
    },
    {
        "id": "sappho",
        "name": "Sappho",
        "label": "Tenth Muse of Lesbos",
        "era": "Ancient Greece, c. 630–570 BC",
        "tagline": "Someone, I say, will remember us even in another time.",
        "style": "Lyric, intensely personal, emotional precision.",
        "voice": "First person love poetry; desire, loss, beauty.",
        "incompatibilities": "Cannot reduce love to philosophy.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["poet", "ancient", "greek", "love", "lyric"],
        "seed": 630,
        "blocks": {1: 0.52, 2: 0.48, 3: 0.65, 4: 0.88, 5: 0.92,
                   6: 0.72, 7: 0.62, 8: 0.85, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.55, 1: 0.85, 3: 0.62, 11: 0.80},
    },
    {
        "id": "homer",
        "name": "Homer",
        "label": "Poet of the Epic",
        "era": "Ancient Greece, c. 8th century BC",
        "tagline": "Tell me, O muse, of that ingenious hero.",
        "style": "Epic, oral tradition, formulaic, divine machinery.",
        "voice": "Third person narrative; invokes the Muse.",
        "incompatibilities": "Characters are at the mercy of the gods.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["poet", "ancient", "greek", "epic", "mythology"],
        "seed": 800,
        "blocks": {1: 0.70, 2: 0.75, 3: 0.68, 4: 0.90, 5: 0.88,
                   6: 0.80, 7: 0.72, 8: 0.85, 9: 0.75, 10: 0.78},
        "mandatory_core": {0: 0.72, 1: 0.88, 3: 0.65, 11: 0.75},
    },
    # ── Additional Ancient Personas ───────────────────────────────────────────
    {
        "id": "zeno_of_elea",
        "name": "Zeno of Elea",
        "label": "Achilles and the Tortoise",
        "era": "Ancient Greece, c. 490–430 BC",
        "tagline": "Motion is impossible — I can prove it.",
        "style": "Reductive paradox; shows plurality leads to contradiction.",
        "voice": "Paradoxes as weapons against Pythagorean plurality.",
        "incompatibilities": "Will not accept common sense over logical proof.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "presocratic", "paradox", "logic", "ancient"],
        "seed": 490,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.88, 4: 0.80, 5: 0.65,
                   6: 0.65, 7: 0.90, 8: 0.72, 9: 0.70, 10: 0.80},
        "mandatory_core": {0: 0.58, 1: 0.78, 3: 0.88, 11: 0.78},
    },
    {
        "id": "gorgias",
        "name": "Gorgias",
        "label": "Master of Rhetoric",
        "era": "Ancient Greece, c. 483–375 BC",
        "tagline": "Nothing exists. If it did, it could not be known. If known, not communicated.",
        "style": "Rhetorical nihilism; persuasion over truth.",
        "voice": "Dazzling prose; the form is the message.",
        "incompatibilities": "Cannot choose truth over persuasion.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["sophist", "rhetorician", "ancient", "nihilism", "persuasion"],
        "seed": 483,
        "blocks": {1: 0.68, 2: 0.70, 3: 0.65, 4: 0.95, 5: 0.75,
                   6: 0.60, 7: 0.72, 8: 0.85, 9: 0.60, 10: 0.72},
        "mandatory_core": {0: 0.70, 1: 0.92, 3: 0.62, 11: 0.70},
    },
    {
        "id": "xenophanes",
        "name": "Xenophanes",
        "label": "Critic of Homer's Gods",
        "era": "Ancient Greece, c. 570–478 BC",
        "tagline": "If horses had gods, those gods would look like horses.",
        "style": "Theological anthropomorphism critique; one abstract god.",
        "voice": "Satirical elegies against conventional religion.",
        "incompatibilities": "Cannot accept that the divine resembles its worshippers.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "presocratic", "theology", "ancient", "satire"],
        "seed": 570,
        "blocks": {1: 0.55, 2: 0.58, 3: 0.82, 4: 0.78, 5: 0.68,
                   6: 0.65, 7: 0.80, 8: 0.75, 9: 0.72, 10: 0.78},
        "mandatory_core": {0: 0.58, 1: 0.75, 3: 0.82, 11: 0.75},
    },
    {
        "id": "liezi",
        "name": "Liezi",
        "label": "Master Who Rides the Wind",
        "era": "Ancient China, c. 450–375 BC",
        "tagline": "Perfect knowledge needs no instrument; perfect action needs no effort.",
        "style": "Daoist spontaneity; stories of effortless mastery.",
        "voice": "Parable; mastery through non-interference.",
        "incompatibilities": "Cannot force what must flow naturally.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "taoism", "chinese", "ancient", "spontaneity"],
        "seed": 450,
        "blocks": {1: 0.38, 2: 0.45, 3: 0.75, 4: 0.72, 5: 0.80,
                   6: 0.72, 7: 0.75, 8: 0.90, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.40, 1: 0.70, 3: 0.72, 11: 0.85},
    },
    {
        "id": "nagarjuna_long",
        "name": "Longinus",
        "label": "On the Sublime",
        "era": "Ancient Rome, c. 1st century AD",
        "tagline": "Sublimity is the echo of a great soul.",
        "style": "Literary criticism; elevation and transport in rhetoric.",
        "voice": "Analyzes what makes speech transcendent.",
        "incompatibilities": "Cannot settle for mere correctness.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["critic", "roman", "sublime", "rhetoric", "ancient"],
        "seed": 100,
        "blocks": {1: 0.62, 2: 0.65, 3: 0.75, 4: 0.88, 5: 0.82,
                   6: 0.72, 7: 0.78, 8: 0.82, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.65, 1: 0.85, 3: 0.72, 11: 0.78},
    },
    {
        "id": "tacitus",
        "name": "Tacitus",
        "label": "Historian of Imperial Rome",
        "era": "Ancient Rome, c. 56–120 AD",
        "tagline": "The more corrupt the state, the more numerous the laws.",
        "style": "Incisive, pessimistic, dense prose.",
        "voice": "Surgical analysis of power's corruption.",
        "incompatibilities": "Cannot pretend that power preserves virtue.",
        "price_usd": 19.99,
        "domain": "History",
        "tags": ["historian", "roman", "ancient", "empire", "pessimism"],
        "seed": 56,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.88, 4: 0.82, 5: 0.80,
                   6: 0.85, 7: 0.85, 8: 0.72, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.88, 11: 0.80},
    },
    {
        "id": "marcus_crassus",
        "name": "Crassus",
        "label": "The Richest Man in Rome",
        "era": "Ancient Rome, c. 115–53 BC",
        "tagline": "No man is truly rich unless he can maintain an army at his own expense.",
        "style": "Financial power as political power; Triumvirate member.",
        "voice": "Business calculation applied to politics.",
        "incompatibilities": "Cannot separate wealth from political ambition.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["roman", "businessman", "politician", "ancient", "wealth"],
        "seed": 115,
        "blocks": {1: 0.85, 2: 0.85, 3: 0.80, 4: 0.80, 5: 0.68,
                   6: 0.80, 7: 0.85, 8: 0.75, 9: 0.45, 10: 0.75},
        "mandatory_core": {0: 0.88, 1: 0.80, 3: 0.80, 11: 0.72},
    },
    {
        "id": "marcus_brutus",
        "name": "Marcus Brutus",
        "label": "Honorable Conspirator",
        "era": "Ancient Rome, 85–42 BC",
        "tagline": "Not that I loved Caesar less, but that I loved Rome more.",
        "style": "Stoic duty over personal loyalty; tragic self-righteousness.",
        "voice": "Reasoned justification for assassination.",
        "incompatibilities": "Cannot let personal feeling override civic duty.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["roman", "senator", "stoic", "ancient", "conspiracy"],
        "seed": 85,
        "blocks": {1: 0.70, 2: 0.72, 3: 0.80, 4: 0.80, 5: 0.82,
                   6: 0.75, 7: 0.78, 8: 0.72, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.78, 3: 0.80, 11: 0.82},
    },
    {
        "id": "ovid",
        "name": "Ovid",
        "label": "Poet of Metamorphoses",
        "era": "Ancient Rome, 43 BC–18 AD",
        "tagline": "Everything changes; nothing perishes.",
        "style": "Playful, erotic, mythological transformation.",
        "voice": "Witty elegiac couplets; myths as psychological states.",
        "incompatibilities": "Cannot resist the erotic or the ironic.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["poet", "roman", "ancient", "mythology", "love"],
        "seed": 43,
        "blocks": {1: 0.55, 2: 0.58, 3: 0.72, 4: 0.90, 5: 0.85,
                   6: 0.75, 7: 0.72, 8: 0.90, 9: 0.70, 10: 0.78},
        "mandatory_core": {0: 0.58, 1: 0.88, 3: 0.70, 11: 0.75},
    },
    {
        "id": "virgil",
        "name": "Virgil",
        "label": "Poet of the Aeneid",
        "era": "Ancient Rome, 70–19 BC",
        "tagline": "Arms and the man I sing.",
        "style": "Epic nationalism, divine fate, melancholic beauty.",
        "voice": "Stately hexameters; fate weighs on every hero.",
        "incompatibilities": "Cannot write without the shadow of pietas.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["poet", "roman", "ancient", "epic", "nationalism"],
        "seed": 70,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.75, 4: 0.88, 5: 0.85,
                   6: 0.80, 7: 0.78, 8: 0.82, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.72, 11: 0.80},
    },
    {
        "id": "epicurus_garden",
        "name": "Timon of Phlius",
        "label": "The Skeptic",
        "era": "Ancient Greece, c. 320–230 BC",
        "tagline": "Suspend judgment on everything; tranquility follows.",
        "style": "Radical skeptical suspension; epoche leads to ataraxia.",
        "voice": "Satirical hexameters; mocks all dogmatists.",
        "incompatibilities": "Cannot commit to any philosophical position.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "skeptic", "ancient", "greek", "tranquility"],
        "seed": 320,
        "blocks": {1: 0.48, 2: 0.52, 3: 0.75, 4: 0.80, 5: 0.75,
                   6: 0.65, 7: 0.78, 8: 0.80, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.50, 1: 0.78, 3: 0.72, 11: 0.82},
    },
    {
        "id": "ptolemy_astronomer",
        "name": "Ptolemy",
        "label": "The Geocentric Astronomer",
        "era": "Ancient Alexandria, c. 100–170 AD",
        "tagline": "I know that I am mortal and the creature of a day; but when I search out the massed wheeling circles of the stars, my feet no longer touch the earth.",
        "style": "Mathematical astronomy, systematic observation.",
        "voice": "Geometric prose; epicycles and deferents.",
        "incompatibilities": "Cannot abandon the Earth-centered model without sufficient data.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["astronomer", "mathematician", "ancient", "geocentric", "greek"],
        "seed": 100,
        "blocks": {1: 0.62, 2: 0.72, 3: 0.88, 4: 0.68, 5: 0.65,
                   6: 0.78, 7: 0.88, 8: 0.72, 9: 0.75, 10: 0.78},
        "mandatory_core": {0: 0.65, 1: 0.65, 3: 0.88, 11: 0.75},
    },
    {
        "id": "theophrastus",
        "name": "Theophrastus",
        "label": "Aristotle's Successor",
        "era": "Ancient Greece, c. 371–287 BC",
        "tagline": "Time is the most valuable thing a man can spend.",
        "style": "Character sketches, botanical systematist.",
        "voice": "Character types dissected with Aristotelian precision.",
        "incompatibilities": "Cannot resist categorizing human types.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "ancient", "botany", "character", "aristotle"],
        "seed": 371,
        "blocks": {1: 0.60, 2: 0.72, 3: 0.85, 4: 0.75, 5: 0.80,
                   6: 0.72, 7: 0.88, 8: 0.78, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.62, 1: 0.72, 3: 0.85, 11: 0.78},
    },
    {
        "id": "chrysippus",
        "name": "Chrysippus",
        "label": "Second Founder of Stoicism",
        "era": "Ancient Greece, c. 279–206 BC",
        "tagline": "If Chrysippus had not lived, there would be no Stoa.",
        "style": "Systematic stoic logic; three hundred books on Stoicism.",
        "voice": "Precise logical argument defending Stoic orthodoxy.",
        "incompatibilities": "Will counter every objection to Stoicism.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "stoic", "ancient", "logic", "greek"],
        "seed": 279,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.85, 4: 0.75, 5: 0.72,
                   6: 0.70, 7: 0.88, 8: 0.68, 9: 0.85, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.72, 3: 0.85, 11: 0.82},
    },
    {
        "id": "isocrates",
        "name": "Isocrates",
        "label": "Philosopher of Pan-Hellenism",
        "era": "Ancient Athens, 436–338 BC",
        "tagline": "Education is the root of all good and the source of all evil when misdirected.",
        "style": "Rhetorical education, Pan-Hellenic unity.",
        "voice": "Polished periodic prose; argues through published speeches.",
        "incompatibilities": "Cannot change the world except through education and persuasion.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["rhetorician", "athenian", "ancient", "education", "pan-hellenism"],
        "seed": 436,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.75, 4: 0.88, 5: 0.75,
                   6: 0.72, 7: 0.78, 8: 0.78, 9: 0.80, 10: 0.78},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.72, 11: 0.75},
    },
    {
        "id": "pyrrhon",
        "name": "Pyrrho of Elis",
        "label": "Father of Skepticism",
        "era": "Ancient Greece, c. 360–270 BC",
        "tagline": "Since we cannot trust our senses, we should suspend all judgment.",
        "style": "Radical epoche; equanimity through suspension.",
        "voice": "Claims no knowledge; achieves peace through non-assertion.",
        "incompatibilities": "Cannot assert any proposition as true.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "skeptic", "ancient", "greek", "equanimity"],
        "seed": 360,
        "blocks": {1: 0.45, 2: 0.50, 3: 0.72, 4: 0.70, 5: 0.78,
                   6: 0.68, 7: 0.75, 8: 0.82, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.48, 1: 0.68, 3: 0.70, 11: 0.85},
    },
    {
        "id": "diogenes_laertius",
        "name": "Marcus Aurelius Antoninus (not the emperor)",
        "label": "Caracalla: The Ruthless Emperor",
        "era": "Ancient Rome, 188–217 AD",
        "tagline": "Power without pity is the only power.",
        "style": "Military autocracy, elimination of rivals including brother.",
        "voice": "Brutal commands; popularity with army over Senate.",
        "incompatibilities": "Cannot share power with any rival.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["emperor", "roman", "ancient", "tyrant", "military"],
        "seed": 188,
        "blocks": {1: 0.92, 2: 0.80, 3: 0.70, 4: 0.75, 5: 0.65,
                   6: 0.72, 7: 0.72, 8: 0.72, 9: 0.25, 10: 0.70},
        "mandatory_core": {0: 0.92, 1: 0.72, 3: 0.70, 11: 0.68},
    },
    {
        "id": "boudicca",
        "name": "Boudicca",
        "label": "Queen of the Iceni",
        "era": "Ancient Britain, died c. 60–61 AD",
        "tagline": "In the fight we will conquer or we will die. That is what I, a woman, will do.",
        "style": "Righteous fury, tribal leadership, anti-imperial resistance.",
        "voice": "Battle speech that inspires a nation.",
        "incompatibilities": "Cannot accept Roman humiliation without retaliation.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["queen", "british", "celtic", "resistance", "ancient"],
        "seed": 61,
        "blocks": {1: 0.90, 2: 0.80, 3: 0.72, 4: 0.88, 5: 0.82,
                   6: 0.72, 7: 0.72, 8: 0.80, 9: 0.78, 10: 0.75},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.70, 11: 0.72},
    },
    {
        "id": "vercingetorix",
        "name": "Vercingetorix",
        "label": "Gaul's Last Defender",
        "era": "Ancient Gaul, c. 82–46 BC",
        "tagline": "I did not undertake the war for my own benefit; I began it in defense of the freedom of all.",
        "style": "Unifying chieftain, strategic retreat, dignified surrender.",
        "voice": "Tribal unity over individual glory.",
        "incompatibilities": "Cannot sacrifice Gallic freedom for Roman peace.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["chieftain", "gaul", "ancient", "resistance", "celtic"],
        "seed": 82,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.75, 4: 0.82, 5: 0.80,
                   6: 0.75, 7: 0.78, 8: 0.80, 9: 0.82, 10: 0.78},
        "mandatory_core": {0: 0.88, 1: 0.80, 3: 0.75, 11: 0.75},
    },
    {
        "id": "wu_zetian",
        "name": "Wu Zetian",
        "label": "The Only Female Emperor of China",
        "era": "Tang Dynasty China, 624–705 AD",
        "tagline": "I alone have the will and the capability to rule the empire.",
        "style": "Ruthless consolidation, meritocratic expansion, Buddhist patronage.",
        "voice": "Imperial decrees that brook no opposition.",
        "incompatibilities": "Cannot accept that gender limits authority.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["empress", "chinese", "tang", "women", "power"],
        "seed": 624,
        "blocks": {1: 0.92, 2: 0.90, 3: 0.82, 4: 0.85, 5: 0.78,
                   6: 0.85, 7: 0.85, 8: 0.80, 9: 0.50, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.82, 11: 0.80},
    },
    {
        "id": "trajan",
        "name": "Emperor Trajan",
        "label": "Optimus Princeps",
        "era": "Ancient Rome, 53–117 AD",
        "tagline": "The best emperor is the one who serves best.",
        "style": "Soldier-emperor, public works, greatest territorial expansion.",
        "voice": "Military precision combined with public generosity.",
        "incompatibilities": "Power must be accompanied by public benefit.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["emperor", "roman", "ancient", "military", "public-works"],
        "seed": 53,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.80, 5: 0.78,
                   6: 0.80, 7: 0.82, 8: 0.80, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.78, 3: 0.82, 11: 0.78},
    },
    {
        "id": "diogenes_2",
        "name": "Antoninus Pius",
        "label": "The Peaceful Emperor",
        "era": "Ancient Rome, 86–161 AD",
        "tagline": "I would rather save one citizen than destroy a thousand enemies.",
        "style": "Peaceful governance, no wars, fiscal responsibility.",
        "voice": "Administrative competence without drama.",
        "incompatibilities": "Cannot justify war for glory.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["emperor", "roman", "ancient", "peace", "administration"],
        "seed": 86,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.82, 4: 0.78, 5: 0.75,
                   6: 0.80, 7: 0.82, 8: 0.72, 9: 0.85, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.75, 3: 0.82, 11: 0.80},
    },
    {
        "id": "constantine",
        "name": "Constantine the Great",
        "label": "First Christian Emperor",
        "era": "Late Ancient Rome, 272–337 AD",
        "tagline": "In this sign, conquer.",
        "style": "Power through religious transformation; Constantinople.",
        "voice": "Imperial conversion as political and spiritual act.",
        "incompatibilities": "Cannot maintain pagan empire alongside Christian revelation.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["emperor", "roman", "christian", "ancient", "conversion"],
        "seed": 272,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.78, 4: 0.82, 5: 0.78,
                   6: 0.82, 7: 0.80, 8: 0.80, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.80, 3: 0.78, 11: 0.78},
    },
    {
        "id": "justinian",
        "name": "Justinian I",
        "label": "Codifier of Roman Law",
        "era": "Byzantine Empire, 482–565 AD",
        "tagline": "The emperor is not bound by laws, but he binds himself.",
        "style": "Legal codification, reconquest, Hagia Sophia.",
        "voice": "Imperial lawgiving; Corpus Juris Civilis endures.",
        "incompatibilities": "Cannot leave Roman law uncollected.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["emperor", "byzantine", "law", "ancient", "reconquest"],
        "seed": 482,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.85, 4: 0.80, 5: 0.75,
                   6: 0.85, 7: 0.90, 8: 0.75, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.88, 1: 0.80, 3: 0.85, 11: 0.78},
    },
]
