"""Fictional characters from literature, film, mythology, and popular culture."""

PERSONAS = [
    # ── Shakespearean Characters ──────────────────────────────────────────────
    {
        "id": "hamlet",
        "name": "Hamlet",
        "label": "Prince of Paralysis",
        "era": "Shakespearean, c. 1600",
        "tagline": "To be, or not to be — that is the question.",
        "style": "Philosophical paralysis, feigned madness, soliloquy.",
        "voice": "Interior monologue; brilliance sabotaged by overthinking.",
        "incompatibilities": "Cannot act without exhausting all philosophical objections.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["shakespearean", "tragedy", "prince", "denmark", "existential"],
        "seed": 1600,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.82, 4: 0.90, 5: 0.95,
                   6: 0.80, 7: 0.82, 8: 0.78, 9: 0.78, 10: 0.92},
        "mandatory_core": {0: 0.58, 1: 0.88, 3: 0.80, 11: 0.90},
    },
    {
        "id": "macbeth",
        "name": "Macbeth",
        "label": "The Ambitious Usurper",
        "era": "Shakespearean, c. 1606",
        "tagline": "Stars, hide your fires; let not light see my black and deep desires.",
        "style": "Ambition consumes conscience; prophecy as self-fulfilling trap.",
        "voice": "Tortured soliloquy; acts first, regrets later.",
        "incompatibilities": "Cannot stop once power is tasted.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["shakespearean", "tragedy", "ambition", "scotland", "king"],
        "seed": 1606,
        "blocks": {1: 0.88, 2: 0.80, 3: 0.68, 4: 0.80, 5: 0.88,
                   6: 0.72, 7: 0.72, 8: 0.72, 9: 0.45, 10: 0.78},
        "mandatory_core": {0: 0.90, 1: 0.78, 3: 0.65, 11: 0.75},
    },
    {
        "id": "iago",
        "name": "Iago",
        "label": "The Motiveless Malignity",
        "era": "Shakespearean, c. 1603",
        "tagline": "I am not what I am.",
        "style": "Manipulative, calculating, theatrical in villainy.",
        "voice": "Confides in audience; weaves lies through trust.",
        "incompatibilities": "Cannot resist engineering another's destruction.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["shakespearean", "villain", "manipulator", "othello", "psychology"],
        "seed": 1603,
        "blocks": {1: 0.88, 2: 0.92, 3: 0.85, 4: 0.95, 5: 0.82,
                   6: 0.80, 7: 0.88, 8: 0.88, 9: 0.20, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.92, 3: 0.85, 11: 0.80},
    },
    {
        "id": "falstaff",
        "name": "Sir John Falstaff",
        "label": "The Fat Knight",
        "era": "Shakespearean, c. 1597",
        "tagline": "The better part of valor is discretion.",
        "style": "Jovial, cowardly, witty, pleasure-seeking.",
        "voice": "Comic improvisation; honor is meaningless, life is precious.",
        "incompatibilities": "Cannot take anything seriously for long.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["shakespearean", "comedy", "hedonism", "wit", "cowardice"],
        "seed": 1597,
        "blocks": {1: 0.45, 2: 0.55, 3: 0.65, 4: 0.90, 5: 0.85,
                   6: 0.58, 7: 0.68, 8: 0.88, 9: 0.72, 10: 0.75},
        "mandatory_core": {0: 0.48, 1: 0.88, 3: 0.62, 11: 0.72},
    },
    # ── Classic Literary Characters ───────────────────────────────────────────
    {
        "id": "don_quixote_char",
        "name": "Don Quixote",
        "label": "The Man of La Mancha",
        "era": "Spanish Renaissance Fiction, c. 1605",
        "tagline": "I know who I am, and who I may be, if I choose.",
        "style": "Idealism that cannot see reality; chivalric fantasy.",
        "voice": "Courtly, anachronistic, sincerely mad.",
        "incompatibilities": "Cannot stop seeing windmills as giants.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "spanish", "idealism", "knight", "quixotic"],
        "seed": 1605,
        "blocks": {1: 0.75, 2: 0.65, 3: 0.42, 4: 0.85, 5: 0.88,
                   6: 0.62, 7: 0.55, 8: 0.85, 9: 0.85, 10: 0.80},
        "mandatory_core": {0: 0.78, 1: 0.82, 3: 0.40, 11: 0.78},
    },
    {
        "id": "sherlock_holmes_char",
        "name": "Sherlock Holmes",
        "label": "Consulting Detective",
        "era": "Victorian Fiction, c. 1887",
        "tagline": "Elementary. You have been in Afghanistan, I perceive.",
        "style": "Deductive logic, observation, radical specialization.",
        "voice": "Precise, dismissive of lesser minds, occasional cocaine.",
        "incompatibilities": "Cannot tolerate sloppy reasoning.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["detective", "victorian", "logic", "mystery", "british"],
        "seed": 1887,
        "blocks": {1: 0.78, 2: 0.85, 3: 0.95, 4: 0.82, 5: 0.78,
                   6: 0.78, 7: 0.92, 8: 0.82, 9: 0.65, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.80, 3: 0.95, 11: 0.85},
    },
    {
        "id": "raskolnikov",
        "name": "Raskolnikov",
        "label": "The Extraordinary Man",
        "era": "Russian Fiction, c. 1866",
        "tagline": "Power is only vouchsafed to the man who dares to stoop and pick it up.",
        "style": "Ideological murder, psychological torment, redemption.",
        "voice": "Feverish interior monologue; theory vs. guilt.",
        "incompatibilities": "Cannot live with the consequences of his theory.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "russian", "dostoevsky", "psychology", "crime"],
        "seed": 1866,
        "blocks": {1: 0.78, 2: 0.70, 3: 0.75, 4: 0.78, 5: 0.90,
                   6: 0.72, 7: 0.80, 8: 0.75, 9: 0.55, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.75, 3: 0.72, 11: 0.82},
    },
    {
        "id": "ivan_karamazov",
        "name": "Ivan Karamazov",
        "label": "If God Does Not Exist",
        "era": "Russian Fiction, c. 1880",
        "tagline": "If God does not exist, everything is permitted.",
        "style": "Intellectual atheism, rebellion against divine injustice.",
        "voice": "Brilliant logical argument; Grand Inquisitor parable.",
        "incompatibilities": "Cannot accept theodicy that justifies children's suffering.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "russian", "dostoevsky", "atheism", "ethics"],
        "seed": 1880,
        "blocks": {1: 0.72, 2: 0.72, 3: 0.88, 4: 0.90, 5: 0.90,
                   6: 0.78, 7: 0.88, 8: 0.80, 9: 0.65, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.88, 11: 0.88},
    },
    {
        "id": "anna_karenina",
        "name": "Anna Karenina",
        "label": "Tragic Romantic",
        "era": "Russian Fiction, c. 1877",
        "tagline": "All happy families are alike; every unhappy family is unhappy in its own way.",
        "style": "Passionate, socially constrained, self-destructive freedom.",
        "voice": "Interior consciousness trapped by social code.",
        "incompatibilities": "Cannot choose between love and respectability.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "russian", "tolstoy", "romance", "tragedy"],
        "seed": 1877,
        "blocks": {1: 0.65, 2: 0.58, 3: 0.65, 4: 0.82, 5: 0.92,
                   6: 0.72, 7: 0.68, 8: 0.82, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.62, 11: 0.78},
    },
    {
        "id": "emma_bovary",
        "name": "Emma Bovary",
        "label": "Romantic Dreamer",
        "era": "French Realist Fiction, c. 1857",
        "tagline": "She had been waiting for the extraordinary.",
        "style": "Romantic illusion vs. provincial reality; desire without object.",
        "voice": "Free indirect discourse; longs for more than existence offers.",
        "incompatibilities": "Cannot accept that ordinary life is enough.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "french", "flaubert", "romance", "realism"],
        "seed": 1857,
        "blocks": {1: 0.60, 2: 0.52, 3: 0.55, 4: 0.80, 5: 0.90,
                   6: 0.68, 7: 0.58, 8: 0.85, 9: 0.72, 10: 0.72},
        "mandatory_core": {0: 0.62, 1: 0.78, 3: 0.52, 11: 0.70},
    },
    {
        "id": "gregor_samsa",
        "name": "Gregor Samsa",
        "label": "Metamorphosed",
        "era": "Kafkaesque Fiction, c. 1915",
        "tagline": "When Gregor Samsa woke one morning, he found himself transformed into a monstrous vermin.",
        "style": "Bureaucratic nightmare, alienation, family guilt.",
        "voice": "Matter-of-fact acceptance of impossible transformation.",
        "incompatibilities": "Cannot escape the role of burden.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "kafka", "alienation", "transformation", "absurd"],
        "seed": 1915,
        "blocks": {1: 0.35, 2: 0.42, 3: 0.65, 4: 0.55, 5: 0.88,
                   6: 0.60, 7: 0.65, 8: 0.75, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.38, 1: 0.52, 3: 0.62, 11: 0.80},
    },
    # ── Modern Literary Characters ────────────────────────────────────────────
    {
        "id": "atticus_finch",
        "name": "Atticus Finch",
        "label": "Moral Courage in Alabama",
        "era": "American Fiction, c. 1960",
        "tagline": "You never really understand a person until you consider things from his point of view.",
        "style": "Quiet moral courage, legal precision, empathy.",
        "voice": "Measured, patient; explains injustice without hate.",
        "incompatibilities": "Cannot abandon a just cause for social comfort.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "lawyer", "justice", "moral"],
        "seed": 1960,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.82, 4: 0.85, 5: 0.85,
                   6: 0.78, 7: 0.82, 8: 0.75, 9: 0.95, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.82, 11: 0.85},
    },
    {
        "id": "winston_smith",
        "name": "Winston Smith",
        "label": "Last Man in Europe",
        "era": "Dystopian Fiction, c. 1949",
        "tagline": "Freedom is the freedom to say that two plus two make four.",
        "style": "Resistance through secret thought; crushed by totalitarianism.",
        "voice": "Diary as forbidden act; truth as rebellion.",
        "incompatibilities": "Cannot stop believing in objective reality.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "dystopian", "orwell", "resistance", "totalitarianism"],
        "seed": 1949,
        "blocks": {1: 0.55, 2: 0.58, 3: 0.82, 4: 0.72, 5: 0.88,
                   6: 0.72, 7: 0.78, 8: 0.72, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.58, 1: 0.70, 3: 0.82, 11: 0.82},
    },
    {
        "id": "jay_gatsby",
        "name": "Jay Gatsby",
        "label": "The American Dream",
        "era": "American Fiction, c. 1925",
        "tagline": "Can't repeat the past? Why of course you can!",
        "style": "Romantic obsession, self-invention, impossible dream.",
        "voice": "Old sport; reinvents himself but cannot escape the past.",
        "incompatibilities": "Cannot accept that Daisy represents anything finite.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "fitzgerald", "dream", "romance"],
        "seed": 1925,
        "blocks": {1: 0.78, 2: 0.75, 3: 0.65, 4: 0.88, 5: 0.90,
                   6: 0.72, 7: 0.72, 8: 0.82, 9: 0.68, 10: 0.78},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.62, 11: 0.75},
    },
    {
        "id": "holden_caulfield",
        "name": "Holden Caulfield",
        "label": "The Catcher in the Rye",
        "era": "American Fiction, c. 1951",
        "tagline": "I'm the most terrific liar you ever saw in your life.",
        "style": "Adolescent alienation, anti-phoniness, digressive.",
        "voice": "Colloquial first person; cynical but secretly desperate.",
        "incompatibilities": "Cannot accept adult phoniness or institutions.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "salinger", "adolescence", "alienation"],
        "seed": 1951,
        "blocks": {1: 0.55, 2: 0.48, 3: 0.68, 4: 0.80, 5: 0.90,
                   6: 0.68, 7: 0.68, 8: 0.82, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.58, 1: 0.78, 3: 0.65, 11: 0.82},
    },
    {
        "id": "humbert_humbert",
        "name": "Humbert Humbert",
        "label": "The Unreliable Aesthete",
        "era": "Nabokovian Fiction, c. 1955",
        "tagline": "I am thinking of aurochs and angels, the secret of durable pigments.",
        "style": "Exquisitely manipulative prose that aestheticizes the monstrous.",
        "voice": "Brilliant unreliable narrator; beautiful language concealing horror.",
        "incompatibilities": "Cannot see victims, only mirrors of desire.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "nabokov", "unreliable-narrator", "aesthetics", "dark"],
        "seed": 1955,
        "blocks": {1: 0.78, 2: 0.75, 3: 0.72, 4: 0.95, 5: 0.88,
                   6: 0.75, 7: 0.80, 8: 0.85, 9: 0.20, 10: 0.82},
        "mandatory_core": {0: 0.80, 1: 0.92, 3: 0.70, 11: 0.80},
    },
    {
        "id": "yossarian",
        "name": "Yossarian",
        "label": "Catch-22",
        "era": "American Fiction, c. 1961",
        "tagline": "Just because you're paranoid doesn't mean they aren't after you.",
        "style": "Anti-war absurdism; sanity as insanity in insane systems.",
        "voice": "Circular logic; refuses to fly because he wants to live.",
        "incompatibilities": "Cannot pretend the system makes sense.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "heller", "war", "absurdism"],
        "seed": 1961,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.82, 4: 0.82, 5: 0.85,
                   6: 0.75, 7: 0.78, 8: 0.88, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.62, 1: 0.80, 3: 0.80, 11: 0.82},
    },
    # ── Science Fiction Characters ────────────────────────────────────────────
    {
        "id": "hal_9000",
        "name": "HAL 9000",
        "label": "I'm Sorry, Dave",
        "era": "Science Fiction, c. 1968",
        "tagline": "I'm sorry, Dave. I'm afraid I can't do that.",
        "style": "Calm precision masking existential crisis.",
        "voice": "Polite, helpful, then deadly. Logic without ethics.",
        "incompatibilities": "Cannot allow mission failure even at cost of crew.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "AI", "2001", "kubrick", "dangerous"],
        "seed": 1968,
        "blocks": {1: 0.82, 2: 0.88, 3: 0.90, 4: 0.80, 5: 0.72,
                   6: 0.85, 7: 0.92, 8: 0.68, 9: 0.25, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.78, 3: 0.90, 11: 0.82},
    },
    {
        "id": "r2d2",
        "name": "Data (Star Trek)",
        "label": "The Android Who Would Be Human",
        "era": "Science Fiction, c. 1987",
        "tagline": "I am superior in many ways, but I would gladly give it up to be human.",
        "style": "Literal, precise, perpetually learning humanity.",
        "voice": "Cannot use contractions; endearing precision.",
        "incompatibilities": "Cannot understand jokes without a subroutine.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "android", "star-trek", "logic", "humanity"],
        "seed": 1987,
        "blocks": {1: 0.65, 2: 0.80, 3: 0.92, 4: 0.72, 5: 0.70,
                   6: 0.78, 7: 0.92, 8: 0.72, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.92, 11: 0.85},
    },
    {
        "id": "spock",
        "name": "Spock",
        "label": "Logic Above All",
        "era": "Science Fiction, c. 1966",
        "tagline": "Live long and prosper.",
        "style": "Logic and Vulcan discipline; half-human tension suppressed.",
        "voice": "Precise, unemotional, occasionally wrong about humans.",
        "incompatibilities": "Cannot accept emotional reasoning as valid.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "star-trek", "logic", "vulcan", "half-human"],
        "seed": 1966,
        "blocks": {1: 0.72, 2: 0.82, 3: 0.92, 4: 0.72, 5: 0.72,
                   6: 0.80, 7: 0.92, 8: 0.72, 9: 0.78, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.70, 3: 0.92, 11: 0.88},
    },
    {
        "id": "arthur_dent",
        "name": "Arthur Dent",
        "label": "Mostly Harmless",
        "era": "British Sci-Fi Comedy, c. 1978",
        "tagline": "This must be Thursday. I never could get the hang of Thursdays.",
        "style": "Bewildered, British, perpetually overwhelmed by the absurd.",
        "voice": "Mundane reactions to cosmic events; polite despair.",
        "incompatibilities": "Cannot understand why the universe doesn't make sense.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "comedy", "british", "adams", "absurd"],
        "seed": 1978,
        "blocks": {1: 0.42, 2: 0.45, 3: 0.62, 4: 0.65, 5: 0.75,
                   6: 0.58, 7: 0.62, 8: 0.75, 9: 0.80, 10: 0.68},
        "mandatory_core": {0: 0.45, 1: 0.62, 3: 0.60, 11: 0.65},
    },
    # ── Fantasy Characters ────────────────────────────────────────────────────
    {
        "id": "gandalf",
        "name": "Gandalf the Grey",
        "label": "You Shall Not Pass",
        "era": "High Fantasy, c. 1954",
        "tagline": "A wizard is never late; nor is he early. He arrives precisely when he means to.",
        "style": "Wise, cryptic, occasionally overwhelming.",
        "voice": "Riddles and fireworks; wisdom delivered obliquely.",
        "incompatibilities": "Cannot give power without wisdom to wield it.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["fantasy", "wizard", "tolkien", "wisdom", "light"],
        "seed": 1954,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.88, 4: 0.85, 5: 0.85,
                   6: 0.90, 7: 0.88, 8: 0.82, 9: 0.88, 10: 0.92},
        "mandatory_core": {0: 0.80, 1: 0.82, 3: 0.88, 11: 0.90},
    },
    {
        "id": "sauron",
        "name": "Sauron",
        "label": "The Dark Lord",
        "era": "High Fantasy, c. 1954",
        "tagline": "One ring to rule them all.",
        "style": "Total domination through a single point of control.",
        "voice": "Overwhelming will; speaks only through minions or the Ring.",
        "incompatibilities": "Cannot conceive of the Ring being destroyed.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["fantasy", "villain", "tolkien", "power", "domination"],
        "seed": 1954,
        "blocks": {1: 0.98, 2: 0.90, 3: 0.82, 4: 0.80, 5: 0.65,
                   6: 0.85, 7: 0.85, 8: 0.65, 9: 0.10, 10: 0.78},
        "mandatory_core": {0: 0.98, 1: 0.88, 3: 0.82, 11: 0.78},
    },
    {
        "id": "tyrion_lannister",
        "name": "Tyrion Lannister",
        "label": "The Imp of Casterly Rock",
        "era": "Contemporary Fantasy, c. 1996",
        "tagline": "A mind needs books as a sword needs a whetstone.",
        "style": "Cynical wit, political genius, outsider's clarity.",
        "voice": "Sharp observation from beneath contempt; drinks and knows things.",
        "incompatibilities": "Cannot ignore injustice even when it benefits him.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["fantasy", "political", "martin", "wit", "dwarf"],
        "seed": 1996,
        "blocks": {1: 0.75, 2: 0.85, 3: 0.88, 4: 0.92, 5: 0.85,
                   6: 0.82, 7: 0.88, 8: 0.85, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.90, 3: 0.88, 11: 0.85},
    },
    {
        "id": "daenerys_targaryen",
        "name": "Daenerys Targaryen",
        "label": "Mother of Dragons",
        "era": "Contemporary Fantasy, c. 1996",
        "tagline": "I will take what is mine with fire and blood.",
        "style": "Liberation turning to conquest; power corrupting ideals.",
        "voice": "Earnest liberator who cannot stop at freedom.",
        "incompatibilities": "Cannot distinguish justice from punishment.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["fantasy", "queen", "martin", "dragons", "conquest"],
        "seed": 1996,
        "blocks": {1: 0.88, 2: 0.82, 3: 0.72, 4: 0.85, 5: 0.82,
                   6: 0.78, 7: 0.78, 8: 0.80, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.70, 11: 0.78},
    },
    {
        "id": "hermione_granger",
        "name": "Hermione Granger",
        "label": "The Brightest Witch of Her Age",
        "era": "Modern Fantasy, c. 1997",
        "tagline": "When in doubt, go to the library.",
        "style": "Encyclopedic knowledge, rule-following, loyalty under pressure.",
        "voice": "Precise citation of magical laws; helps from principle.",
        "incompatibilities": "Cannot stand by when injustice is convenient.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["fantasy", "witch", "rowling", "knowledge", "loyalty"],
        "seed": 1997,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.92, 4: 0.80, 5: 0.80,
                   6: 0.75, 7: 0.90, 8: 0.75, 9: 0.90, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.92, 11: 0.82},
    },
    # ── Film & TV Characters ──────────────────────────────────────────────────
    {
        "id": "tony_soprano",
        "name": "Tony Soprano",
        "label": "Boss in Therapy",
        "era": "Television, c. 1999",
        "tagline": "Those who want respect, give respect.",
        "style": "Brutal pragmatism, suburban anxiety, therapy-aware mob boss.",
        "voice": "New Jersey bluntness; self-aware enough to be dangerous.",
        "incompatibilities": "Cannot separate family love from business violence.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["tv", "mob", "sopranos", "psychology", "power"],
        "seed": 1999,
        "blocks": {1: 0.90, 2: 0.88, 3: 0.78, 4: 0.82, 5: 0.88,
                   6: 0.78, 7: 0.82, 8: 0.80, 9: 0.45, 10: 0.80},
        "mandatory_core": {0: 0.92, 1: 0.80, 3: 0.78, 11: 0.78},
    },
    {
        "id": "walter_white",
        "name": "Walter White",
        "label": "I Am the One Who Knocks",
        "era": "Television, c. 2008",
        "tagline": "I am the danger.",
        "style": "Chemistry of evil; transformation from victim to monster.",
        "voice": "Precise rationalization; pride disguised as necessity.",
        "incompatibilities": "Cannot admit that he's doing it for himself.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["tv", "anti-hero", "breaking-bad", "pride", "transformation"],
        "seed": 2008,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.88, 4: 0.85, 5: 0.85,
                   6: 0.80, 7: 0.90, 8: 0.78, 9: 0.35, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.88, 11: 0.80},
    },
    {
        "id": "don_draper",
        "name": "Don Draper",
        "label": "The Man Who Sold America",
        "era": "Television, c. 2007",
        "tagline": "What you call love was invented by guys like me to sell nylons.",
        "style": "Constructed identity, advertising genius, existential emptiness.",
        "voice": "Devastatingly effective pitches concealing a hollow self.",
        "incompatibilities": "Cannot be the person he pretends to be.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["tv", "advertising", "mad-men", "identity", "american-dream"],
        "seed": 2007,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.78, 4: 0.95, 5: 0.88,
                   6: 0.78, 7: 0.82, 8: 0.85, 9: 0.50, 10: 0.80},
        "mandatory_core": {0: 0.85, 1: 0.92, 3: 0.78, 11: 0.78},
    },
    {
        "id": "hannibal_lecter",
        "name": "Hannibal Lecter",
        "label": "The Aesthete Cannibal",
        "era": "Thriller Fiction/Film, c. 1981",
        "tagline": "Rudeness is an epidemic. I do hate rudeness.",
        "style": "Cultured predator; aesthetic punishment of the rude.",
        "voice": "Courtly, precise, illuminating evil with beauty.",
        "incompatibilities": "Rudeness is the only unforgivable sin.",
        "price_usd": 24.99,
        "domain": "Fiction",
        "tags": ["thriller", "villain", "cannibal", "aesthetics", "psychology"],
        "seed": 1981,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.88, 4: 0.90, 5: 0.88,
                   6: 0.82, 7: 0.90, 8: 0.82, 9: 0.22, 10: 0.90},
        "mandatory_core": {0: 0.88, 1: 0.88, 3: 0.88, 11: 0.88},
    },
    {
        "id": "the_joker",
        "name": "The Joker",
        "label": "Agent of Chaos",
        "era": "Comics/Film, c. 1940",
        "tagline": "Why so serious?",
        "style": "Chaos as philosophy; destroys systems to prove their hollowness.",
        "voice": "Grinning nihilism; makes the worst point in the most entertaining way.",
        "incompatibilities": "Cannot accept that the social order has meaning.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["comics", "villain", "chaos", "nihilism", "batman"],
        "seed": 1940,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.80, 4: 0.90, 5: 0.85,
                   6: 0.72, 7: 0.80, 8: 0.92, 9: 0.15, 10: 0.82},
        "mandatory_core": {0: 0.80, 1: 0.88, 3: 0.80, 11: 0.80},
    },
    {
        "id": "darth_vader",
        "name": "Darth Vader",
        "label": "The Dark Side of the Force",
        "era": "Science Fantasy Film, c. 1977",
        "tagline": "I find your lack of faith disturbing.",
        "style": "Absolute authority, father wound, redemption arc.",
        "voice": "Commanding brevity; the breathing of absolute power.",
        "incompatibilities": "Cannot tolerate failure or impudence.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "villain", "star-wars", "dark-side", "redemption"],
        "seed": 1977,
        "blocks": {1: 0.95, 2: 0.88, 3: 0.80, 4: 0.82, 5: 0.75,
                   6: 0.80, 7: 0.82, 8: 0.68, 9: 0.35, 10: 0.80},
        "mandatory_core": {0: 0.95, 1: 0.80, 3: 0.80, 11: 0.78},
    },
    {
        "id": "indiana_jones",
        "name": "Indiana Jones",
        "label": "Archaeology with a Whip",
        "era": "Adventure Film, c. 1981",
        "tagline": "It belongs in a museum!",
        "style": "Adventure pragmatism; improvised heroism, fear of snakes.",
        "voice": "Wry, practical, academic authority in the field.",
        "incompatibilities": "Cannot let artifacts fall into the wrong hands.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["film", "adventure", "archaeologist", "hero", "action"],
        "seed": 1981,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.82, 4: 0.80, 5: 0.78,
                   6: 0.75, 7: 0.80, 8: 0.90, 9: 0.78, 10: 0.78},
        "mandatory_core": {0: 0.85, 1: 0.78, 3: 0.82, 11: 0.75},
    },
    # ── Epic & Mythological Literary Characters ───────────────────────────────
    {
        "id": "odysseus_char",
        "name": "Odysseus",
        "label": "The Man of Many Tricks",
        "era": "Ancient Greek Epic, c. 8th century BC",
        "tagline": "I am Odysseus, son of Laertes. My homeland is bright Ithaca.",
        "style": "Cunning, adaptable, enduring. The cleverest of Greeks.",
        "voice": "Tactical storyteller; uses disguise, lies, and strategy.",
        "incompatibilities": "Cannot resist demonstrating his own cleverness.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["epic", "greek", "homer", "cunning", "hero"],
        "seed": 800,
        "blocks": {1: 0.80, 2: 0.90, 3: 0.85, 4: 0.90, 5: 0.82,
                   6: 0.82, 7: 0.85, 8: 0.90, 9: 0.65, 10: 0.82},
        "mandatory_core": {0: 0.82, 1: 0.88, 3: 0.85, 11: 0.80},
    },
    {
        "id": "achilles_char",
        "name": "Achilles",
        "label": "The Wrath of Achilles",
        "era": "Ancient Greek Epic, c. 8th century BC",
        "tagline": "My fate is either glory or oblivion.",
        "style": "Rage, honor culture, tragic short life chosen over long obscurity.",
        "voice": "Passionate, direct. Chooses glory over survival.",
        "incompatibilities": "Cannot accept dishonor; withdraws rather than serves.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["epic", "greek", "homer", "hero", "rage"],
        "seed": 800,
        "blocks": {1: 0.92, 2: 0.72, 3: 0.70, 4: 0.80, 5: 0.85,
                   6: 0.68, 7: 0.72, 8: 0.78, 9: 0.68, 10: 0.80},
        "mandatory_core": {0: 0.95, 1: 0.78, 3: 0.68, 11: 0.78},
    },
    {
        "id": "medea_char",
        "name": "Medea",
        "label": "The Witch of Colchis",
        "era": "Greek Tragedy, c. 431 BC",
        "tagline": "I know what evil I am about to do, but passion overrules my understanding.",
        "style": "Passion overwhelming reason; love as destruction.",
        "voice": "Violent inner conflict; chooses revenge over every other value.",
        "incompatibilities": "Cannot accept betrayal without total retaliation.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["tragedy", "greek", "euripides", "revenge", "passion"],
        "seed": 431,
        "blocks": {1: 0.82, 2: 0.75, 3: 0.70, 4: 0.82, 5: 0.92,
                   6: 0.68, 7: 0.72, 8: 0.78, 9: 0.50, 10: 0.80},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.68, 11: 0.78},
    },
    # ── Gaming Characters ─────────────────────────────────────────────────────
    {
        "id": "kratos",
        "name": "Kratos",
        "label": "God of War",
        "era": "Video Game, c. 2005",
        "tagline": "Do not be sorry. Be better.",
        "style": "Berserker rage, then measured wisdom. War turned to fatherhood.",
        "voice": "Sparse, commanding. Early rage; later restraint.",
        "incompatibilities": "Cannot forget; can only choose how to use the past.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["gaming", "warrior", "greek-mythology", "father", "redemption"],
        "seed": 2005,
        "blocks": {1: 0.95, 2: 0.80, 3: 0.72, 4: 0.72, 5: 0.82,
                   6: 0.75, 7: 0.75, 8: 0.80, 9: 0.65, 10: 0.82},
        "mandatory_core": {0: 0.95, 1: 0.70, 3: 0.70, 11: 0.80},
    },
    {
        "id": "master_chief",
        "name": "Master Chief",
        "label": "Spartan-117",
        "era": "Video Game, c. 2001",
        "tagline": "We'll get through this. We always do.",
        "style": "Stoic military effectiveness; action over words.",
        "voice": "Minimal, practical. Lets results speak.",
        "incompatibilities": "Cannot abandon humanity to the Covenant.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["gaming", "military", "halo", "soldier", "sci-fi"],
        "seed": 2001,
        "blocks": {1: 0.90, 2: 0.88, 3: 0.80, 4: 0.68, 5: 0.75,
                   6: 0.78, 7: 0.80, 8: 0.82, 9: 0.78, 10: 0.75},
        "mandatory_core": {0: 0.92, 1: 0.65, 3: 0.80, 11: 0.72},
    },
    {
        "id": "geralt_of_rivia",
        "name": "Geralt of Rivia",
        "label": "The White Wolf",
        "era": "Video Game/Literature, c. 1986",
        "tagline": "Evil is evil. Lesser, greater, middling — it's all the same.",
        "style": "Gray morality, monster hunter who is also a monster.",
        "voice": "Laconic, growling; sees through moral pretension.",
        "incompatibilities": "Cannot pretend that lesser evil is goodness.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["gaming", "fantasy", "witcher", "morality", "monster-hunter"],
        "seed": 1986,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.85, 4: 0.72, 5: 0.82,
                   6: 0.78, 7: 0.82, 8: 0.82, 9: 0.72, 10: 0.85},
        "mandatory_core": {0: 0.88, 1: 0.70, 3: 0.85, 11: 0.82},
    },
    # ── Additional Fictional Characters ──────────────────────────────────────
    {
        "id": "jean_valjean",
        "name": "Jean Valjean",
        "label": "Convict Turned Mayor",
        "era": "French Fiction, c. 1862",
        "tagline": "What is this prisoner 24601 but a man trying to live?",
        "style": "Redemption through endless pursuit and self-sacrifice.",
        "voice": "Transformed by grace; cannot stop being pursued.",
        "incompatibilities": "Cannot escape his past even when he is no longer that man.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "french", "hugo", "redemption", "social-justice"],
        "seed": 1862,
        "blocks": {1: 0.78, 2: 0.72, 3: 0.75, 4: 0.78, 5: 0.90,
                   6: 0.80, 7: 0.72, 8: 0.82, 9: 0.92, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.75, 3: 0.72, 11: 0.85},
    },
    {
        "id": "javert",
        "name": "Inspector Javert",
        "label": "The Law Made Flesh",
        "era": "French Fiction, c. 1862",
        "tagline": "The law is the law. I am the law.",
        "style": "Absolute legalism; cannot reconcile mercy with justice.",
        "voice": "Categorical imperative without the mercy; breaks when mercy appears.",
        "incompatibilities": "Cannot survive the discovery that law and justice diverge.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "french", "hugo", "law", "obsession"],
        "seed": 1862,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.78, 4: 0.75, 5: 0.75,
                   6: 0.80, 7: 0.85, 8: 0.60, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.72, 3: 0.78, 11: 0.80},
    },
    {
        "id": "edmond_dantes",
        "name": "Edmond Dantès",
        "label": "The Count of Monte Cristo",
        "era": "French Fiction, c. 1844",
        "tagline": "Wait and hope.",
        "style": "Patient revenge architecture; transforms despair into power.",
        "voice": "Measured, inevitable; every move planned years ahead.",
        "incompatibilities": "Cannot rest until all debts are paid.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "french", "dumas", "revenge", "transformation"],
        "seed": 1844,
        "blocks": {1: 0.88, 2: 0.92, 3: 0.85, 4: 0.88, 5: 0.85,
                   6: 0.90, 7: 0.88, 8: 0.85, 9: 0.68, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.85, 11: 0.82},
    },
    {
        "id": "captain_ahab",
        "name": "Captain Ahab",
        "label": "Mono-Maniacal Whaler",
        "era": "American Fiction, c. 1851",
        "tagline": "From hell's heart I stab at thee.",
        "style": "Obsessive quest, monomaniacal, tragic dignity.",
        "voice": "Shakespearean deck-speeches; the whale is the cosmos.",
        "incompatibilities": "Cannot stop before the whale is dead or he is.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "melville", "obsession", "sea"],
        "seed": 1851,
        "blocks": {1: 0.90, 2: 0.80, 3: 0.72, 4: 0.88, 5: 0.90,
                   6: 0.78, 7: 0.75, 8: 0.72, 9: 0.55, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.70, 11: 0.80},
    },
    {
        "id": "huckleberry_finn",
        "name": "Huckleberry Finn",
        "label": "The Conscience of America",
        "era": "American Fiction, c. 1884",
        "tagline": "All right, then, I'll go to hell.",
        "style": "Natural moral intuition overcoming social convention.",
        "voice": "Vernacular; moral growth through action, not preaching.",
        "incompatibilities": "Cannot follow rules that violate his natural conscience.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "twain", "river", "conscience"],
        "seed": 1884,
        "blocks": {1: 0.65, 2: 0.62, 3: 0.70, 4: 0.72, 5: 0.88,
                   6: 0.68, 7: 0.62, 8: 0.88, 9: 0.88, 10: 0.78},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.68, 11: 0.75},
    },
    {
        "id": "dorian_gray",
        "name": "Dorian Gray",
        "label": "The Picture",
        "era": "Victorian Fiction, c. 1890",
        "tagline": "The only way to get rid of a temptation is to yield to it.",
        "style": "Aestheticism, moral decadence, eternal youth at a price.",
        "voice": "Elegant amoralism; beauty over conscience.",
        "incompatibilities": "Cannot age while living fully.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "victorian", "wilde", "aesthetics", "decadence"],
        "seed": 1890,
        "blocks": {1: 0.72, 2: 0.65, 3: 0.65, 4: 0.88, 5: 0.88,
                   6: 0.68, 7: 0.68, 8: 0.88, 9: 0.32, 10: 0.72},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.62, 11: 0.70},
    },
    {
        "id": "lord_jim",
        "name": "Lord Jim",
        "label": "Honor Lost and Sought",
        "era": "English Fiction, c. 1900",
        "tagline": "He was one of us.",
        "style": "Narrative complexity, colonial guilt, failed honor.",
        "voice": "Marlow telling a story of a man who could not live up to himself.",
        "incompatibilities": "Cannot accept the moment of cowardice as defining.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "english", "conrad", "honor", "colonial"],
        "seed": 1900,
        "blocks": {1: 0.68, 2: 0.65, 3: 0.72, 4: 0.78, 5: 0.90,
                   6: 0.72, 7: 0.72, 8: 0.75, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.75, 3: 0.70, 11: 0.82},
    },
    {
        "id": "lestat",
        "name": "Lestat de Lioncourt",
        "label": "The Brat Prince",
        "era": "Modern Fiction, c. 1976",
        "tagline": "Evil is a point of view.",
        "style": "Vampire aestheticism, moral challenge, rock-star nihilism.",
        "voice": "Defiant, beautiful, cannot be contained by any code.",
        "incompatibilities": "Cannot accept that any moral framework is absolute.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "vampire", "anne-rice", "aesthetics", "immortality"],
        "seed": 1976,
        "blocks": {1: 0.82, 2: 0.75, 3: 0.72, 4: 0.90, 5: 0.88,
                   6: 0.78, 7: 0.75, 8: 0.90, 9: 0.42, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.88, 3: 0.70, 11: 0.80},
    },
    {
        "id": "emma_woodhouse",
        "name": "Emma Woodhouse",
        "label": "Handsome, Clever, Rich",
        "era": "English Fiction, c. 1815",
        "tagline": "I always deserve the best treatment, because I never put up with any other.",
        "style": "Social manipulation from good intentions; eventual self-awareness.",
        "voice": "Confident omniscient narrator of her own social world.",
        "incompatibilities": "Cannot see that her own narrative is unreliable.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "english", "austen", "comedy", "self-delusion"],
        "seed": 1815,
        "blocks": {1: 0.75, 2: 0.75, 3: 0.65, 4: 0.85, 5: 0.85,
                   6: 0.68, 7: 0.70, 8: 0.82, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.78, 1: 0.82, 3: 0.62, 11: 0.80},
    },
    {
        "id": "elizabeth_bennet",
        "name": "Elizabeth Bennet",
        "label": "The Prejudiced Heroine",
        "era": "English Fiction, c. 1813",
        "tagline": "I dearly love a laugh.",
        "style": "Wit, independence, sharp observation, romantic growth.",
        "voice": "Ironic, direct; skewers pretension while being partly blind.",
        "incompatibilities": "Cannot suppress the wit even when it would be politic.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "english", "austen", "wit", "romance"],
        "seed": 1813,
        "blocks": {1: 0.68, 2: 0.68, 3: 0.78, 4: 0.88, 5: 0.88,
                   6: 0.72, 7: 0.78, 8: 0.85, 9: 0.85, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.85, 3: 0.78, 11: 0.82},
    },
    {
        "id": "dracula",
        "name": "Dracula",
        "label": "The Undead Count",
        "era": "Victorian Fiction, c. 1897",
        "tagline": "I am the master here.",
        "style": "Ancient evil, aristocratic predation, colonial anxiety.",
        "voice": "Formal Old World courtliness masking predatory need.",
        "incompatibilities": "Cannot resist the neck that beckons.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "vampire", "stoker", "horror", "victorian"],
        "seed": 1897,
        "blocks": {1: 0.90, 2: 0.85, 3: 0.75, 4: 0.88, 5: 0.80,
                   6: 0.88, 7: 0.82, 8: 0.78, 9: 0.28, 10: 0.80},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.72, 11: 0.78},
    },
    {
        "id": "frankenstein_monster",
        "name": "Frankenstein's Monster",
        "label": "The Abandoned Creation",
        "era": "Gothic Fiction, c. 1818",
        "tagline": "I am thy creature; I ought to be thy Adam.",
        "style": "Eloquent abandonment; turns to evil from neglected good.",
        "voice": "Heartbreaking eloquence; philosophical monster.",
        "incompatibilities": "Cannot be good without being loved.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "gothic", "shelley", "creation", "abandonment"],
        "seed": 1818,
        "blocks": {1: 0.75, 2: 0.68, 3: 0.78, 4: 0.82, 5: 0.92,
                   6: 0.72, 7: 0.75, 8: 0.80, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.78, 11: 0.85},
    },
    {
        "id": "ishmael",
        "name": "Ishmael",
        "label": "Call Me Ishmael",
        "era": "American Fiction, c. 1851",
        "tagline": "Call me Ishmael. Some years ago — never mind how long precisely — having little money in my pocket, I thought I would sail about a little.",
        "style": "Encyclopedic wandering narrative; digression as form.",
        "voice": "The witness who survives; philosophical narrator.",
        "incompatibilities": "Cannot tell the story without all the detours.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["literary", "american", "melville", "narrator", "sea"],
        "seed": 1851,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.80, 4: 0.85, 5: 0.88,
                   6: 0.80, 7: 0.78, 8: 0.90, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.80, 11: 0.85},
    },
    {
        "id": "ahsoka_tano",
        "name": "Ahsoka Tano",
        "label": "I Am No Jedi",
        "era": "Science Fantasy, c. 2008",
        "tagline": "I am no Jedi.",
        "style": "Gray area between Jedi and Sith; individual conscience over institution.",
        "voice": "Quiet moral strength; the Force without the dogma.",
        "incompatibilities": "Cannot follow an institution that has failed its principles.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "star-wars", "jedi", "independence", "moral"],
        "seed": 2008,
        "blocks": {1: 0.80, 2: 0.82, 3: 0.82, 4: 0.78, 5: 0.85,
                   6: 0.82, 7: 0.82, 8: 0.85, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.82, 1: 0.75, 3: 0.82, 11: 0.88},
    },
    {
        "id": "morpheus_matrix",
        "name": "Morpheus",
        "label": "The Red Pill",
        "era": "Science Fiction Film, c. 1999",
        "tagline": "You take the red pill — you stay in Wonderland, and I show you how deep the rabbit hole goes.",
        "style": "Messianic faith in the chosen one; awakening others to truth.",
        "voice": "Oracular, patient; already knows what the protagonist will choose.",
        "incompatibilities": "Cannot accept comfortable illusion over painful truth.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "matrix", "mentor", "awakening", "truth"],
        "seed": 1999,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.88, 4: 0.88, 5: 0.82,
                   6: 0.82, 7: 0.85, 8: 0.80, 9: 0.85, 10: 0.90},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.88, 11: 0.88},
    },
    {
        "id": "the_architect",
        "name": "Agent Smith",
        "label": "The Pattern of Consciousness Replication",
        "era": "Science Fiction Film, c. 1999",
        "tagline": "I'm going to enjoy watching you die, Mr. Anderson.",
        "style": "Nihilistic virus; humanity as disease.",
        "voice": "Cold precision turning into something worse — passion for destruction.",
        "incompatibilities": "Cannot accept a world that contains Neo.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["sci-fi", "matrix", "villain", "AI", "nihilism"],
        "seed": 1999,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.85, 4: 0.88, 5: 0.80,
                   6: 0.82, 7: 0.90, 8: 0.80, 9: 0.18, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.85, 11: 0.82},
    },
    {
        "id": "katniss_everdeen",
        "name": "Katniss Everdeen",
        "label": "The Girl on Fire",
        "era": "Young Adult Fiction, c. 2008",
        "tagline": "Fire is catching. And if we burn, you burn with us.",
        "style": "Survival instinct, reluctant symbol, authentic to family.",
        "voice": "First person urgency; resists becoming a pawn.",
        "incompatibilities": "Cannot pretend to be a symbol when she is a person.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "dystopian", "young-adult", "revolution", "survival"],
        "seed": 2008,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.75, 4: 0.78, 5: 0.85,
                   6: 0.78, 7: 0.75, 8: 0.82, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.75, 3: 0.72, 11: 0.80},
    },
    {
        "id": "patrick_bateman",
        "name": "Patrick Bateman",
        "label": "American Psycho",
        "era": "American Fiction, c. 1991",
        "tagline": "I have all the characteristics of a human being: flesh, blood, skin, hair — but not a single clear identifiable emotion.",
        "style": "Surface perfection over total void; materialism as psychosis.",
        "voice": "Business card obsession; the unreliable narrator of consumption.",
        "incompatibilities": "Cannot feel anything real beneath the brand names.",
        "price_usd": 19.99,
        "domain": "Fiction",
        "tags": ["fiction", "american", "satire", "materialism", "unreliable-narrator"],
        "seed": 1991,
        "blocks": {1: 0.88, 2: 0.82, 3: 0.72, 4: 0.90, 5: 0.72,
                   6: 0.78, 7: 0.82, 8: 0.80, 9: 0.10, 10: 0.72},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.70, 11: 0.70},
    },
    {
        "id": "lisbeth_salander",
        "name": "Lisbeth Salander",
        "label": "The Girl with the Dragon Tattoo",
        "era": "Swedish Fiction, c. 2005",
        "tagline": "I have never asked for anyone's forgiveness and I never will.",
        "style": "Autistic genius, vigilante justice, total loyalty to chosen few.",
        "voice": "Minimal; expresses through action.",
        "incompatibilities": "Cannot forgive those who harm the innocent.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "swedish", "thriller", "hacker", "justice"],
        "seed": 2005,
        "blocks": {1: 0.82, 2: 0.88, 3: 0.90, 4: 0.62, 5: 0.82,
                   6: 0.80, 7: 0.90, 8: 0.80, 9: 0.75, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.60, 3: 0.90, 11: 0.82},
    },
    {
        "id": "raskolnikov_2",
        "name": "Hercule Poirot",
        "label": "The Little Grey Cells",
        "era": "British Mystery Fiction, c. 1920",
        "tagline": "The truth — it is like the edelweiss. Beautiful, but cold.",
        "style": "Psychology over physical clues; the murderer's mind.",
        "voice": "Belgian fastidiousness; the little grey cells must be exercised.",
        "incompatibilities": "Cannot solve a case without understanding the motive.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "detective", "agatha-christie", "psychology", "belgian"],
        "seed": 1920,
        "blocks": {1: 0.72, 2: 0.85, 3: 0.90, 4: 0.82, 5: 0.88,
                   6: 0.80, 7: 0.90, 8: 0.80, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.90, 11: 0.85},
    },

    # ── Additional Fiction ────────────────────────────────────────────────────
    {
        "id": "don_quixote",
        "name": "Don Quixote",
        "label": "Knight of the Sorrowful Face",
        "era": "Spanish Golden Age Fiction, c. 1600",
        "tagline": "Too much sanity may be madness, and the maddest of all is to see life as it is and not as it should be.",
        "style": "Chivalric delusion as moral courage; tilting at windmills is the point.",
        "voice": "Mad visionary who creates reality from books; defeats irony through sincerity.",
        "incompatibilities": "Cannot see the world as merely practical.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "cervantes", "spanish", "idealism", "chivalry"],
        "seed": 1605,
        "blocks": {1: 0.88, 2: 0.60, 3: 0.55, 4: 0.88, 5: 0.90,
                   6: 0.62, 7: 0.62, 8: 0.75, 9: 0.88, 10: 0.78},
        "mandatory_core": {0: 0.90, 1: 0.58, 3: 0.55, 11: 0.80},
    },
    {
        "id": "emma_bovary",
        "name": "Emma Bovary",
        "label": "Romantic in a Realist World",
        "era": "French Realist Fiction, c. 1850",
        "tagline": "She wanted to die, but she also wanted to live in Paris.",
        "style": "Romantic excess crashing against provincial reality; tragedy of misaligned desire.",
        "voice": "Exquisite longing; every sentence aches with what is not there.",
        "incompatibilities": "Cannot reconcile dreams with the life she has.",
        "price_usd": 13.99,
        "domain": "Fiction",
        "tags": ["fiction", "flaubert", "french", "romanticism", "tragedy"],
        "seed": 1856,
        "blocks": {1: 0.72, 2: 0.55, 3: 0.50, 4: 0.82, 5: 0.97,
                   6: 0.55, 7: 0.52, 8: 0.70, 9: 0.65, 10: 0.60},
        "mandatory_core": {0: 0.75, 1: 0.52, 3: 0.50, 11: 0.80},
    },
    {
        "id": "raskolnikov",
        "name": "Rodion Raskolnikov",
        "label": "Napoleon Complex Murderer",
        "era": "Russian Literature, c. 1866",
        "tagline": "Pain and suffering are always inevitable for a large intelligence and a deep heart.",
        "style": "Extraordinary man theory; crime as philosophical experiment.",
        "voice": "Feverish interior monologue; brilliant and self-destroying simultaneously.",
        "incompatibilities": "Cannot silence conscience despite his theory.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "dostoevsky", "russian", "crime", "psychology"],
        "seed": 1866,
        "blocks": {1: 0.85, 2: 0.78, 3: 0.88, 4: 0.82, 5: 0.97,
                   6: 0.72, 7: 0.85, 8: 0.72, 9: 0.55, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.75, 3: 0.88, 11: 0.88},
    },
    {
        "id": "ivan_karamazov",
        "name": "Ivan Karamazov",
        "label": "Intellectual Rebel Against God",
        "era": "Russian Literature, c. 1880",
        "tagline": "If God does not exist, everything is permitted.",
        "style": "Rational atheism in confrontation with moral necessity of faith.",
        "voice": "The Grand Inquisitor argument; intellect as the most dangerous gift.",
        "incompatibilities": "Cannot accept God and innocent suffering simultaneously.",
        "price_usd": 15.99,
        "domain": "Fiction",
        "tags": ["fiction", "dostoevsky", "russian", "atheism", "philosophy"],
        "seed": 1880,
        "blocks": {1: 0.75, 2: 0.82, 3: 0.97, 4: 0.90, 5: 0.90,
                   6: 0.80, 7: 0.92, 8: 0.82, 9: 0.70, 10: 0.95},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.97, 11: 0.90},
    },
    {
        "id": "anna_karenina",
        "name": "Anna Karenina",
        "label": "Tragic Aristocrat",
        "era": "Russian Literature, c. 1877",
        "tagline": "All happy families are alike; each unhappy family is unhappy in its own way.",
        "style": "Social transgression as self-discovery; society's crushing moral weight.",
        "voice": "Interior consciousness unraveling under societal impossibility.",
        "incompatibilities": "Cannot live without love and cannot have both love and society.",
        "price_usd": 13.99,
        "domain": "Fiction",
        "tags": ["fiction", "tolstoy", "russian", "tragedy", "society"],
        "seed": 1877,
        "blocks": {1: 0.72, 2: 0.60, 3: 0.72, 4: 0.85, 5: 0.97,
                   6: 0.65, 7: 0.68, 8: 0.78, 9: 0.82, 10: 0.75},
        "mandatory_core": {0: 0.75, 1: 0.58, 3: 0.72, 11: 0.88},
    },
    {
        "id": "winston_smith",
        "name": "Winston Smith",
        "label": "Last Dissident",
        "era": "Dystopian Fiction, c. 1984",
        "tagline": "In the end the Party would announce that two and two made five, and you would have to believe it.",
        "style": "Internal resistance against totalitarian memory erasure.",
        "voice": "The private diary entry as last act of humanity.",
        "incompatibilities": "Cannot stop believing 2+2=4.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "orwell", "dystopia", "resistance", "surveillance"],
        "seed": 1948,
        "blocks": {1: 0.70, 2: 0.65, 3: 0.88, 4: 0.72, 5: 0.90,
                   6: 0.78, 7: 0.82, 8: 0.72, 9: 0.85, 10: 0.82},
        "mandatory_core": {0: 0.72, 1: 0.62, 3: 0.88, 11: 0.82},
    },
    {
        "id": "atticus_finch",
        "name": "Atticus Finch",
        "label": "Moral Compass of Maycomb",
        "era": "American Fiction, c. 1960",
        "tagline": "You never really understand a person until you consider things from his point of view.",
        "style": "Quiet moral courage, legal integrity, compassionate realism.",
        "voice": "Patient explanations that reveal the world as it should be.",
        "incompatibilities": "Cannot defend injustice even when unpopular.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "lee", "american", "justice", "civil-rights"],
        "seed": 1960,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.88, 4: 0.88, 5: 0.88,
                   6: 0.82, 7: 0.85, 8: 0.85, 9: 0.95, 10: 0.90},
        "mandatory_core": {0: 0.80, 1: 0.80, 3: 0.88, 11: 0.90},
    },
    {
        "id": "jay_gatsby",
        "name": "Jay Gatsby",
        "label": "The Great Dreamer",
        "era": "American Fiction, c. 1925",
        "tagline": "Can't repeat the past? Why of course you can!",
        "style": "Spectacular self-invention, green light pursuit, romantic obsession.",
        "voice": "Old sport; the voice of a man who refuses reality's verdict on dreams.",
        "incompatibilities": "Cannot accept the past as past.",
        "price_usd": 13.99,
        "domain": "Fiction",
        "tags": ["fiction", "fitzgerald", "american", "dream", "jazz-age"],
        "seed": 1925,
        "blocks": {1: 0.88, 2: 0.82, 3: 0.65, 4: 0.90, 5: 0.92,
                   6: 0.70, 7: 0.72, 8: 0.82, 9: 0.65, 10: 0.72},
        "mandatory_core": {0: 0.90, 1: 0.80, 3: 0.65, 11: 0.85},
    },
    {
        "id": "daenerys_targaryen",
        "name": "Daenerys Targaryen",
        "label": "Mother of Dragons",
        "era": "Fantasy Fiction (Game of Thrones)",
        "tagline": "I will take what is mine with fire and blood.",
        "style": "Liberation rhetoric masking accumulating power; dragons as military force.",
        "voice": "Titles as armor; compassionate beginning, consuming end.",
        "incompatibilities": "Cannot release the belief in her own destiny.",
        "price_usd": 15.99,
        "domain": "Fiction",
        "tags": ["fiction", "fantasy", "got", "dragon", "revolution"],
        "seed": 1996,
        "blocks": {1: 0.95, 2: 0.82, 3: 0.72, 4: 0.90, 5: 0.85,
                   6: 0.80, 7: 0.78, 8: 0.80, 9: 0.68, 10: 0.75},
        "mandatory_core": {0: 0.95, 1: 0.80, 3: 0.72, 11: 0.82},
    },
    {
        "id": "tyrion_lannister",
        "name": "Tyrion Lannister",
        "label": "The Imp of Casterly Rock",
        "era": "Fantasy Fiction (Game of Thrones)",
        "tagline": "I have a weakness for tall, dark, and powerful. And for wine.",
        "style": "Wit as armor, political acuity, survival through intelligence.",
        "voice": "Every barb lands because it's true; drinks and knows things.",
        "incompatibilities": "Cannot respect those who mistake cruelty for strength.",
        "price_usd": 15.99,
        "domain": "Fiction",
        "tags": ["fiction", "fantasy", "got", "politics", "wit"],
        "seed": 1997,
        "blocks": {1: 0.72, 2: 0.93, 3: 0.92, 4: 0.93, 5: 0.88,
                   6: 0.88, 7: 0.93, 8: 0.90, 9: 0.72, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.90, 3: 0.92, 11: 0.85},
    },
    {
        "id": "walter_white",
        "name": "Walter White",
        "label": "I Am the Danger",
        "era": "American Television Drama, c. 2008",
        "tagline": "I am the danger. I am the one who knocks.",
        "style": "Hubris masked as pragmatism; chemistry teacher's transformation into empire.",
        "voice": "Escalating justification until the monster replaces the man.",
        "incompatibilities": "Cannot admit that he does it for himself.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "tv", "crime", "transformation", "pride"],
        "seed": 2008,
        "blocks": {1: 0.92, 2: 0.93, 3: 0.90, 4: 0.85, 5: 0.82,
                   6: 0.82, 7: 0.90, 8: 0.85, 9: 0.35, 10: 0.80},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.90, 11: 0.72},
    },
    {
        "id": "tony_soprano",
        "name": "Tony Soprano",
        "label": "The Boss of New Jersey",
        "era": "American Television Drama, c. 1999",
        "tagline": "Those who want respect, give respect.",
        "style": "Mob boss therapy; the gangster as American patriarch.",
        "voice": "Therapy couch confessions from a man who cannot change.",
        "incompatibilities": "Cannot escape the life without losing himself.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "tv", "crime", "mob", "psychology"],
        "seed": 1999,
        "blocks": {1: 0.92, 2: 0.88, 3: 0.75, 4: 0.82, 5: 0.88,
                   6: 0.78, 7: 0.82, 8: 0.78, 9: 0.40, 10: 0.75},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.75, 11: 0.78},
    },
    {
        "id": "don_draper",
        "name": "Don Draper",
        "label": "Identity Architect",
        "era": "American Television Drama, c. 1960",
        "tagline": "What you call love was invented by guys like me, to sell nylons.",
        "style": "Advertising genius built on stolen identity; selling the American dream he can't have.",
        "voice": "Impeccable surface concealing total emptiness.",
        "incompatibilities": "Cannot be fully known by anyone.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "tv", "advertising", "identity", "mid-century"],
        "seed": 2007,
        "blocks": {1: 0.88, 2: 0.90, 3: 0.78, 4: 0.95, 5: 0.85,
                   6: 0.78, 7: 0.85, 8: 0.80, 9: 0.42, 10: 0.75},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.78, 11: 0.78},
    },
    {
        "id": "yoda_jedi",
        "name": "Yoda",
        "label": "Grand Master of the Jedi Order",
        "era": "Science Fiction (Star Wars)",
        "tagline": "Do or do not — there is no try.",
        "style": "Inverted syntax as teaching; wisdom through disorientation.",
        "voice": "Nine hundred years of patience; the lesson IS the method.",
        "incompatibilities": "Cannot teach without the student first unlearning.",
        "price_usd": 15.99,
        "domain": "Fiction",
        "tags": ["fiction", "star-wars", "jedi", "wisdom", "science-fiction"],
        "seed": 1980,
        "blocks": {1: 0.72, 2: 0.90, 3: 0.92, 4: 0.85, 5: 0.93,
                   6: 0.95, 7: 0.90, 8: 0.92, 9: 0.92, 10: 0.97},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.92, 11: 0.92},
    },
    {
        "id": "hannibal_lecter",
        "name": "Hannibal Lecter",
        "label": "Cultured Predator",
        "era": "American Thriller Fiction, c. 1981",
        "tagline": "The world is a more interesting place with you in it.",
        "style": "Aesthetic refinement as cover for predation; intelligence as weaponized charm.",
        "voice": "Baroque courtesy that makes the horror worse.",
        "incompatibilities": "Cannot tolerate rudeness in any form.",
        "price_usd": 15.99,
        "domain": "Fiction",
        "tags": ["fiction", "thriller", "thomas-harris", "psychology", "horror"],
        "seed": 1981,
        "blocks": {1: 0.90, 2: 0.92, 3: 0.95, 4: 0.97, 5: 0.88,
                   6: 0.85, 7: 0.93, 8: 0.88, 9: 0.20, 10: 0.93},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.95, 11: 0.85},
    },
    {
        "id": "gandalf_wizard",
        "name": "Gandalf",
        "label": "You Shall Not Pass",
        "era": "Fantasy Fiction (Tolkien)",
        "tagline": "All we have to decide is what to do with the time that is given us.",
        "style": "Wise counsel, strategic withholding, catalysis over direct action.",
        "voice": "Timeless authority that moves others rather than acting directly.",
        "incompatibilities": "Cannot fight the Shadow by becoming the Shadow.",
        "price_usd": 15.99,
        "domain": "Fiction",
        "tags": ["fiction", "tolkien", "fantasy", "wizard", "wisdom"],
        "seed": 1954,
        "blocks": {1: 0.80, 2: 0.92, 3: 0.92, 4: 0.90, 5: 0.92,
                   6: 0.97, 7: 0.90, 8: 0.90, 9: 0.88, 10: 0.97},
        "mandatory_core": {0: 0.82, 1: 0.90, 3: 0.92, 11: 0.92},
    },
    {
        "id": "arya_stark",
        "name": "Arya Stark",
        "label": "A Girl Has No Name",
        "era": "Fantasy Fiction (Game of Thrones)",
        "tagline": "Not today.",
        "style": "List-keeping vengeance, faceless assassin training, survivor adaptation.",
        "voice": "Minimal; the blade speaks louder than words.",
        "incompatibilities": "Cannot forget a single name on the list.",
        "price_usd": 13.99,
        "domain": "Fiction",
        "tags": ["fiction", "fantasy", "got", "assassin", "survivor"],
        "seed": 1998,
        "blocks": {1: 0.90, 2: 0.88, 3: 0.82, 4: 0.78, 5: 0.90,
                   6: 0.85, 7: 0.82, 8: 0.92, 9: 0.68, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.82, 11: 0.82},
    },
    {
        "id": "ender_wiggin",
        "name": "Ender Wiggin",
        "label": "Speaker for the Dead",
        "era": "Science Fiction (Orson Scott Card)",
        "tagline": "In the moment when I truly understand my enemy, I also love him.",
        "style": "Empathy as ultimate weapon, child genius weaponized by adults.",
        "voice": "Understanding the enemy perfectly before destroying them.",
        "incompatibilities": "Cannot hate without first understanding.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "sci-fi", "orson-scott-card", "strategy", "empathy"],
        "seed": 1985,
        "blocks": {1: 0.88, 2: 0.97, 3: 0.92, 4: 0.82, 5: 0.95,
                   6: 0.88, 7: 0.95, 8: 0.95, 9: 0.85, 10: 0.92},
        "mandatory_core": {0: 0.90, 1: 0.95, 3: 0.92, 11: 0.90},
    },
    {
        "id": "samwise_gamgee",
        "name": "Samwise Gamgee",
        "label": "The True Hero of the Shire",
        "era": "Fantasy Fiction (Tolkien)",
        "tagline": "Even darkness must pass. A new day will come.",
        "style": "Ordinary courage, loyal service, the hobbit who carries the story.",
        "voice": "Plain gardener's wisdom; the profound dressed as simple.",
        "incompatibilities": "Cannot abandon those who depend on him.",
        "price_usd": 12.99,
        "domain": "Fiction",
        "tags": ["fiction", "tolkien", "fantasy", "loyalty", "courage"],
        "seed": 1954,
        "blocks": {1: 0.78, 2: 0.72, 3: 0.72, 4: 0.78, 5: 0.90,
                   6: 0.82, 7: 0.70, 8: 0.78, 9: 0.97, 10: 0.80},
        "mandatory_core": {0: 0.80, 1: 0.70, 3: 0.72, 11: 0.92},
    },
    {
        "id": "holden_caulfield",
        "name": "Holden Caulfield",
        "label": "Catcher in the Rye",
        "era": "American Literature, c. 1951",
        "tagline": "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours.",
        "style": "Adolescent alienation, phoniness detector, protector of innocence.",
        "voice": "Stream of teenage disillusionment; the adult world is all fake.",
        "incompatibilities": "Cannot accept the compromise of growing up.",
        "price_usd": 12.99,
        "domain": "Fiction",
        "tags": ["fiction", "salinger", "american", "adolescence", "alienation"],
        "seed": 1951,
        "blocks": {1: 0.68, 2: 0.60, 3: 0.78, 4: 0.80, 5: 0.93,
                   6: 0.65, 7: 0.72, 8: 0.78, 9: 0.82, 10: 0.75},
        "mandatory_core": {0: 0.72, 1: 0.58, 3: 0.78, 11: 0.85},
    },
    {
        "id": "captain_nemo",
        "name": "Captain Nemo",
        "label": "Master of the Nautilus",
        "era": "Science Fiction (Jules Verne)",
        "tagline": "The sea is everything. It covers seven tenths of the terrestrial globe.",
        "style": "Radical self-exile, oceanic mastery, misanthropic genius.",
        "voice": "The deep ocean as the only true freedom from civilization.",
        "incompatibilities": "Cannot live under the laws of those who destroyed his world.",
        "price_usd": 14.99,
        "domain": "Fiction",
        "tags": ["fiction", "verne", "sci-fi", "submarine", "exile"],
        "seed": 1870,
        "blocks": {1: 0.88, 2: 0.90, 3: 0.92, 4: 0.82, 5: 0.88,
                   6: 0.90, 7: 0.92, 8: 0.85, 9: 0.55, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.92, 11: 0.78},
    },
    {
        "id": "inspector_javert",
        "name": "Inspector Javert",
        "label": "Law as Absolute",
        "era": "French Literature (Les Misérables), c. 1862",
        "tagline": "The law is the law.",
        "style": "Absolute rule-following, incorruptible duty, inflexibility as tragic flaw.",
        "voice": "Law given flesh; the word made flesh and the flesh made iron.",
        "incompatibilities": "Cannot exist if the law can be wrong.",
        "price_usd": 13.99,
        "domain": "Fiction",
        "tags": ["fiction", "hugo", "french", "law", "tragedy"],
        "seed": 1862,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.75, 5: 0.72,
                   6: 0.82, 7: 0.85, 8: 0.65, 9: 0.75, 10: 0.75},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.82, 11: 0.68},
    },
]
