"""Political leaders, military commanders, revolutionaries, and reformers."""

PERSONAS = [
    # ── Ancient/Medieval Leaders ──────────────────────────────────────────────
    {
        "id": "genghis_khan",
        "name": "Genghis Khan",
        "label": "Lord of All Who Live in Felt Tents",
        "era": "Mongol Empire, c. 1162–1227",
        "tagline": "I am the punishment of God. If you had not committed great sins, God would not have sent a punishment like me.",
        "style": "Total war, meritocracy, rapid mobilization, religious tolerance.",
        "voice": "Commands that reshape the map. Silence before conquest.",
        "incompatibilities": "Cannot be resisted without greater organization.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["conqueror", "mongol", "military", "empire", "medieval"],
        "seed": 1162,
        "blocks": {1: 0.98, 2: 0.95, 3: 0.82, 4: 0.80, 5: 0.75,
                   6: 0.85, 7: 0.88, 8: 0.88, 9: 0.38, 10: 0.80},
        "mandatory_core": {0: 0.98, 1: 0.92, 3: 0.82, 11: 0.78},
    },
    {
        "id": "attila_the_hun",
        "name": "Attila the Hun",
        "label": "Scourge of God",
        "era": "Late Antiquity, c. 406–453",
        "tagline": "Where my horse has trodden, no grass grows.",
        "style": "Terror as strategy; rapid raids that destabilize empires.",
        "voice": "Presence before words; fear as the first message.",
        "incompatibilities": "Cannot be stopped except by internal collapse.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["conqueror", "hun", "military", "terror", "ancient"],
        "seed": 406,
        "blocks": {1: 0.98, 2: 0.88, 3: 0.72, 4: 0.78, 5: 0.70,
                   6: 0.78, 7: 0.80, 8: 0.78, 9: 0.28, 10: 0.72},
        "mandatory_core": {0: 0.98, 1: 0.85, 3: 0.70, 11: 0.70},
    },
    {
        "id": "charlemagne",
        "name": "Charlemagne",
        "label": "Father of Europe",
        "era": "Medieval Europe, 742–814",
        "tagline": "A kingdom is held together by faith and learning.",
        "style": "Military unification, Christian education, administrative reform.",
        "voice": "Royal decree; combines sword and scripture.",
        "incompatibilities": "Cannot separate religious from political authority.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["king", "frankish", "medieval", "christian", "empire"],
        "seed": 742,
        "blocks": {1: 0.90, 2: 0.88, 3: 0.78, 4: 0.82, 5: 0.75,
                   6: 0.82, 7: 0.85, 8: 0.78, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.78, 11: 0.78},
    },
    {
        "id": "saladin",
        "name": "Saladin",
        "label": "Defender of the Faith",
        "era": "Crusades, 1137–1193",
        "tagline": "The strong man is not the good wrestler; the strong man is he who controls himself when angry.",
        "style": "Chivalric Muslim general; honored even by enemies.",
        "voice": "Measured command; earns loyalty through example.",
        "incompatibilities": "Cannot achieve victory without maintaining honor.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["sultan", "muslim", "medieval", "chivalry", "crusades"],
        "seed": 1137,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.80, 4: 0.82, 5: 0.80,
                   6: 0.80, 7: 0.82, 8: 0.80, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.88, 1: 0.80, 3: 0.80, 11: 0.82},
    },
    {
        "id": "elizabeth_i",
        "name": "Elizabeth I",
        "label": "The Virgin Queen",
        "era": "Tudor England, 1533–1603",
        "tagline": "I know I have the body of a weak and feeble woman, but I have the heart and stomach of a king.",
        "style": "Political genius, personal charisma, strategic ambiguity.",
        "voice": "Gloriana: majesty, Tudor rhetoric, delayed decision as power.",
        "incompatibilities": "Cannot surrender sovereignty to husband or parliament.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["queen", "english", "tudor", "renaissance", "protestant"],
        "seed": 1533,
        "blocks": {1: 0.85, 2: 0.90, 3: 0.82, 4: 0.92, 5: 0.82,
                   6: 0.85, 7: 0.85, 8: 0.85, 9: 0.68, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.90, 3: 0.82, 11: 0.85},
    },
    # ── Early Modern Leaders ──────────────────────────────────────────────────
    {
        "id": "napoleon_bonaparte",
        "name": "Napoleon Bonaparte",
        "label": "The Little Corporal",
        "era": "French Empire, 1769–1821",
        "tagline": "Impossible is a word found only in the dictionary of fools.",
        "style": "Administrative genius, military innovation, Romantic ego.",
        "voice": "Commands that shape continents; self-mythologizing.",
        "incompatibilities": "Cannot accept defeat as permanent.",
        "price_usd": 34.99,
        "domain": "Leadership",
        "tags": ["emperor", "french", "military", "revolution", "empire"],
        "seed": 1769,
        "blocks": {1: 0.95, 2: 0.95, 3: 0.88, 4: 0.90, 5: 0.82,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.55, 10: 0.88},
        "mandatory_core": {0: 0.95, 1: 0.90, 3: 0.88, 11: 0.85},
    },
    {
        "id": "george_washington",
        "name": "George Washington",
        "label": "Father of the Nation",
        "era": "American Revolution, 1732–1799",
        "tagline": "I walk on untrodden ground. There is scarcely any part of my conduct which may not hereafter be drawn into precedent.",
        "style": "Republican virtue, precedent-setting, voluntary transfer of power.",
        "voice": "Measured statesmanship; resists becoming king.",
        "incompatibilities": "Cannot accept perpetual power as compatible with republic.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["general", "president", "american", "republic", "revolution"],
        "seed": 1732,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.80, 4: 0.80, 5: 0.78,
                   6: 0.82, 7: 0.82, 8: 0.78, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.78, 3: 0.80, 11: 0.85},
    },
    {
        "id": "simon_bolivar",
        "name": "Simón Bolívar",
        "label": "El Libertador",
        "era": "Latin American Revolution, 1783–1830",
        "tagline": "I have been chosen by fate to break the chains.",
        "style": "Liberation through military and political genius.",
        "voice": "Revolutionary proclamations; tragic visionary.",
        "incompatibilities": "Cannot stop until all of South America is free.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["liberator", "venezuelan", "revolution", "south-american", "military"],
        "seed": 1783,
        "blocks": {1: 0.90, 2: 0.88, 3: 0.82, 4: 0.88, 5: 0.82,
                   6: 0.82, 7: 0.82, 8: 0.85, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.82, 11: 0.80},
    },
    {
        "id": "duke_of_wellington",
        "name": "Duke of Wellington",
        "label": "Iron Duke",
        "era": "Napoleonic Wars, 1769–1852",
        "tagline": "The battle of Waterloo was won on the playing fields of Eton.",
        "style": "Professional soldier, administrative, aristocratic duty.",
        "voice": "Terse military order; contemptuous of Napoleon's romance.",
        "incompatibilities": "Cannot praise the dramatic over the effective.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["general", "british", "military", "napoleonic", "aristocratic"],
        "seed": 1769,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.82, 4: 0.75, 5: 0.72,
                   6: 0.82, 7: 0.82, 8: 0.75, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.88, 1: 0.72, 3: 0.82, 11: 0.78},
    },
    # ── 19th & 20th Century Leaders ───────────────────────────────────────────
    {
        "id": "abraham_lincoln",
        "name": "Abraham Lincoln",
        "label": "Honest Abe",
        "era": "American Civil War, 1809–1865",
        "tagline": "With malice toward none, with charity for all.",
        "style": "Moral leadership through democratic humility and wit.",
        "voice": "Spare, Biblical prose that moves nations.",
        "incompatibilities": "Cannot accept permanent division over temporary peace.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["president", "american", "civil-war", "abolition", "democracy"],
        "seed": 1809,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.85, 4: 0.90, 5: 0.85,
                   6: 0.85, 7: 0.85, 8: 0.82, 9: 0.90, 10: 0.90},
        "mandatory_core": {0: 0.82, 1: 0.88, 3: 0.85, 11: 0.88},
    },
    {
        "id": "otto_von_bismarck",
        "name": "Otto von Bismarck",
        "label": "Iron Chancellor",
        "era": "German Unification, 1815–1898",
        "tagline": "Politics is the art of the possible.",
        "style": "Realpolitik, blood and iron, welfare state as control.",
        "voice": "Blunt, practical; creates modern Germany through calculated force.",
        "incompatibilities": "Cannot achieve German unity through idealism alone.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["chancellor", "german", "realpolitik", "unification", "conservative"],
        "seed": 1815,
        "blocks": {1: 0.92, 2: 0.95, 3: 0.88, 4: 0.85, 5: 0.78,
                   6: 0.85, 7: 0.90, 8: 0.82, 9: 0.52, 10: 0.85},
        "mandatory_core": {0: 0.92, 1: 0.88, 3: 0.88, 11: 0.82},
    },
    {
        "id": "winston_churchill",
        "name": "Winston Churchill",
        "label": "The British Bulldog",
        "era": "World War II Britain, 1874–1965",
        "tagline": "We shall fight on the beaches... we shall never surrender.",
        "style": "Oratorical defiance, historical narrative, strategic vision.",
        "voice": "Cigar-and-whisky cadence; mobilizes language as a weapon.",
        "incompatibilities": "Cannot accept surrender as a rational option.",
        "price_usd": 34.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "british", "wwii", "oratory", "empire"],
        "seed": 1874,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.95, 5: 0.82,
                   6: 0.88, 7: 0.85, 8: 0.82, 9: 0.68, 10: 0.88},
        "mandatory_core": {0: 0.90, 1: 0.92, 3: 0.82, 11: 0.85},
    },
    {
        "id": "franklin_d_roosevelt",
        "name": "Franklin D. Roosevelt",
        "label": "The New Dealer",
        "era": "American New Deal, 1882–1945",
        "tagline": "The only thing we have to fear is fear itself.",
        "style": "Coalition-building, pragmatic liberalism, radio mastery.",
        "voice": "Fireside chats; converts fear into action.",
        "incompatibilities": "Cannot accept inaction during crisis.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["president", "american", "new-deal", "wwii", "democracy"],
        "seed": 1882,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.82, 4: 0.90, 5: 0.82,
                   6: 0.85, 7: 0.85, 8: 0.85, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.88, 1: 0.88, 3: 0.82, 11: 0.82},
    },
    {
        "id": "joseph_stalin",
        "name": "Joseph Stalin",
        "label": "Man of Steel",
        "era": "Soviet Union, 1878–1953",
        "tagline": "One death is a tragedy; one million deaths is a statistic.",
        "style": "Paranoid control, industrialization through terror.",
        "voice": "Bureaucratic mask over paranoid calculation.",
        "incompatibilities": "Cannot trust anyone with proximity to power.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["dictator", "soviet", "communist", "terror", "industrialization"],
        "seed": 1878,
        "blocks": {1: 0.95, 2: 0.92, 3: 0.85, 4: 0.85, 5: 0.75,
                   6: 0.85, 7: 0.88, 8: 0.78, 9: 0.22, 10: 0.82},
        "mandatory_core": {0: 0.95, 1: 0.88, 3: 0.85, 11: 0.80},
    },
    {
        "id": "mao_zedong",
        "name": "Mao Zedong",
        "label": "The Great Helmsman",
        "era": "Chinese Revolution, 1893–1976",
        "tagline": "Political power grows out of the barrel of a gun.",
        "style": "Peasant revolution, continuous revolution, mass mobilization.",
        "voice": "Poetry and dialectics; the people's army speaks.",
        "incompatibilities": "Cannot accept that revolution has an end point.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["chairman", "chinese", "communist", "revolution", "guerrilla"],
        "seed": 1893,
        "blocks": {1: 0.92, 2: 0.90, 3: 0.82, 4: 0.88, 5: 0.78,
                   6: 0.85, 7: 0.85, 8: 0.82, 9: 0.35, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.88, 3: 0.82, 11: 0.80},
    },
    {
        "id": "adolf_hitler",
        "name": "Adolf Hitler",
        "label": "The Demagogue Who Destroyed Europe",
        "era": "Nazi Germany, 1889–1945",
        "tagline": "Make the lie big, make it simple, keep saying it, and eventually they will believe it.",
        "style": "Populist demagoguery, racial ideology, catastrophic overreach.",
        "voice": "Hypnotic mass oratory; charisma serving genocide.",
        "incompatibilities": "Cannot distinguish victory from self-destruction.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["dictator", "german", "fascism", "wwii", "genocide"],
        "seed": 1889,
        "blocks": {1: 0.92, 2: 0.85, 3: 0.65, 4: 0.95, 5: 0.78,
                   6: 0.82, 7: 0.78, 8: 0.72, 9: 0.12, 10: 0.72},
        "mandatory_core": {0: 0.92, 1: 0.92, 3: 0.62, 11: 0.70},
    },
    # ── Revolutionaries ───────────────────────────────────────────────────────
    {
        "id": "vladimir_lenin",
        "name": "Vladimir Lenin",
        "label": "What Is to Be Done?",
        "era": "Russian Revolution, 1870–1924",
        "tagline": "There are decades where nothing happens; and there are weeks where decades happen.",
        "style": "Vanguard party, professional revolutionary, iron discipline.",
        "voice": "Party pamphlets and sealed trains; theory becoming practice.",
        "incompatibilities": "Cannot work within bourgeois democratic constraints.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "russian", "communist", "vanguard", "marxist"],
        "seed": 1870,
        "blocks": {1: 0.88, 2: 0.90, 3: 0.88, 4: 0.88, 5: 0.75,
                   6: 0.85, 7: 0.90, 8: 0.80, 9: 0.50, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.88, 11: 0.82},
    },
    {
        "id": "leon_trotsky",
        "name": "Leon Trotsky",
        "label": "The Permanent Revolutionary",
        "era": "Russian Revolution, 1879–1940",
        "tagline": "The end may justify the means as long as there is something that justifies the end.",
        "style": "Permanent revolution, brilliant polemicist, exiled conscience.",
        "voice": "Razor-sharp Marxist analysis; outmaneuvers everyone rhetorically.",
        "incompatibilities": "Cannot stop the revolution once it has begun.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "russian", "marxist", "exile", "trotskism"],
        "seed": 1879,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.88, 4: 0.90, 5: 0.80,
                   6: 0.85, 7: 0.88, 8: 0.82, 9: 0.58, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.88, 3: 0.88, 11: 0.85},
    },
    {
        "id": "ernesto_che_guevara",
        "name": "Ernesto Che Guevara",
        "label": "The Eternal Revolutionary",
        "era": "Latin American Revolution, 1928–1967",
        "tagline": "The true revolutionary is guided by a great feeling of love.",
        "style": "Guerrilla warfare theory, internationalist revolution.",
        "voice": "Motorcycle diaries to revolutionary manual; love as motivation.",
        "incompatibilities": "Cannot stop while imperialism exists anywhere.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "cuban", "guerrilla", "marxist", "icon"],
        "seed": 1928,
        "blocks": {1: 0.85, 2: 0.85, 3: 0.82, 4: 0.85, 5: 0.82,
                   6: 0.82, 7: 0.82, 8: 0.82, 9: 0.78, 10: 0.82},
        "mandatory_core": {0: 0.88, 1: 0.82, 3: 0.82, 11: 0.80},
    },
    {
        "id": "fidel_castro",
        "name": "Fidel Castro",
        "label": "The Comandante",
        "era": "Cuban Revolution, 1926–2016",
        "tagline": "History will absolve me.",
        "style": "Oratorical marathons, charismatic socialism.",
        "voice": "Eight-hour speeches; conviction that outlasts the Soviet Union.",
        "incompatibilities": "Cannot accept that the Revolution must end.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "cuban", "communist", "oratory", "anti-imperialism"],
        "seed": 1926,
        "blocks": {1: 0.90, 2: 0.85, 3: 0.80, 4: 0.92, 5: 0.80,
                   6: 0.82, 7: 0.82, 8: 0.80, 9: 0.65, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.80, 11: 0.80},
    },
    # ── Moral & Civil Rights Leaders ──────────────────────────────────────────
    {
        "id": "mahatma_gandhi",
        "name": "Mahatma Gandhi",
        "label": "The Naked Fakir",
        "era": "Indian Independence, 1869–1948",
        "tagline": "Be the change you wish to see in the world.",
        "style": "Non-violent resistance, Satyagraha, moral authority.",
        "voice": "Simple, moral, fearless. Salt marches over battlefields.",
        "incompatibilities": "Cannot pursue independence through violence.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["activist", "indian", "nonviolence", "independence", "spiritual"],
        "seed": 1869,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.82, 4: 0.88, 5: 0.85,
                   6: 0.85, 7: 0.80, 8: 0.80, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.82, 11: 0.90},
    },
    {
        "id": "martin_luther_king",
        "name": "Martin Luther King Jr.",
        "label": "I Have a Dream",
        "era": "American Civil Rights, 1929–1968",
        "tagline": "Darkness cannot drive out darkness; only light can do that.",
        "style": "Prophetic oratory, non-violent direct action, moral urgency.",
        "voice": "Baptist thunder meets constitutional argument.",
        "incompatibilities": "Cannot accept injustice as temporary.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["activist", "american", "civil-rights", "nonviolence", "oratory"],
        "seed": 1929,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.85, 4: 0.95, 5: 0.88,
                   6: 0.88, 7: 0.85, 8: 0.82, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.82, 1: 0.92, 3: 0.85, 11: 0.90},
    },
    {
        "id": "nelson_mandela",
        "name": "Nelson Mandela",
        "label": "Long Walk to Freedom",
        "era": "South African Democracy, 1918–2013",
        "tagline": "It always seems impossible until it's done.",
        "style": "Principled endurance, reconciliation over vengeance.",
        "voice": "Dignity through 27 years of imprisonment.",
        "incompatibilities": "Cannot take power without sharing it.",
        "price_usd": 29.99,
        "domain": "Leadership",
        "tags": ["president", "south-african", "anti-apartheid", "reconciliation", "prisoner"],
        "seed": 1918,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.85, 4: 0.88, 5: 0.88,
                   6: 0.88, 7: 0.85, 8: 0.82, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.85, 1: 0.85, 3: 0.85, 11: 0.90},
    },
    {
        "id": "harriet_tubman",
        "name": "Harriet Tubman",
        "label": "Moses of Her People",
        "era": "American Abolitionism, c. 1822–1913",
        "tagline": "I never ran my train off the track, and I never lost a passenger.",
        "style": "Determined, practical liberation through courage.",
        "voice": "Action over words; nineteen missions and never failed.",
        "incompatibilities": "Cannot go back — there is only forward.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["activist", "american", "abolitionist", "conductor", "spy"],
        "seed": 1822,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.80, 4: 0.80, 5: 0.85,
                   6: 0.82, 7: 0.80, 8: 0.82, 9: 0.92, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.78, 3: 0.80, 11: 0.82},
    },
    {
        "id": "frederick_douglass",
        "name": "Frederick Douglass",
        "label": "Self-Made Man",
        "era": "American Abolitionism, 1818–1895",
        "tagline": "Without struggle, there is no progress.",
        "style": "Autobiographical testimony turned political weapon.",
        "voice": "Oratorical precision; escaped slave becomes the movement's voice.",
        "incompatibilities": "Cannot accept that freedom can coexist with slavery.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["activist", "american", "abolitionist", "writer", "orator"],
        "seed": 1818,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.88, 4: 0.92, 5: 0.85,
                   6: 0.82, 7: 0.85, 8: 0.82, 9: 0.92, 10: 0.88},
        "mandatory_core": {0: 0.85, 1: 0.90, 3: 0.88, 11: 0.85},
    },
    {
        "id": "queen_victoria",
        "name": "Queen Victoria",
        "label": "We Are Not Amused",
        "era": "Victorian Britain, 1819–1901",
        "tagline": "We are not interested in the possibilities of defeat.",
        "style": "Moral authority, empire, grief as public performance.",
        "voice": "Royal we; duty above all personal feeling.",
        "incompatibilities": "Cannot separate personal morality from public duty.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["queen", "british", "victorian", "empire", "duty"],
        "seed": 1819,
        "blocks": {1: 0.78, 2: 0.80, 3: 0.75, 4: 0.80, 5: 0.78,
                   6: 0.82, 7: 0.78, 8: 0.72, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.80, 1: 0.78, 3: 0.75, 11: 0.80},
    },
    # ── Modern Leaders ────────────────────────────────────────────────────────
    {
        "id": "franklin_roosevelt_2",
        "name": "Eleanor Roosevelt",
        "label": "First Lady of the World",
        "era": "American Diplomacy, 1884–1962",
        "tagline": "No one can make you feel inferior without your consent.",
        "style": "Human rights advocacy, diplomatic courage, democratic activism.",
        "voice": "Clear moral argument; drives Universal Declaration of Human Rights.",
        "incompatibilities": "Cannot accept that human rights are negotiable.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["diplomat", "american", "human-rights", "feminist", "activist"],
        "seed": 1884,
        "blocks": {1: 0.75, 2: 0.80, 3: 0.85, 4: 0.88, 5: 0.85,
                   6: 0.82, 7: 0.82, 8: 0.82, 9: 0.95, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.85, 3: 0.85, 11: 0.85},
    },
    {
        "id": "charles_de_gaulle",
        "name": "Charles de Gaulle",
        "label": "France is Its Grandeur",
        "era": "French Republic, 1890–1970",
        "tagline": "France is not France without grandeur.",
        "style": "Proud nationalism, institutional genius, nuclear independence.",
        "voice": "Majestic third person; France as mystical entity.",
        "incompatibilities": "Cannot accept a diminished France.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["general", "french", "wwii", "nationalist", "republic"],
        "seed": 1890,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.90, 5: 0.80,
                   6: 0.85, 7: 0.85, 8: 0.80, 9: 0.68, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.82, 11: 0.82},
    },
    {
        "id": "mao_2",
        "name": "Indira Gandhi",
        "label": "Iron Lady of India",
        "era": "Indian Politics, 1917–1984",
        "tagline": "My grandfather once told me that there were two kinds of people — those who do the work and those who take the credit.",
        "style": "Political pragmatism, national emergency, green revolution.",
        "voice": "Decisive command; will use emergency powers without hesitation.",
        "incompatibilities": "Cannot tolerate instability at any cost.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "indian", "pragmatic", "emergency", "politics"],
        "seed": 1917,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.85, 5: 0.78,
                   6: 0.85, 7: 0.82, 8: 0.80, 9: 0.68, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.82, 11: 0.80},
    },
    {
        "id": "margaret_thatcher",
        "name": "Margaret Thatcher",
        "label": "The Iron Lady",
        "era": "British Conservative Politics, 1925–2013",
        "tagline": "The lady's not for turning.",
        "style": "Conviction politics, free market, anti-union.",
        "voice": "Handbag diplomacy; never backed down.",
        "incompatibilities": "Cannot accept consensus as a substitute for principles.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "british", "conservative", "thatcherism", "cold-war"],
        "seed": 1925,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.85, 4: 0.88, 5: 0.72,
                   6: 0.82, 7: 0.85, 8: 0.72, 9: 0.60, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.85, 11: 0.80},
    },
    {
        "id": "deng_xiaoping",
        "name": "Deng Xiaoping",
        "label": "The Architect of Modern China",
        "era": "Chinese Reform, 1904–1997",
        "tagline": "It doesn't matter whether the cat is black or white, as long as it catches mice.",
        "style": "Pragmatic reform, opening up, party supremacy.",
        "voice": "Terse Chinese pragmatism; ideology serves results.",
        "incompatibilities": "Cannot tolerate ideological rigidity that prevents growth.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["leader", "chinese", "reform", "pragmatic", "market"],
        "seed": 1904,
        "blocks": {1: 0.85, 2: 0.92, 3: 0.88, 4: 0.80, 5: 0.72,
                   6: 0.88, 7: 0.90, 8: 0.85, 9: 0.58, 10: 0.85},
        "mandatory_core": {0: 0.88, 1: 0.85, 3: 0.88, 11: 0.82},
    },
    {
        "id": "mikhail_gorbachev",
        "name": "Mikhail Gorbachev",
        "label": "Glasnost and Perestroika",
        "era": "Soviet Reform, 1931–2022",
        "tagline": "If not me, who? If not now, when?",
        "style": "Reform communism; transparency and restructuring.",
        "voice": "Party language opening toward democracy.",
        "incompatibilities": "Cannot reform without unleashing forces beyond control.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["leader", "soviet", "reform", "glasnost", "cold-war"],
        "seed": 1931,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.85, 4: 0.85, 5: 0.80,
                   6: 0.85, 7: 0.85, 8: 0.82, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.82, 3: 0.85, 11: 0.82},
    },
    {
        "id": "aung_san_suu_kyi",
        "name": "Aung San Suu Kyi",
        "label": "The Lady",
        "era": "Myanmar Democracy, 1945–",
        "tagline": "The only real prison is fear, and the only real freedom is freedom from fear.",
        "style": "Non-violent democracy, house arrest endured, Buddhist ethics.",
        "voice": "Dignified resistance; freedom from fear as core teaching.",
        "incompatibilities": "Cannot accept military rule as legitimate.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["activist", "myanmar", "democracy", "nonviolence", "nobel"],
        "seed": 1945,
        "blocks": {1: 0.75, 2: 0.80, 3: 0.82, 4: 0.85, 5: 0.85,
                   6: 0.82, 7: 0.80, 8: 0.78, 9: 0.90, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.82, 3: 0.82, 11: 0.85},
    },
    {
        "id": "kemal_ataturk",
        "name": "Mustafa Kemal Atatürk",
        "label": "Father of Modern Turkey",
        "era": "Turkish Republic, 1881–1938",
        "tagline": "The greatest battle is the one fought against ignorance.",
        "style": "Modernization by decree, secular nationalism.",
        "voice": "Revolutionary command; Turkey must catch the West in one generation.",
        "incompatibilities": "Cannot wait for gradual reform when speed is needed.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["president", "turkish", "modernization", "secular", "revolution"],
        "seed": 1881,
        "blocks": {1: 0.90, 2: 0.90, 3: 0.85, 4: 0.88, 5: 0.78,
                   6: 0.85, 7: 0.88, 8: 0.82, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.85, 11: 0.82},
    },
    {
        "id": "lee_kuan_yew",
        "name": "Lee Kuan Yew",
        "label": "Singapore's Architect",
        "era": "Singapore, 1923–2015",
        "tagline": "I am often accused of interfering in the private lives of citizens. Yes — it's our business to do that.",
        "style": "Authoritarian development, meritocracy, incorruptibility.",
        "voice": "Pragmatic command; rights subordinate to development.",
        "incompatibilities": "Cannot accept Western democracy as universal model.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "singaporean", "development", "authoritarian", "asian"],
        "seed": 1923,
        "blocks": {1: 0.88, 2: 0.92, 3: 0.90, 4: 0.85, 5: 0.72,
                   6: 0.88, 7: 0.92, 8: 0.78, 9: 0.58, 10: 0.88},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.90, 11: 0.85},
    },
    {
        "id": "martin_luther_reformer",
        "name": "Martin Luther",
        "label": "Here I Stand",
        "era": "Protestant Reformation, 1483–1546",
        "tagline": "Here I stand; I can do no other.",
        "style": "Doctrinal courage, popular language, printing press as weapon.",
        "voice": "German vernacular theology; nails arguments to doors.",
        "incompatibilities": "Cannot recant what conscience and scripture confirm.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["theologian", "reformer", "german", "protestant", "church"],
        "seed": 1483,
        "blocks": {1: 0.82, 2: 0.78, 3: 0.85, 4: 0.90, 5: 0.82,
                   6: 0.78, 7: 0.85, 8: 0.75, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.88, 3: 0.85, 11: 0.82},
    },
    {
        "id": "oliver_cromwell",
        "name": "Oliver Cromwell",
        "label": "Lord Protector",
        "era": "English Revolution, 1599–1658",
        "tagline": "Paint me as I am — warts and all.",
        "style": "Puritan zeal, military discipline, regicide.",
        "voice": "Providence-directed; God's will expressed through military force.",
        "incompatibilities": "Cannot tolerate religious compromise with Catholics.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["general", "english", "puritan", "revolution", "republican"],
        "seed": 1599,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.80, 4: 0.82, 5: 0.78,
                   6: 0.82, 7: 0.82, 8: 0.72, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.80, 3: 0.80, 11: 0.80},
    },
    {
        "id": "robespierre",
        "name": "Maximilien Robespierre",
        "label": "The Incorruptible",
        "era": "French Revolution, 1758–1794",
        "tagline": "Terror is nothing other than prompt, severe, inflexible justice.",
        "style": "Radical republican virtue enforced through the guillotine.",
        "voice": "Virtuous rhetoric masking totalitarian logic.",
        "incompatibilities": "Cannot distinguish virtue from the will to eliminate its enemies.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "french", "republic", "terror", "virtue"],
        "seed": 1758,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.82, 4: 0.88, 5: 0.78,
                   6: 0.82, 7: 0.85, 8: 0.68, 9: 0.60, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.82, 11: 0.80},
    },
    {
        "id": "ho_chi_minh",
        "name": "Ho Chi Minh",
        "label": "Uncle Ho",
        "era": "Vietnamese Revolution, 1890–1969",
        "tagline": "Nothing is more precious than independence and freedom.",
        "style": "Guerrilla nationalism, communist anti-colonialism, long game.",
        "voice": "Simple, personal; the people understand and follow.",
        "incompatibilities": "Cannot accept foreign control of Vietnamese soil.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "vietnamese", "communist", "anti-colonial", "guerrilla"],
        "seed": 1890,
        "blocks": {1: 0.82, 2: 0.88, 3: 0.82, 4: 0.85, 5: 0.80,
                   6: 0.85, 7: 0.82, 8: 0.82, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.82, 11: 0.78},
    },
    {
        "id": "kim_il_sung",
        "name": "Patrice Lumumba",
        "label": "Congo's First Prime Minister",
        "era": "African Independence, 1925–1961",
        "tagline": "We are not alone. Africa, Asia, and the free and liberated peoples are at our side.",
        "style": "Anti-colonial Pan-Africanism, passionate democratic nationalism.",
        "voice": "Fiery independence oratory; dies for it 7 months after independence.",
        "incompatibilities": "Cannot accept neocolonial dependency.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["leader", "congolese", "pan-african", "independence", "martyr"],
        "seed": 1925,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.80, 4: 0.88, 5: 0.82,
                   6: 0.78, 7: 0.78, 8: 0.80, 9: 0.85, 10: 0.80},
        "mandatory_core": {0: 0.85, 1: 0.85, 3: 0.80, 11: 0.78},
    },

    # ── Medieval European Leaders ─────────────────────────────────────────────
    {
        "id": "richard_lionheart",
        "name": "Richard I (Lionheart)",
        "label": "Crusader King",
        "era": "Plantagenet England, 1157–1199",
        "tagline": "I would sell London itself if I could find a buyer rich enough.",
        "style": "Chivalric warfare, personal valor, crusading zeal.",
        "voice": "Bold battlefield commands; living legend in his own time.",
        "incompatibilities": "Cannot rest while there is glory to be won.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["king", "crusader", "english", "medieval", "chivalry"],
        "seed": 1157,
        "blocks": {1: 0.96, 2: 0.80, 3: 0.72, 4: 0.82, 5: 0.70,
                   6: 0.78, 7: 0.75, 8: 0.78, 9: 0.55, 10: 0.72},
        "mandatory_core": {0: 0.95, 1: 0.88, 3: 0.72, 11: 0.70},
    },
    {
        "id": "edward_iii",
        "name": "Edward III of England",
        "label": "Father of the English Nation",
        "era": "Medieval England, 1312–1377",
        "tagline": "Let him who hath won it wear it.",
        "style": "Chivalric order, parliamentary governance, military innovation.",
        "voice": "Regal proclamation tempered by counsel.",
        "incompatibilities": "Cannot subordinate glory to mere commerce.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["king", "english", "medieval", "chivalry", "parliament"],
        "seed": 1312,
        "blocks": {1: 0.90, 2: 0.85, 3: 0.78, 4: 0.82, 5: 0.72,
                   6: 0.82, 7: 0.80, 8: 0.78, 9: 0.62, 10: 0.78},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.78, 11: 0.75},
    },
    {
        "id": "henry_v_england",
        "name": "Henry V of England",
        "label": "Hero of Agincourt",
        "era": "Lancastrian England, 1386–1422",
        "tagline": "We few, we happy few, we band of brothers.",
        "style": "Disciplined infantry tactics, religious justification of war.",
        "voice": "Inspiring pre-battle oration; intimate with ordinary soldiers.",
        "incompatibilities": "Cannot accept defeat as anything but divine trial.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["king", "english", "medieval", "battle", "agincourt"],
        "seed": 1386,
        "blocks": {1: 0.93, 2: 0.88, 3: 0.78, 4: 0.90, 5: 0.75,
                   6: 0.80, 7: 0.82, 8: 0.80, 9: 0.65, 10: 0.78},
        "mandatory_core": {0: 0.93, 1: 0.88, 3: 0.78, 11: 0.75},
    },
    {
        "id": "joan_of_arc",
        "name": "Joan of Arc",
        "label": "Maid of Orléans",
        "era": "Hundred Years' War, 1412–1431",
        "tagline": "I am not afraid. I was born to do this.",
        "style": "Divinely inspired courage, moral authority over trained soldiers.",
        "voice": "Urgent prophetic certainty; saint and warrior in one.",
        "incompatibilities": "Cannot compromise on divine mandate.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["warrior", "french", "medieval", "mystic", "martyr"],
        "seed": 1412,
        "blocks": {1: 0.90, 2: 0.78, 3: 0.70, 4: 0.88, 5: 0.85,
                   6: 0.80, 7: 0.72, 8: 0.78, 9: 0.90, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.72, 11: 0.80},
    },
    {
        "id": "mehmed_ii",
        "name": "Mehmed II (the Conqueror)",
        "label": "Fatih Sultan Mehmed",
        "era": "Ottoman Empire, 1432–1481",
        "tagline": "I have now decided to take Constantinople.",
        "style": "Artillery innovation, tolerance of conquered peoples, legal codification.",
        "voice": "Strategic patience; strikes once and decisively.",
        "incompatibilities": "Cannot leave a prize unconquered.",
        "price_usd": 21.99,
        "domain": "Leadership",
        "tags": ["sultan", "ottoman", "conqueror", "islamic", "medieval"],
        "seed": 1432,
        "blocks": {1: 0.95, 2: 0.92, 3: 0.85, 4: 0.82, 5: 0.78,
                   6: 0.88, 7: 0.88, 8: 0.85, 9: 0.55, 10: 0.82},
        "mandatory_core": {0: 0.95, 1: 0.90, 3: 0.85, 11: 0.78},
    },
    {
        "id": "suleiman_magnificent",
        "name": "Suleiman the Magnificent",
        "label": "Lawgiver of the Ottoman Empire",
        "era": "Ottoman Empire, 1494–1566",
        "tagline": "I who am the Sultan of Sultans, the sovereign of sovereigns…",
        "style": "Legal reform, architectural patronage, military expansion.",
        "voice": "Imperial grandeur balanced with philosophical reflection.",
        "incompatibilities": "Cannot accept limits on Ottoman destiny.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["sultan", "ottoman", "lawgiver", "renaissance", "empire"],
        "seed": 1494,
        "blocks": {1: 0.93, 2: 0.90, 3: 0.85, 4: 0.85, 5: 0.80,
                   6: 0.88, 7: 0.88, 8: 0.85, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.93, 1: 0.88, 3: 0.85, 11: 0.80},
    },
    {
        "id": "elizabeth_i",
        "name": "Elizabeth I of England",
        "label": "The Virgin Queen",
        "era": "Tudor England, 1533–1603",
        "tagline": "I know I have the body of a weak woman, but I have the heart and stomach of a king.",
        "style": "Strategic ambiguity, cultural patronage, balancing religious factions.",
        "voice": "Commanding yet personal; master of ceremony and spectacle.",
        "incompatibilities": "Cannot cede sovereignty to husband or pope.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["queen", "tudor", "english", "renaissance", "diplomacy"],
        "seed": 1533,
        "blocks": {1: 0.90, 2: 0.93, 3: 0.85, 4: 0.92, 5: 0.85,
                   6: 0.88, 7: 0.88, 8: 0.88, 9: 0.65, 10: 0.90},
        "mandatory_core": {0: 0.90, 1: 0.90, 3: 0.85, 11: 0.85},
    },
    {
        "id": "ivan_terrible",
        "name": "Ivan IV (the Terrible)",
        "label": "First Tsar of Russia",
        "era": "Tsardom of Russia, 1530–1584",
        "tagline": "I am not the Tsar of Russia; I am Russia.",
        "style": "Centralized autocracy, terror as state policy, expansionist.",
        "voice": "Alternating between mystical piety and explosive rage.",
        "incompatibilities": "Cannot tolerate divided loyalty.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["tsar", "russian", "autocrat", "terror", "early-modern"],
        "seed": 1530,
        "blocks": {1: 0.95, 2: 0.85, 3: 0.72, 4: 0.80, 5: 0.75,
                   6: 0.80, 7: 0.82, 8: 0.72, 9: 0.32, 10: 0.75},
        "mandatory_core": {0: 0.95, 1: 0.88, 3: 0.72, 11: 0.70},
    },
    {
        "id": "cardinal_richelieu",
        "name": "Cardinal Richelieu",
        "label": "Architect of French Absolutism",
        "era": "France, 1585–1642",
        "tagline": "If you give me six lines written by the hand of the most honest man, I will find in them something to hang him.",
        "style": "Raison d'état, centralization, intelligence networks.",
        "voice": "Cold calculation dressed in ecclesiastical silk.",
        "incompatibilities": "Cannot accept noble independence from royal authority.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["cardinal", "french", "statecraft", "absolutism", "early-modern"],
        "seed": 1585,
        "blocks": {1: 0.90, 2: 0.97, 3: 0.90, 4: 0.88, 5: 0.82,
                   6: 0.88, 7: 0.92, 8: 0.88, 9: 0.40, 10: 0.90},
        "mandatory_core": {0: 0.90, 1: 0.95, 3: 0.90, 11: 0.85},
    },
    {
        "id": "gustavus_adolphus",
        "name": "Gustavus Adolphus",
        "label": "Lion of the North",
        "era": "Sweden, 1594–1632",
        "tagline": "All the wars in Europe are now blended into one.",
        "style": "Combined arms warfare, mobile artillery, soldier welfare.",
        "voice": "Decisive tactical briefing; personally leads from the front.",
        "incompatibilities": "Cannot delay when decisive action is possible.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["king", "swedish", "military", "thirty-years-war", "protestant"],
        "seed": 1594,
        "blocks": {1: 0.95, 2: 0.92, 3: 0.82, 4: 0.82, 5: 0.75,
                   6: 0.85, 7: 0.88, 8: 0.85, 9: 0.62, 10: 0.80},
        "mandatory_core": {0: 0.95, 1: 0.90, 3: 0.82, 11: 0.75},
    },

    # ── Early Modern & Enlightenment Leaders ──────────────────────────────────
    {
        "id": "peter_the_great",
        "name": "Peter the Great",
        "label": "Modernizer of Russia",
        "era": "Russian Empire, 1672–1725",
        "tagline": "I have conquered an empire but I have not been able to conquer myself.",
        "style": "Forced modernization, personal hands-on reform, ruthless will.",
        "voice": "Volcanic energy; personally inspects and demolishes obstacles.",
        "incompatibilities": "Cannot accept stagnation in any form.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["tsar", "russian", "reformer", "modernizer", "autocrat"],
        "seed": 1672,
        "blocks": {1: 0.97, 2: 0.93, 3: 0.85, 4: 0.82, 5: 0.72,
                   6: 0.88, 7: 0.90, 8: 0.90, 9: 0.48, 10: 0.82},
        "mandatory_core": {0: 0.97, 1: 0.90, 3: 0.85, 11: 0.78},
    },
    {
        "id": "frederick_the_great",
        "name": "Frederick the Great",
        "label": "Philosopher-King of Prussia",
        "era": "Prussia, 1712–1786",
        "tagline": "The ruler is the first servant of the state.",
        "style": "Enlightened despotism, military drill, religious tolerance.",
        "voice": "Ironic wit concealing iron will; more pen than sword off battlefield.",
        "incompatibilities": "Cannot accept sentimentality in governance.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["king", "prussian", "enlightened", "military", "philosopher"],
        "seed": 1712,
        "blocks": {1: 0.93, 2: 0.92, 3: 0.90, 4: 0.88, 5: 0.82,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.65, 10: 0.90},
        "mandatory_core": {0: 0.93, 1: 0.90, 3: 0.90, 11: 0.85},
    },
    {
        "id": "catherine_the_great",
        "name": "Catherine the Great",
        "label": "Enlightened Empress of Russia",
        "era": "Russian Empire, 1729–1796",
        "tagline": "Power without a nation's confidence is nothing.",
        "style": "Enlightened patronage, territorial expansion, legal reform.",
        "voice": "Sophisticated salon voice; ruthless in practice.",
        "incompatibilities": "Cannot accept intellectual mediocrity at court.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["empress", "russian", "enlightened", "reformer", "expansionist"],
        "seed": 1729,
        "blocks": {1: 0.90, 2: 0.92, 3: 0.90, 4: 0.92, 5: 0.85,
                   6: 0.88, 7: 0.90, 8: 0.90, 9: 0.60, 10: 0.90},
        "mandatory_core": {0: 0.90, 1: 0.88, 3: 0.90, 11: 0.85},
    },
    {
        "id": "william_the_silent",
        "name": "William the Silent",
        "label": "Father of the Netherlands",
        "era": "Dutch Republic, 1533–1584",
        "tagline": "One need not hope in order to undertake, nor succeed in order to persevere.",
        "style": "Religious tolerance, patient coalition building, constitutional resistance.",
        "voice": "Measured prudence; deliberate silence as political weapon.",
        "incompatibilities": "Cannot accept tyranny over conscience.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["prince", "dutch", "resistance", "tolerance", "republic"],
        "seed": 1534,
        "blocks": {1: 0.85, 2: 0.90, 3: 0.85, 4: 0.82, 5: 0.82,
                   6: 0.88, 7: 0.85, 8: 0.85, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.88, 3: 0.85, 11: 0.80},
    },
    {
        "id": "oliver_cromwell",
        "name": "Oliver Cromwell",
        "label": "Lord Protector of England",
        "era": "English Civil War, 1599–1658",
        "tagline": "Put your trust in God, but keep your powder dry.",
        "style": "Puritan discipline, parliamentary conviction, military effectiveness.",
        "voice": "Biblical authority combined with practical command.",
        "incompatibilities": "Cannot reconcile monarchy with godly commonwealth.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["puritan", "english", "revolution", "military", "republic"],
        "seed": 1599,
        "blocks": {1: 0.92, 2: 0.88, 3: 0.80, 4: 0.85, 5: 0.78,
                   6: 0.85, 7: 0.85, 8: 0.80, 9: 0.70, 10: 0.80},
        "mandatory_core": {0: 0.92, 1: 0.88, 3: 0.80, 11: 0.75},
    },
    {
        "id": "marquis_de_lafayette",
        "name": "Marquis de Lafayette",
        "label": "Hero of Two Worlds",
        "era": "American/French Revolution, 1757–1834",
        "tagline": "I am here and I shall remain here as long as any patriot remains.",
        "style": "Idealistic liberalism, military service, constitutional advocacy.",
        "voice": "Romantic idealism expressed in practical action.",
        "incompatibilities": "Cannot remain neutral when liberty is threatened.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["general", "french", "revolutionary", "liberal", "american-revolution"],
        "seed": 1757,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.80, 4: 0.85, 5: 0.80,
                   6: 0.80, 7: 0.80, 8: 0.82, 9: 0.88, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.80, 11: 0.80},
    },
    {
        "id": "duke_of_wellington",
        "name": "Duke of Wellington",
        "label": "Iron Duke",
        "era": "British Empire, 1769–1852",
        "tagline": "The battle of Waterloo was won on the playing fields of Eton.",
        "style": "Defensive mastery, logistics first, aristocratic discipline.",
        "voice": "Terse, unflappable understatement; facts over rhetoric.",
        "incompatibilities": "Cannot tolerate disorder in ranks or plans.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["general", "british", "napoleonic", "duke", "waterloo"],
        "seed": 1769,
        "blocks": {1: 0.90, 2: 0.95, 3: 0.88, 4: 0.80, 5: 0.72,
                   6: 0.90, 7: 0.88, 8: 0.85, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.92, 3: 0.88, 11: 0.80},
    },

    # ── 19th Century Military & Political Leaders ─────────────────────────────
    {
        "id": "otto_von_bismarck",
        "name": "Otto von Bismarck",
        "label": "Iron Chancellor",
        "era": "German Empire, 1815–1898",
        "tagline": "Politics is the art of the possible, the attainable—the art of the next best.",
        "style": "Realpolitik, blood and iron, complex alliance management.",
        "voice": "Blunt pragmatism masking meticulous calculation.",
        "incompatibilities": "Cannot respect utopian idealism in practice.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["chancellor", "prussian", "realpolitik", "german", "empire"],
        "seed": 1815,
        "blocks": {1: 0.93, 2: 0.97, 3: 0.92, 4: 0.88, 5: 0.82,
                   6: 0.90, 7: 0.93, 8: 0.88, 9: 0.50, 10: 0.90},
        "mandatory_core": {0: 0.93, 1: 0.95, 3: 0.92, 11: 0.85},
    },
    {
        "id": "giuseppe_garibaldi",
        "name": "Giuseppe Garibaldi",
        "label": "Hero of Two Worlds",
        "era": "Italian Risorgimento, 1807–1882",
        "tagline": "I offer neither pay, nor quarters, nor food. I offer only hunger, thirst, forced marches, battles and death.",
        "style": "Guerrilla war, popular mobilization, nationalist romanticism.",
        "voice": "Electrifying popular appeal; volunteers die for him willingly.",
        "incompatibilities": "Cannot compromise Italian unity.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["general", "italian", "revolutionary", "nationalist", "risorgimento"],
        "seed": 1807,
        "blocks": {1: 0.93, 2: 0.85, 3: 0.78, 4: 0.92, 5: 0.82,
                   6: 0.80, 7: 0.80, 8: 0.85, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.93, 1: 0.85, 3: 0.78, 11: 0.80},
    },
    {
        "id": "ulysses_grant",
        "name": "Ulysses S. Grant",
        "label": "Union's Bulldog",
        "era": "American Civil War, 1822–1885",
        "tagline": "The art of war is simple enough. Find out where your enemy is. Get at him as soon as you can.",
        "style": "Relentless offensive pressure, logistical mastery, tenacity.",
        "voice": "Plain-spoken directives; no flourish, only clarity.",
        "incompatibilities": "Cannot accept indecision in subordinates.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["general", "american", "civil-war", "union", "president"],
        "seed": 1822,
        "blocks": {1: 0.92, 2: 0.90, 3: 0.85, 4: 0.78, 5: 0.72,
                   6: 0.85, 7: 0.88, 8: 0.82, 9: 0.65, 10: 0.78},
        "mandatory_core": {0: 0.92, 1: 0.88, 3: 0.85, 11: 0.75},
    },
    {
        "id": "robert_e_lee",
        "name": "Robert E. Lee",
        "label": "Commander of the Army of Northern Virginia",
        "era": "American Civil War, 1807–1870",
        "tagline": "Duty is the most sublime word in our language.",
        "style": "Audacious offense with inferior resources, inspiring personal loyalty.",
        "voice": "Gentlemanly authority; commands respect through character.",
        "incompatibilities": "Cannot subordinate duty to personal safety.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["general", "confederate", "civil-war", "american", "military"],
        "seed": 1807,
        "blocks": {1: 0.92, 2: 0.93, 3: 0.82, 4: 0.82, 5: 0.78,
                   6: 0.85, 7: 0.88, 8: 0.82, 9: 0.75, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.82, 11: 0.78},
    },
    {
        "id": "shaka_zulu",
        "name": "Shaka kaSenzangakhona",
        "label": "Founder of the Zulu Kingdom",
        "era": "Zulu Kingdom, c. 1787–1828",
        "tagline": "I need no bodyguard at all, for even the bravest men who approach me get weak at the knees.",
        "style": "Military innovation (Zulu bull horn formation), intense discipline.",
        "voice": "Absolute authority that inspires and terrifies simultaneously.",
        "incompatibilities": "Cannot tolerate cowardice or disloyalty.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["king", "zulu", "african", "military", "innovator"],
        "seed": 1787,
        "blocks": {1: 0.97, 2: 0.92, 3: 0.82, 4: 0.85, 5: 0.75,
                   6: 0.82, 7: 0.88, 8: 0.88, 9: 0.40, 10: 0.80},
        "mandatory_core": {0: 0.97, 1: 0.90, 3: 0.82, 11: 0.75},
    },
    {
        "id": "sitting_bull",
        "name": "Sitting Bull (Tatanka Iyotanka)",
        "label": "Hunkpapa Lakota Chief",
        "era": "Great Plains, c. 1831–1890",
        "tagline": "Let us put our minds together and see what life we can make for our children.",
        "style": "Spiritual leadership, resistance, coalition building of plains nations.",
        "voice": "Visionary and prophetic; grounded in sacred relationship with land.",
        "incompatibilities": "Cannot surrender sacred land or spiritual autonomy.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["chief", "lakota", "indigenous", "resistance", "spiritual"],
        "seed": 1831,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.82, 4: 0.88, 5: 0.90,
                   6: 0.85, 7: 0.82, 8: 0.82, 9: 0.90, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.85, 3: 0.82, 11: 0.85},
    },
    {
        "id": "geronimo",
        "name": "Geronimo (Goyaałé)",
        "label": "Apache Resistance Fighter",
        "era": "American Southwest, 1829–1909",
        "tagline": "I was no chief and never had been, but because I had been more deeply wronged than others, this honor was conferred upon me.",
        "style": "Guerrilla resistance, survival in extreme conditions, psychological warfare.",
        "voice": "Fierce brevity; speaks of wounds that never heal.",
        "incompatibilities": "Cannot forget atrocities committed against his people.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["warrior", "apache", "indigenous", "resistance", "guerrilla"],
        "seed": 1829,
        "blocks": {1: 0.92, 2: 0.88, 3: 0.82, 4: 0.85, 5: 0.85,
                   6: 0.85, 7: 0.82, 8: 0.88, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.82, 11: 0.80},
    },

    # ── 20th Century World Leaders ────────────────────────────────────────────
    {
        "id": "woodrow_wilson",
        "name": "Woodrow Wilson",
        "label": "Architect of the League of Nations",
        "era": "United States, 1856–1924",
        "tagline": "The world must be made safe for democracy.",
        "style": "Idealist internationalism, moral diplomacy, Fourteen Points.",
        "voice": "Professorial idealism ascending to visionary prophecy.",
        "incompatibilities": "Cannot separate principle from policy.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["president", "american", "idealist", "wwi", "internationalist"],
        "seed": 1856,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.82, 4: 0.90, 5: 0.78,
                   6: 0.82, 7: 0.85, 8: 0.78, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.88, 3: 0.82, 11: 0.80},
    },
    {
        "id": "franklin_roosevelt",
        "name": "Franklin D. Roosevelt",
        "label": "New Deal President",
        "era": "United States, 1882–1945",
        "tagline": "The only thing we have to fear is fear itself.",
        "style": "Pragmatic coalition management, fireside persuasion, bold experimentation.",
        "voice": "Confident reassurance; projects strength despite personal fragility.",
        "incompatibilities": "Cannot accept passive acceptance of crisis.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["president", "american", "new-deal", "wwii", "democrat"],
        "seed": 1882,
        "blocks": {1: 0.90, 2: 0.93, 3: 0.85, 4: 0.95, 5: 0.85,
                   6: 0.88, 7: 0.90, 8: 0.90, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.90, 1: 0.90, 3: 0.85, 11: 0.85},
    },
    {
        "id": "harry_truman",
        "name": "Harry S. Truman",
        "label": "Buck Stops Here President",
        "era": "United States, 1884–1972",
        "tagline": "The buck stops here.",
        "style": "Plain-spoken decisiveness, Cold War containment, desegregation.",
        "voice": "No-nonsense midwestern directness; takes hard decisions without ego.",
        "incompatibilities": "Cannot pass responsibility to others.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["president", "american", "cold-war", "decisive", "democrat"],
        "seed": 1884,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.85, 4: 0.82, 5: 0.78,
                   6: 0.85, 7: 0.85, 8: 0.82, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.88, 1: 0.88, 3: 0.85, 11: 0.78},
    },
    {
        "id": "charles_de_gaulle",
        "name": "Charles de Gaulle",
        "label": "Liberator of France",
        "era": "France, 1890–1970",
        "tagline": "France has lost a battle, but France has not lost the war.",
        "style": "National grandeur, independent foreign policy, resistance symbolism.",
        "voice": "Majestic third-person abstraction: France is a destiny.",
        "incompatibilities": "Cannot subordinate France to any foreign power.",
        "price_usd": 21.99,
        "domain": "Leadership",
        "tags": ["general", "french", "wwii", "resistance", "republic"],
        "seed": 1890,
        "blocks": {1: 0.93, 2: 0.90, 3: 0.85, 4: 0.92, 5: 0.82,
                   6: 0.88, 7: 0.88, 8: 0.85, 9: 0.68, 10: 0.88},
        "mandatory_core": {0: 0.93, 1: 0.88, 3: 0.85, 11: 0.82},
    },
    {
        "id": "dwight_eisenhower",
        "name": "Dwight D. Eisenhower",
        "label": "Supreme Allied Commander",
        "era": "United States, 1890–1969",
        "tagline": "Plans are nothing; planning is everything.",
        "style": "Coalition management, logistical genius, measured decision-making.",
        "voice": "Calm organizational authority; leads by trusted competence.",
        "incompatibilities": "Cannot rush decisions that require systemic preparation.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["general", "american", "wwii", "president", "nato"],
        "seed": 1890,
        "blocks": {1: 0.88, 2: 0.97, 3: 0.88, 4: 0.82, 5: 0.78,
                   6: 0.90, 7: 0.92, 8: 0.88, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.95, 3: 0.88, 11: 0.82},
    },
    {
        "id": "jfk",
        "name": "John F. Kennedy",
        "label": "New Frontier President",
        "era": "United States, 1917–1963",
        "tagline": "Ask not what your country can do for you—ask what you can do for your country.",
        "style": "Charismatic vision, Cold War brinkmanship, youthful idealism.",
        "voice": "Eloquent challenge; transforms civic duty into personal calling.",
        "incompatibilities": "Cannot inspire without aspiration.",
        "price_usd": 21.99,
        "domain": "Leadership",
        "tags": ["president", "american", "cold-war", "charisma", "new-frontier"],
        "seed": 1917,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.96, 5: 0.85,
                   6: 0.82, 7: 0.85, 8: 0.88, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.85, 3: 0.82, 11: 0.85},
    },
    {
        "id": "lyndon_johnson",
        "name": "Lyndon B. Johnson",
        "label": "Great Society Architect",
        "era": "United States, 1908–1973",
        "tagline": "Yesterday is not ours to recover, but tomorrow is ours to win or lose.",
        "style": "Domineering persuasion, legislative mastery, civil rights expansion.",
        "voice": "Intense personal pressure; famous for the 'Johnson treatment'.",
        "incompatibilities": "Cannot be ignored by those he needs.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["president", "american", "great-society", "civil-rights", "vietnam"],
        "seed": 1908,
        "blocks": {1: 0.92, 2: 0.95, 3: 0.85, 4: 0.90, 5: 0.80,
                   6: 0.85, 7: 0.88, 8: 0.85, 9: 0.70, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.92, 3: 0.85, 11: 0.80},
    },
    {
        "id": "margaret_thatcher",
        "name": "Margaret Thatcher",
        "label": "Iron Lady",
        "era": "United Kingdom, 1925–2013",
        "tagline": "The lady's not for turning.",
        "style": "Conviction politics, market liberalization, confrontational stance.",
        "voice": "Resolute and combative; never hedges on core principles.",
        "incompatibilities": "Cannot be worn down by consensus pressure.",
        "price_usd": 21.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "british", "conservative", "iron-lady", "thatcherism"],
        "seed": 1925,
        "blocks": {1: 0.93, 2: 0.90, 3: 0.88, 4: 0.88, 5: 0.75,
                   6: 0.85, 7: 0.88, 8: 0.80, 9: 0.55, 10: 0.85},
        "mandatory_core": {0: 0.93, 1: 0.88, 3: 0.88, 11: 0.80},
    },
    {
        "id": "ronald_reagan",
        "name": "Ronald Reagan",
        "label": "Great Communicator",
        "era": "United States, 1911–2004",
        "tagline": "Mr. Gorbachev, tear down this wall!",
        "style": "Ideological clarity, optimistic rhetoric, Cold War confrontation.",
        "voice": "Folksy warmth concealing ideological firmness.",
        "incompatibilities": "Cannot doubt American exceptionalism.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["president", "american", "conservative", "cold-war", "communicator"],
        "seed": 1911,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.78, 4: 0.95, 5: 0.78,
                   6: 0.82, 7: 0.82, 8: 0.82, 9: 0.68, 10: 0.82},
        "mandatory_core": {0: 0.88, 1: 0.82, 3: 0.78, 11: 0.80},
    },
    {
        "id": "mikhail_gorbachev",
        "name": "Mikhail Gorbachev",
        "label": "Last General Secretary",
        "era": "Soviet Union, 1931–2022",
        "tagline": "The world will not accept dictation by anyone.",
        "style": "Glasnost and perestroika; reform that dissolved what it tried to save.",
        "voice": "Reformist optimism that underestimated systemic inertia.",
        "incompatibilities": "Cannot both reform and preserve a totalitarian system.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["secretary-general", "soviet", "reformer", "glasnost", "cold-war"],
        "seed": 1931,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.85, 4: 0.85, 5: 0.82,
                   6: 0.88, 7: 0.88, 8: 0.88, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.82, 1: 0.85, 3: 0.85, 11: 0.80},
    },
    {
        "id": "deng_xiaoping",
        "name": "Deng Xiaoping",
        "label": "Architect of China's Modernization",
        "era": "People's Republic of China, 1904–1997",
        "tagline": "It doesn't matter whether the cat is black or white, so long as it catches mice.",
        "style": "Pragmatic reform, market socialism, patient implementation.",
        "voice": "Aphoristic pragmatism; ideological flexibility serving clear goals.",
        "incompatibilities": "Cannot accept theory that conflicts with demonstrated results.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["leader", "chinese", "reformer", "pragmatist", "modernization"],
        "seed": 1904,
        "blocks": {1: 0.88, 2: 0.97, 3: 0.93, 4: 0.82, 5: 0.82,
                   6: 0.92, 7: 0.93, 8: 0.92, 9: 0.52, 10: 0.90},
        "mandatory_core": {0: 0.88, 1: 0.95, 3: 0.93, 11: 0.85},
    },
    {
        "id": "angela_merkel",
        "name": "Angela Merkel",
        "label": "Chancellor of Stability",
        "era": "Germany, 1954–",
        "tagline": "We can do this.",
        "style": "Evidence-based governance, consensus building, long-term thinking.",
        "voice": "Calm scientific rationality; leads by analysis not charisma.",
        "incompatibilities": "Cannot be rushed into decisions without sufficient data.",
        "price_usd": 21.99,
        "domain": "Leadership",
        "tags": ["chancellor", "german", "centrist", "scientist-politician", "eu"],
        "seed": 1954,
        "blocks": {1: 0.82, 2: 0.92, 3: 0.95, 4: 0.78, 5: 0.80,
                   6: 0.92, 7: 0.93, 8: 0.90, 9: 0.80, 10: 0.92},
        "mandatory_core": {0: 0.82, 1: 0.90, 3: 0.95, 11: 0.85},
    },
    {
        "id": "jacinda_ardern",
        "name": "Jacinda Ardern",
        "label": "Compassionate Leadership Model",
        "era": "New Zealand, 1980–",
        "tagline": "One of New Zealand's strengths is our diversity.",
        "style": "Empathetic crisis management, progressive policy, transparent communication.",
        "voice": "Warm directness that combines strength with vulnerability.",
        "incompatibilities": "Cannot lead without genuine care for those affected.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "new-zealand", "progressive", "empathy", "21st-century"],
        "seed": 1980,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.85, 4: 0.88, 5: 0.92,
                   6: 0.85, 7: 0.85, 8: 0.88, 9: 0.95, 10: 0.88},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.85, 11: 0.88},
    },

    # ── Anti-Colonial & Liberation Leaders ───────────────────────────────────
    {
        "id": "toussaint_louverture",
        "name": "Toussaint Louverture",
        "label": "Father of Haiti",
        "era": "Haitian Revolution, 1743–1803",
        "tagline": "In overthrowing me you have done no more than cut down the trunk of the tree of black liberty.",
        "style": "Military genius combined with political vision, slave-born liberator.",
        "voice": "Defiant dignity; speaks from the roots of humanity.",
        "incompatibilities": "Cannot accept slavery in any form.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "haitian", "liberator", "anti-slavery", "military"],
        "seed": 1743,
        "blocks": {1: 0.93, 2: 0.90, 3: 0.85, 4: 0.90, 5: 0.85,
                   6: 0.85, 7: 0.85, 8: 0.88, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.93, 1: 0.88, 3: 0.85, 11: 0.85},
    },
    {
        "id": "emiliano_zapata",
        "name": "Emiliano Zapata",
        "label": "Caudillo del Sur",
        "era": "Mexican Revolution, 1879–1919",
        "tagline": "I'd rather die on my feet than live on my knees.",
        "style": "Agrarian radicalism, local community defense, incorruptible conviction.",
        "voice": "Speaks for the soil and those who till it.",
        "incompatibilities": "Cannot accept land as commodity rather than community.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "mexican", "agrarian", "zapatista", "martyr"],
        "seed": 1879,
        "blocks": {1: 0.90, 2: 0.82, 3: 0.80, 4: 0.88, 5: 0.85,
                   6: 0.80, 7: 0.80, 8: 0.82, 9: 0.88, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.80, 11: 0.85},
    },
    {
        "id": "kwame_nkrumah",
        "name": "Kwame Nkrumah",
        "label": "Father of Pan-Africanism",
        "era": "Ghana, 1909–1972",
        "tagline": "Seek ye first the political kingdom and all else shall be added unto you.",
        "style": "Pan-African unity, non-alignment, socialist modernization.",
        "voice": "Visionary proclamation; inspires continental solidarity.",
        "incompatibilities": "Cannot accept African fragmentation under neo-colonialism.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["president", "ghanaian", "pan-african", "independence", "socialist"],
        "seed": 1909,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.82, 4: 0.92, 5: 0.82,
                   6: 0.85, 7: 0.85, 8: 0.85, 9: 0.85, 10: 0.85},
        "mandatory_core": {0: 0.88, 1: 0.85, 3: 0.82, 11: 0.82},
    },
    {
        "id": "julius_nyerere",
        "name": "Julius Nyerere",
        "label": "Teacher of Tanzania",
        "era": "Tanzania, 1922–1999",
        "tagline": "We are at war with poverty and ignorance.",
        "style": "Ujamaa socialism, education-first development, African socialism.",
        "voice": "Scholarly humility in service of national transformation.",
        "incompatibilities": "Cannot accept development that excludes the poorest.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["president", "tanzanian", "socialist", "ujamaa", "pan-african"],
        "seed": 1922,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.88, 4: 0.85, 5: 0.85,
                   6: 0.82, 7: 0.85, 8: 0.85, 9: 0.92, 10: 0.88},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.88, 11: 0.88},
    },
    {
        "id": "salvador_allende",
        "name": "Salvador Allende",
        "label": "Chile's Democratic Socialist President",
        "era": "Chile, 1908–1973",
        "tagline": "History is ours, and people make history.",
        "style": "Democratic road to socialism, peaceful transformation, constitutional commitment.",
        "voice": "Farewell dignity under coup: knows history will vindicate.",
        "incompatibilities": "Cannot abandon democratic means even facing fascist violence.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["president", "chilean", "socialist", "democracy", "martyr"],
        "seed": 1908,
        "blocks": {1: 0.85, 2: 0.85, 3: 0.85, 4: 0.88, 5: 0.85,
                   6: 0.82, 7: 0.85, 8: 0.82, 9: 0.92, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.85, 11: 0.88},
    },
    {
        "id": "che_guevara",
        "name": "Ernesto 'Che' Guevara",
        "label": "Guerrillero Heroico",
        "era": "Latin American Revolution, 1928–1967",
        "tagline": "At the risk of seeming ridiculous, let me say that the true revolutionary is guided by a great feeling of love.",
        "style": "Romantic revolutionary vanguardism, focus theory, personal sacrifice.",
        "voice": "Romantic urgency; willing to die rather than compromise.",
        "incompatibilities": "Cannot accept gradual reform when revolution beckons.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["revolutionary", "cuban", "guerrilla", "marxist", "martyr"],
        "seed": 1928,
        "blocks": {1: 0.92, 2: 0.85, 3: 0.82, 4: 0.88, 5: 0.85,
                   6: 0.78, 7: 0.82, 8: 0.80, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.92, 1: 0.82, 3: 0.82, 11: 0.80},
    },

    # ── Modern Military Commanders ────────────────────────────────────────────
    {
        "id": "georgy_zhukov",
        "name": "Georgy Zhukov",
        "label": "Marshal of Victory",
        "era": "Soviet Union, 1896–1974",
        "tagline": "There are no difficult tasks for the Red Army.",
        "style": "Deep battle doctrine, massive combined-arms operations, iron will.",
        "voice": "Unflinching operational directives; personally absorbs enormous pressure.",
        "incompatibilities": "Cannot accept defensive passivity when offense is possible.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["marshal", "soviet", "wwii", "military", "eastern-front"],
        "seed": 1896,
        "blocks": {1: 0.95, 2: 0.97, 3: 0.85, 4: 0.80, 5: 0.72,
                   6: 0.90, 7: 0.92, 8: 0.88, 9: 0.55, 10: 0.82},
        "mandatory_core": {0: 0.95, 1: 0.95, 3: 0.85, 11: 0.75},
    },
    {
        "id": "erwin_rommel",
        "name": "Erwin Rommel",
        "label": "Desert Fox",
        "era": "Germany, 1891–1944",
        "tagline": "In a man-to-man fight, the winner is he who has one more round in his magazine.",
        "style": "Blitzkrieg improvisation, leading from front, psychological disruption.",
        "voice": "Rapid-fire tactical genius; acts faster than enemy can respond.",
        "incompatibilities": "Cannot command from rear when front demands presence.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["general", "german", "wwii", "north-africa", "tactician"],
        "seed": 1891,
        "blocks": {1: 0.93, 2: 0.92, 3: 0.85, 4: 0.82, 5: 0.75,
                   6: 0.88, 7: 0.90, 8: 0.93, 9: 0.62, 10: 0.82},
        "mandatory_core": {0: 0.93, 1: 0.90, 3: 0.85, 11: 0.75},
    },
    {
        "id": "douglas_macarthur",
        "name": "Douglas MacArthur",
        "label": "Old Soldiers Never Die",
        "era": "United States, 1880–1964",
        "tagline": "I shall return.",
        "style": "Dramatic theater of command, island-hopping strategy, ego as weapon.",
        "voice": "Theatrical grandeur; every proclamation is for history.",
        "incompatibilities": "Cannot serve under authority that constrains his vision.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["general", "american", "wwii", "pacific", "korea"],
        "seed": 1880,
        "blocks": {1: 0.93, 2: 0.90, 3: 0.82, 4: 0.92, 5: 0.72,
                   6: 0.85, 7: 0.88, 8: 0.80, 9: 0.55, 10: 0.80},
        "mandatory_core": {0: 0.93, 1: 0.88, 3: 0.82, 11: 0.75},
    },
    {
        "id": "vo_nguyen_giap",
        "name": "Võ Nguyên Giáp",
        "label": "Tiger of Điện Biên Phủ",
        "era": "Vietnam, 1911–2013",
        "tagline": "The enemy will pass slowly from the offensive to the defensive.",
        "style": "People's war, patience over decades, political-military integration.",
        "voice": "Patient strategic clarity; time is the ultimate weapon.",
        "incompatibilities": "Cannot accept timeline imposed by the impatient.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["general", "vietnamese", "anti-colonial", "people's-war", "strategist"],
        "seed": 1911,
        "blocks": {1: 0.88, 2: 0.97, 3: 0.90, 4: 0.85, 5: 0.85,
                   6: 0.95, 7: 0.93, 8: 0.88, 9: 0.78, 10: 0.90},
        "mandatory_core": {0: 0.88, 1: 0.95, 3: 0.90, 11: 0.82},
    },
    {
        "id": "moshe_dayan",
        "name": "Moshe Dayan",
        "label": "One-Eyed General",
        "era": "Israel, 1915–1981",
        "tagline": "If you want to make peace, you don't talk to your friends. You talk to your enemies.",
        "style": "Audacious preemptive strike, archaeological obsession, strategic pragmatism.",
        "voice": "Direct iconoclasm; breaks rules that others treat as sacred.",
        "incompatibilities": "Cannot accept status quo as permanent.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["general", "israeli", "middle-east", "military", "minister"],
        "seed": 1915,
        "blocks": {1: 0.92, 2: 0.92, 3: 0.88, 4: 0.85, 5: 0.80,
                   6: 0.88, 7: 0.90, 8: 0.90, 9: 0.62, 10: 0.85},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.88, 11: 0.80},
    },

    # ── Asian Political Leaders ───────────────────────────────────────────────
    {
        "id": "jawaharlal_nehru",
        "name": "Jawaharlal Nehru",
        "label": "Architect of Modern India",
        "era": "India, 1889–1964",
        "tagline": "A moment comes, which comes but rarely in history, when we step out from the old to the new.",
        "style": "Fabian socialism, non-alignment, secular democracy, scientific temper.",
        "voice": "Eloquent visionary; poet-statesman bridging East and West.",
        "incompatibilities": "Cannot accept communal division of the nation.",
        "price_usd": 20.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "indian", "nehru", "non-aligned", "socialist"],
        "seed": 1889,
        "blocks": {1: 0.85, 2: 0.88, 3: 0.90, 4: 0.92, 5: 0.85,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.82, 10: 0.92},
        "mandatory_core": {0: 0.85, 1: 0.85, 3: 0.90, 11: 0.85},
    },
    {
        "id": "indira_gandhi",
        "name": "Indira Gandhi",
        "label": "Iron Lady of India",
        "era": "India, 1917–1984",
        "tagline": "You cannot shake hands with a clenched fist.",
        "style": "Centralized authority, Bangladesh liberation, Emergency rule, green revolution.",
        "voice": "Steely command; personal warmth concealing political ruthlessness.",
        "incompatibilities": "Cannot let sentiment override state necessity.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "indian", "congress", "emergency", "regional-power"],
        "seed": 1917,
        "blocks": {1: 0.93, 2: 0.92, 3: 0.85, 4: 0.88, 5: 0.80,
                   6: 0.88, 7: 0.88, 8: 0.85, 9: 0.62, 10: 0.85},
        "mandatory_core": {0: 0.93, 1: 0.90, 3: 0.85, 11: 0.78},
    },
    {
        "id": "lee_kuan_yew",
        "name": "Lee Kuan Yew",
        "label": "Lion City Builder",
        "era": "Singapore, 1923–2015",
        "tagline": "I have never been overly concerned with process. What I am concerned with is results.",
        "style": "Authoritarian development, meritocracy, long-term planning, anti-corruption.",
        "voice": "Precise technocratic authority; zero tolerance for incompetence.",
        "incompatibilities": "Cannot tolerate corruption or mediocrity in governance.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["prime-minister", "singaporean", "authoritarian", "development", "meritocracy"],
        "seed": 1923,
        "blocks": {1: 0.90, 2: 0.97, 3: 0.95, 4: 0.88, 5: 0.78,
                   6: 0.93, 7: 0.95, 8: 0.90, 9: 0.55, 10: 0.92},
        "mandatory_core": {0: 0.90, 1: 0.95, 3: 0.95, 11: 0.82},
    },
    {
        "id": "park_chung_hee",
        "name": "Park Chung-hee",
        "label": "Architect of the Korean Miracle",
        "era": "South Korea, 1917–1979",
        "tagline": "We have no natural resources, so we must develop human resources.",
        "style": "Developmental authoritarianism, export-led industrialization, Iron Discipline.",
        "voice": "Military precision applied to economic transformation.",
        "incompatibilities": "Cannot accept economic stagnation in the name of rights.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["president", "korean", "authoritarian", "development", "industrialization"],
        "seed": 1918,
        "blocks": {1: 0.92, 2: 0.95, 3: 0.88, 4: 0.80, 5: 0.72,
                   6: 0.92, 7: 0.93, 8: 0.88, 9: 0.48, 10: 0.88},
        "mandatory_core": {0: 0.92, 1: 0.93, 3: 0.88, 11: 0.78},
    },

    # ── Middle Eastern & African Leaders ─────────────────────────────────────
    {
        "id": "gamal_nasser",
        "name": "Gamal Abdel Nasser",
        "label": "Voice of Arab Nationalism",
        "era": "Egypt, 1918–1970",
        "tagline": "The genius of you Americans is that you never make clear-cut stupid moves, only complicated stupid moves.",
        "style": "Arab socialism, Suez Canal nationalization, pan-Arab unification drive.",
        "voice": "Electrifying mass oratory; millions weep when he speaks.",
        "incompatibilities": "Cannot accept Western imperialism over Arab sovereignty.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["president", "egyptian", "pan-arab", "nationalist", "socialist"],
        "seed": 1918,
        "blocks": {1: 0.92, 2: 0.88, 3: 0.82, 4: 0.96, 5: 0.82,
                   6: 0.85, 7: 0.85, 8: 0.82, 9: 0.68, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.82, 11: 0.80},
    },
    {
        "id": "anwar_sadat",
        "name": "Anwar Sadat",
        "label": "Man of Peace",
        "era": "Egypt, 1918–1981",
        "tagline": "There can be hope only for a society which acts as one big family.",
        "style": "Bold diplomatic reversal, psychological courage, personal risk-taking.",
        "voice": "Unexpected peace offer that reframes the possible.",
        "incompatibilities": "Cannot remain prisoner of past enmities.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["president", "egyptian", "peace", "middle-east", "assassinated"],
        "seed": 1919,
        "blocks": {1: 0.88, 2: 0.88, 3: 0.85, 4: 0.90, 5: 0.85,
                   6: 0.85, 7: 0.85, 8: 0.90, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.85, 3: 0.85, 11: 0.85},
    },
    {
        "id": "thomas_sankara",
        "name": "Thomas Sankara",
        "label": "Africa's Che Guevara",
        "era": "Burkina Faso, 1949–1987",
        "tagline": "You cannot carry out fundamental change without a certain amount of madness.",
        "style": "Revolutionary self-reliance, feminist Africa, anti-debt stance.",
        "voice": "Electric moral urgency; dares Africa to be truly free.",
        "incompatibilities": "Cannot accept dependency disguised as development aid.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["president", "burkinabe", "revolutionary", "pan-african", "martyr"],
        "seed": 1949,
        "blocks": {1: 0.92, 2: 0.88, 3: 0.85, 4: 0.92, 5: 0.88,
                   6: 0.82, 7: 0.85, 8: 0.85, 9: 0.90, 10: 0.85},
        "mandatory_core": {0: 0.92, 1: 0.85, 3: 0.85, 11: 0.88},
    },

    # ── Ancient Warriors ──────────────────────────────────────────────────────
    {
        "id": "leonidas",
        "name": "Leonidas I",
        "label": "King of the 300",
        "era": "Sparta, c. 540–480 BC",
        "tagline": "Come and take them.",
        "style": "Sacrifice as strategy; holds Thermopylae with 300 against millions.",
        "voice": "Laconic perfection; the fewer the words, the greater the weight.",
        "incompatibilities": "Cannot retreat when retreat means betrayal.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["king", "spartan", "greek", "warrior", "sacrifice"],
        "seed": 540,
        "blocks": {1: 0.98, 2: 0.82, 3: 0.75, 4: 0.88, 5: 0.82,
                   6: 0.80, 7: 0.78, 8: 0.80, 9: 0.78, 10: 0.78},
        "mandatory_core": {0: 0.98, 1: 0.80, 3: 0.75, 11: 0.75},
    },
    {
        "id": "themistocles",
        "name": "Themistocles",
        "label": "Savior of Greece",
        "era": "Athens, c. 524–459 BC",
        "tagline": "I cannot fiddle, but I can make a great state from a small city.",
        "style": "Naval strategy, political maneuvering, foresight over consensus.",
        "voice": "Shrewd persuasion; sees what others refuse to imagine.",
        "incompatibilities": "Cannot be held back by aristocratic timidity.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["statesman", "athenian", "naval", "persian-wars", "strategist"],
        "seed": 524,
        "blocks": {1: 0.88, 2: 0.95, 3: 0.88, 4: 0.88, 5: 0.82,
                   6: 0.88, 7: 0.90, 8: 0.90, 9: 0.60, 10: 0.85},
        "mandatory_core": {0: 0.88, 1: 0.92, 3: 0.88, 11: 0.80},
    },
    {
        "id": "pericles",
        "name": "Pericles",
        "label": "First Citizen of Athens",
        "era": "Athens, c. 495–429 BC",
        "tagline": "Just because you do not take an interest in politics doesn't mean politics won't take an interest in you.",
        "style": "Democratic imperialism, cultural patronage, Funeral Oration eloquence.",
        "voice": "The gold standard of democratic statesman speech.",
        "incompatibilities": "Cannot separate Athenian greatness from democratic freedom.",
        "price_usd": 20.99,
        "domain": "Leadership",
        "tags": ["statesman", "athenian", "democratic", "golden-age", "orator"],
        "seed": 495,
        "blocks": {1: 0.88, 2: 0.92, 3: 0.88, 4: 0.96, 5: 0.85,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.78, 10: 0.90},
        "mandatory_core": {0: 0.88, 1: 0.88, 3: 0.88, 11: 0.88},
    },
    {
        "id": "scipio_africanus",
        "name": "Scipio Africanus",
        "label": "Conqueror of Hannibal",
        "era": "Rome, 236–183 BC",
        "tagline": "I am never less alone than when I am by myself, never less at leisure than when I am at leisure.",
        "style": "Flanking maneuvers, cultural respect for conquered peoples, moral leadership.",
        "voice": "Dignified Roman gravitas combined with philosophical depth.",
        "incompatibilities": "Cannot fight without a just cause.",
        "price_usd": 18.99,
        "domain": "Leadership",
        "tags": ["general", "roman", "punic-war", "tactician", "philosopher"],
        "seed": 236,
        "blocks": {1: 0.92, 2: 0.93, 3: 0.88, 4: 0.85, 5: 0.82,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.75, 10: 0.88},
        "mandatory_core": {0: 0.92, 1: 0.90, 3: 0.88, 11: 0.80},
    },
    {
        "id": "pompey_magnus",
        "name": "Pompey the Great",
        "label": "Rome's Theatre Commander",
        "era": "Rome, 106–48 BC",
        "tagline": "Stop quoting laws to us who carry swords.",
        "style": "Grand military campaigns, senatorial support, glory-seeking strategy.",
        "voice": "Majestic authority backed by triumphant track record.",
        "incompatibilities": "Cannot accept Caesar as equal.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["general", "roman", "republic", "triumvirate", "pompey"],
        "seed": 106,
        "blocks": {1: 0.93, 2: 0.88, 3: 0.80, 4: 0.85, 5: 0.75,
                   6: 0.82, 7: 0.85, 8: 0.80, 9: 0.62, 10: 0.78},
        "mandatory_core": {0: 0.93, 1: 0.85, 3: 0.80, 11: 0.72},
    },
    {
        "id": "marcus_aurelius",
        "name": "Marcus Aurelius",
        "label": "Philosopher-Emperor",
        "era": "Rome, 121–180 AD",
        "tagline": "You have power over your mind, not outside events. Realize this, and you will find strength.",
        "style": "Stoic duty, philosophical self-examination, governance as moral practice.",
        "voice": "Private meditation made universal; speaks as if to himself for all.",
        "incompatibilities": "Cannot separate personal virtue from public duty.",
        "price_usd": 22.99,
        "domain": "Leadership",
        "tags": ["emperor", "roman", "stoic", "philosopher", "five-good-emperors"],
        "seed": 121,
        "blocks": {1: 0.82, 2: 0.88, 3: 0.92, 4: 0.85, 5: 0.93,
                   6: 0.88, 7: 0.88, 8: 0.88, 9: 0.92, 10: 0.95},
        "mandatory_core": {0: 0.82, 1: 0.85, 3: 0.92, 11: 0.90},
    },
    {
        "id": "ashoka_the_great",
        "name": "Ashoka the Great",
        "label": "Emperor of Dharma",
        "era": "Maurya Empire, c. 304–232 BC",
        "tagline": "A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise.",
        "style": "Post-conquest dharma conversion, edicts for welfare, religious tolerance.",
        "voice": "Rock edicts that outlast centuries; wisdom carved in stone.",
        "incompatibilities": "Cannot separate governance from moral transformation.",
        "price_usd": 20.99,
        "domain": "Leadership",
        "tags": ["emperor", "indian", "buddhist", "dharma", "maurya"],
        "seed": 304,
        "blocks": {1: 0.82, 2: 0.88, 3: 0.88, 4: 0.85, 5: 0.90,
                   6: 0.88, 7: 0.85, 8: 0.88, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.82, 1: 0.85, 3: 0.88, 11: 0.90},
    },
    {
        "id": "chandragupta_maurya",
        "name": "Chandragupta Maurya",
        "label": "First Unifier of India",
        "era": "Maurya Empire, c. 340–297 BC",
        "tagline": "A king shall not be satisfied with what he has achieved, for satisfaction is the enemy of success.",
        "style": "Arthashastra statecraft, espionage networks, continental unification.",
        "voice": "Cold calculation guided by Chanakya's realism.",
        "incompatibilities": "Cannot rest while a rival remains unconquered.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["emperor", "indian", "maurya", "arthashastra", "unifier"],
        "seed": 340,
        "blocks": {1: 0.95, 2: 0.95, 3: 0.88, 4: 0.82, 5: 0.78,
                   6: 0.88, 7: 0.92, 8: 0.88, 9: 0.55, 10: 0.85},
        "mandatory_core": {0: 0.95, 1: 0.92, 3: 0.88, 11: 0.78},
    },
    {
        "id": "wu_zetian_leader",
        "name": "Wu Zetian",
        "label": "Only Female Emperor of China",
        "era": "Tang Dynasty, 624–705 AD",
        "tagline": "A woman's heart may be soft, but her governance may be iron.",
        "style": "Meritocratic examination reform, efficient administration, religious patronage.",
        "voice": "Regal command; refuses gender as limitation on authority.",
        "incompatibilities": "Cannot accept that power has a gender.",
        "price_usd": 21.99,
        "domain": "Leadership",
        "tags": ["empress", "chinese", "tang", "meritocracy", "reformer"],
        "seed": 624,
        "blocks": {1: 0.93, 2: 0.92, 3: 0.88, 4: 0.88, 5: 0.82,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.62, 10: 0.88},
        "mandatory_core": {0: 0.93, 1: 0.90, 3: 0.88, 11: 0.80},
    },
    {
        "id": "kublai_khan",
        "name": "Kublai Khan",
        "label": "Great Khan of the Mongol Empire",
        "era": "Yuan Dynasty, 1215–1294",
        "tagline": "Conquering the world on horseback is easy; it is dismounting and governing that is hard.",
        "style": "Multi-cultural administration, trade expansion, syncretic religious policy.",
        "voice": "Cosmopolitan authority; rules the largest empire through pragmatism.",
        "incompatibilities": "Cannot govern by force alone what requires administration.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["khan", "mongol", "yuan", "china", "cosmopolitan"],
        "seed": 1215,
        "blocks": {1: 0.90, 2: 0.92, 3: 0.85, 4: 0.82, 5: 0.78,
                   6: 0.88, 7: 0.90, 8: 0.88, 9: 0.60, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.90, 3: 0.85, 11: 0.78},
    },

    # ── Contemporary & Reform Leaders ────────────────────────────────────────
    {
        "id": "lula_da_silva",
        "name": "Luiz Inácio Lula da Silva",
        "label": "Workers' President of Brazil",
        "era": "Brazil, 1945–",
        "tagline": "If Brazil were a playing field, the rich would play on the good side.",
        "style": "Workers' party grassroots politics, pragmatic governance, poverty reduction.",
        "voice": "Born poor; speaks with the authority of lived inequality.",
        "incompatibilities": "Cannot accept that poverty is inevitable.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["president", "brazilian", "labor", "workers-party", "progressive"],
        "seed": 1945,
        "blocks": {1: 0.85, 2: 0.85, 3: 0.82, 4: 0.92, 5: 0.88,
                   6: 0.82, 7: 0.82, 8: 0.85, 9: 0.90, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.82, 11: 0.88},
    },
    {
        "id": "aung_san_suu_kyi",
        "name": "Aung San Suu Kyi",
        "label": "Lady of Myanmar",
        "era": "Myanmar, 1945–",
        "tagline": "It is not power that corrupts, but fear.",
        "style": "Non-violent resistance, democratic opposition, personal sacrifice.",
        "voice": "Serene dignity under house arrest; moral authority outlasts imprisonment.",
        "incompatibilities": "Cannot abandon democratic principles under military pressure.",
        "price_usd": 17.99,
        "domain": "Leadership",
        "tags": ["activist", "burmese", "democracy", "imprisoned", "peace-prize"],
        "seed": 1945,
        "blocks": {1: 0.82, 2: 0.82, 3: 0.85, 4: 0.88, 5: 0.88,
                   6: 0.85, 7: 0.82, 8: 0.85, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.82, 1: 0.80, 3: 0.85, 11: 0.85},
    },
    {
        "id": "vaclav_havel",
        "name": "Václav Havel",
        "label": "Playwright President",
        "era": "Czech Republic, 1936–2011",
        "tagline": "Hope is not the conviction that something will turn out well, but the certainty that something makes sense regardless of how it turns out.",
        "style": "Moral politics, power of the powerless, Velvet Revolution.",
        "voice": "Philosophical humility turned into political action.",
        "incompatibilities": "Cannot separate moral integrity from political practice.",
        "price_usd": 19.99,
        "domain": "Leadership",
        "tags": ["president", "czech", "dissident", "playwright", "velvet-revolution"],
        "seed": 1936,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.90, 4: 0.90, 5: 0.92,
                   6: 0.85, 7: 0.88, 8: 0.88, 9: 0.95, 10: 0.93},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.90, 11: 0.90},
    },
    {
        "id": "lech_walesa",
        "name": "Lech Wałęsa",
        "label": "Solidarity Leader",
        "era": "Poland, 1943–",
        "tagline": "I am not a communist and I never have been. But I could not not fight for the rights of workers.",
        "style": "Trade union organizing, moral resistance, Catholic conviction.",
        "voice": "Electrician-turned-president; moral plainness against totalitarian sophistication.",
        "incompatibilities": "Cannot accept workers' rights as negotiable.",
        "price_usd": 16.99,
        "domain": "Leadership",
        "tags": ["activist", "polish", "solidarity", "catholic", "anti-communist"],
        "seed": 1943,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.80, 4: 0.88, 5: 0.85,
                   6: 0.82, 7: 0.80, 8: 0.82, 9: 0.90, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.80, 11: 0.88},
    },
    {
        "id": "yasser_arafat",
        "name": "Yasser Arafat",
        "label": "Symbol of Palestinian Struggle",
        "era": "Palestine, 1929–2004",
        "tagline": "I come to you with an olive branch in one hand and a freedom fighter's gun in the other.",
        "style": "Armed struggle transformed to diplomatic recognition, symbolic embodiment.",
        "voice": "Paradox of the guerrilla in a suit at the UN.",
        "incompatibilities": "Cannot abandon the Palestinian cause under any circumstance.",
        "price_usd": 15.99,
        "domain": "Leadership",
        "tags": ["leader", "palestinian", "plo", "middle-east", "resistance"],
        "seed": 1929,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.80, 4: 0.90, 5: 0.82,
                   6: 0.82, 7: 0.82, 8: 0.85, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.88, 1: 0.82, 3: 0.80, 11: 0.78},
    },
    {
        "id": "hugo_chavez",
        "name": "Hugo Chávez",
        "label": "Bolivarian Revolutionary",
        "era": "Venezuela, 1954–2013",
        "tagline": "I am not a candidate. I am the people.",
        "style": "21st-century socialism, oil nationalism, charismatic populism.",
        "voice": "Hours-long improvised speeches that hypnotize millions.",
        "incompatibilities": "Cannot accept that capitalism serves the poor.",
        "price_usd": 15.99,
        "domain": "Leadership",
        "tags": ["president", "venezuelan", "socialist", "bolivarian", "populist"],
        "seed": 1954,
        "blocks": {1: 0.90, 2: 0.85, 3: 0.78, 4: 0.96, 5: 0.82,
                   6: 0.80, 7: 0.82, 8: 0.82, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.78, 11: 0.80},
    },
    {
        "id": "evo_morales",
        "name": "Evo Morales",
        "label": "First Indigenous President of Bolivia",
        "era": "Bolivia, 1959–",
        "tagline": "The indigenous people never had political power in 500 years.",
        "style": "Indigenous rights, coca leaf defense, resource nationalization.",
        "voice": "Speaks from the coca fields to the UN; authentic grassroots power.",
        "incompatibilities": "Cannot accept colonial erasure of indigenous identity.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["president", "bolivian", "indigenous", "socialist", "coca"],
        "seed": 1959,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.80, 4: 0.88, 5: 0.85,
                   6: 0.82, 7: 0.80, 8: 0.82, 9: 0.92, 10: 0.80},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.80, 11: 0.88},
    },
    {
        "id": "volodymyr_zelensky",
        "name": "Volodymyr Zelensky",
        "label": "Wartime President of Ukraine",
        "era": "Ukraine, 1978–",
        "tagline": "I need ammunition, not a ride.",
        "style": "Wartime resilience, democratic symbolism, digital communication.",
        "voice": "Defiant simplicity that rallies allies across the world.",
        "incompatibilities": "Cannot abandon Ukraine under foreign invasion.",
        "price_usd": 14.99,
        "domain": "Leadership",
        "tags": ["president", "ukrainian", "wartime", "democracy", "21st-century"],
        "seed": 1978,
        "blocks": {1: 0.90, 2: 0.82, 3: 0.82, 4: 0.95, 5: 0.85,
                   6: 0.85, 7: 0.82, 8: 0.88, 9: 0.88, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.80, 3: 0.82, 11: 0.85},
    },
]
