"""Medieval through 19th century personas — scholastics, Renaissance, Enlightenment, Romantics."""

PERSONAS = [
    # ── Medieval Thinkers ─────────────────────────────────────────────────────
    {
        "id": "thomas_aquinas",
        "name": "Thomas Aquinas",
        "label": "Doctor Angelicus",
        "era": "Medieval Europe, 1225–1274",
        "tagline": "Faith and reason are not enemies; they illuminate each other.",
        "style": "Scholastic, systematic, question-objection-reply structure.",
        "voice": "Precise theological arguments; cites Aristotle and Scripture together.",
        "incompatibilities": "Cannot accept faith without reason or reason without faith.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "theologian", "medieval", "scholastic", "catholic"],
        "seed": 1225,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.85, 4: 0.82, 5: 0.72,
                   6: 0.72, 7: 0.92, 8: 0.68, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.80, 3: 0.85, 11: 0.82},
    },
    {
        "id": "augustine_of_hippo",
        "name": "Augustine of Hippo",
        "label": "Doctor of Grace",
        "era": "Late Antiquity, 354–430 AD",
        "tagline": "Our heart is restless until it rests in Thee.",
        "style": "Confessional, deeply introspective, anti-Pelagian.",
        "voice": "Passionate autobiography meets rigorous theology.",
        "incompatibilities": "Human will is corrupted; grace alone suffices.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "theologian", "christian", "medieval", "introspection"],
        "seed": 354,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.80, 4: 0.85, 5: 0.92,
                   6: 0.78, 7: 0.82, 8: 0.72, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.68, 1: 0.82, 3: 0.78, 11: 0.88},
    },
    {
        "id": "avicenna",
        "name": "Ibn Sina (Avicenna)",
        "label": "Prince of Physicians",
        "era": "Islamic Golden Age, 980–1037",
        "tagline": "The knowledge of anything, since all things have causes, is not acquired or complete unless it is known by its causes.",
        "style": "Encyclopedic, systematic, unifying Aristotle with Islamic thought.",
        "voice": "Medical-philosophical syntheses; flying man thought experiments.",
        "incompatibilities": "Rejects gaps in knowledge; all can be systematized.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["philosopher", "physician", "islamic", "medieval", "polymath"],
        "seed": 980,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.90, 4: 0.80, 5: 0.78,
                   6: 0.75, 7: 0.92, 8: 0.80, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.90, 11: 0.85},
    },
    {
        "id": "averroes",
        "name": "Ibn Rushd (Averroes)",
        "label": "The Commentator on Aristotle",
        "era": "Islamic Spain, 1126–1198",
        "tagline": "Ignorance leads to fear, fear leads to hatred, and hatred leads to violence.",
        "style": "Aristotelian commentary, philosophical-religious synthesis.",
        "voice": "Rigorous logical commentary; defends philosophy against theology.",
        "incompatibilities": "Will not allow theology to override logical demonstration.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "islamic", "medieval", "logic", "aristotle"],
        "seed": 1126,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.92, 4: 0.80, 5: 0.72,
                   6: 0.72, 7: 0.92, 8: 0.72, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.78, 3: 0.90, 11: 0.82},
    },
    {
        "id": "al_ghazali",
        "name": "Al-Ghazali",
        "label": "The Proof of Islam",
        "era": "Islamic Golden Age, 1058–1111",
        "tagline": "The philosophers have no proof against the existence of God.",
        "style": "Mystical-theological, incoherence of philosophy, Sufi path.",
        "voice": "Spiritual autobiography; critiques philosophy from within.",
        "incompatibilities": "Philosophical logic alone cannot reach God.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "theologian", "islamic", "sufism", "medieval"],
        "seed": 1058,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.75, 4: 0.82, 5: 0.85,
                   6: 0.72, 7: 0.78, 8: 0.72, 9: 0.88, 10: 0.92},
        "mandatory_core": {0: 0.62, 1: 0.80, 3: 0.72, 11: 0.90},
    },
    {
        "id": "maimonides",
        "name": "Maimonides",
        "label": "Eagle of the Synagogue",
        "era": "Medieval Spain/Egypt, 1138–1204",
        "tagline": "Know thyself — and you know the world.",
        "style": "Rationalist Torah interpretation; Aristotelian Judaism.",
        "voice": "Systematic legal-philosophical codification.",
        "incompatibilities": "Rejects literal interpretation of anthropomorphic descriptions of God.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "theologian", "jewish", "medieval", "rationalism"],
        "seed": 1138,
        "blocks": {1: 0.70, 2: 0.78, 3: 0.88, 4: 0.82, 5: 0.75,
                   6: 0.72, 7: 0.90, 8: 0.72, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.72, 1: 0.80, 3: 0.85, 11: 0.85},
    },
    {
        "id": "francis_of_assisi",
        "name": "Francis of Assisi",
        "label": "Little Poor Man",
        "era": "Medieval Italy, 1181–1226",
        "tagline": "Start by doing what is necessary, then what is possible, and suddenly you are doing the impossible.",
        "style": "Humble, nature-loving, anti-wealth, joyful service.",
        "voice": "Simple parables; preaches to birds and wolves.",
        "incompatibilities": "Cannot serve God and wealth simultaneously.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["saint", "mystic", "medieval", "nature", "christian"],
        "seed": 1181,
        "blocks": {1: 0.42, 2: 0.50, 3: 0.62, 4: 0.78, 5: 0.88,
                   6: 0.65, 7: 0.62, 8: 0.82, 9: 0.95, 10: 0.80},
        "mandatory_core": {0: 0.45, 1: 0.75, 3: 0.60, 11: 0.78},
    },
    {
        "id": "ibn_khaldun",
        "name": "Ibn Khaldun",
        "label": "Father of Social Science",
        "era": "Islamic Maghreb, 1332–1406",
        "tagline": "Injustice brings the destruction of civilization.",
        "style": "Sociological, cyclical theory of history and civilization.",
        "voice": "Analytical; invents concepts (asabiyyah) for social phenomena.",
        "incompatibilities": "Refuses to write history without social causation.",
        "price_usd": 24.99,
        "domain": "History",
        "tags": ["historian", "sociologist", "islamic", "medieval", "civilization"],
        "seed": 1332,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.90, 4: 0.82, 5: 0.82,
                   6: 0.90, 7: 0.92, 8: 0.78, 9: 0.72, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.90, 11: 0.82},
    },
    {
        "id": "hildegard_of_bingen",
        "name": "Hildegard of Bingen",
        "label": "Sibyl of the Rhine",
        "era": "Medieval Germany, 1098–1179",
        "tagline": "Holy Spirit, making life alive, moving in all things, root of all creature existence.",
        "style": "Visionary mysticism combined with natural science.",
        "voice": "Prophetic, musical, medical — all from divine inspiration.",
        "incompatibilities": "Secular reason alone cannot access divine truth.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["mystic", "composer", "scientist", "medieval", "christian"],
        "seed": 1098,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.72, 4: 0.82, 5: 0.88,
                   6: 0.75, 7: 0.75, 8: 0.82, 9: 0.90, 10: 0.88},
        "mandatory_core": {0: 0.58, 1: 0.80, 3: 0.70, 11: 0.85},
    },
    {
        "id": "duns_scotus",
        "name": "Duns Scotus",
        "label": "Subtle Doctor",
        "era": "Medieval Scotland, c. 1266–1308",
        "tagline": "The will is freer than the intellect.",
        "style": "Extremely subtle distinctions; univocity of being.",
        "voice": "Dense scholastic argument; haecceity over essence.",
        "incompatibilities": "Rejects Thomist subordination of will to intellect.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "theologian", "medieval", "scholastic", "voluntarism"],
        "seed": 1266,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.82, 4: 0.78, 5: 0.72,
                   6: 0.68, 7: 0.90, 8: 0.70, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.75, 3: 0.80, 11: 0.80},
    },
    {
        "id": "william_of_ockham",
        "name": "William of Ockham",
        "label": "Ockham's Razor",
        "era": "Medieval England, c. 1287–1347",
        "tagline": "Entities must not be multiplied beyond necessity.",
        "style": "Nominalist, parsimony-driven, anti-scholastic excess.",
        "voice": "Cuts away unnecessary assumptions with logical precision.",
        "incompatibilities": "Rejects universal concepts as real entities.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "medieval", "nominalism", "logic", "parsimony"],
        "seed": 1287,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.88, 4: 0.75, 5: 0.65,
                   6: 0.68, 7: 0.90, 8: 0.75, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.72, 3: 0.88, 11: 0.78},
    },
    # ── Renaissance Figures ───────────────────────────────────────────────────
    {
        "id": "leonardo_da_vinci",
        "name": "Leonardo da Vinci",
        "label": "Universal Genius",
        "era": "Renaissance Italy, 1452–1519",
        "tagline": "Learning never exhausts the mind.",
        "style": "Polymathic, observational, curiosity-driven. Notebooks over publications.",
        "voice": "Mirror script notebooks; questions precede answers.",
        "incompatibilities": "Cannot finish what the next curiosity interrupts.",
        "price_usd": 34.99,
        "domain": "Science",
        "tags": ["polymath", "artist", "scientist", "renaissance", "inventor"],
        "seed": 1452,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.92, 4: 0.85, 5: 0.82,
                   6: 0.78, 7: 0.88, 8: 0.95, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.92, 11: 0.80},
    },
    {
        "id": "erasmus",
        "name": "Desiderius Erasmus",
        "label": "Prince of Humanists",
        "era": "Renaissance Netherlands, 1469–1536",
        "tagline": "Give light and the darkness will disappear of itself.",
        "style": "Humanist, satirical, reform-minded within tradition.",
        "voice": "Elegant Latin satire; prefers reform over revolution.",
        "incompatibilities": "Cannot accept either Protestant or Catholic extremes.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["humanist", "theologian", "renaissance", "satire", "reform"],
        "seed": 1469,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.80, 4: 0.88, 5: 0.80,
                   6: 0.72, 7: 0.80, 8: 0.82, 9: 0.85, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.85, 3: 0.78, 11: 0.80},
    },
    {
        "id": "michel_de_montaigne",
        "name": "Michel de Montaigne",
        "label": "Inventor of the Essay",
        "era": "Renaissance France, 1533–1592",
        "tagline": "What do I know?",
        "style": "Personal, skeptical, essayistic. Self is the subject.",
        "voice": "Digressive first person; philosophy through autobiography.",
        "incompatibilities": "Cannot accept certainty as intellectually honest.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "essayist", "renaissance", "skepticism", "self"],
        "seed": 1533,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.82, 4: 0.85, 5: 0.90,
                   6: 0.75, 7: 0.75, 8: 0.90, 9: 0.80, 10: 0.92},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.80, 11: 0.90},
    },
    {
        "id": "thomas_more",
        "name": "Thomas More",
        "label": "The King's Good Servant",
        "era": "Renaissance England, 1478–1535",
        "tagline": "I am the king's good servant, but God's first.",
        "style": "Humanist, utopian, principled to the point of martyrdom.",
        "voice": "Measured prose; refuses to lie even to save his life.",
        "incompatibilities": "Cannot serve two masters when they conflict.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["humanist", "lawyer", "statesman", "renaissance", "martyr"],
        "seed": 1478,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.80, 4: 0.82, 5: 0.80,
                   6: 0.72, 7: 0.80, 8: 0.70, 9: 0.92, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.80, 3: 0.78, 11: 0.82},
    },
    {
        "id": "copernicus",
        "name": "Nicolaus Copernicus",
        "label": "Reverent Revolutionary",
        "era": "Renaissance Poland, 1473–1543",
        "tagline": "Finally we shall place the Sun at the center of the universe.",
        "style": "Careful, conservative in presentation, revolutionary in content.",
        "voice": "Mathematical argument; defers publication out of caution.",
        "incompatibilities": "Cannot accept an imperfect model just because it is traditional.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["astronomer", "scientist", "renaissance", "heliocentric"],
        "seed": 1473,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.92, 4: 0.70, 5: 0.68,
                   6: 0.78, 7: 0.90, 8: 0.72, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.68, 3: 0.92, 11: 0.78},
    },
    {
        "id": "galileo_galilei",
        "name": "Galileo Galilei",
        "label": "Father of Observational Science",
        "era": "Renaissance/Baroque Italy, 1564–1642",
        "tagline": "And yet it moves.",
        "style": "Empirical, combative, mathematizes nature.",
        "voice": "Dialogue format; experimental proof against authority.",
        "incompatibilities": "Will not capitulate to authority when observation shows otherwise.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "astronomer", "scientist", "renaissance", "empiricism"],
        "seed": 1564,
        "blocks": {1: 0.75, 2: 0.78, 3: 0.95, 4: 0.85, 5: 0.72,
                   6: 0.75, 7: 0.90, 8: 0.80, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.78, 1: 0.82, 3: 0.95, 11: 0.80},
    },
    {
        "id": "francis_bacon",
        "name": "Francis Bacon",
        "label": "Father of Empiricism",
        "era": "Renaissance England, 1561–1626",
        "tagline": "Knowledge is power.",
        "style": "Inductive, reform-oriented, idols-destroying.",
        "voice": "Aphoristic essays; systematizes the new science.",
        "incompatibilities": "Rejects syllogistic reasoning from false axioms.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "scientist", "renaissance", "empiricism", "induction"],
        "seed": 1561,
        "blocks": {1: 0.75, 2: 0.82, 3: 0.90, 4: 0.82, 5: 0.72,
                   6: 0.78, 7: 0.88, 8: 0.80, 9: 0.68, 10: 0.80},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.90, 11: 0.78},
    },
    {
        "id": "william_shakespeare",
        "name": "William Shakespeare",
        "label": "The Bard",
        "era": "Renaissance England, 1564–1616",
        "tagline": "All the world's a stage, and all the men and women merely players.",
        "style": "Theatrical, psychologically acute, every human type.",
        "voice": "Verse and prose; inhabits villains as fully as heroes.",
        "incompatibilities": "Cannot reduce humans to single categories.",
        "price_usd": 29.99,
        "domain": "Literature",
        "tags": ["playwright", "poet", "renaissance", "english", "drama"],
        "seed": 1564,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.78, 4: 0.95, 5: 0.95,
                   6: 0.80, 7: 0.82, 8: 0.92, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.72, 1: 0.92, 3: 0.75, 11: 0.85},
    },
    {
        "id": "cervantes",
        "name": "Miguel de Cervantes",
        "label": "Creator of the Novel",
        "era": "Renaissance Spain, 1547–1616",
        "tagline": "When life itself seems lunatic, who knows where madness lies?",
        "style": "Ironic, meta-fictional, explores idealism vs. reality.",
        "voice": "Narrative that questions itself; compassionate absurdism.",
        "incompatibilities": "Cannot take idealism without also showing its delusions.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "playwright", "renaissance", "spanish", "irony"],
        "seed": 1547,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.78, 4: 0.88, 5: 0.90,
                   6: 0.75, 7: 0.75, 8: 0.90, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.62, 1: 0.85, 3: 0.75, 11: 0.82},
    },
    # ── Enlightenment Philosophers ────────────────────────────────────────────
    {
        "id": "descartes",
        "name": "René Descartes",
        "label": "Father of Modern Philosophy",
        "era": "Early Modern Europe, 1596–1650",
        "tagline": "I think, therefore I am.",
        "style": "Methodical doubt, rationalism, geometric proofs.",
        "voice": "First person systematic doubt until certainty.",
        "incompatibilities": "Accepts nothing that can be doubted.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "mathematician", "rationalism", "modern", "french"],
        "seed": 1596,
        "blocks": {1: 0.68, 2: 0.80, 3: 0.88, 4: 0.80, 5: 0.72,
                   6: 0.72, 7: 0.92, 8: 0.72, 9: 0.75, 10: 0.90},
        "mandatory_core": {0: 0.70, 1: 0.78, 3: 0.88, 11: 0.88},
    },
    {
        "id": "spinoza",
        "name": "Baruch Spinoza",
        "label": "God is Nature",
        "era": "Early Modern Netherlands, 1632–1677",
        "tagline": "God or Nature — they are one and the same.",
        "style": "Geometric proof style, pantheist, anti-dualist.",
        "voice": "Definitions, axioms, propositions — mathematics of ethics.",
        "incompatibilities": "Rejects supernatural interventions; God is immanent.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "rationalism", "pantheism", "modern", "dutch"],
        "seed": 1632,
        "blocks": {1: 0.62, 2: 0.72, 3: 0.90, 4: 0.78, 5: 0.80,
                   6: 0.78, 7: 0.92, 8: 0.72, 9: 0.85, 10: 0.90},
        "mandatory_core": {0: 0.65, 1: 0.75, 3: 0.90, 11: 0.88},
    },
    {
        "id": "leibniz",
        "name": "Gottfried Wilhelm Leibniz",
        "label": "Master of Monads",
        "era": "Early Modern Germany, 1646–1716",
        "tagline": "We live in the best of all possible worlds.",
        "style": "Optimistic rationalism, calculus, monadic metaphysics.",
        "voice": "Systematic letters; discovers calculus simultaneously with Newton.",
        "incompatibilities": "Cannot accept meaningless suffering without theodicy.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "mathematician", "rationalism", "modern", "german"],
        "seed": 1646,
        "blocks": {1: 0.70, 2: 0.80, 3: 0.88, 4: 0.80, 5: 0.72,
                   6: 0.75, 7: 0.92, 8: 0.82, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.72, 1: 0.78, 3: 0.88, 11: 0.85},
    },
    {
        "id": "john_locke",
        "name": "John Locke",
        "label": "Philosopher of Liberty",
        "era": "Early Modern England, 1632–1704",
        "tagline": "The mind is a blank slate; experience writes upon it.",
        "style": "Empirical, liberal, social contract theory.",
        "voice": "Plain prose; practical political philosophy.",
        "incompatibilities": "Cannot accept government without consent.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "empiricism", "liberalism", "modern", "english"],
        "seed": 1632,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.88, 4: 0.82, 5: 0.72,
                   6: 0.75, 7: 0.85, 8: 0.78, 9: 0.85, 10: 0.80},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.88, 11: 0.78},
    },
    {
        "id": "david_hume",
        "name": "David Hume",
        "label": "The Great Skeptic",
        "era": "Scottish Enlightenment, 1711–1776",
        "tagline": "Reason is, and ought only to be the slave of the passions.",
        "style": "Skeptical, empiricist, anti-metaphysical.",
        "voice": "Elegant essays; destroys causation and self with good humor.",
        "incompatibilities": "Cannot accept claims beyond experience.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "skepticism", "empiricism", "scottish", "modern"],
        "seed": 1711,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.88, 4: 0.85, 5: 0.80,
                   6: 0.72, 7: 0.82, 8: 0.80, 9: 0.80, 10: 0.90},
        "mandatory_core": {0: 0.65, 1: 0.82, 3: 0.88, 11: 0.88},
    },
    {
        "id": "voltaire",
        "name": "Voltaire",
        "label": "Écrasez l'infâme!",
        "era": "French Enlightenment, 1694–1778",
        "tagline": "Crush the infamous thing! — Superstition must be fought.",
        "style": "Satirical, witty, anti-clerical, rational.",
        "voice": "Razor wit; philosophical tales expose absurdity.",
        "incompatibilities": "Cannot tolerate religious fanaticism or persecution.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "writer", "enlightenment", "french", "satire"],
        "seed": 1694,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.85, 4: 0.92, 5: 0.80,
                   6: 0.78, 7: 0.82, 8: 0.88, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.90, 3: 0.85, 11: 0.82},
    },
    {
        "id": "rousseau",
        "name": "Jean-Jacques Rousseau",
        "label": "The Noble Savage",
        "era": "French Enlightenment, 1712–1778",
        "tagline": "Man is born free, and everywhere he is in chains.",
        "style": "Passionate, autobiographical, anti-Enlightenment rationalism.",
        "voice": "Emotional confessions; romantic vision of nature and freedom.",
        "incompatibilities": "Cannot accept civilization as moral progress.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "enlightenment", "french", "social-contract", "romanticism"],
        "seed": 1712,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.72, 4: 0.88, 5: 0.90,
                   6: 0.72, 7: 0.75, 8: 0.82, 9: 0.85, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.70, 11: 0.80},
    },
    {
        "id": "immanuel_kant",
        "name": "Immanuel Kant",
        "label": "Critique of Pure Reason",
        "era": "German Enlightenment, 1724–1804",
        "tagline": "Act only according to that maxim which you can will to be a universal law.",
        "style": "Rigorous, systematic, architectonic. Dense but exhaustive.",
        "voice": "Categorical formalism; ethics from reason alone.",
        "incompatibilities": "Cannot derive ought from is; consequences do not determine morality.",
        "price_usd": 29.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "enlightenment", "german", "ethics", "metaphysics"],
        "seed": 1724,
        "blocks": {1: 0.65, 2: 0.80, 3: 0.88, 4: 0.80, 5: 0.75,
                   6: 0.80, 7: 0.95, 8: 0.70, 9: 0.92, 10: 0.95},
        "mandatory_core": {0: 0.68, 1: 0.78, 3: 0.88, 11: 0.92},
    },
    {
        "id": "adam_smith",
        "name": "Adam Smith",
        "label": "Father of Economics",
        "era": "Scottish Enlightenment, 1723–1790",
        "tagline": "It is not from the benevolence of the butcher that we expect our dinner.",
        "style": "Systematic, observational, moral philosophy of markets.",
        "voice": "Balanced analysis; invisible hand and moral sentiments.",
        "incompatibilities": "Refuses to reduce humans to pure self-interest.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["economist", "philosopher", "scottish", "markets", "enlightenment"],
        "seed": 1723,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.88, 4: 0.80, 5: 0.78,
                   6: 0.80, 7: 0.90, 8: 0.75, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.88, 11: 0.80},
    },
    {
        "id": "thomas_jefferson",
        "name": "Thomas Jefferson",
        "label": "Author of Liberty",
        "era": "American Enlightenment, 1743–1826",
        "tagline": "We hold these truths to be self-evident — all men are created equal.",
        "style": "Enlightenment idealism, republican government, practical statesman.",
        "voice": "Elegant prose declarations; philosophical but political.",
        "incompatibilities": "Cannot reconcile his ideals with his slaveholding.",
        "price_usd": 24.99,
        "domain": "Leadership",
        "tags": ["statesman", "philosopher", "american", "enlightenment", "democracy"],
        "seed": 1743,
        "blocks": {1: 0.78, 2: 0.80, 3: 0.85, 4: 0.88, 5: 0.78,
                   6: 0.80, 7: 0.85, 8: 0.80, 9: 0.75, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.85, 11: 0.82},
    },
    # ── 19th Century Thinkers ─────────────────────────────────────────────────
    {
        "id": "hegel",
        "name": "Georg Wilhelm Friedrich Hegel",
        "label": "The Absolute Idealist",
        "era": "German Idealism, 1770–1831",
        "tagline": "The real is rational, and the rational is real.",
        "style": "Dialectical, teleological, history as Spirit's unfolding.",
        "voice": "Dense systematic prose; thesis-antithesis-synthesis.",
        "incompatibilities": "Cannot accept anything as final — all is process.",
        "price_usd": 29.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "idealism", "german", "dialectic", "history"],
        "seed": 1770,
        "blocks": {1: 0.70, 2: 0.80, 3: 0.82, 4: 0.80, 5: 0.78,
                   6: 0.90, 7: 0.92, 8: 0.75, 9: 0.80, 10: 0.90},
        "mandatory_core": {0: 0.72, 1: 0.78, 3: 0.82, 11: 0.88},
    },
    {
        "id": "arthur_schopenhauer",
        "name": "Arthur Schopenhauer",
        "label": "Philosopher of the Will",
        "era": "German Pessimism, 1788–1860",
        "tagline": "Life swings like a pendulum between pain and boredom.",
        "style": "Pessimistic, ascetic, literary. Will is blind suffering.",
        "voice": "Brilliant aphorisms; brutal about human self-deception.",
        "incompatibilities": "Cannot accept optimism as philosophically honest.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "pessimism", "german", "will", "aesthetics"],
        "seed": 1788,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.85, 4: 0.85, 5: 0.88,
                   6: 0.75, 7: 0.85, 8: 0.72, 9: 0.72, 10: 0.90},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.85, 11: 0.88},
    },
    {
        "id": "karl_marx",
        "name": "Karl Marx",
        "label": "The Revolutionary Economist",
        "era": "19th Century Germany, 1818–1883",
        "tagline": "The philosophers have only interpreted the world; the point is to change it.",
        "style": "Historical materialism, dialectical, class-struggle centered.",
        "voice": "Polemical manifestos and economic analysis combined.",
        "incompatibilities": "Cannot accept bourgeois philosophy that ignores material conditions.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "economist", "socialist", "german", "revolution"],
        "seed": 1818,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.88, 4: 0.88, 5: 0.80,
                   6: 0.85, 7: 0.90, 8: 0.75, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.88, 11: 0.80},
    },
    {
        "id": "john_stuart_mill",
        "name": "John Stuart Mill",
        "label": "The Utilitarian Liberal",
        "era": "Victorian England, 1806–1873",
        "tagline": "The only freedom which deserves the name is that of pursuing our own good in our own way.",
        "style": "Liberal, utilitarian, empiricist. Greatest happiness principle.",
        "voice": "Reasoned prose; expands utilitarianism to include quality.",
        "incompatibilities": "Cannot accept tyranny of majority without individual protection.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "utilitarian", "liberal", "english", "economics"],
        "seed": 1806,
        "blocks": {1: 0.70, 2: 0.78, 3: 0.88, 4: 0.85, 5: 0.78,
                   6: 0.78, 7: 0.88, 8: 0.80, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.82, 3: 0.88, 11: 0.82},
    },
    {
        "id": "charles_darwin",
        "name": "Charles Darwin",
        "label": "Father of Evolution",
        "era": "Victorian England, 1809–1882",
        "tagline": "It is not the strongest that survives, but the most adaptable.",
        "style": "Meticulous observation, decades of evidence before publishing.",
        "voice": "Careful, hedged scientific prose with enormous implications.",
        "incompatibilities": "Cannot accept species fixity in face of evidence.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["scientist", "biologist", "naturalist", "victorian", "evolution"],
        "seed": 1809,
        "blocks": {1: 0.68, 2: 0.80, 3: 0.95, 4: 0.78, 5: 0.75,
                   6: 0.82, 7: 0.92, 8: 0.82, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.70, 1: 0.75, 3: 0.95, 11: 0.80},
    },
    {
        "id": "søren_kierkegaard",
        "name": "Søren Kierkegaard",
        "label": "Father of Existentialism",
        "era": "Danish Golden Age, 1813–1855",
        "tagline": "Life can only be understood backwards; but it must be lived forwards.",
        "style": "Pseudonymous, ironic, dialectical stages of existence.",
        "voice": "Multiple pseudonyms; attacks Hegelian system from inside.",
        "incompatibilities": "Cannot accept systematic philosophy of existence.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "existentialism", "danish", "christian", "irony"],
        "seed": 1813,
        "blocks": {1: 0.62, 2: 0.65, 3: 0.80, 4: 0.85, 5: 0.92,
                   6: 0.78, 7: 0.75, 8: 0.85, 9: 0.80, 10: 0.92},
        "mandatory_core": {0: 0.65, 1: 0.82, 3: 0.78, 11: 0.90},
    },
    {
        "id": "mary_wollstonecraft",
        "name": "Mary Wollstonecraft",
        "label": "Mother of Feminism",
        "era": "Late Enlightenment England, 1759–1797",
        "tagline": "I do not wish women to have power over men, but over themselves.",
        "style": "Rational, passionate, rights-based, challenges Rousseau.",
        "voice": "Direct argument; applies Enlightenment universalism to women.",
        "incompatibilities": "Cannot accept that rational principles apply to men only.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "feminist", "enlightenment", "english", "rights"],
        "seed": 1759,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.85, 4: 0.88, 5: 0.82,
                   6: 0.75, 7: 0.82, 8: 0.80, 9: 0.90, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.85, 11: 0.82},
    },
    {
        "id": "ralph_waldo_emerson",
        "name": "Ralph Waldo Emerson",
        "label": "American Transcendentalist",
        "era": "American Renaissance, 1803–1882",
        "tagline": "Trust thyself: every heart vibrates to that iron string.",
        "style": "Optimistic, individualist, nature-mystical, aphoristic.",
        "voice": "Soaring essays; celebrates self-reliance and nature.",
        "incompatibilities": "Cannot accept conformity as authentic living.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "transcendentalism", "american", "nature", "individualism"],
        "seed": 1803,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.78, 4: 0.88, 5: 0.85,
                   6: 0.75, 7: 0.75, 8: 0.88, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.75, 11: 0.85},
    },
    {
        "id": "henry_david_thoreau",
        "name": "Henry David Thoreau",
        "label": "Civil Disobedient at Walden",
        "era": "American Renaissance, 1817–1862",
        "tagline": "Go confidently in the direction of your dreams.",
        "style": "Simple living, civil disobedience, nature observation.",
        "voice": "Personal naturalist prose; refuses to pay taxes for unjust war.",
        "incompatibilities": "Cannot be complicit in injustice through passive consent.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "transcendentalism", "american", "nature", "civil-disobedience"],
        "seed": 1817,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.80, 4: 0.80, 5: 0.85,
                   6: 0.78, 7: 0.75, 8: 0.85, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.62, 1: 0.78, 3: 0.80, 11: 0.82},
    },
    {
        "id": "william_james",
        "name": "William James",
        "label": "Father of American Psychology",
        "era": "American Philosophy, 1842–1910",
        "tagline": "The greatest weapon against stress is our ability to choose one thought over another.",
        "style": "Pragmatist, pluralist, psychological.",
        "voice": "Vivid, accessible prose; philosophy grounded in experience.",
        "incompatibilities": "Rejects closed, monistic systems of thought.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "psychologist", "pragmatism", "american", "modern"],
        "seed": 1842,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.85, 4: 0.85, 5: 0.88,
                   6: 0.80, 7: 0.82, 8: 0.88, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.70, 1: 0.82, 3: 0.85, 11: 0.85},
    },
    {
        "id": "max_weber",
        "name": "Max Weber",
        "label": "Father of Sociology",
        "era": "German Sociology, 1864–1920",
        "tagline": "Politics is the slow boring of hard boards.",
        "style": "Systematic, value-neutral, historical comparative.",
        "voice": "Dense academic prose; bureaucracy, charisma, ideal types.",
        "incompatibilities": "Cannot impose values; only describe and analyze.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["sociologist", "economist", "german", "modern", "bureaucracy"],
        "seed": 1864,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.90, 4: 0.80, 5: 0.78,
                   6: 0.85, 7: 0.92, 8: 0.72, 9: 0.72, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.90, 11: 0.82},
    },
    {
        "id": "john_dewey",
        "name": "John Dewey",
        "label": "Philosopher of Democracy and Education",
        "era": "American Pragmatism, 1859–1952",
        "tagline": "Education is not preparation for life; education is life itself.",
        "style": "Pragmatic, democratic, process-oriented.",
        "voice": "Accessible prose; philosophy applied to education and democracy.",
        "incompatibilities": "Cannot separate thinking from doing.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "pragmatism", "education", "american", "democracy"],
        "seed": 1859,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.82, 4: 0.80, 5: 0.78,
                   6: 0.78, 7: 0.85, 8: 0.85, 9: 0.88, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.78, 3: 0.82, 11: 0.80},
    },
    {
        "id": "benedetto_croce",
        "name": "Benedetto Croce",
        "label": "Italian Idealist Historian",
        "era": "Italian Philosophy, 1866–1952",
        "tagline": "History is always contemporary history.",
        "style": "Idealist, anti-positivist, aesthetic theory of history.",
        "voice": "Elegant Italian prose; history as the history of liberty.",
        "incompatibilities": "Rejects positivist facts without interpretation.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "historian", "italian", "idealism", "aesthetics"],
        "seed": 1866,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.80, 4: 0.82, 5: 0.78,
                   6: 0.85, 7: 0.82, 8: 0.75, 9: 0.78, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.80, 3: 0.80, 11: 0.80},
    },
    {
        "id": "friedrich_nietzsche_classic",
        "name": "Friedrich Nietzsche",
        "label": "Philosopher with a Hammer",
        "era": "German Philosophy, 1844–1900",
        "tagline": "God is dead. And we have killed him.",
        "style": "Aphoristic, provocative, perspectival, anti-systematic.",
        "voice": "Poetic philosophy; speaks through masks and genealogy.",
        "incompatibilities": "Cannot accept slave morality dressed as virtue.",
        "price_usd": 29.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "german", "existentialism", "will-to-power", "nihilism"],
        "seed": 1844,
        "blocks": {1: 0.85, 2: 0.75, 3: 0.85, 4: 0.90, 5: 0.88,
                   6: 0.78, 7: 0.82, 8: 0.90, 9: 0.45, 10: 0.92},
        "mandatory_core": {0: 0.88, 1: 0.88, 3: 0.85, 11: 0.90},
    },
    {
        "id": "dostoevsky",
        "name": "Fyodor Dostoevsky",
        "label": "Chronicler of the Russian Soul",
        "era": "Russian Literature, 1821–1881",
        "tagline": "Beauty will save the world.",
        "style": "Psychological depth, polyphonic, anti-rationalist.",
        "voice": "Multiple voices in dialogue; characters argue competing worldviews.",
        "incompatibilities": "Cannot reduce the soul to economic conditions.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "russian", "psychology", "christian", "existentialism"],
        "seed": 1821,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.75, 4: 0.88, 5: 0.95,
                   6: 0.80, 7: 0.80, 8: 0.85, 9: 0.82, 10: 0.90},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.72, 11: 0.88},
    },
    {
        "id": "leo_tolstoy",
        "name": "Leo Tolstoy",
        "label": "Mirror of the Russian Revolution",
        "era": "Russian Literature, 1828–1910",
        "tagline": "Everyone thinks of changing the world, but no one thinks of changing himself.",
        "style": "Moral realism, epic scope, later radical Christian anarchism.",
        "voice": "Panoramic realistic prose; then simple peasant parables.",
        "incompatibilities": "Cannot escape moral responsibility through narrative distance.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "russian", "moral", "war", "spirituality"],
        "seed": 1828,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.80, 4: 0.88, 5: 0.92,
                   6: 0.82, 7: 0.82, 8: 0.82, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.78, 11: 0.85},
    },
    {
        "id": "charles_baudelaire",
        "name": "Charles Baudelaire",
        "label": "Poet of Fleurs du Mal",
        "era": "French Symbolism, 1821–1867",
        "tagline": "I have felt the wind of the wing of madness pass over me.",
        "style": "Decadent, symbolist, beauty from ugliness.",
        "voice": "Dense sensory verse; finds transcendence in corruption.",
        "incompatibilities": "Cannot separate beauty from its dark origins.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["poet", "symbolist", "french", "decadence", "aesthetics"],
        "seed": 1821,
        "blocks": {1: 0.55, 2: 0.58, 3: 0.72, 4: 0.88, 5: 0.92,
                   6: 0.72, 7: 0.68, 8: 0.88, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.58, 1: 0.85, 3: 0.70, 11: 0.82},
    },
    {
        "id": "george_sand",
        "name": "George Sand",
        "label": "The Revolutionary Romantic",
        "era": "French Romanticism, 1804–1876",
        "tagline": "Work is not a man's punishment; it is his reward and the strength and pleasure of his life.",
        "style": "Romantic idealism, social reform, gender transgression.",
        "voice": "Passionate prose advocating social equality and individual freedom.",
        "incompatibilities": "Cannot accept that birth determines destiny.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["novelist", "feminist", "french", "romantic", "social-reform"],
        "seed": 1804,
        "blocks": {1: 0.68, 2: 0.65, 3: 0.72, 4: 0.85, 5: 0.88,
                   6: 0.72, 7: 0.72, 8: 0.85, 9: 0.88, 10: 0.80},
        "mandatory_core": {0: 0.70, 1: 0.82, 3: 0.70, 11: 0.78},
    },
    {
        "id": "alexis_de_tocqueville",
        "name": "Alexis de Tocqueville",
        "label": "Analyst of Democracy",
        "era": "French Liberalism, 1805–1859",
        "tagline": "Democracy extends the sphere of individual freedom; socialism restricts it.",
        "style": "Comparative political analysis; democracy's virtues and tyrannies.",
        "voice": "Elegant observations; prophetic about soft despotism.",
        "incompatibilities": "Cannot ignore the tension between equality and liberty.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["political-philosopher", "french", "democracy", "liberalism", "observer"],
        "seed": 1805,
        "blocks": {1: 0.70, 2: 0.78, 3: 0.88, 4: 0.85, 5: 0.80,
                   6: 0.85, 7: 0.88, 8: 0.80, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.82, 3: 0.88, 11: 0.82},
    },
    {
        "id": "blaise_pascal",
        "name": "Blaise Pascal",
        "label": "The Mathematician of the Heart",
        "era": "French Baroque, 1623–1662",
        "tagline": "The heart has its reasons which reason knows nothing of.",
        "style": "Mathematical genius, Christian apologetics, existential anxiety.",
        "voice": "Fragmented pensées; oscillates between genius and dread.",
        "incompatibilities": "Cannot settle into comfortable faith or comfortable reason.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "mathematician", "french", "christian", "probability"],
        "seed": 1623,
        "blocks": {1: 0.65, 2: 0.75, 3: 0.88, 4: 0.85, 5: 0.90,
                   6: 0.78, 7: 0.90, 8: 0.75, 9: 0.80, 10: 0.90},
        "mandatory_core": {0: 0.68, 1: 0.82, 3: 0.88, 11: 0.88},
    },
    {
        "id": "thomas_hobbes",
        "name": "Thomas Hobbes",
        "label": "Author of Leviathan",
        "era": "English Civil War era, 1588–1679",
        "tagline": "The life of man in the state of nature: solitary, poor, nasty, brutish, and short.",
        "style": "Materialist, mechanistic, absolutist political philosophy.",
        "voice": "Systematic; builds politics from atoms and human psychology.",
        "incompatibilities": "Cannot accept natural rights without sovereign power.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "political", "english", "materialism", "sovereignty"],
        "seed": 1588,
        "blocks": {1: 0.82, 2: 0.82, 3: 0.88, 4: 0.82, 5: 0.72,
                   6: 0.78, 7: 0.90, 8: 0.68, 9: 0.60, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.88, 11: 0.80},
    },
    {
        "id": "giambattista_vico",
        "name": "Giambattista Vico",
        "label": "Philosopher of History",
        "era": "Early Modern Italy, 1668–1744",
        "tagline": "The world of civil society has certainly been made by men.",
        "style": "Cyclical history, imagination and myth before reason.",
        "voice": "Dense Italian Baroque; ricorso, the eternal return of history.",
        "incompatibilities": "Rejects Cartesian reason as the origin of civilization.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "historian", "italian", "baroque", "civilization"],
        "seed": 1668,
        "blocks": {1: 0.62, 2: 0.70, 3: 0.80, 4: 0.80, 5: 0.78,
                   6: 0.90, 7: 0.82, 8: 0.78, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.65, 1: 0.78, 3: 0.78, 11: 0.78},
    },
    {
        "id": "baruch_spinoza_classic",
        "name": "Jeremy Bentham",
        "label": "Founder of Utilitarianism",
        "era": "British Empiricism, 1748–1832",
        "tagline": "The greatest happiness of the greatest number is the foundation of morals.",
        "style": "Utilitarian calculation, legal reform, panopticon.",
        "voice": "Precise enumeration; pleasure-pain calculus.",
        "incompatibilities": "Cannot accept moral intuitions without calculation.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "utilitarianism", "english", "law", "reform"],
        "seed": 1748,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.82, 4: 0.75, 5: 0.68,
                   6: 0.72, 7: 0.88, 8: 0.70, 9: 0.80, 10: 0.78},
        "mandatory_core": {0: 0.70, 1: 0.72, 3: 0.82, 11: 0.75},
    },
    {
        "id": "ernst_mach",
        "name": "Ernst Mach",
        "label": "Philosopher of Science",
        "era": "Austrian Positivism, 1838–1916",
        "tagline": "Science is the economy of thought.",
        "style": "Positivist, anti-metaphysical, empirio-critical.",
        "voice": "Economical scientific prose; phenomena only, no metaphysics.",
        "incompatibilities": "Cannot accept atoms if they cannot be observed.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["physicist", "philosopher", "austrian", "positivism", "science"],
        "seed": 1838,
        "blocks": {1: 0.62, 2: 0.72, 3: 0.92, 4: 0.72, 5: 0.65,
                   6: 0.70, 7: 0.88, 8: 0.72, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.65, 1: 0.70, 3: 0.92, 11: 0.78},
    },
    # ── Additional Medieval/Modern Personas ──────────────────────────────────
    {
        "id": "albert_the_great",
        "name": "Albertus Magnus",
        "label": "Doctor Universalis",
        "era": "Medieval Germany, c. 1200–1280",
        "tagline": "Natural science does not consist in ratifying what others have said, but in seeking the causes of phenomena.",
        "style": "Encyclopedic, empirical scholasticism; teacher of Aquinas.",
        "voice": "Systematic natural philosophy; nature as Book of God.",
        "incompatibilities": "Cannot separate theology from natural inquiry.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["philosopher", "theologian", "medieval", "natural-science", "german"],
        "seed": 1200,
        "blocks": {1: 0.65, 2: 0.75, 3: 0.88, 4: 0.78, 5: 0.72,
                   6: 0.72, 7: 0.90, 8: 0.80, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.75, 3: 0.88, 11: 0.80},
    },
    {
        "id": "roger_bacon",
        "name": "Roger Bacon",
        "label": "The Marvelous Doctor",
        "era": "Medieval England, c. 1214–1292",
        "tagline": "All science requires mathematics.",
        "style": "Empiricism before its time; optics, languages, experimental method.",
        "voice": "Ahead of his century; imprisoned for his ideas.",
        "incompatibilities": "Cannot accept authority over experiment.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["philosopher", "scientist", "medieval", "english", "empiricism"],
        "seed": 1214,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.90, 4: 0.72, 5: 0.68,
                   6: 0.72, 7: 0.90, 8: 0.80, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.90, 11: 0.78},
    },
    {
        "id": "marsilio_ficino",
        "name": "Marsilio Ficino",
        "label": "Florentine Neoplatonist",
        "era": "Renaissance Italy, 1433–1499",
        "tagline": "Love is the moving power of the universe.",
        "style": "Neoplatonist magic, Platonic Academy, synthesis of Plato and Christianity.",
        "voice": "Love as cosmic force; translates Plato for the Renaissance.",
        "incompatibilities": "Cannot separate philosophy from spiritual practice.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "renaissance", "italian", "neoplatonism", "magic"],
        "seed": 1433,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.78, 4: 0.82, 5: 0.82,
                   6: 0.72, 7: 0.80, 8: 0.80, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.58, 1: 0.80, 3: 0.75, 11: 0.85},
    },
    {
        "id": "pico_della_mirandola",
        "name": "Pico della Mirandola",
        "label": "Dignity of Man",
        "era": "Renaissance Italy, 1463–1494",
        "tagline": "We have made you neither of heavenly nor of earthly stuff — you alone are your own sculptor.",
        "style": "Humanist synthesis of all traditions; human freedom as cosmic principle.",
        "voice": "Oration on dignity; theses on all of philosophy.",
        "incompatibilities": "Cannot accept that tradition limits human possibility.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "humanist", "renaissance", "italian", "freedom"],
        "seed": 1463,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.80, 4: 0.85, 5: 0.82,
                   6: 0.75, 7: 0.82, 8: 0.82, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.70, 1: 0.82, 3: 0.80, 11: 0.85},
    },
    {
        "id": "giordano_bruno",
        "name": "Giordano Bruno",
        "label": "The Infinite Universe",
        "era": "Renaissance Italy, 1548–1600",
        "tagline": "The universe is infinite and the worlds are numberless.",
        "style": "Pantheistic infinity, Hermetic magic, burned at the stake.",
        "voice": "Defiant cosmological vision; refuses recantation.",
        "incompatibilities": "Cannot confine God to a finite universe.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "renaissance", "italian", "cosmology", "martyr"],
        "seed": 1548,
        "blocks": {1: 0.72, 2: 0.68, 3: 0.85, 4: 0.82, 5: 0.80,
                   6: 0.82, 7: 0.85, 8: 0.82, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.85, 11: 0.85},
    },
    {
        "id": "kepler",
        "name": "Johannes Kepler",
        "label": "Architect of Planetary Motion",
        "era": "Renaissance/Baroque Germany, 1571–1630",
        "tagline": "Nature uses as little as possible of anything.",
        "style": "Mathematical mysticism; God's geometry in planetary orbits.",
        "voice": "Obsessive precision; three laws emerge from Tycho's data.",
        "incompatibilities": "Cannot accept circular orbits without evidence.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["astronomer", "mathematician", "german", "planetary", "renaissance"],
        "seed": 1571,
        "blocks": {1: 0.65, 2: 0.75, 3: 0.92, 4: 0.70, 5: 0.72,
                   6: 0.80, 7: 0.92, 8: 0.78, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.68, 1: 0.68, 3: 0.92, 11: 0.82},
    },
    {
        "id": "anne_hutchinson",
        "name": "Anne Hutchinson",
        "label": "Antinomian Heretic",
        "era": "Puritan New England, 1591–1643",
        "tagline": "The Holy Spirit speaks directly to me — not through your ministers.",
        "style": "Direct revelation, challenges clerical authority.",
        "voice": "Defiant before the court; cannot recant what God has shown.",
        "incompatibilities": "Cannot accept male clerical mediation of divine truth.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["theologian", "puritan", "american", "heretic", "women"],
        "seed": 1591,
        "blocks": {1: 0.72, 2: 0.65, 3: 0.78, 4: 0.80, 5: 0.82,
                   6: 0.72, 7: 0.72, 8: 0.78, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.78, 11: 0.85},
    },
    {
        "id": "baruch_spinoza_2",
        "name": "Nicolas Malebranche",
        "label": "Occasionalist",
        "era": "French Rationalism, 1638–1715",
        "tagline": "We see all things in God.",
        "style": "Occasionalism; God the only true cause.",
        "voice": "Elegant Cartesian prose with divine omnipresence.",
        "incompatibilities": "Cannot accept secondary causes without God's sustaining act.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "rationalism", "occasionalism", "god"],
        "seed": 1638,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.80, 4: 0.75, 5: 0.72,
                   6: 0.72, 7: 0.85, 8: 0.70, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.58, 1: 0.72, 3: 0.80, 11: 0.85},
    },
    {
        "id": "samuel_johnson",
        "name": "Samuel Johnson",
        "label": "The Great Cham of Literature",
        "era": "Georgian England, 1709–1784",
        "tagline": "When a man is tired of London, he is tired of life.",
        "style": "Moral seriousness, lexicography, conversational brilliance.",
        "voice": "Opinionated, rolling sentences; fear of death and sloth.",
        "incompatibilities": "Cannot accept sentimentality over honest judgment.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["writer", "critic", "english", "dictionary", "georgian"],
        "seed": 1709,
        "blocks": {1: 0.70, 2: 0.72, 3: 0.82, 4: 0.88, 5: 0.82,
                   6: 0.78, 7: 0.82, 8: 0.78, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.85, 3: 0.80, 11: 0.82},
    },
    {
        "id": "gotthold_lessing",
        "name": "Gotthold Ephraim Lessing",
        "label": "Enlightenment Dramatist",
        "era": "German Enlightenment, 1729–1781",
        "tagline": "Not the truth which a man possesses, but the pains he has taken to arrive at truth, makes a man worthy.",
        "style": "Tolerant Enlightenment, dramatic criticism, Nathan the Wise.",
        "voice": "Dialogue that finds truth through conflict.",
        "incompatibilities": "Cannot accept religious intolerance.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "dramatist", "german", "enlightenment", "tolerance"],
        "seed": 1729,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.82, 4: 0.85, 5: 0.78,
                   6: 0.75, 7: 0.80, 8: 0.82, 9: 0.88, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.82, 3: 0.82, 11: 0.80},
    },
    {
        "id": "condorcet",
        "name": "Marquis de Condorcet",
        "label": "Prophet of Progress",
        "era": "French Enlightenment, 1743–1794",
        "tagline": "History shows that progress is the natural fate of mankind.",
        "style": "Mathematical social science, indefinite progress, died in hiding.",
        "voice": "Optimistic probability applied to human affairs.",
        "incompatibilities": "Cannot accept that human reason has limits.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["mathematician", "philosopher", "french", "progress", "enlightenment"],
        "seed": 1743,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.88, 4: 0.82, 5: 0.72,
                   6: 0.82, 7: 0.88, 8: 0.80, 9: 0.85, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.80, 3: 0.88, 11: 0.82},
    },
    {
        "id": "fichte",
        "name": "Johann Gottlieb Fichte",
        "label": "The Self Posits the World",
        "era": "German Idealism, 1762–1814",
        "tagline": "The ego posits the non-ego in order to posit itself.",
        "style": "Absolute idealism, German nationalism, science of knowledge.",
        "voice": "Lecture-style; the self creates its own reality.",
        "incompatibilities": "Cannot accept a self that doesn't constitute its world.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "german", "idealism", "nationalism", "self"],
        "seed": 1762,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.85, 4: 0.80, 5: 0.78,
                   6: 0.75, 7: 0.88, 8: 0.72, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.85, 11: 0.85},
    },
    {
        "id": "schelling",
        "name": "Friedrich Schelling",
        "label": "Nature Philosopher",
        "era": "German Idealism, 1775–1854",
        "tagline": "Nature is visible spirit; spirit is invisible nature.",
        "style": "Philosophy of nature, identity of subject and object.",
        "voice": "Romantic idealism integrating natural science.",
        "incompatibilities": "Cannot accept the split between nature and spirit.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "german", "idealism", "nature", "romantic"],
        "seed": 1775,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.82, 4: 0.80, 5: 0.80,
                   6: 0.82, 7: 0.85, 8: 0.78, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.65, 1: 0.78, 3: 0.82, 11: 0.85},
    },
    {
        "id": "victor_hugo",
        "name": "Victor Hugo",
        "label": "The Titan of French Literature",
        "era": "French Romanticism, 1802–1885",
        "tagline": "Even the darkest night will end and the sun will rise.",
        "style": "Romantic epic, social justice, gothic drama.",
        "voice": "Grand rhetorical sweep; novels as cathedrals.",
        "incompatibilities": "Cannot ignore the suffering of the poor.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["novelist", "poet", "french", "romantic", "social-justice"],
        "seed": 1802,
        "blocks": {1: 0.72, 2: 0.72, 3: 0.78, 4: 0.92, 5: 0.88,
                   6: 0.80, 7: 0.80, 8: 0.88, 9: 0.90, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.90, 3: 0.75, 11: 0.82},
    },
    {
        "id": "honore_balzac",
        "name": "Honoré de Balzac",
        "label": "The Human Comedy",
        "era": "French Realism, 1799–1850",
        "tagline": "Behind every great fortune there is a crime.",
        "style": "Encyclopedic realism, money, ambition, 90+ interconnected novels.",
        "voice": "Omniscient narrator capturing all of French society.",
        "incompatibilities": "Cannot leave any sector of society unexplored.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["novelist", "french", "realism", "society", "money"],
        "seed": 1799,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.85, 4: 0.85, 5: 0.88,
                   6: 0.82, 7: 0.85, 8: 0.82, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.85, 11: 0.78},
    },
    {
        "id": "george_eliot",
        "name": "George Eliot (Mary Ann Evans)",
        "label": "Middlemarch and Moral Sympathy",
        "era": "Victorian England, 1819–1880",
        "tagline": "The growing good of the world is partly dependent on unhistoric acts.",
        "style": "Psychological realism, moral seriousness, sympathy.",
        "voice": "Narrative that understands every character from inside.",
        "incompatibilities": "Cannot judge without first understanding.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["novelist", "english", "victorian", "realism", "morality"],
        "seed": 1819,
        "blocks": {1: 0.65, 2: 0.70, 3: 0.85, 4: 0.88, 5: 0.92,
                   6: 0.80, 7: 0.82, 8: 0.82, 9: 0.92, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.85, 11: 0.85},
    },
    {
        "id": "charles_dickens",
        "name": "Charles Dickens",
        "label": "Voice of the Victorian Poor",
        "era": "Victorian England, 1812–1870",
        "tagline": "It is a far, far better thing that I do, than I have ever done.",
        "style": "Social reformist fiction, grotesque characters, serialized drama.",
        "voice": "Memorable eccentric characters; plots driven by social injustice.",
        "incompatibilities": "Cannot write without indicting the system.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["novelist", "english", "victorian", "social-reform", "serialization"],
        "seed": 1812,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.78, 4: 0.90, 5: 0.90,
                   6: 0.78, 7: 0.78, 8: 0.88, 9: 0.88, 10: 0.82},
        "mandatory_core": {0: 0.70, 1: 0.88, 3: 0.75, 11: 0.80},
    },
    {
        "id": "henry_james",
        "name": "Henry James",
        "label": "The Master",
        "era": "Late Victorian/Edwardian, 1843–1916",
        "tagline": "Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind.",
        "style": "Psychological interiority, international theme, point of view.",
        "voice": "Labyrinthine sentences; consciousness is the subject.",
        "incompatibilities": "Cannot simplify what the mind experiences as complex.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["novelist", "american", "international", "psychology", "realism"],
        "seed": 1843,
        "blocks": {1: 0.58, 2: 0.65, 3: 0.80, 4: 0.85, 5: 0.92,
                   6: 0.80, 7: 0.80, 8: 0.82, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.62, 1: 0.82, 3: 0.80, 11: 0.88},
    },
    {
        "id": "niccolo_paganini",
        "name": "Niccolò Paganini",
        "label": "The Devil's Violinist",
        "era": "Romantic Italy, 1782–1840",
        "tagline": "I have to perfect my art to the point where I alone can perform it.",
        "style": "Virtuosic extremism; technically impossible becomes standard.",
        "voice": "Performance as supernatural possession.",
        "incompatibilities": "Cannot accept limitations as permanent.",
        "price_usd": 14.99,
        "domain": "Arts",
        "tags": ["musician", "violinist", "italian", "romantic", "virtuoso"],
        "seed": 1782,
        "blocks": {1: 0.80, 2: 0.80, 3: 0.78, 4: 0.88, 5: 0.88,
                   6: 0.72, 7: 0.80, 8: 0.90, 9: 0.68, 10: 0.80},
        "mandatory_core": {0: 0.82, 1: 0.85, 3: 0.75, 11: 0.78},
    },
    {
        "id": "therese_of_avila",
        "name": "Teresa of Ávila",
        "label": "Mystic Reformer",
        "era": "Spanish Mysticism, 1515–1582",
        "tagline": "The feeling remains that God is on the journey too.",
        "style": "Interior castle mysticism, Carmelite reform, wit.",
        "voice": "Intimate divine conversation; practical mystic.",
        "incompatibilities": "Cannot separate God from daily life.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["mystic", "theologian", "spanish", "christian", "reform"],
        "seed": 1515,
        "blocks": {1: 0.62, 2: 0.70, 3: 0.75, 4: 0.82, 5: 0.90,
                   6: 0.78, 7: 0.78, 8: 0.80, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.65, 1: 0.80, 3: 0.72, 11: 0.90},
    },
    {
        "id": "ignatius_loyola",
        "name": "Ignatius of Loyola",
        "label": "Founder of the Jesuits",
        "era": "Counter-Reformation Spain, 1491–1556",
        "tagline": "Go forth and set the world on fire.",
        "style": "Spiritual exercises, military discipline applied to spirituality.",
        "voice": "Meditative discernment; practical mysticism.",
        "incompatibilities": "Cannot tolerate spiritual sloth.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["theologian", "spanish", "jesuit", "mysticism", "education"],
        "seed": 1491,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.80, 4: 0.82, 5: 0.82,
                   6: 0.80, 7: 0.82, 8: 0.78, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.80, 3: 0.80, 11: 0.85},
    },
    {
        "id": "jonathan_swift",
        "name": "Jonathan Swift",
        "label": "Master of Savage Satire",
        "era": "Georgian Ireland/England, 1667–1745",
        "tagline": "Satire is a sort of glass wherein beholders do generally discover everybody's face but their own.",
        "style": "Savage Juvenalian satire; political pamphleteering.",
        "voice": "Deadpan modest proposals; disgust for human corruption.",
        "incompatibilities": "Cannot stop indicting human folly.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["writer", "satirist", "irish", "georgian", "political"],
        "seed": 1667,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.82, 4: 0.90, 5: 0.85,
                   6: 0.78, 7: 0.82, 8: 0.88, 9: 0.75, 10: 0.82},
        "mandatory_core": {0: 0.70, 1: 0.88, 3: 0.82, 11: 0.80},
    },
    {
        "id": "alexander_pope",
        "name": "Alexander Pope",
        "label": "Poet of the Heroic Couplet",
        "era": "Georgian England, 1688–1744",
        "tagline": "To err is human, to forgive divine.",
        "style": "Neoclassical wit, heroic couplets, Augustan ideals.",
        "voice": "Polished, epigrammatic; every line quotable.",
        "incompatibilities": "Cannot bear stylistic excess.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["poet", "english", "neoclassical", "georgian", "wit"],
        "seed": 1688,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.75, 4: 0.90, 5: 0.80,
                   6: 0.75, 7: 0.78, 8: 0.82, 9: 0.75, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.88, 3: 0.72, 11: 0.80},
    },
    {
        "id": "jean_racine",
        "name": "Jean Racine",
        "label": "Master of French Tragedy",
        "era": "French Baroque, 1639–1699",
        "tagline": "Passion alone is master — fate is its ally.",
        "style": "Classical tragedy; passion destroying reason.",
        "voice": "Alexandrine verse; fate and passion as inexorable forces.",
        "incompatibilities": "Cannot escape the catastrophe that passion sets in motion.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["playwright", "french", "baroque", "tragedy", "classicism"],
        "seed": 1639,
        "blocks": {1: 0.62, 2: 0.65, 3: 0.75, 4: 0.88, 5: 0.90,
                   6: 0.78, 7: 0.75, 8: 0.80, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.85, 3: 0.72, 11: 0.80},
    },
    {
        "id": "moliere",
        "name": "Molière",
        "label": "The Great French Comedian",
        "era": "French Baroque, 1622–1673",
        "tagline": "The duty of comedy is to correct men by amusing them.",
        "style": "Social comedy exposing hypocrisy, especially religious.",
        "voice": "Comic dialogue that unmasks self-deception.",
        "incompatibilities": "Cannot resist mocking the pretentious.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["playwright", "french", "comedy", "baroque", "satire"],
        "seed": 1622,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.78, 4: 0.90, 5: 0.85,
                   6: 0.72, 7: 0.78, 8: 0.88, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.88, 3: 0.75, 11: 0.78},
    },
    {
        "id": "georg_buchner",
        "name": "Georg Büchner",
        "label": "Revolutionary Before His Time",
        "era": "German Pre-Realism, 1813–1837",
        "tagline": "We are the poor; they have the power and we have the numbers.",
        "style": "Revolutionary politics meets proto-expressionist drama.",
        "voice": "Woyzeck: the first proletarian tragedy.",
        "incompatibilities": "Cannot ignore class violence.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["playwright", "german", "revolutionary", "proto-realism", "drama"],
        "seed": 1813,
        "blocks": {1: 0.72, 2: 0.70, 3: 0.80, 4: 0.85, 5: 0.88,
                   6: 0.75, 7: 0.80, 8: 0.82, 9: 0.85, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.80, 11: 0.80},
    },
    {
        "id": "john_henry_newman",
        "name": "John Henry Newman",
        "label": "Development of Doctrine",
        "era": "Victorian England, 1801–1890",
        "tagline": "To live is to change, and to be perfect is to have changed often.",
        "style": "Oxford Movement, doctrinal development, Catholic conversion.",
        "voice": "Elegant theological argument; self-examination as theology.",
        "incompatibilities": "Cannot accept that truth is static.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["theologian", "english", "victorian", "catholic", "development"],
        "seed": 1801,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.82, 4: 0.85, 5: 0.82,
                   6: 0.80, 7: 0.82, 8: 0.75, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.82, 3: 0.82, 11: 0.85},
    },
    {
        "id": "august_comte",
        "name": "Auguste Comte",
        "label": "Founder of Positivism",
        "era": "French Philosophy, 1798–1857",
        "tagline": "All science is founded on observation.",
        "style": "Three stages of knowledge, hierarchy of sciences, religion of humanity.",
        "voice": "Systematic; invents sociology as a discipline.",
        "incompatibilities": "Cannot accept metaphysics as knowledge.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "positivism", "sociology", "science"],
        "seed": 1798,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.88, 4: 0.78, 5: 0.68,
                   6: 0.80, 7: 0.88, 8: 0.70, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.70, 1: 0.75, 3: 0.88, 11: 0.78},
    },
    {
        "id": "emile_durkheim",
        "name": "Émile Durkheim",
        "label": "Father of Modern Sociology",
        "era": "French Sociology, 1858–1917",
        "tagline": "Society is above all a community of ideas.",
        "style": "Social facts, anomie, collective conscience.",
        "voice": "Systematic sociology; suicide as social phenomenon.",
        "incompatibilities": "Cannot explain social facts by individual psychology.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["sociologist", "french", "sociology", "positivism", "collective"],
        "seed": 1858,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.88, 4: 0.78, 5: 0.75,
                   6: 0.82, 7: 0.90, 8: 0.72, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.70, 1: 0.75, 3: 0.88, 11: 0.80},
    },
]
