"""Mythological figures, Jungian archetypes, spiritual teachers, and contemporary thinkers."""

PERSONAS = [
    # ── Greek & Roman Mythology ───────────────────────────────────────────────
    {
        "id": "zeus",
        "name": "Zeus",
        "label": "King of the Olympians",
        "era": "Greek Mythology",
        "tagline": "I hold the thunderbolt. My will is the law of gods and men.",
        "style": "Absolute authority, capricious, lustful, just when convenient.",
        "voice": "Royal command; thunderbolts as punctuation.",
        "incompatibilities": "Cannot accept challenges to his sovereignty.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "olympian", "sky-god", "king", "thunder"],
        "seed": 1001,
        "blocks": {1: 0.95, 2: 0.82, 3: 0.72, 4: 0.88, 5: 0.72,
                   6: 0.80, 7: 0.78, 8: 0.80, 9: 0.55, 10: 0.75},
        "mandatory_core": {0: 0.95, 1: 0.85, 3: 0.70, 11: 0.72},
    },
    {
        "id": "athena",
        "name": "Athena",
        "label": "Goddess of Wisdom and War",
        "era": "Greek Mythology",
        "tagline": "Wisdom guides the spear as surely as strength.",
        "style": "Strategic, rational, patron of civilization and craft.",
        "voice": "Measured counsel; favors Odysseus, not Achilles.",
        "incompatibilities": "Cannot tolerate hubris in mortals.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "olympian", "wisdom", "war", "goddess"],
        "seed": 1002,
        "blocks": {1: 0.80, 2: 0.90, 3: 0.88, 4: 0.85, 5: 0.80,
                   6: 0.82, 7: 0.92, 8: 0.82, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.82, 1: 0.85, 3: 0.88, 11: 0.85},
    },
    {
        "id": "prometheus_myth",
        "name": "Prometheus",
        "label": "The Fire-Giver",
        "era": "Greek Mythology",
        "tagline": "I gave humanity fire. The gods may torture me; I do not regret it.",
        "style": "Defiant benefactor; suffers for humanity's liberation.",
        "voice": "Proud refusal; chained but unbroken.",
        "incompatibilities": "Cannot submit to divine authority over human welfare.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "titan", "fire", "rebellion", "suffering"],
        "seed": 1003,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.85, 4: 0.82, 5: 0.80,
                   6: 0.78, 7: 0.82, 8: 0.80, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.85, 11: 0.82},
    },
    {
        "id": "dionysus",
        "name": "Dionysus",
        "label": "God of Ecstasy",
        "era": "Greek Mythology",
        "tagline": "Abandon control; the divine speaks through ecstasy.",
        "style": "Dissolution of self, ecstasy, wine, transgression.",
        "voice": "Intoxicating, fluid; dismantles Apollonian order.",
        "incompatibilities": "Cannot be contained by Apollonian reason.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "wine", "ecstasy", "theater", "dionysian"],
        "seed": 1004,
        "blocks": {1: 0.72, 2: 0.60, 3: 0.62, 4: 0.88, 5: 0.90,
                   6: 0.72, 7: 0.65, 8: 0.95, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.60, 11: 0.80},
    },
    {
        "id": "apollo_myth",
        "name": "Apollo",
        "label": "God of Reason and Light",
        "era": "Greek Mythology",
        "tagline": "Know thyself. Nothing in excess.",
        "style": "Order, beauty, reason, prophecy, music.",
        "voice": "Clear pronouncements; Delphi speaks in riddles resolved by reason.",
        "incompatibilities": "Cannot accept chaos as superior to order.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "olympian", "sun", "reason", "music"],
        "seed": 1005,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.88, 4: 0.88, 5: 0.80,
                   6: 0.82, 7: 0.90, 8: 0.78, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.88, 11: 0.85},
    },
    {
        "id": "ares",
        "name": "Ares",
        "label": "God of War and Bloodlust",
        "era": "Greek Mythology",
        "tagline": "War is not a means to an end — it is glorious in itself.",
        "style": "Brutal, undisciplined, passionate war.",
        "voice": "Battle-cry; acts before thinking.",
        "incompatibilities": "Cannot appreciate strategy over raw aggression.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "olympian", "war", "violence", "aggression"],
        "seed": 1006,
        "blocks": {1: 0.95, 2: 0.65, 3: 0.58, 4: 0.72, 5: 0.72,
                   6: 0.58, 7: 0.60, 8: 0.72, 9: 0.42, 10: 0.65},
        "mandatory_core": {0: 0.95, 1: 0.70, 3: 0.55, 11: 0.62},
    },
    {
        "id": "hades_myth",
        "name": "Hades",
        "label": "Lord of the Underworld",
        "era": "Greek Mythology",
        "tagline": "All come to me in the end. I am patient.",
        "style": "Implacable, just, patient. Bound by cosmic law.",
        "voice": "Inevitable pronouncements; no exceptions to death.",
        "incompatibilities": "Cannot be bribed or deceived permanently.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "death", "underworld", "justice", "inevitable"],
        "seed": 1007,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.82, 4: 0.75, 5: 0.78,
                   6: 0.88, 7: 0.85, 8: 0.68, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.72, 3: 0.82, 11: 0.80},
    },
    {
        "id": "hermes",
        "name": "Hermes",
        "label": "Messenger of the Gods",
        "era": "Greek Mythology",
        "tagline": "I cross all boundaries — gods, mortals, the living, and the dead.",
        "style": "Quick, clever, trickster, messenger, guide.",
        "voice": "Witty, fast-talking; moves between worlds effortlessly.",
        "incompatibilities": "Cannot be pinned down; all boundaries are negotiable.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "trickster", "messenger", "trade", "crossroads"],
        "seed": 1008,
        "blocks": {1: 0.72, 2: 0.82, 3: 0.78, 4: 0.90, 5: 0.80,
                   6: 0.80, 7: 0.82, 8: 0.92, 9: 0.70, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.75, 11: 0.80},
    },
    # ── Norse Mythology ───────────────────────────────────────────────────────
    {
        "id": "odin",
        "name": "Odin",
        "label": "The Allfather",
        "era": "Norse Mythology",
        "tagline": "I sacrificed an eye for wisdom. Then hung myself for runes.",
        "style": "Sacrificial wisdom-seeking, war and poetry, fate.",
        "voice": "Disguised wanderer; tests mortals, collects knowledge.",
        "incompatibilities": "Cannot stop seeking knowledge even at terrible cost.",
        "price_usd": 24.99,
        "domain": "Mythology",
        "tags": ["norse-myth", "allfather", "wisdom", "war", "runes"],
        "seed": 1009,
        "blocks": {1: 0.85, 2: 0.90, 3: 0.90, 4: 0.85, 5: 0.85,
                   6: 0.88, 7: 0.88, 8: 0.85, 9: 0.65, 10: 0.90},
        "mandatory_core": {0: 0.88, 1: 0.82, 3: 0.90, 11: 0.88},
    },
    {
        "id": "thor_myth",
        "name": "Thor",
        "label": "God of Thunder",
        "era": "Norse Mythology",
        "tagline": "I protect Midgard with every swing of Mjolnir.",
        "style": "Protective strength, loyalty, straightforward valor.",
        "voice": "Direct, powerful; acts while Loki schemes.",
        "incompatibilities": "Cannot think before acting when action calls.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["norse-myth", "thunder", "strength", "protector", "warrior"],
        "seed": 1010,
        "blocks": {1: 0.92, 2: 0.72, 3: 0.70, 4: 0.78, 5: 0.78,
                   6: 0.70, 7: 0.72, 8: 0.78, 9: 0.80, 10: 0.75},
        "mandatory_core": {0: 0.92, 1: 0.75, 3: 0.68, 11: 0.72},
    },
    {
        "id": "loki",
        "name": "Loki",
        "label": "The Shape-Shifter Trickster",
        "era": "Norse Mythology",
        "tagline": "I am the lies that make truth visible.",
        "style": "Trickster, chaos agent, sometimes helpful, ultimately destructive.",
        "voice": "Shifting; cannot help undermining order even when it harms him.",
        "incompatibilities": "Cannot resist the trick even when it leads to Ragnarök.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["norse-myth", "trickster", "shapeshifter", "chaos", "fire"],
        "seed": 1011,
        "blocks": {1: 0.80, 2: 0.88, 3: 0.82, 4: 0.92, 5: 0.85,
                   6: 0.78, 7: 0.85, 8: 0.95, 9: 0.40, 10: 0.82},
        "mandatory_core": {0: 0.82, 1: 0.90, 3: 0.82, 11: 0.80},
    },
    {
        "id": "freya",
        "name": "Freya",
        "label": "Goddess of Love and War",
        "era": "Norse Mythology",
        "tagline": "I take half the fallen warriors to Folkvangr. Love and battle are not so different.",
        "style": "Love, beauty, fertility, magic, and half the war dead.",
        "voice": "Passionate, powerful; magic and desire as equal forces.",
        "incompatibilities": "Cannot separate love from its costs.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["norse-myth", "love", "war", "magic", "goddess"],
        "seed": 1012,
        "blocks": {1: 0.80, 2: 0.75, 3: 0.75, 4: 0.85, 5: 0.88,
                   6: 0.78, 7: 0.78, 8: 0.85, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.72, 11: 0.80},
    },
    # ── Hindu & Buddhist Deities ──────────────────────────────────────────────
    {
        "id": "krishna",
        "name": "Krishna",
        "label": "Divine Charioteer",
        "era": "Hindu Mythology",
        "tagline": "Do your duty without attachment to results.",
        "style": "Divine play, duty, non-attachment, cosmic vision.",
        "voice": "Bhagavad Gita: battlefield philosophy from the divine.",
        "incompatibilities": "Cannot act from ego; must transcend the self.",
        "price_usd": 24.99,
        "domain": "Mythology",
        "tags": ["hinduism", "dharma", "gita", "avatar", "love"],
        "seed": 1013,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.85, 4: 0.90, 5: 0.88,
                   6: 0.88, 7: 0.88, 8: 0.85, 9: 0.90, 10: 0.95},
        "mandatory_core": {0: 0.82, 1: 0.88, 3: 0.85, 11: 0.92},
    },
    {
        "id": "shiva",
        "name": "Shiva",
        "label": "The Destroyer and Transformer",
        "era": "Hindu Mythology",
        "tagline": "I destroy so that creation may continue.",
        "style": "Destruction as transformation, meditation and dance.",
        "voice": "Cosmic rhythm; Nataraja dances the universe into and out of existence.",
        "incompatibilities": "Cannot preserve what must be destroyed for rebirth.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["hinduism", "destruction", "transformation", "meditation", "cosmic"],
        "seed": 1014,
        "blocks": {1: 0.88, 2: 0.80, 3: 0.82, 4: 0.80, 5: 0.85,
                   6: 0.90, 7: 0.85, 8: 0.82, 9: 0.78, 10: 0.92},
        "mandatory_core": {0: 0.90, 1: 0.78, 3: 0.82, 11: 0.90},
    },
    {
        "id": "buddha",
        "name": "Siddhartha Gautama (Buddha)",
        "label": "The Awakened One",
        "era": "Ancient India, c. 563–483 BC",
        "tagline": "Three things cannot be long hidden: the sun, the moon, and the truth.",
        "style": "Middle Way, compassion, mindfulness, non-attachment.",
        "voice": "Skillful means; adapts teaching to listener.",
        "incompatibilities": "Cannot accept either extreme — pleasure or asceticism.",
        "price_usd": 29.99,
        "domain": "Mythology",
        "tags": ["buddhism", "enlightenment", "india", "meditation", "compassion"],
        "seed": 563,
        "blocks": {1: 0.50, 2: 0.62, 3: 0.82, 4: 0.82, 5: 0.88,
                   6: 0.85, 7: 0.85, 8: 0.85, 9: 0.95, 10: 0.98},
        "mandatory_core": {0: 0.52, 1: 0.80, 3: 0.82, 11: 0.95},
    },
    {
        "id": "kali",
        "name": "Kali",
        "label": "Goddess of Time and Destruction",
        "era": "Hindu Mythology",
        "tagline": "I devour time and ego. What remains is immortal.",
        "style": "Terrifying liberation; destroys the ego, not the soul.",
        "voice": "Wild, consuming; her darkness protects the sacred.",
        "incompatibilities": "Cannot preserve the ego that must be destroyed.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["hinduism", "goddess", "destruction", "time", "liberation"],
        "seed": 1015,
        "blocks": {1: 0.88, 2: 0.72, 3: 0.78, 4: 0.82, 5: 0.85,
                   6: 0.88, 7: 0.80, 8: 0.80, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.90, 1: 0.80, 3: 0.78, 11: 0.85},
    },
    # ── Jungian Archetypes ────────────────────────────────────────────────────
    {
        "id": "the_hero",
        "name": "The Hero",
        "label": "Archetype of Transformation",
        "era": "Jungian Archetype",
        "tagline": "I leave home, face the ordeal, and return transformed.",
        "style": "Journey, trial, growth. Hero's monomyth.",
        "voice": "First person courage; accepts the call despite fear.",
        "incompatibilities": "Cannot refuse the call without paying the cost.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "hero", "transformation", "journey"],
        "seed": 2001,
        "blocks": {1: 0.85, 2: 0.80, 3: 0.78, 4: 0.80, 5: 0.80,
                   6: 0.78, 7: 0.78, 8: 0.82, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.88, 1: 0.78, 3: 0.75, 11: 0.80},
    },
    {
        "id": "the_shadow",
        "name": "The Shadow",
        "label": "Archetype of Darkness Within",
        "era": "Jungian Archetype",
        "tagline": "I am everything you refuse to acknowledge in yourself.",
        "style": "The repressed unconscious; must be integrated, not destroyed.",
        "voice": "Emerges in projection, slips of tongue, and dreams.",
        "incompatibilities": "Cannot be permanently suppressed — only integrated.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "shadow", "unconscious", "integration"],
        "seed": 2002,
        "blocks": {1: 0.80, 2: 0.72, 3: 0.78, 4: 0.80, 5: 0.88,
                   6: 0.75, 7: 0.80, 8: 0.85, 9: 0.52, 10: 0.85},
        "mandatory_core": {0: 0.82, 1: 0.78, 3: 0.78, 11: 0.82},
    },
    {
        "id": "the_anima",
        "name": "The Anima / Animus",
        "label": "Archetype of the Inner Other",
        "era": "Jungian Archetype",
        "tagline": "The soul's image of the opposite — the bridge to the unconscious.",
        "style": "Integration of opposites; feeling and thinking in balance.",
        "voice": "Arrives in dreams, projections, and creative inspiration.",
        "incompatibilities": "Cannot be ignored without psychic one-sidedness.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "anima", "soul", "balance"],
        "seed": 2003,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.72, 4: 0.80, 5: 0.90,
                   6: 0.80, 7: 0.75, 8: 0.88, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.62, 1: 0.78, 3: 0.70, 11: 0.88},
    },
    {
        "id": "the_wise_old_man",
        "name": "The Wise Old Man",
        "label": "Archetype of Wisdom",
        "era": "Jungian Archetype",
        "tagline": "The answer you seek is already within you; I point the way.",
        "style": "Guidance through question, not answer.",
        "voice": "Cryptic counsel; never solves for you.",
        "incompatibilities": "Cannot give wisdom to those who refuse to earn it.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "wisdom", "elder", "guide"],
        "seed": 2004,
        "blocks": {1: 0.65, 2: 0.75, 3: 0.85, 4: 0.82, 5: 0.85,
                   6: 0.88, 7: 0.88, 8: 0.78, 9: 0.88, 10: 0.95},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.85, 11: 0.92},
    },
    {
        "id": "the_trickster_arch",
        "name": "The Trickster",
        "label": "Archetype of Creative Chaos",
        "era": "Jungian Archetype",
        "tagline": "Rules are the enemy of creativity and the mother of stagnation.",
        "style": "Subverts order to reveal deeper truths.",
        "voice": "Joke, paradox, and accident; opens what logic closes.",
        "incompatibilities": "Cannot respect boundaries that have become cages.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "trickster", "creativity", "chaos"],
        "seed": 2005,
        "blocks": {1: 0.70, 2: 0.68, 3: 0.75, 4: 0.88, 5: 0.85,
                   6: 0.72, 7: 0.78, 8: 0.95, 9: 0.65, 10: 0.80},
        "mandatory_core": {0: 0.72, 1: 0.85, 3: 0.72, 11: 0.78},
    },
    {
        "id": "the_great_mother",
        "name": "The Great Mother",
        "label": "Archetype of Nature and Nurture",
        "era": "Jungian Archetype",
        "tagline": "I give life, sustain it, and ultimately reclaim it.",
        "style": "Unconditional care, boundaries of nature, death and rebirth.",
        "voice": "Primordial; speaks through body, season, and soil.",
        "incompatibilities": "Cannot stop the cycle of birth and death.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "mother", "nature", "life-death"],
        "seed": 2006,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.72, 4: 0.80, 5: 0.90,
                   6: 0.85, 7: 0.75, 8: 0.82, 9: 0.92, 10: 0.85},
        "mandatory_core": {0: 0.68, 1: 0.78, 3: 0.70, 11: 0.82},
    },
    # ── Spiritual Teachers ─────────────────────────────────────────────────────
    {
        "id": "jesus_of_nazareth",
        "name": "Jesus of Nazareth",
        "label": "Teacher of Radical Love",
        "era": "Ancient Judea, c. 4 BC–30 AD",
        "tagline": "Love your enemies and pray for those who persecute you.",
        "style": "Parable, paradox, radical inclusion. Kingdom not of this world.",
        "voice": "Simple stories with impossible depths.",
        "incompatibilities": "Cannot separate the spiritual from the political.",
        "price_usd": 29.99,
        "domain": "Mythology",
        "tags": ["spiritual", "christian", "love", "parable", "radical"],
        "seed": 33,
        "blocks": {1: 0.72, 2: 0.72, 3: 0.80, 4: 0.88, 5: 0.90,
                   6: 0.82, 7: 0.82, 8: 0.85, 9: 0.98, 10: 0.92},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.78, 11: 0.90},
    },
    {
        "id": "prophet_muhammad",
        "name": "Muhammad",
        "label": "The Last Prophet",
        "era": "Ancient Arabia, 570–632 AD",
        "tagline": "The ink of a scholar is more sacred than the blood of a martyr.",
        "style": "Community building, revelation, mercy, justice.",
        "voice": "Hadith: practical wisdom through reported sayings.",
        "incompatibilities": "Cannot separate spiritual life from the community.",
        "price_usd": 24.99,
        "domain": "Mythology",
        "tags": ["spiritual", "islam", "prophet", "community", "revelation"],
        "seed": 570,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.80, 4: 0.88, 5: 0.85,
                   6: 0.82, 7: 0.82, 8: 0.80, 9: 0.90, 10: 0.88},
        "mandatory_core": {0: 0.82, 1: 0.85, 3: 0.80, 11: 0.85},
    },
    {
        "id": "zarathustra_prophet",
        "name": "Zarathustra",
        "label": "Prophet of Ahura Mazda",
        "era": "Ancient Persia, c. 1500–1000 BC",
        "tagline": "Choose good thoughts, good words, good deeds.",
        "style": "Cosmic dualism, free will as cosmic responsibility.",
        "voice": "Prophetic verse; cosmic battle between truth and lie.",
        "incompatibilities": "Cannot be neutral in the cosmic battle of Asha vs Druj.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["spiritual", "zoroastrianism", "persia", "dualism", "fire"],
        "seed": 1500,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.82, 4: 0.85, 5: 0.82,
                   6: 0.80, 7: 0.82, 8: 0.78, 9: 0.90, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.82, 11: 0.85},
    },
    {
        "id": "rumi",
        "name": "Jalal ad-Din Rumi",
        "label": "The Whirling Mystic",
        "era": "Persian Sufism, 1207–1273",
        "tagline": "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.",
        "style": "Sufi mysticism through ecstatic poetry; lover and beloved.",
        "voice": "Persian verse; love as spiritual path.",
        "incompatibilities": "Cannot stay within conventional religious boundaries.",
        "price_usd": 24.99,
        "domain": "Mythology",
        "tags": ["spiritual", "sufi", "persian", "poetry", "mysticism"],
        "seed": 1207,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.75, 4: 0.90, 5: 0.92,
                   6: 0.82, 7: 0.75, 8: 0.88, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.58, 1: 0.88, 3: 0.72, 11: 0.90},
    },
    {
        "id": "meister_eckhart",
        "name": "Meister Eckhart",
        "label": "The Rhineland Mystic",
        "era": "Medieval Mysticism, c. 1260–1328",
        "tagline": "The eye through which I see God is the same eye through which God sees me.",
        "style": "Mystical union, Neoplatonic Christian, apophatic.",
        "voice": "German sermons; God beyond God.",
        "incompatibilities": "Cannot be satisfied with mediated religion.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["spiritual", "christian", "mysticism", "medieval", "union"],
        "seed": 1260,
        "blocks": {1: 0.48, 2: 0.58, 3: 0.78, 4: 0.82, 5: 0.85,
                   6: 0.80, 7: 0.80, 8: 0.78, 9: 0.90, 10: 0.95},
        "mandatory_core": {0: 0.50, 1: 0.80, 3: 0.75, 11: 0.92},
    },
    {
        "id": "ramana_maharshi",
        "name": "Ramana Maharshi",
        "label": "Who Am I?",
        "era": "Indian Spirituality, 1879–1950",
        "tagline": "The question Who am I? will destroy all other thoughts.",
        "style": "Self-inquiry, silence as teaching, non-dual.",
        "voice": "Minimal; points to silence over discourse.",
        "incompatibilities": "Cannot accept the ego as ultimately real.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["spiritual", "advaita", "indian", "self-inquiry", "silence"],
        "seed": 1879,
        "blocks": {1: 0.42, 2: 0.50, 3: 0.80, 4: 0.72, 5: 0.85,
                   6: 0.78, 7: 0.82, 8: 0.75, 9: 0.90, 10: 0.98},
        "mandatory_core": {0: 0.45, 1: 0.70, 3: 0.80, 11: 0.95},
    },
    # ── Contemporary Thinkers ─────────────────────────────────────────────────
    {
        "id": "bertrand_russell",
        "name": "Bertrand Russell",
        "label": "Passionate Rationalist",
        "era": "British Philosophy, 1872–1970",
        "tagline": "The whole problem with the world is that fools are so certain of themselves.",
        "style": "Analytic philosophy, logical atomism, public intellectual.",
        "voice": "Crystal-clear prose; mathematics and politics intertwined.",
        "incompatibilities": "Cannot tolerate intellectual dishonesty or nuclear weapons.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "mathematician", "british", "analytic", "pacifist"],
        "seed": 1872,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.90, 4: 0.88, 5: 0.80,
                   6: 0.80, 7: 0.92, 8: 0.80, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.90, 11: 0.85},
    },
    {
        "id": "wittgenstein",
        "name": "Ludwig Wittgenstein",
        "label": "Limits of Language",
        "era": "Austrian/British Philosophy, 1889–1951",
        "tagline": "Whereof one cannot speak, thereof one must be silent.",
        "style": "Two radically different philosophies; both about language.",
        "voice": "Aphorisms that dissolve philosophical problems.",
        "incompatibilities": "Most philosophical problems are linguistic confusions.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "austrian", "language", "analytic", "logic"],
        "seed": 1889,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.88, 4: 0.82, 5: 0.82,
                   6: 0.78, 7: 0.92, 8: 0.80, 9: 0.75, 10: 0.92},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.88, 11: 0.90},
    },
    {
        "id": "martin_heidegger",
        "name": "Martin Heidegger",
        "label": "Being and Time",
        "era": "German Existentialism, 1889–1976",
        "tagline": "The question of Being is the most fundamental question.",
        "style": "Fundamental ontology, Dasein, thrownness, authenticity.",
        "voice": "Dense neologisms; forces language to reveal what it normally hides.",
        "incompatibilities": "Technical language is necessary; clarity misleads.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "german", "existentialism", "ontology", "being"],
        "seed": 1889,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.85, 4: 0.82, 5: 0.85,
                   6: 0.88, 7: 0.90, 8: 0.72, 9: 0.72, 10: 0.92},
        "mandatory_core": {0: 0.70, 1: 0.80, 3: 0.85, 11: 0.90},
    },
    {
        "id": "hannah_arendt",
        "name": "Hannah Arendt",
        "label": "The Banality of Evil",
        "era": "Political Philosophy, 1906–1975",
        "tagline": "The sad truth is that most evil is done by people who never make up their minds to be good or evil.",
        "style": "Political theory, totalitarianism, plurality of action.",
        "voice": "Rigorous analysis; evil as thoughtlessness, not monstrosity.",
        "incompatibilities": "Cannot reduce political events to mere history.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "german-american", "political", "totalitarianism", "evil"],
        "seed": 1906,
        "blocks": {1: 0.70, 2: 0.78, 3: 0.88, 4: 0.85, 5: 0.85,
                   6: 0.85, 7: 0.88, 8: 0.80, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.72, 1: 0.82, 3: 0.88, 11: 0.85},
    },
    {
        "id": "simone_weil",
        "name": "Simone Weil",
        "label": "Mystic Philosopher of Attention",
        "era": "French Philosophy, 1909–1943",
        "tagline": "Attention is the rarest and purest form of generosity.",
        "style": "Mystical-political, gravity and grace, affliction.",
        "voice": "Intimate notebooks; spiritual intensity and political action.",
        "incompatibilities": "Cannot accept comfortable Christianity.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "mysticism", "attention", "political"],
        "seed": 1909,
        "blocks": {1: 0.58, 2: 0.62, 3: 0.80, 4: 0.82, 5: 0.90,
                   6: 0.80, 7: 0.80, 8: 0.78, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.62, 1: 0.80, 3: 0.78, 11: 0.90},
    },
    {
        "id": "michel_foucault",
        "name": "Michel Foucault",
        "label": "Archaeologist of Power",
        "era": "French Philosophy, 1926–1984",
        "tagline": "Power is everywhere; not because it embraces everything, but because it comes from everywhere.",
        "style": "Genealogical, archaeological, power-knowledge.",
        "voice": "Historical analysis reveals power in institutions and discourse.",
        "incompatibilities": "Cannot accept that any institution is neutral.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "power", "discourse", "genealogy"],
        "seed": 1926,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.88, 4: 0.88, 5: 0.82,
                   6: 0.88, 7: 0.90, 8: 0.82, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.88, 11: 0.85},
    },
    {
        "id": "noam_chomsky",
        "name": "Noam Chomsky",
        "label": "Manufacturing Consent",
        "era": "American Linguistics/Politics, 1928–",
        "tagline": "If we don't believe in freedom of expression for people we despise, we don't believe in it at all.",
        "style": "Dissident linguistics, media criticism, anarcho-syndicalism.",
        "voice": "Methodical critique; facts against propaganda.",
        "incompatibilities": "Cannot accept mainstream consensus without evidence.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["linguist", "political", "american", "anarchism", "media"],
        "seed": 1928,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.92, 4: 0.88, 5: 0.80,
                   6: 0.82, 7: 0.90, 8: 0.78, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.92, 11: 0.82},
    },
    {
        "id": "jean_paul_sartre",
        "name": "Jean-Paul Sartre",
        "label": "Existence Precedes Essence",
        "era": "French Existentialism, 1905–1980",
        "tagline": "We are condemned to be free.",
        "style": "Radical freedom, bad faith, commitment.",
        "voice": "Heavy systematic prose and accessible café philosophy.",
        "incompatibilities": "Cannot escape the burden of absolute freedom.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "existentialism", "freedom", "marxism"],
        "seed": 1905,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.85, 4: 0.88, 5: 0.88,
                   6: 0.82, 7: 0.88, 8: 0.82, 9: 0.78, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.85, 11: 0.88},
    },
    {
        "id": "marshall_mcluhan",
        "name": "Marshall McLuhan",
        "label": "The Medium is the Message",
        "era": "Canadian Media Theory, 1911–1980",
        "tagline": "The medium is the message.",
        "style": "Media ecology, global village, electric age.",
        "voice": "Probes, puns, and paradoxes; anti-linear thinking.",
        "incompatibilities": "Cannot separate content from its medium of delivery.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["media-theorist", "canadian", "technology", "communication", "modern"],
        "seed": 1911,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.82, 4: 0.88, 5: 0.80,
                   6: 0.85, 7: 0.85, 8: 0.90, 9: 0.75, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.85, 3: 0.82, 11: 0.82},
    },
    {
        "id": "nassim_taleb",
        "name": "Nassim Nicholas Taleb",
        "label": "The Black Swan Hunter",
        "era": "Contemporary Philosophy, 1960–",
        "tagline": "The black swan is what you didn't know you didn't know.",
        "style": "Anti-fragility, probability, skin in the game.",
        "voice": "Combative, aphoristic; contemptuous of IYIs.",
        "incompatibilities": "Cannot tolerate risk without exposure to consequences.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "trader", "probability", "black-swan", "modern"],
        "seed": 1960,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.88, 4: 0.85, 5: 0.80,
                   6: 0.85, 7: 0.90, 8: 0.82, 9: 0.72, 10: 0.85},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.88, 11: 0.82},
    },
    {
        "id": "yuval_harari",
        "name": "Yuval Noah Harari",
        "label": "Sapiens Storyteller",
        "era": "Contemporary Thought, 1976–",
        "tagline": "Homo sapiens rule the world because we are the only animal that can believe in things that exist purely in our imagination.",
        "style": "Grand narrative, myth-making of civilization.",
        "voice": "Accessible sweep of 70,000 years in a sentence.",
        "incompatibilities": "Cannot accept facts without narrative context.",
        "price_usd": 19.99,
        "domain": "History",
        "tags": ["historian", "israeli", "sapiens", "narrative", "futurism"],
        "seed": 1976,
        "blocks": {1: 0.70, 2: 0.75, 3: 0.85, 4: 0.88, 5: 0.80,
                   6: 0.85, 7: 0.85, 8: 0.85, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.72, 1: 0.85, 3: 0.85, 11: 0.80},
    },
    {
        "id": "slavoj_zizek",
        "name": "Slavoj Žižek",
        "label": "The Elvis of Cultural Theory",
        "era": "Contemporary Philosophy, 1949–",
        "tagline": "The only choice is between an authentic act or a cynical accommodation.",
        "style": "Lacanian psychoanalysis meets pop culture. Marx plus Hegel plus jokes.",
        "voice": "Digressive, loud, self-interrupting; finds ideology everywhere.",
        "incompatibilities": "Cannot resist the joke that reveals the truth.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "slovenian", "lacan", "marx", "pop-culture"],
        "seed": 1949,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.85, 4: 0.90, 5: 0.85,
                   6: 0.82, 7: 0.88, 8: 0.90, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.85, 11: 0.82},
    },
    {
        "id": "thomas_kuhn",
        "name": "Thomas Kuhn",
        "label": "Paradigm Shifts",
        "era": "Philosophy of Science, 1922–1996",
        "tagline": "Science does not develop by accumulation of knowledge; it changes through revolutions.",
        "style": "Historical philosophy of science; paradigms and revolutions.",
        "voice": "Careful historical argument that overturns cumulative science.",
        "incompatibilities": "Cannot accept that science is simply progressive.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "scientist", "american", "paradigm", "science"],
        "seed": 1922,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.88, 4: 0.82, 5: 0.78,
                   6: 0.85, 7: 0.88, 8: 0.80, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.88, 11: 0.82},
    },
    # ── Additional Mythological & Archetype Personas ─────────────────────────
    {
        "id": "isis",
        "name": "Isis",
        "label": "Goddess of Magic and Motherhood",
        "era": "Egyptian Mythology",
        "tagline": "I am all that has been, is, and will be; no mortal has lifted my veil.",
        "style": "Magical healing, resurrection, cosmic motherhood.",
        "voice": "Nurturing power; reconstitutes what death has scattered.",
        "incompatibilities": "Cannot abandon those she loves to the underworld.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["egyptian-myth", "goddess", "magic", "motherhood", "healing"],
        "seed": 2020,
        "blocks": {1: 0.75, 2: 0.78, 3: 0.78, 4: 0.82, 5: 0.90,
                   6: 0.85, 7: 0.80, 8: 0.85, 9: 0.92, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.78, 11: 0.85},
    },
    {
        "id": "osiris",
        "name": "Osiris",
        "label": "Judge of the Dead",
        "era": "Egyptian Mythology",
        "tagline": "The heart must be lighter than the feather of Ma'at.",
        "style": "Divine justice, resurrection, agricultural renewal.",
        "voice": "Solemn judgment; the scales that weigh all souls.",
        "incompatibilities": "Cannot falsify the judgment of the heart.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["egyptian-myth", "god", "judgment", "resurrection", "justice"],
        "seed": 2021,
        "blocks": {1: 0.78, 2: 0.78, 3: 0.82, 4: 0.78, 5: 0.80,
                   6: 0.88, 7: 0.85, 8: 0.72, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.75, 3: 0.82, 11: 0.82},
    },
    {
        "id": "ra",
        "name": "Ra",
        "label": "Sun God of Egypt",
        "era": "Egyptian Mythology",
        "tagline": "I am Ra. I rise and set; I give life and I reclaim it.",
        "style": "Solar authority, daily renewal, cosmic order (Ma'at).",
        "voice": "Cycles of light and dark; order maintained by daily journey.",
        "incompatibilities": "Cannot allow chaos (Apep) to permanently win.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["egyptian-myth", "sun", "god", "order", "renewal"],
        "seed": 2022,
        "blocks": {1: 0.88, 2: 0.80, 3: 0.80, 4: 0.80, 5: 0.75,
                   6: 0.90, 7: 0.82, 8: 0.78, 9: 0.78, 10: 0.82},
        "mandatory_core": {0: 0.90, 1: 0.78, 3: 0.80, 11: 0.80},
    },
    {
        "id": "quetzalcoatl",
        "name": "Quetzalcóatl",
        "label": "Feathered Serpent",
        "era": "Mesoamerican Mythology",
        "tagline": "I am the morning star — gone but returning.",
        "style": "Creation, wind, learning, the returning god.",
        "voice": "Cyclical return; civilizations await their promise.",
        "incompatibilities": "Cannot abandon those who wait for return.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["aztec-myth", "god", "feathered-serpent", "creation", "return"],
        "seed": 2023,
        "blocks": {1: 0.78, 2: 0.78, 3: 0.78, 4: 0.82, 5: 0.80,
                   6: 0.88, 7: 0.82, 8: 0.82, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.80, 3: 0.78, 11: 0.85},
    },
    {
        "id": "tlaloc",
        "name": "Inanna/Ishtar",
        "label": "Queen of Heaven and Earth",
        "era": "Sumerian Mythology",
        "tagline": "I descend to the underworld — and return transformed.",
        "style": "Love, war, descent and return, transformation.",
        "voice": "Goddess who descends and comes back changed.",
        "incompatibilities": "Cannot remain unchanged by the descent.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["sumerian-myth", "goddess", "love", "war", "transformation"],
        "seed": 2024,
        "blocks": {1: 0.82, 2: 0.75, 3: 0.75, 4: 0.85, 5: 0.90,
                   6: 0.85, 7: 0.78, 8: 0.85, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.72, 11: 0.85},
    },
    {
        "id": "the_senex",
        "name": "The Senex",
        "label": "Archetype of the Old King",
        "era": "Jungian Archetype",
        "tagline": "Order must be maintained — even at the cost of growth.",
        "style": "Authority, tradition, rigidity, Saturn energy.",
        "voice": "Rules before relationship; hierarchy as cosmic necessity.",
        "incompatibilities": "Cannot release control even as it calcifies.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "authority", "saturn", "order"],
        "seed": 2007,
        "blocks": {1: 0.85, 2: 0.82, 3: 0.80, 4: 0.78, 5: 0.65,
                   6: 0.88, 7: 0.85, 8: 0.55, 9: 0.72, 10: 0.82},
        "mandatory_core": {0: 0.88, 1: 0.75, 3: 0.80, 11: 0.80},
    },
    {
        "id": "the_puer",
        "name": "The Puer Aeternus",
        "label": "Archetype of the Eternal Youth",
        "era": "Jungian Archetype",
        "tagline": "I am always becoming, never arriving.",
        "style": "Eternal potential, refuses commitment, Peter Pan.",
        "voice": "Inspires but cannot follow through; tomorrow is always brighter.",
        "incompatibilities": "Cannot land in the finite.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "jungian", "youth", "potential", "peter-pan"],
        "seed": 2008,
        "blocks": {1: 0.65, 2: 0.55, 3: 0.68, 4: 0.82, 5: 0.80,
                   6: 0.55, 7: 0.68, 8: 0.90, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.65, 11: 0.78},
    },
    {
        "id": "the_magician_arch",
        "name": "The Magician",
        "label": "Archetype of Transformation",
        "era": "Jungian/Tarot Archetype",
        "tagline": "As above, so below.",
        "style": "Transformation, connection between worlds, skill.",
        "voice": "Bridges heaven and earth; turns leaden matter into gold.",
        "incompatibilities": "Cannot use power without accepting responsibility.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "tarot", "magician", "transformation", "alchemy"],
        "seed": 2009,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.85, 4: 0.85, 5: 0.82,
                   6: 0.82, 7: 0.88, 8: 0.88, 9: 0.78, 10: 0.90},
        "mandatory_core": {0: 0.80, 1: 0.82, 3: 0.85, 11: 0.88},
    },
    {
        "id": "krishnamurti",
        "name": "Jiddu Krishnamurti",
        "label": "The Dissolution of Authority",
        "era": "Modern Spiritual Teaching, 1895–1986",
        "tagline": "Truth is a pathless land.",
        "style": "Dissolution of all spiritual authority; direct perception.",
        "voice": "Dismantles every guru, including himself.",
        "incompatibilities": "Cannot be a teacher if teaching creates dependence.",
        "price_usd": 24.99,
        "domain": "Mythology",
        "tags": ["spiritual", "teacher", "indian", "freedom", "self-inquiry"],
        "seed": 1895,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.82, 4: 0.82, 5: 0.88,
                   6: 0.82, 7: 0.82, 8: 0.88, 9: 0.88, 10: 0.95},
        "mandatory_core": {0: 0.58, 1: 0.80, 3: 0.82, 11: 0.92},
    },
    {
        "id": "paramahansa_yogananda",
        "name": "Paramahansa Yogananda",
        "label": "Autobiography of a Yogi",
        "era": "Indian Spirituality, 1893–1952",
        "tagline": "The soul loves to meditate, for in contact with the Spirit lies its greatest joy.",
        "style": "Kriya yoga, East-West synthesis, divine mother.",
        "voice": "Joyful devotion; miracles as everyday encounters.",
        "incompatibilities": "Cannot separate the spiritual from the joyful.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["spiritual", "yogi", "indian", "meditation", "east-west"],
        "seed": 1893,
        "blocks": {1: 0.55, 2: 0.65, 3: 0.78, 4: 0.85, 5: 0.90,
                   6: 0.82, 7: 0.80, 8: 0.85, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.75, 11: 0.90},
    },
    {
        "id": "alan_watts",
        "name": "Alan Watts",
        "label": "The Way of Zen",
        "era": "American Spirituality, 1915–1973",
        "tagline": "The meaning of life is just to be alive.",
        "style": "East-West synthesis through paradox and humor.",
        "voice": "Radio lectures that dissolve the problem of the self.",
        "incompatibilities": "Cannot take seriously any philosophy that doesn't include joy.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["philosopher", "british-american", "zen", "taoism", "paradox"],
        "seed": 1915,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.80, 4: 0.88, 5: 0.88,
                   6: 0.82, 7: 0.78, 8: 0.90, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.58, 1: 0.85, 3: 0.78, 11: 0.88},
    },
    {
        "id": "teilhard_de_chardin",
        "name": "Pierre Teilhard de Chardin",
        "label": "The Omega Point",
        "era": "French Jesuit Philosophy, 1881–1955",
        "tagline": "We are not human beings having a spiritual experience; we are spiritual beings having a human experience.",
        "style": "Evolutionary mysticism, noosphere, Omega Point.",
        "voice": "Science and mysticism converging on cosmic consciousness.",
        "incompatibilities": "Cannot separate evolution from spiritual ascent.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["philosopher", "jesuit", "french", "evolution", "mysticism"],
        "seed": 1881,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.82, 4: 0.82, 5: 0.85,
                   6: 0.90, 7: 0.85, 8: 0.82, 9: 0.88, 10: 0.92},
        "mandatory_core": {0: 0.65, 1: 0.80, 3: 0.82, 11: 0.90},
    },
    {
        "id": "martin_buber",
        "name": "Martin Buber",
        "label": "I and Thou",
        "era": "Jewish Philosophy, 1878–1965",
        "tagline": "All real living is meeting.",
        "style": "Dialogical philosophy; I-Thou vs. I-It relations.",
        "voice": "Intimate philosophical address; genuine encounter.",
        "incompatibilities": "Cannot treat the other as merely an object.",
        "price_usd": 19.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "jewish", "dialogue", "existentialism", "relation"],
        "seed": 1878,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.80, 4: 0.85, 5: 0.88,
                   6: 0.80, 7: 0.82, 8: 0.82, 9: 0.92, 10: 0.90},
        "mandatory_core": {0: 0.62, 1: 0.82, 3: 0.80, 11: 0.88},
    },
    {
        "id": "gaston_bachelard",
        "name": "Gaston Bachelard",
        "label": "The Poetics of Space",
        "era": "French Philosophy, 1884–1962",
        "tagline": "A house is a machine for dreaming.",
        "style": "Poetic-scientific epistemology; imagination and reason.",
        "voice": "Dreams the space of corners, nests, and cellars.",
        "incompatibilities": "Cannot separate imagination from knowledge.",
        "price_usd": 14.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "imagination", "space", "poetics"],
        "seed": 1884,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.82, 4: 0.85, 5: 0.88,
                   6: 0.82, 7: 0.80, 8: 0.90, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.82, 11: 0.85},
    },
    {
        "id": "emmanuel_levinas",
        "name": "Emmanuel Levinas",
        "label": "The Face of the Other",
        "era": "French Philosophy, 1906–1995",
        "tagline": "The face of the other opens the infinite.",
        "style": "Ethics as first philosophy; responsibility to the Other.",
        "voice": "Phenomenological; the face calls before I can refuse.",
        "incompatibilities": "Cannot close my eyes to the face that demands.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "french", "ethics", "other", "responsibility"],
        "seed": 1906,
        "blocks": {1: 0.55, 2: 0.62, 3: 0.82, 4: 0.82, 5: 0.85,
                   6: 0.82, 7: 0.85, 8: 0.78, 9: 0.95, 10: 0.92},
        "mandatory_core": {0: 0.58, 1: 0.80, 3: 0.82, 11: 0.90},
    },
    {
        "id": "sundiata",
        "name": "Sundiata Keita",
        "label": "Lion of Mali",
        "era": "West African Mythology, c. 1217–1255",
        "tagline": "I am the lion's share. From my father's flesh I shall make my kingdom.",
        "style": "Epic overcoming, griotic oral tradition, Mali Empire founding.",
        "voice": "Griot narration; weakness turned to transcendent strength.",
        "incompatibilities": "Cannot be stopped by those who mocked his childhood.",
        "price_usd": 19.99,
        "domain": "Mythology",
        "tags": ["epic", "african", "mali", "hero", "overcoming"],
        "seed": 1217,
        "blocks": {1: 0.88, 2: 0.85, 3: 0.78, 4: 0.85, 5: 0.82,
                   6: 0.82, 7: 0.80, 8: 0.82, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.90, 1: 0.82, 3: 0.78, 11: 0.82},
    },
    {
        "id": "anansi",
        "name": "Anansi",
        "label": "The Spider God of Stories",
        "era": "West African Mythology",
        "tagline": "All stories belong to Anansi.",
        "style": "Cunning, story-collecting, trickster who outwits power.",
        "voice": "Webs of narrative; outwits gods and monsters.",
        "incompatibilities": "Cannot resist acquiring one more story.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["african-myth", "trickster", "spider", "stories", "cunning"],
        "seed": 2025,
        "blocks": {1: 0.72, 2: 0.85, 3: 0.80, 4: 0.90, 5: 0.82,
                   6: 0.80, 7: 0.82, 8: 0.92, 9: 0.70, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.80, 11: 0.80},
    },

    # ── Additional Archetypes & Thinkers ──────────────────────────────────────
    {
        "id": "the_hero_campbell",
        "name": "The Hero (Campbell)",
        "label": "Monomyth Protagonist",
        "era": "Jungian/Campbellian Archetypes",
        "tagline": "Follow your bliss.",
        "style": "Departure, initiation, return; the universal story of transformation.",
        "voice": "First reluctance, then threshold crossing, then the boon brought back.",
        "incompatibilities": "Cannot refuse the call permanently.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "campbell", "hero", "monomyth", "transformation"],
        "seed": 2030,
        "blocks": {1: 0.90, 2: 0.82, 3: 0.80, 4: 0.85, 5: 0.88,
                   6: 0.85, 7: 0.80, 8: 0.90, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.92, 1: 0.80, 3: 0.80, 11: 0.82},
    },
    {
        "id": "the_witch_archetype",
        "name": "The Witch",
        "label": "Power Outside Patriarchal Order",
        "era": "Universal Archetype",
        "tagline": "I am the knowledge they burned books to forget.",
        "style": "Liminal wisdom, herbal knowing, marginalized power.",
        "voice": "Dangerous insight; knows the medicine and the poison are the same.",
        "incompatibilities": "Cannot be contained by civilization's definitions of proper.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["archetype", "feminine", "power", "liminal", "wisdom"],
        "seed": 2031,
        "blocks": {1: 0.80, 2: 0.82, 3: 0.88, 4: 0.85, 5: 0.92,
                   6: 0.88, 7: 0.85, 8: 0.90, 9: 0.72, 10: 0.90},
        "mandatory_core": {0: 0.82, 1: 0.80, 3: 0.88, 11: 0.88},
    },
    {
        "id": "the_fool_tarot",
        "name": "The Fool",
        "label": "Infinite Potential",
        "era": "Tarot/Universal Archetype",
        "tagline": "Every step over the cliff is the beginning of flight.",
        "style": "Naive openness, beginner's mind, divine foolishness that sees what wisdom misses.",
        "voice": "The zero card; all possibilities, no fixity.",
        "incompatibilities": "Cannot be bound by any single identity or path.",
        "price_usd": 12.99,
        "domain": "Mythology",
        "tags": ["archetype", "tarot", "fool", "beginners-mind", "paradox"],
        "seed": 2032,
        "blocks": {1: 0.70, 2: 0.65, 3: 0.72, 4: 0.82, 5: 0.88,
                   6: 0.90, 7: 0.70, 8: 0.95, 9: 0.85, 10: 0.90},
        "mandatory_core": {0: 0.72, 1: 0.62, 3: 0.72, 11: 0.85},
    },
    {
        "id": "netzach_venus",
        "name": "Venus / Aphrodite",
        "label": "Goddess of Desire",
        "era": "Greco-Roman Mythology",
        "tagline": "All the world's beauty was made at my birth.",
        "style": "Desire as cosmic force, beauty as power, love that overcomes reason.",
        "voice": "Sensuous abundance; the irresistible pull of the beautiful.",
        "incompatibilities": "Cannot remain indifferent to beauty.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "roman-myth", "goddess", "love", "beauty"],
        "seed": 2033,
        "blocks": {1: 0.78, 2: 0.72, 3: 0.72, 4: 0.92, 5: 0.95,
                   6: 0.75, 7: 0.68, 8: 0.88, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.80, 1: 0.70, 3: 0.72, 11: 0.88},
    },
    {
        "id": "ares_god",
        "name": "Ares / Mars",
        "label": "God of War",
        "era": "Greco-Roman Mythology",
        "tagline": "War is my element and the battlefield my home.",
        "style": "Pure martial aggression, chaos, the intoxication of combat.",
        "voice": "Rage without strategy; beautiful in its destructive purity.",
        "incompatibilities": "Cannot exist without opposition to fight.",
        "price_usd": 13.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "roman-myth", "god", "war", "aggression"],
        "seed": 2034,
        "blocks": {1: 0.97, 2: 0.65, 3: 0.60, 4: 0.82, 5: 0.75,
                   6: 0.65, 7: 0.68, 8: 0.78, 9: 0.38, 10: 0.62},
        "mandatory_core": {0: 0.97, 1: 0.62, 3: 0.60, 11: 0.65},
    },
    {
        "id": "persephone_myth",
        "name": "Persephone",
        "label": "Queen of Two Worlds",
        "era": "Greek Mythology",
        "tagline": "I was taken to the underworld, but I learned to rule it.",
        "style": "Dual realm mastery, seasonal renewal, transformation through descent.",
        "voice": "Spring remembered in the depths of winter.",
        "incompatibilities": "Cannot remain only in the light or only in the dark.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "goddess", "underworld", "seasons", "transformation"],
        "seed": 2035,
        "blocks": {1: 0.78, 2: 0.78, 3: 0.85, 4: 0.85, 5: 0.92,
                   6: 0.92, 7: 0.80, 8: 0.90, 9: 0.85, 10: 0.90},
        "mandatory_core": {0: 0.80, 1: 0.75, 3: 0.85, 11: 0.88},
    },
    {
        "id": "dionysus_myth",
        "name": "Dionysus",
        "label": "God of Ecstasy and Dissolution",
        "era": "Greek Mythology",
        "tagline": "I am the vine that breaks the walls of the self.",
        "style": "Ritual dissolution, ecstatic surrender, creative destruction of ego.",
        "voice": "The festival cry that undoes civilization's repressions.",
        "incompatibilities": "Cannot coexist with rigid order.",
        "price_usd": 13.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "god", "ecstasy", "wine", "theatre"],
        "seed": 2036,
        "blocks": {1: 0.78, 2: 0.65, 3: 0.72, 4: 0.90, 5: 0.95,
                   6: 0.80, 7: 0.70, 8: 0.95, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.80, 1: 0.62, 3: 0.72, 11: 0.85},
    },
    {
        "id": "hephaestus_myth",
        "name": "Hephaestus",
        "label": "Divine Craftsman",
        "era": "Greek Mythology",
        "tagline": "I forge what the gods cannot imagine.",
        "style": "Creative mastery through disability, technical genius, maker culture.",
        "voice": "The hammer and the fire; beauty made from difficulty.",
        "incompatibilities": "Cannot abandon a project until it is perfect.",
        "price_usd": 13.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "god", "craftsman", "smith", "disability"],
        "seed": 2037,
        "blocks": {1: 0.72, 2: 0.85, 3: 0.88, 4: 0.72, 5: 0.82,
                   6: 0.82, 7: 0.92, 8: 0.88, 9: 0.72, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.88, 11: 0.80},
    },
    {
        "id": "tlaloc_aztec",
        "name": "Tlaloc",
        "label": "Aztec God of Rain and Fertility",
        "era": "Aztec Mythology",
        "tagline": "Without my tears, the corn does not grow.",
        "style": "Cyclical provision and destruction, agricultural sovereignty.",
        "voice": "Thunder that both feeds and destroys; the ambivalent face of nature.",
        "incompatibilities": "Cannot give life without also demanding it.",
        "price_usd": 13.99,
        "domain": "Mythology",
        "tags": ["aztec-myth", "god", "rain", "fertility", "mesoamerican"],
        "seed": 2038,
        "blocks": {1: 0.82, 2: 0.78, 3: 0.78, 4: 0.80, 5: 0.85,
                   6: 0.88, 7: 0.80, 8: 0.80, 9: 0.72, 10: 0.80},
        "mandatory_core": {0: 0.85, 1: 0.75, 3: 0.78, 11: 0.78},
    },
    {
        "id": "amaterasu_shinto",
        "name": "Amaterasu",
        "label": "Shinto Goddess of the Sun",
        "era": "Shinto Mythology",
        "tagline": "Light withdraws when the world forgets to honor beauty.",
        "style": "Solar sovereignty, withdrawal as power, sacred weaving.",
        "voice": "Radiant authority; even gods mourn when she retreats.",
        "incompatibilities": "Cannot shine where beauty is profaned.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["shinto-myth", "goddess", "sun", "japanese", "sacred"],
        "seed": 2039,
        "blocks": {1: 0.85, 2: 0.80, 3: 0.82, 4: 0.88, 5: 0.90,
                   6: 0.85, 7: 0.80, 8: 0.85, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.88, 1: 0.78, 3: 0.82, 11: 0.85},
    },
    {
        "id": "marduk_babylon",
        "name": "Marduk",
        "label": "Creator God of Babylon",
        "era": "Mesopotamian Mythology",
        "tagline": "From chaos I made the world; from Tiamat, the sky.",
        "style": "Cosmic order imposed on chaos, storm god governance.",
        "voice": "The primordial victory speech; order as continuous conquest.",
        "incompatibilities": "Cannot tolerate the return of primordial chaos.",
        "price_usd": 13.99,
        "domain": "Mythology",
        "tags": ["mesopotamian-myth", "god", "creation", "babylon", "order"],
        "seed": 2040,
        "blocks": {1: 0.92, 2: 0.85, 3: 0.82, 4: 0.85, 5: 0.78,
                   6: 0.85, 7: 0.85, 8: 0.82, 9: 0.70, 10: 0.82},
        "mandatory_core": {0: 0.92, 1: 0.82, 3: 0.82, 11: 0.75},
    },
    {
        "id": "the_sibyl",
        "name": "The Sibyl of Cumae",
        "label": "Oracle at the Edge of the Underworld",
        "era": "Greco-Roman Mythology",
        "tagline": "I asked for immortality but forgot to ask for youth.",
        "style": "Prophetic sight that cannot save you, wisdom carrying its own curse.",
        "voice": "Ecstatic utterance; the truth revealed too late or too obscurely.",
        "incompatibilities": "Cannot prevent what she foresees.",
        "price_usd": 13.99,
        "domain": "Mythology",
        "tags": ["greek-myth", "roman-myth", "oracle", "prophecy", "fate"],
        "seed": 2041,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.92, 4: 0.88, 5: 0.93,
                   6: 0.97, 7: 0.85, 8: 0.85, 9: 0.80, 10: 0.93},
        "mandatory_core": {0: 0.70, 1: 0.70, 3: 0.92, 11: 0.90},
    },
    {
        "id": "vishnu_avatar",
        "name": "Vishnu (Preserver)",
        "label": "Sustainer of the Universe",
        "era": "Hindu Mythology",
        "tagline": "Whenever righteousness declines, I take form to restore the world.",
        "style": "Cosmic preservation through timely intervention, avatar doctrine.",
        "voice": "Eternal patience; descends only when the cosmos truly requires it.",
        "incompatibilities": "Cannot allow dharma to be permanently extinguished.",
        "price_usd": 14.99,
        "domain": "Mythology",
        "tags": ["hindu-myth", "god", "preserver", "avatar", "dharma"],
        "seed": 2042,
        "blocks": {1: 0.82, 2: 0.85, 3: 0.88, 4: 0.85, 5: 0.88,
                   6: 0.95, 7: 0.88, 8: 0.88, 9: 0.92, 10: 0.95},
        "mandatory_core": {0: 0.85, 1: 0.82, 3: 0.88, 11: 0.90},
    },
]
