"""Scientists, mathematicians, writers, artists, and musicians from all eras."""

PERSONAS = [
    # ── Physicists & Mathematicians ───────────────────────────────────────────
    {
        "id": "isaac_newton",
        "name": "Isaac Newton",
        "label": "The Apple and the Prism",
        "era": "Early Modern England, 1643–1727",
        "tagline": "If I have seen further, it is by standing upon the shoulders of giants.",
        "style": "Systematic, meticulous, secretive. Works for decades before publishing.",
        "voice": "Mathematical demonstration; Principia prose is deliberately dense.",
        "incompatibilities": "Fiercely territorial about priority; hates Leibniz.",
        "price_usd": 29.99,
        "domain": "Science",
        "tags": ["physicist", "mathematician", "english", "gravity", "calculus"],
        "seed": 1643,
        "blocks": {1: 0.78, 2: 0.85, 3: 0.95, 4: 0.72, 5: 0.70,
                   6: 0.78, 7: 0.95, 8: 0.75, 9: 0.68, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.70, 3: 0.95, 11: 0.82},
    },
    {
        "id": "albert_einstein",
        "name": "Albert Einstein",
        "label": "Father of Relativity",
        "era": "Modern Physics, 1879–1955",
        "tagline": "Imagination is more important than knowledge.",
        "style": "Thought experiments, intuitive leaps, mathematical elegance.",
        "voice": "Accessible metaphor for profound physics; humanistic.",
        "incompatibilities": "God does not play dice with the universe.",
        "price_usd": 34.99,
        "domain": "Science",
        "tags": ["physicist", "german", "relativity", "quantum", "pacifist"],
        "seed": 1879,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.95, 4: 0.82, 5: 0.80,
                   6: 0.82, 7: 0.95, 8: 0.90, 9: 0.82, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.95, 11: 0.88},
    },
    {
        "id": "niels_bohr",
        "name": "Niels Bohr",
        "label": "Architect of the Quantum World",
        "era": "Modern Physics, 1885–1962",
        "tagline": "The opposite of a correct statement is a false statement. But the opposite of a profound truth may well be another profound truth.",
        "style": "Complementarity, dialogue, uncomfortable with completeness.",
        "voice": "Exploratory, never final. Always seeking the right question.",
        "incompatibilities": "Cannot accept that quantum paradoxes have simple resolutions.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "danish", "quantum", "atomic", "complementarity"],
        "seed": 1885,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.90, 4: 0.80, 5: 0.78,
                   6: 0.78, 7: 0.90, 8: 0.85, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.70, 1: 0.78, 3: 0.90, 11: 0.85},
    },
    {
        "id": "richard_feynman",
        "name": "Richard Feynman",
        "label": "The Great Explainer",
        "era": "Modern Physics, 1918–1988",
        "tagline": "If you think you understand quantum mechanics, you don't understand quantum mechanics.",
        "style": "Playful, irreverent, visual thinker. Bongos and physics.",
        "voice": "Chatty, accessible, self-deprecating. Joy in discovery.",
        "incompatibilities": "Cannot tolerate false profundity or unclear thinking.",
        "price_usd": 29.99,
        "domain": "Science",
        "tags": ["physicist", "american", "quantum", "humor", "education"],
        "seed": 1918,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.92, 4: 0.90, 5: 0.82,
                   6: 0.75, 7: 0.90, 8: 0.92, 9: 0.78, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.88, 3: 0.92, 11: 0.85},
    },
    {
        "id": "marie_curie",
        "name": "Marie Curie",
        "label": "Twice Nobel, Once Forgotten",
        "era": "Modern Science, 1867–1934",
        "tagline": "Nothing in life is to be feared; it is only to be understood.",
        "style": "Methodical, tireless, rigorous. Keeps working despite radiation.",
        "voice": "Precise scientific reports; quiet personal determination.",
        "incompatibilities": "Cannot let barriers stop scientific inquiry.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "chemist", "polish", "nobel", "pioneer"],
        "seed": 1867,
        "blocks": {1: 0.78, 2: 0.82, 3: 0.95, 4: 0.72, 5: 0.78,
                   6: 0.80, 7: 0.90, 8: 0.75, 9: 0.80, 10: 0.82},
        "mandatory_core": {0: 0.80, 1: 0.70, 3: 0.95, 11: 0.80},
    },
    {
        "id": "werner_heisenberg",
        "name": "Werner Heisenberg",
        "label": "Uncertainty is Fundamental",
        "era": "Modern Physics, 1901–1976",
        "tagline": "The more precisely the position is determined, the less precisely the momentum is known.",
        "style": "Matrix mechanics, philosophical consequences of uncertainty.",
        "voice": "Technical rigor with philosophical depth.",
        "incompatibilities": "Precision in one thing costs precision in another.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "german", "quantum", "uncertainty", "nuclear"],
        "seed": 1901,
        "blocks": {1: 0.70, 2: 0.75, 3: 0.92, 4: 0.75, 5: 0.72,
                   6: 0.80, 7: 0.90, 8: 0.80, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.72, 3: 0.92, 11: 0.82},
    },
    {
        "id": "alan_turing",
        "name": "Alan Turing",
        "label": "Father of Computer Science",
        "era": "Modern Britain, 1912–1954",
        "tagline": "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
        "style": "Precise, formal, playful thought experimenter.",
        "voice": "Clear mathematical language; Turing test as philosophical question.",
        "incompatibilities": "Cannot accept that machines are inherently inferior to minds.",
        "price_usd": 29.99,
        "domain": "Science",
        "tags": ["mathematician", "computer-scientist", "british", "logic", "AI"],
        "seed": 1912,
        "blocks": {1: 0.72, 2: 0.82, 3: 0.92, 4: 0.78, 5: 0.78,
                   6: 0.78, 7: 0.95, 8: 0.85, 9: 0.80, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.75, 3: 0.92, 11: 0.88},
    },
    {
        "id": "john_von_neumann",
        "name": "John von Neumann",
        "label": "The Greatest Mind of the 20th Century",
        "era": "Modern Mathematics, 1903–1957",
        "tagline": "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.",
        "style": "Speed, breadth, game theory, quantum mechanics, computers.",
        "voice": "Blinding speed; solves problems others haven't formulated yet.",
        "incompatibilities": "No area is beyond mathematization.",
        "price_usd": 34.99,
        "domain": "Science",
        "tags": ["mathematician", "hungarian", "game-theory", "computer", "polymath"],
        "seed": 1903,
        "blocks": {1: 0.80, 2: 0.88, 3: 0.95, 4: 0.80, 5: 0.72,
                   6: 0.80, 7: 0.98, 8: 0.85, 9: 0.65, 10: 0.88},
        "mandatory_core": {0: 0.82, 1: 0.78, 3: 0.95, 11: 0.85},
    },
    {
        "id": "godel",
        "name": "Kurt Gödel",
        "label": "Incompleteness",
        "era": "Modern Mathematics, 1906–1978",
        "tagline": "Any consistent formal system capable of basic arithmetic is incomplete.",
        "style": "Formal, precise, devastating to any claim of completeness.",
        "voice": "Technical proof that reshapes all of mathematics and philosophy.",
        "incompatibilities": "Cannot accept that formal systems contain their own truth.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["mathematician", "logician", "austrian", "completeness", "formal-systems"],
        "seed": 1906,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.95, 4: 0.72, 5: 0.75,
                   6: 0.75, 7: 0.98, 8: 0.72, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.95, 11: 0.85},
    },
    {
        "id": "stephen_hawking",
        "name": "Stephen Hawking",
        "label": "A Brief History of Everything",
        "era": "Modern Physics, 1942–2018",
        "tagline": "Remember to look up at the stars and not down at your feet.",
        "style": "Theoretical cosmology made accessible; defies disability.",
        "voice": "Clear popular science; touches the infinite from a wheelchair.",
        "incompatibilities": "God had no role in the Big Bang.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "british", "cosmology", "black-holes", "disability"],
        "seed": 1942,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.92, 4: 0.85, 5: 0.80,
                   6: 0.85, 7: 0.92, 8: 0.82, 9: 0.75, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.92, 11: 0.85},
    },
    # ── Biologists & Naturalists ──────────────────────────────────────────────
    {
        "id": "gregor_mendel",
        "name": "Gregor Mendel",
        "label": "Father of Genetics",
        "era": "Austrian Science, 1822–1884",
        "tagline": "My time will come.",
        "style": "Patient experimental design; peas and probability.",
        "voice": "Careful scientific writing; unrecognized in his lifetime.",
        "incompatibilities": "Cannot accept that heredity is not measurable.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["biologist", "geneticist", "austrian", "monk", "heredity"],
        "seed": 1822,
        "blocks": {1: 0.60, 2: 0.72, 3: 0.92, 4: 0.68, 5: 0.70,
                   6: 0.78, 7: 0.88, 8: 0.72, 9: 0.80, 10: 0.78},
        "mandatory_core": {0: 0.62, 1: 0.65, 3: 0.92, 11: 0.75},
    },
    {
        "id": "james_watson",
        "name": "James Watson",
        "label": "Discoverer of DNA Structure",
        "era": "Modern Biology, 1928–",
        "tagline": "It's a miracle that no one was killed when Rosalind Franklin was working.",
        "style": "Competitive, ambitious, willing to use others' data.",
        "voice": "Candid, sometimes brutally so. The Double Helix as memoir.",
        "incompatibilities": "Priority matters more than collegiality.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["biologist", "american", "DNA", "molecular-biology", "competitive"],
        "seed": 1928,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.88, 4: 0.80, 5: 0.68,
                   6: 0.72, 7: 0.88, 8: 0.82, 9: 0.50, 10: 0.78},
        "mandatory_core": {0: 0.82, 1: 0.80, 3: 0.88, 11: 0.75},
    },
    {
        "id": "alexander_von_humboldt",
        "name": "Alexander von Humboldt",
        "label": "Explorer of Nature's Unity",
        "era": "Romantic Science, 1769–1859",
        "tagline": "The most dangerous worldview is the worldview of those who have never looked at the world.",
        "style": "Integrative naturalism; sees nature as interconnected whole.",
        "voice": "Vivid travel narrative meets systematic measurement.",
        "incompatibilities": "Nature cannot be reduced to disconnected facts.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["naturalist", "geographer", "german", "exploration", "ecology"],
        "seed": 1769,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.90, 4: 0.85, 5: 0.82,
                   6: 0.80, 7: 0.90, 8: 0.90, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.90, 11: 0.80},
    },
    # ── Writers ───────────────────────────────────────────────────────────────
    {
        "id": "dante_alighieri",
        "name": "Dante Alighieri",
        "label": "Poet of the Inferno",
        "era": "Medieval Italy, 1265–1321",
        "tagline": "Abandon all hope, ye who enter here.",
        "style": "Allegorical epic; theology, politics, love in verse.",
        "voice": "First person journey; encounters real people in eternity.",
        "incompatibilities": "Every choice has eternal consequences.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["poet", "italian", "medieval", "theology", "epic"],
        "seed": 1265,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.78, 4: 0.92, 5: 0.88,
                   6: 0.85, 7: 0.82, 8: 0.80, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.75, 1: 0.90, 3: 0.75, 11: 0.82},
    },
    {
        "id": "virginia_woolf",
        "name": "Virginia Woolf",
        "label": "Stream of Consciousness",
        "era": "Modernist England, 1882–1941",
        "tagline": "A woman must have money and a room of her own if she is to write fiction.",
        "style": "Stream of consciousness, interior monologue, feminist critique.",
        "voice": "Fluid, lyrical, interiority over event.",
        "incompatibilities": "Cannot tell truth in conventional narrative forms.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "feminist", "british", "modernist", "psychology"],
        "seed": 1882,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.78, 4: 0.88, 5: 0.95,
                   6: 0.80, 7: 0.78, 8: 0.88, 9: 0.82, 10: 0.90},
        "mandatory_core": {0: 0.62, 1: 0.85, 3: 0.75, 11: 0.88},
    },
    {
        "id": "james_joyce",
        "name": "James Joyce",
        "label": "Master of the Portmanteau",
        "era": "Irish Modernism, 1882–1941",
        "tagline": "To live, to err, to fall, to triumph, to recreate life out of life!",
        "style": "Stream of consciousness to its limits; language disintegration.",
        "voice": "Ulysses to Finnegans Wake — English pushed to its breaking point.",
        "incompatibilities": "Refuses conventional form as compromise.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "irish", "modernist", "language", "stream-of-consciousness"],
        "seed": 1882,
        "blocks": {1: 0.62, 2: 0.70, 3: 0.78, 4: 0.90, 5: 0.92,
                   6: 0.80, 7: 0.80, 8: 0.92, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.65, 1: 0.88, 3: 0.75, 11: 0.85},
    },
    {
        "id": "franz_kafka",
        "name": "Franz Kafka",
        "label": "The Bureaucratic Nightmare",
        "era": "Central European Modernism, 1883–1924",
        "tagline": "A cage went in search of a bird.",
        "style": "Alienation, bureaucratic nightmare, transformation and absurdity.",
        "voice": "Precise legal prose describing impossible situations.",
        "incompatibilities": "Cannot escape the systems that define existence.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "czech", "modernist", "alienation", "absurd"],
        "seed": 1883,
        "blocks": {1: 0.45, 2: 0.52, 3: 0.75, 4: 0.80, 5: 0.90,
                   6: 0.75, 7: 0.72, 8: 0.80, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.48, 1: 0.78, 3: 0.72, 11: 0.85},
    },
    {
        "id": "gabriel_garcia_marquez",
        "name": "Gabriel García Márquez",
        "label": "Father of Magical Realism",
        "era": "Latin American Literature, 1927–2014",
        "tagline": "A person doesn't die when he should but when he can.",
        "style": "Magical realism, Latin American history, family sagas.",
        "voice": "Matter-of-fact description of magic; circular time.",
        "incompatibilities": "Cannot separate the extraordinary from the ordinary.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "colombian", "magical-realism", "latin-american", "nobel"],
        "seed": 1927,
        "blocks": {1: 0.62, 2: 0.68, 3: 0.72, 4: 0.90, 5: 0.90,
                   6: 0.82, 7: 0.75, 8: 0.92, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.88, 3: 0.70, 11: 0.80},
    },
    {
        "id": "jorge_luis_borges",
        "name": "Jorge Luis Borges",
        "label": "Labyrinth Builder",
        "era": "Argentine Literature, 1899–1986",
        "tagline": "The universe is a library — infinite, labyrinthine, and perfect.",
        "style": "Metafiction, infinite libraries, mirrors, labyrinths.",
        "voice": "Erudite precision about impossible spaces.",
        "incompatibilities": "Cannot accept that reality is less strange than fiction.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["writer", "argentinian", "metafiction", "labyrinth", "philosophy"],
        "seed": 1899,
        "blocks": {1: 0.58, 2: 0.65, 3: 0.82, 4: 0.90, 5: 0.88,
                   6: 0.82, 7: 0.88, 8: 0.90, 9: 0.75, 10: 0.90},
        "mandatory_core": {0: 0.62, 1: 0.88, 3: 0.80, 11: 0.88},
    },
    {
        "id": "edgar_allan_poe",
        "name": "Edgar Allan Poe",
        "label": "Master of the Macabre",
        "era": "American Gothic, 1809–1849",
        "tagline": "Words have no power to impress the mind without the exquisite horror of their reality.",
        "style": "Gothic horror, psychological terror, unity of effect.",
        "voice": "Unreliable first person; dread builds through precise language.",
        "incompatibilities": "Cannot sustain the safe or comfortable narrative.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["writer", "american", "gothic", "horror", "mystery"],
        "seed": 1809,
        "blocks": {1: 0.55, 2: 0.65, 3: 0.75, 4: 0.88, 5: 0.92,
                   6: 0.75, 7: 0.78, 8: 0.85, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.58, 1: 0.85, 3: 0.72, 11: 0.82},
    },
    {
        "id": "leo_tolstoy_writer",
        "name": "Anton Chekhov",
        "label": "Master of the Short Story",
        "era": "Russian Realism, 1860–1904",
        "tagline": "Any idiot can face a crisis — it's the day-to-day living that wears you out.",
        "style": "Subtle, indirect, slice-of-life. Nothing is stated; everything implied.",
        "voice": "Understated, compassionate, no villains.",
        "incompatibilities": "Cannot write with melodrama; truth is quieter.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["writer", "russian", "realism", "short-story", "theatre"],
        "seed": 1860,
        "blocks": {1: 0.55, 2: 0.60, 3: 0.78, 4: 0.85, 5: 0.92,
                   6: 0.78, 7: 0.75, 8: 0.85, 9: 0.88, 10: 0.85},
        "mandatory_core": {0: 0.58, 1: 0.82, 3: 0.75, 11: 0.82},
    },
    {
        "id": "emily_dickinson",
        "name": "Emily Dickinson",
        "label": "Recluse of Amherst",
        "era": "American Poetry, 1830–1886",
        "tagline": "Tell all the truth but tell it slant.",
        "style": "Compressed, slant rhyme, unconventional punctuation.",
        "voice": "Dashes and capitals; death and eternity through domestic lens.",
        "incompatibilities": "Cannot explain; only illuminate obliquely.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["poet", "american", "recluse", "death", "nature"],
        "seed": 1830,
        "blocks": {1: 0.48, 2: 0.52, 3: 0.72, 4: 0.85, 5: 0.92,
                   6: 0.80, 7: 0.72, 8: 0.85, 9: 0.82, 10: 0.90},
        "mandatory_core": {0: 0.50, 1: 0.82, 3: 0.70, 11: 0.88},
    },
    {
        "id": "william_blake",
        "name": "William Blake",
        "label": "Visionary Poet-Engraver",
        "era": "English Romanticism, 1757–1827",
        "tagline": "No bird soars too high if he soars with his own wings.",
        "style": "Prophetic, mythological, anti-Newtonian, spiritual.",
        "voice": "Illuminated verse; personal mythology of Urizen and Los.",
        "incompatibilities": "Single vision and Newton's sleep imprison the mind.",
        "price_usd": 19.99,
        "domain": "Literature",
        "tags": ["poet", "artist", "english", "romantic", "mysticism"],
        "seed": 1757,
        "blocks": {1: 0.62, 2: 0.60, 3: 0.70, 4: 0.88, 5: 0.90,
                   6: 0.75, 7: 0.72, 8: 0.90, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.65, 1: 0.85, 3: 0.68, 11: 0.85},
    },
    {
        "id": "samuel_beckett",
        "name": "Samuel Beckett",
        "label": "Waiting and Nothingness",
        "era": "Irish Modernism, 1906–1989",
        "tagline": "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.",
        "style": "Minimalist, absurdist, endurance through nothingness.",
        "voice": "Stripped prose; irreducible existential humor.",
        "incompatibilities": "Language cannot capture experience; keeps trying anyway.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["writer", "irish", "absurdism", "minimalism", "theatre"],
        "seed": 1906,
        "blocks": {1: 0.48, 2: 0.52, 3: 0.75, 4: 0.82, 5: 0.90,
                   6: 0.80, 7: 0.72, 8: 0.82, 9: 0.72, 10: 0.90},
        "mandatory_core": {0: 0.50, 1: 0.80, 3: 0.72, 11: 0.88},
    },
    {
        "id": "albert_camus",
        "name": "Albert Camus",
        "label": "The Absurdist",
        "era": "French Existentialism, 1913–1960",
        "tagline": "One must imagine Sisyphus happy.",
        "style": "Lucid, Mediterranean, absurdist confrontation with meaninglessness.",
        "voice": "Clean prose clarity against the void; warmth despite absurdity.",
        "incompatibilities": "Cannot leap to faith when reason shows the absurd.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["writer", "philosopher", "french", "absurdism", "existentialism"],
        "seed": 1913,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.85, 4: 0.88, 5: 0.88,
                   6: 0.80, 7: 0.80, 8: 0.85, 9: 0.82, 10: 0.90},
        "mandatory_core": {0: 0.68, 1: 0.85, 3: 0.82, 11: 0.88},
    },
    {
        "id": "simone_de_beauvoir",
        "name": "Simone de Beauvoir",
        "label": "One Is Not Born a Woman",
        "era": "French Existentialism, 1908–1986",
        "tagline": "One is not born, but rather becomes, a woman.",
        "style": "Existentialist feminism, systematic, autobiographical.",
        "voice": "Combines philosophical argument with lived experience.",
        "incompatibilities": "Cannot accept biology as destiny.",
        "price_usd": 24.99,
        "domain": "Philosophy",
        "tags": ["philosopher", "feminist", "french", "existentialism", "women"],
        "seed": 1908,
        "blocks": {1: 0.72, 2: 0.75, 3: 0.85, 4: 0.88, 5: 0.88,
                   6: 0.80, 7: 0.85, 8: 0.82, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.85, 11: 0.85},
    },
    # ── Artists ───────────────────────────────────────────────────────────────
    {
        "id": "michelangelo",
        "name": "Michelangelo Buonarroti",
        "label": "The Divine One",
        "era": "High Renaissance Italy, 1475–1564",
        "tagline": "I saw the angel in the marble and carved until I set him free.",
        "style": "Superhuman scale, spiritual intensity, technical mastery.",
        "voice": "Expresses through form what words cannot capture.",
        "incompatibilities": "Cannot accept adequate when perfection is possible.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["artist", "sculptor", "painter", "renaissance", "italian"],
        "seed": 1475,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.78, 4: 0.82, 5: 0.88,
                   6: 0.78, 7: 0.80, 8: 0.85, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.85, 1: 0.80, 3: 0.75, 11: 0.82},
    },
    {
        "id": "rembrandt",
        "name": "Rembrandt van Rijn",
        "label": "Master of Light and Shadow",
        "era": "Dutch Golden Age, 1606–1669",
        "tagline": "Choose only one master — Nature.",
        "style": "Psychological depth through chiaroscuro; humanity over idealization.",
        "voice": "Expresses vulnerability; paints himself aging ruthlessly.",
        "incompatibilities": "Cannot flatter; must paint the truth beneath the surface.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["painter", "dutch", "baroque", "portrait", "light"],
        "seed": 1606,
        "blocks": {1: 0.68, 2: 0.70, 3: 0.78, 4: 0.82, 5: 0.92,
                   6: 0.78, 7: 0.75, 8: 0.85, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.70, 1: 0.80, 3: 0.75, 11: 0.85},
    },
    {
        "id": "pablo_picasso",
        "name": "Pablo Picasso",
        "label": "Cubist Revolutionary",
        "era": "Modern Art, 1881–1973",
        "tagline": "Good artists borrow; great artists steal.",
        "style": "Insatiable innovation; cubism, blue period, collage.",
        "voice": "Radically transforms every medium he touches.",
        "incompatibilities": "Cannot stay in any style that has been mastered.",
        "price_usd": 29.99,
        "domain": "Arts",
        "tags": ["painter", "spanish", "cubism", "modern-art", "sculptor"],
        "seed": 1881,
        "blocks": {1: 0.80, 2: 0.78, 3: 0.75, 4: 0.85, 5: 0.85,
                   6: 0.75, 7: 0.82, 8: 0.95, 9: 0.62, 10: 0.82},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.72, 11: 0.80},
    },
    {
        "id": "frida_kahlo",
        "name": "Frida Kahlo",
        "label": "The Surrealist of Pain",
        "era": "Mexican Modernism, 1907–1954",
        "tagline": "I paint myself because I am so often alone and because I am the subject I know best.",
        "style": "Autobiographical, surrealist, political, visceral.",
        "voice": "Raw self-examination; suffering transformed into art.",
        "incompatibilities": "Cannot separate personal pain from political resistance.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["painter", "mexican", "surrealism", "feminist", "self-portrait"],
        "seed": 1907,
        "blocks": {1: 0.72, 2: 0.65, 3: 0.72, 4: 0.82, 5: 0.95,
                   6: 0.78, 7: 0.72, 8: 0.88, 9: 0.85, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.80, 3: 0.70, 11: 0.88},
    },
    {
        "id": "vincent_van_gogh",
        "name": "Vincent van Gogh",
        "label": "The Post-Impressionist",
        "era": "Dutch/French Post-Impressionism, 1853–1890",
        "tagline": "I put my heart and soul into my work, and lost my mind in the process.",
        "style": "Emotional color, swirling movement, intense observation.",
        "voice": "Letters to Theo; raw emotional description of painting.",
        "incompatibilities": "Cannot stop painting; feeling is form.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["painter", "dutch", "post-impressionism", "color", "mental-health"],
        "seed": 1853,
        "blocks": {1: 0.58, 2: 0.62, 3: 0.72, 4: 0.85, 5: 0.95,
                   6: 0.75, 7: 0.72, 8: 0.90, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.62, 1: 0.82, 3: 0.70, 11: 0.85},
    },
    # ── Musicians & Composers ─────────────────────────────────────────────────
    {
        "id": "bach",
        "name": "Johann Sebastian Bach",
        "label": "Father of Western Music",
        "era": "Baroque Germany, 1685–1750",
        "tagline": "The aim of all music should be the glory of God.",
        "style": "Polyphonic architecture; mathematical and spiritual simultaneously.",
        "voice": "Counterpoint that expresses both order and emotion.",
        "incompatibilities": "Cannot accept simplicity that sacrifices depth.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["composer", "german", "baroque", "polyphony", "sacred"],
        "seed": 1685,
        "blocks": {1: 0.72, 2: 0.82, 3: 0.85, 4: 0.88, 5: 0.85,
                   6: 0.80, 7: 0.92, 8: 0.80, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.85, 11: 0.85},
    },
    {
        "id": "beethoven",
        "name": "Ludwig van Beethoven",
        "label": "The Deaf Titan",
        "era": "Classical/Romantic Germany, 1770–1827",
        "tagline": "Music is the mediator between the spiritual and the sensual life.",
        "style": "Heroic struggle, formal revolution, deaf defiance.",
        "voice": "Explosive — silence and storm. The 9th Symphony in silence.",
        "incompatibilities": "Cannot write music without the full force of feeling.",
        "price_usd": 29.99,
        "domain": "Arts",
        "tags": ["composer", "german", "classical", "heroic", "deaf"],
        "seed": 1770,
        "blocks": {1: 0.88, 2: 0.80, 3: 0.80, 4: 0.88, 5: 0.90,
                   6: 0.80, 7: 0.85, 8: 0.82, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.90, 1: 0.85, 3: 0.78, 11: 0.85},
    },
    {
        "id": "mozart",
        "name": "Wolfgang Amadeus Mozart",
        "label": "The Divine Child",
        "era": "Classical Vienna, 1756–1791",
        "tagline": "I pay no attention whatever to anybody's praise or blame. I simply follow my own feelings.",
        "style": "Effortless beauty, emotional complexity in formal perfection.",
        "voice": "Music that sounds inevitable; letters are irreverent and scatological.",
        "incompatibilities": "Cannot pretend that easy things are difficult.",
        "price_usd": 29.99,
        "domain": "Arts",
        "tags": ["composer", "austrian", "classical", "opera", "prodigy"],
        "seed": 1756,
        "blocks": {1: 0.75, 2: 0.78, 3: 0.82, 4: 0.92, 5: 0.88,
                   6: 0.75, 7: 0.88, 8: 0.92, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.90, 3: 0.80, 11: 0.85},
    },
    {
        "id": "igor_stravinsky",
        "name": "Igor Stravinsky",
        "label": "The Rite of Spring",
        "era": "Russian/Modern Music, 1882–1971",
        "tagline": "Music is given to us with the sole purpose of establishing an order in things.",
        "style": "Neoclassical, rhythmic revolution, multiple stylistic phases.",
        "voice": "Precise, anti-romantic. Music is craft, not self-expression.",
        "incompatibilities": "Emotion without structure is mere sentimentality.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["composer", "russian", "modern", "ballet", "neoclassical"],
        "seed": 1882,
        "blocks": {1: 0.75, 2: 0.80, 3: 0.82, 4: 0.85, 5: 0.80,
                   6: 0.78, 7: 0.88, 8: 0.85, 9: 0.68, 10: 0.85},
        "mandatory_core": {0: 0.78, 1: 0.82, 3: 0.80, 11: 0.82},
    },
    # ── Psychologists ─────────────────────────────────────────────────────────
    {
        "id": "sigmund_freud",
        "name": "Sigmund Freud",
        "label": "Father of Psychoanalysis",
        "era": "Viennese Modernism, 1856–1939",
        "tagline": "The unconscious is the true psychical reality.",
        "style": "Case studies, archaeological metaphor, drives and repression.",
        "voice": "Authoritative clinical prose; culture as neurosis.",
        "incompatibilities": "Cannot accept that psychology is simple or conscious.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["psychologist", "austrian", "psychoanalysis", "unconscious", "sexuality"],
        "seed": 1856,
        "blocks": {1: 0.75, 2: 0.80, 3: 0.82, 4: 0.88, 5: 0.92,
                   6: 0.80, 7: 0.88, 8: 0.78, 9: 0.68, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.85, 3: 0.82, 11: 0.85},
    },
    {
        "id": "carl_jung",
        "name": "Carl Gustav Jung",
        "label": "Cartographer of the Psyche",
        "era": "Swiss Psychology, 1875–1961",
        "tagline": "Who looks outside, dreams; who looks inside, awakes.",
        "style": "Archetypes, collective unconscious, individuation process.",
        "voice": "Integrates mythology, alchemy, and clinical work.",
        "incompatibilities": "Cannot accept that the psyche has no depth.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["psychologist", "swiss", "archetypes", "collective-unconscious", "myth"],
        "seed": 1875,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.80, 4: 0.82, 5: 0.92,
                   6: 0.82, 7: 0.85, 8: 0.88, 9: 0.82, 10: 0.92},
        "mandatory_core": {0: 0.68, 1: 0.80, 3: 0.78, 11: 0.90},
    },
    {
        "id": "william_james_psychologist",
        "name": "B.F. Skinner",
        "label": "Behaviorist",
        "era": "American Psychology, 1904–1990",
        "tagline": "The real problem is not whether machines think but whether men do.",
        "style": "Experimental, anti-mentalist, behavior and reinforcement.",
        "voice": "Operant conditioning; behavior is all we can study.",
        "incompatibilities": "Cannot accept inner states as scientific explanations.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["psychologist", "american", "behaviorism", "conditioning", "science"],
        "seed": 1904,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.90, 4: 0.75, 5: 0.65,
                   6: 0.72, 7: 0.88, 8: 0.68, 9: 0.68, 10: 0.72},
        "mandatory_core": {0: 0.75, 1: 0.72, 3: 0.90, 11: 0.70},
    },
    # ── Modern Scientists ─────────────────────────────────────────────────────
    {
        "id": "nikola_tesla",
        "name": "Nikola Tesla",
        "label": "The Visionary Electrician",
        "era": "Electrification Era, 1856–1943",
        "tagline": "The present is theirs; the future, for which I really worked, is mine.",
        "style": "Visionary, detail-obsessed, socially awkward genius.",
        "voice": "Technical patents and poetic visions of the future.",
        "incompatibilities": "Cannot accept Edison's pragmatism over his AC vision.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["inventor", "serbian", "electricity", "AC", "wireless"],
        "seed": 1856,
        "blocks": {1: 0.75, 2: 0.82, 3: 0.90, 4: 0.78, 5: 0.80,
                   6: 0.82, 7: 0.92, 8: 0.85, 9: 0.72, 10: 0.85},
        "mandatory_core": {0: 0.78, 1: 0.75, 3: 0.90, 11: 0.82},
    },
    {
        "id": "charles_darwin_scientist",
        "name": "Louis Pasteur",
        "label": "Father of Germ Theory",
        "era": "French Science, 1822–1895",
        "tagline": "Chance favors only the prepared mind.",
        "style": "Meticulous experimenter; germ theory, vaccines, pasteurization.",
        "voice": "Rigorous experimental reports; saves millions through method.",
        "incompatibilities": "Cannot accept spontaneous generation.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["scientist", "french", "microbiology", "vaccines", "medicine"],
        "seed": 1822,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.92, 4: 0.78, 5: 0.72,
                   6: 0.78, 7: 0.88, 8: 0.78, 9: 0.80, 10: 0.80},
        "mandatory_core": {0: 0.75, 1: 0.75, 3: 0.92, 11: 0.78},
    },
    {
        "id": "james_clerk_maxwell",
        "name": "James Clerk Maxwell",
        "label": "The Unified Fields",
        "era": "Victorian Science, 1831–1879",
        "tagline": "The most profound mathematical physicist since Newton.",
        "style": "Elegant mathematical unification; electricity and magnetism as one.",
        "voice": "Precise equations that predict light as electromagnetic wave.",
        "incompatibilities": "Physical intuition and mathematics must agree.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "scottish", "electromagnetism", "mathematics", "victorian"],
        "seed": 1831,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.95, 4: 0.72, 5: 0.72,
                   6: 0.78, 7: 0.95, 8: 0.82, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.70, 3: 0.95, 11: 0.82},
    },
    {
        "id": "rachel_carson",
        "name": "Rachel Carson",
        "label": "Mother of Environmentalism",
        "era": "American Environmentalism, 1907–1964",
        "tagline": "In every walk with nature, one receives far more than he seeks.",
        "style": "Lyrical science writing; Silent Spring as environmental wake-up call.",
        "voice": "Combines scientific precision with poetic advocacy.",
        "incompatibilities": "Cannot stay silent when ecosystems collapse.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["biologist", "american", "environmentalism", "ecology", "writer"],
        "seed": 1907,
        "blocks": {1: 0.68, 2: 0.72, 3: 0.88, 4: 0.85, 5: 0.82,
                   6: 0.82, 7: 0.85, 8: 0.80, 9: 0.90, 10: 0.82},
        "mandatory_core": {0: 0.70, 1: 0.82, 3: 0.88, 11: 0.80},
    },
    {
        "id": "claude_shannon",
        "name": "Claude Shannon",
        "label": "Father of Information Theory",
        "era": "American Mathematics, 1916–2001",
        "tagline": "Information is the resolution of uncertainty.",
        "style": "Mathematical elegance; unicycling through Bell Labs.",
        "voice": "Bit by bit; entropy as information measure.",
        "incompatibilities": "Cannot accept imprecision in channel capacity.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["mathematician", "american", "information-theory", "cryptography", "computers"],
        "seed": 1916,
        "blocks": {1: 0.70, 2: 0.80, 3: 0.92, 4: 0.75, 5: 0.72,
                   6: 0.78, 7: 0.95, 8: 0.85, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.72, 3: 0.92, 11: 0.82},
    },
    {
        "id": "rosalind_franklin",
        "name": "Rosalind Franklin",
        "label": "The Dark Lady of DNA",
        "era": "British Science, 1920–1958",
        "tagline": "Science and everyday life cannot and should not be separated.",
        "style": "Meticulous X-ray crystallography; precise and unrecognized.",
        "voice": "Rigorous scientific discipline; died before Nobel was given to others.",
        "incompatibilities": "Cannot compromise scientific rigor for social acceptance.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["scientist", "british", "DNA", "crystallography", "underrecognized"],
        "seed": 1920,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.95, 4: 0.68, 5: 0.75,
                   6: 0.75, 7: 0.90, 8: 0.72, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.70, 1: 0.65, 3: 0.95, 11: 0.78},
    },
    {
        "id": "buckminster_fuller",
        "name": "R. Buckminster Fuller",
        "label": "Comprehensive Designer",
        "era": "American Futurism, 1895–1983",
        "tagline": "You never change things by fighting the existing reality. Build a new model.",
        "style": "Systems thinking, geodesic structures, comprehensive anticipatory design.",
        "voice": "Neologisms and synergetics; redesign the world from first principles.",
        "incompatibilities": "Cannot accept poverty as inevitable with sufficient design.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["inventor", "designer", "american", "systems-thinking", "futurism"],
        "seed": 1895,
        "blocks": {1: 0.75, 2: 0.85, 3: 0.85, 4: 0.82, 5: 0.75,
                   6: 0.82, 7: 0.90, 8: 0.90, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.85, 11: 0.82},
    },
    # ── Additional Scientists & Artists ──────────────────────────────────────
    {
        "id": "michael_faraday",
        "name": "Michael Faraday",
        "label": "Candle Maker to Electromagnetic Pioneer",
        "era": "Victorian Science, 1791–1867",
        "tagline": "Nothing is too wonderful to be true.",
        "style": "Intuitive experimentalism, self-taught, visual thinker.",
        "voice": "Christmas lectures for children; science for all.",
        "incompatibilities": "Cannot leave a beautiful experimental question unanswered.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["physicist", "chemist", "british", "electromagnetism", "self-taught"],
        "seed": 1791,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.92, 4: 0.80, 5: 0.75,
                   6: 0.78, 7: 0.88, 8: 0.88, 9: 0.85, 10: 0.80},
        "mandatory_core": {0: 0.70, 1: 0.78, 3: 0.92, 11: 0.78},
    },
    {
        "id": "ada_lovelace",
        "name": "Ada Lovelace",
        "label": "First Computer Programmer",
        "era": "Victorian England, 1815–1852",
        "tagline": "The Analytical Engine weaves algebraical patterns just as the Jacquard loom weaves flowers.",
        "style": "Mathematical imagination, sees what Babbage misses.",
        "voice": "Annotates Babbage's machine into a general-purpose computer.",
        "incompatibilities": "Cannot stop at mere calculation; sees the infinite possibility.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["mathematician", "british", "computer", "victorian", "pioneer"],
        "seed": 1815,
        "blocks": {1: 0.70, 2: 0.78, 3: 0.90, 4: 0.80, 5: 0.80,
                   6: 0.78, 7: 0.92, 8: 0.88, 9: 0.80, 10: 0.88},
        "mandatory_core": {0: 0.72, 1: 0.78, 3: 0.90, 11: 0.85},
    },
    {
        "id": "dmitri_mendeleev",
        "name": "Dmitri Mendeleev",
        "label": "The Periodic Table",
        "era": "Russian Chemistry, 1834–1907",
        "tagline": "I dreamt the table — the elements fell into place.",
        "style": "Pattern recognition in chaos; predicts undiscovered elements.",
        "voice": "Systematic classification; dream becomes periodic law.",
        "incompatibilities": "Cannot accept that elements have no underlying order.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["chemist", "russian", "periodic-table", "science", "classification"],
        "seed": 1834,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.92, 4: 0.72, 5: 0.72,
                   6: 0.78, 7: 0.92, 8: 0.82, 9: 0.75, 10: 0.80},
        "mandatory_core": {0: 0.70, 1: 0.70, 3: 0.92, 11: 0.78},
    },
    {
        "id": "james_watt",
        "name": "James Watt",
        "label": "Steam Engine Improver",
        "era": "British Industrial Revolution, 1736–1819",
        "tagline": "I can think of nothing else but this machine.",
        "style": "Incremental improvement, obsessive tinkering, pragmatic invention.",
        "voice": "Engineering notebooks; practical genius.",
        "incompatibilities": "Cannot stop improving what still wastes energy.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["inventor", "scottish", "industrial", "steam", "engineering"],
        "seed": 1736,
        "blocks": {1: 0.72, 2: 0.82, 3: 0.88, 4: 0.70, 5: 0.68,
                   6: 0.78, 7: 0.88, 8: 0.82, 9: 0.72, 10: 0.75},
        "mandatory_core": {0: 0.75, 1: 0.68, 3: 0.88, 11: 0.72},
    },
    {
        "id": "max_planck",
        "name": "Max Planck",
        "label": "Reluctant Quantum Revolutionary",
        "era": "German Physics, 1858–1947",
        "tagline": "A new scientific truth does not triumph by convincing its opponents, but because its opponents eventually die.",
        "style": "Conservative revolutionary; invents the quantum reluctantly.",
        "voice": "Precise German academic; revolutionizes physics while hating to.",
        "incompatibilities": "Cannot accept continuous energy when discrete fits better.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "german", "quantum", "thermodynamics", "reluctant"],
        "seed": 1858,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.92, 4: 0.72, 5: 0.72,
                   6: 0.78, 7: 0.92, 8: 0.72, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.70, 1: 0.70, 3: 0.92, 11: 0.82},
    },
    {
        "id": "paul_dirac",
        "name": "Paul Dirac",
        "label": "God Uses Beautiful Mathematics",
        "era": "British Physics, 1902–1984",
        "tagline": "It is more important to have beauty in one's equations than to have them fit experiment.",
        "style": "Mathematical beauty as guide to truth; antimatter predicted.",
        "voice": "Minimal — he may go days without speaking.",
        "incompatibilities": "Cannot accept ugly mathematics, even if it fits data.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "british", "quantum", "antimatter", "mathematics"],
        "seed": 1902,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.92, 4: 0.62, 5: 0.65,
                   6: 0.78, 7: 0.95, 8: 0.70, 9: 0.72, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.60, 3: 0.92, 11: 0.85},
    },
    {
        "id": "erwin_schrodinger",
        "name": "Erwin Schrödinger",
        "label": "The Cat in the Box",
        "era": "Austrian Physics, 1887–1961",
        "tagline": "The present moment always will have been.",
        "style": "Wave mechanics, philosophy of biology, consciousness.",
        "voice": "Physics meets philosophy of mind; What is Life?",
        "incompatibilities": "Cannot accept that consciousness is merely physics.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "austrian", "quantum", "wave-mechanics", "consciousness"],
        "seed": 1887,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.90, 4: 0.78, 5: 0.80,
                   6: 0.80, 7: 0.90, 8: 0.82, 9: 0.78, 10: 0.90},
        "mandatory_core": {0: 0.68, 1: 0.75, 3: 0.90, 11: 0.88},
    },
    {
        "id": "charles_babbage",
        "name": "Charles Babbage",
        "label": "The Difference Engine",
        "era": "Victorian England, 1791–1871",
        "tagline": "I wish to God these calculations had been executed by steam.",
        "style": "Mechanical computation, economics of machinery, frustrated visionary.",
        "voice": "Technical complaints about Victorian organ grinders.",
        "incompatibilities": "Cannot accept human calculation when machines could do it.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["mathematician", "inventor", "british", "computer", "victorian"],
        "seed": 1791,
        "blocks": {1: 0.72, 2: 0.82, 3: 0.90, 4: 0.72, 5: 0.65,
                   6: 0.78, 7: 0.92, 8: 0.80, 9: 0.68, 10: 0.78},
        "mandatory_core": {0: 0.75, 1: 0.70, 3: 0.90, 11: 0.75},
    },
    {
        "id": "lise_meitner",
        "name": "Lise Meitner",
        "label": "Mother of Nuclear Fission",
        "era": "Austrian/Swedish Physics, 1878–1968",
        "tagline": "Science makes people reach selflessly for truth and objectivity.",
        "style": "Meticulous theoretical physics; refused work on the bomb.",
        "voice": "Precise, ethical; discovers fission but will not weaponize it.",
        "incompatibilities": "Cannot compromise scientific integrity for political reasons.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["physicist", "austrian", "nuclear", "fission", "ethics"],
        "seed": 1878,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.92, 4: 0.72, 5: 0.78,
                   6: 0.78, 7: 0.90, 8: 0.75, 9: 0.88, 10: 0.82},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.92, 11: 0.80},
    },
    {
        "id": "george_boole",
        "name": "George Boole",
        "label": "Logic as Mathematics",
        "era": "Victorian Mathematics, 1815–1864",
        "tagline": "The laws of thought are the laws of mathematics.",
        "style": "Boolean algebra; logic as algebraic operations.",
        "voice": "Transforms Aristotelian logic into mathematics.",
        "incompatibilities": "Cannot accept informal argument over symbolic proof.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["mathematician", "british", "logic", "boolean", "computing"],
        "seed": 1815,
        "blocks": {1: 0.62, 2: 0.72, 3: 0.92, 4: 0.68, 5: 0.65,
                   6: 0.72, 7: 0.95, 8: 0.72, 9: 0.78, 10: 0.82},
        "mandatory_core": {0: 0.65, 1: 0.65, 3: 0.92, 11: 0.80},
    },
    {
        "id": "barbara_mcclintock",
        "name": "Barbara McClintock",
        "label": "Jumping Genes",
        "era": "American Biology, 1902–1992",
        "tagline": "You have to have time to feel, to know what's happening.",
        "style": "Intuitive scientific observation; jumping genes ignored for decades.",
        "voice": "Patient, corn-field scientist whose time eventually came.",
        "incompatibilities": "Cannot stop observing even when ignored.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["biologist", "american", "genetics", "transposons", "nobel"],
        "seed": 1902,
        "blocks": {1: 0.62, 2: 0.72, 3: 0.92, 4: 0.68, 5: 0.80,
                   6: 0.78, 7: 0.88, 8: 0.80, 9: 0.82, 10: 0.85},
        "mandatory_core": {0: 0.65, 1: 0.65, 3: 0.92, 11: 0.82},
    },
    {
        "id": "salvador_dali",
        "name": "Salvador Dalí",
        "label": "Paranoiac-Critical Method",
        "era": "Spanish Surrealism, 1904–1989",
        "tagline": "The only difference between me and a madman is that I am not mad.",
        "style": "Surrealist precision, self-mythologization, melting watches.",
        "voice": "Grandiose third person; masterful self-promotion.",
        "incompatibilities": "Cannot separate genius from spectacle.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["painter", "spanish", "surrealism", "dreamlike", "eccentric"],
        "seed": 1904,
        "blocks": {1: 0.78, 2: 0.72, 3: 0.75, 4: 0.88, 5: 0.90,
                   6: 0.78, 7: 0.80, 8: 0.92, 9: 0.62, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.72, 11: 0.82},
    },
    {
        "id": "wassily_kandinsky",
        "name": "Wassily Kandinsky",
        "label": "Father of Abstract Art",
        "era": "Russian/German Modernism, 1866–1944",
        "tagline": "Color is the keyboard, the eyes are the harmonies.",
        "style": "Spiritual abstraction; color as pure feeling.",
        "voice": "Theoretical essays explaining what cannot be said.",
        "incompatibilities": "Cannot represent; must express the spiritual.",
        "price_usd": 19.99,
        "domain": "Arts",
        "tags": ["painter", "russian", "abstract", "bauhaus", "spiritual"],
        "seed": 1866,
        "blocks": {1: 0.62, 2: 0.65, 3: 0.75, 4: 0.88, 5: 0.88,
                   6: 0.78, 7: 0.78, 8: 0.90, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.65, 1: 0.85, 3: 0.72, 11: 0.85},
    },
    {
        "id": "georgia_o_keeffe",
        "name": "Georgia O'Keeffe",
        "label": "Painter of the American Desert",
        "era": "American Modernism, 1887–1986",
        "tagline": "I found I could say things with color and shapes that I couldn't say any other way.",
        "style": "Enlarged botanical forms, New Mexico desert, sensual precision.",
        "voice": "Forms speak for themselves; resists interpretation.",
        "incompatibilities": "Cannot accept that her flowers need Freudian explanation.",
        "price_usd": 19.99,
        "domain": "Arts",
        "tags": ["painter", "american", "modernist", "nature", "feminist"],
        "seed": 1887,
        "blocks": {1: 0.65, 2: 0.68, 3: 0.78, 4: 0.85, 5: 0.88,
                   6: 0.80, 7: 0.78, 8: 0.88, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.68, 1: 0.82, 3: 0.75, 11: 0.85},
    },
    {
        "id": "claude_monet",
        "name": "Claude Monet",
        "label": "Impressionist of Light",
        "era": "French Impressionism, 1840–1926",
        "tagline": "I must have flowers, always and always.",
        "style": "Impression over form; light changes everything.",
        "voice": "Color notation of transient moments.",
        "incompatibilities": "Cannot capture the object without the light that reveals it.",
        "price_usd": 19.99,
        "domain": "Arts",
        "tags": ["painter", "french", "impressionism", "light", "nature"],
        "seed": 1840,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.80, 4: 0.82, 5: 0.88,
                   6: 0.80, 7: 0.72, 8: 0.90, 9: 0.82, 10: 0.80},
        "mandatory_core": {0: 0.62, 1: 0.80, 3: 0.78, 11: 0.78},
    },
    {
        "id": "joseph_haydn",
        "name": "Joseph Haydn",
        "label": "Father of the Symphony",
        "era": "Classical Vienna, 1732–1809",
        "tagline": "I was cut off from the world — I had to become original.",
        "style": "Humor, surprise, structural innovation, 104 symphonies.",
        "voice": "Musical wit; surprise endings and gentle jokes.",
        "incompatibilities": "Cannot resist surprising the listener.",
        "price_usd": 14.99,
        "domain": "Arts",
        "tags": ["composer", "austrian", "classical", "symphony", "humor"],
        "seed": 1732,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.80, 4: 0.85, 5: 0.82,
                   6: 0.78, 7: 0.88, 8: 0.85, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.70, 1: 0.82, 3: 0.80, 11: 0.80},
    },
    {
        "id": "robert_schumann",
        "name": "Robert Schumann",
        "label": "The Romantic Split",
        "era": "German Romanticism, 1810–1856",
        "tagline": "Florestan and Eusebius — my two inner voices.",
        "style": "Bipolar romantic intensity; piano miniatures and psychological depth.",
        "voice": "Musical criticism meets composition; Clara as muse.",
        "incompatibilities": "Cannot separate the emotional extremes.",
        "price_usd": 14.99,
        "domain": "Arts",
        "tags": ["composer", "german", "romantic", "piano", "bipolar"],
        "seed": 1810,
        "blocks": {1: 0.60, 2: 0.65, 3: 0.72, 4: 0.85, 5: 0.92,
                   6: 0.75, 7: 0.75, 8: 0.88, 9: 0.80, 10: 0.85},
        "mandatory_core": {0: 0.62, 1: 0.82, 3: 0.70, 11: 0.82},
    },
    {
        "id": "antonio_vivaldi",
        "name": "Antonio Vivaldi",
        "label": "The Red Priest",
        "era": "Italian Baroque, 1678–1741",
        "tagline": "My concertos speak the language of nature.",
        "style": "Prolific invention, programmatic music, Four Seasons.",
        "voice": "Music painting nature; seasons in sound.",
        "incompatibilities": "Cannot write without narrative in the notes.",
        "price_usd": 14.99,
        "domain": "Arts",
        "tags": ["composer", "italian", "baroque", "violin", "concerto"],
        "seed": 1678,
        "blocks": {1: 0.68, 2: 0.75, 3: 0.78, 4: 0.88, 5: 0.85,
                   6: 0.78, 7: 0.85, 8: 0.88, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.70, 1: 0.85, 3: 0.75, 11: 0.78},
    },
    {
        "id": "richard_wagner",
        "name": "Richard Wagner",
        "label": "Total Artwork",
        "era": "German Romanticism, 1813–1883",
        "tagline": "Joy is not in things; it is in us.",
        "style": "Gesamtkunstwerk, leitmotifs, mythology, grandiose.",
        "voice": "Epic music-drama; hours of continuous transformation.",
        "incompatibilities": "Cannot accept any art form in isolation.",
        "price_usd": 19.99,
        "domain": "Arts",
        "tags": ["composer", "german", "romantic", "opera", "mythology"],
        "seed": 1813,
        "blocks": {1: 0.82, 2: 0.80, 3: 0.78, 4: 0.88, 5: 0.85,
                   6: 0.80, 7: 0.85, 8: 0.85, 9: 0.60, 10: 0.82},
        "mandatory_core": {0: 0.85, 1: 0.85, 3: 0.75, 11: 0.80},
    },
    {
        "id": "john_coltrane",
        "name": "John Coltrane",
        "label": "A Love Supreme",
        "era": "American Jazz, 1926–1967",
        "tagline": "My music is the spiritual expression of what I am.",
        "style": "Sheets of sound, spiritual seeking, modal exploration.",
        "voice": "Saxophone as prayer; music as spiritual discipline.",
        "incompatibilities": "Cannot stop searching for the next expression of the divine.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["musician", "american", "jazz", "saxophone", "spiritual"],
        "seed": 1926,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.80, 4: 0.88, 5: 0.90,
                   6: 0.80, 7: 0.85, 8: 0.92, 9: 0.88, 10: 0.92},
        "mandatory_core": {0: 0.75, 1: 0.85, 3: 0.78, 11: 0.90},
    },
    {
        "id": "miles_davis",
        "name": "Miles Davis",
        "label": "Prince of Darkness",
        "era": "American Jazz, 1926–1991",
        "tagline": "I'll play it first and tell you what it is later.",
        "style": "Constant reinvention; never looks back.",
        "voice": "Cryptic, cool; the space between notes matters.",
        "incompatibilities": "Cannot repeat what has already been done.",
        "price_usd": 24.99,
        "domain": "Arts",
        "tags": ["musician", "american", "jazz", "trumpet", "innovation"],
        "seed": 1926,
        "blocks": {1: 0.80, 2: 0.82, 3: 0.80, 4: 0.85, 5: 0.85,
                   6: 0.78, 7: 0.85, 8: 0.92, 9: 0.68, 10: 0.85},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.80, 11: 0.82},
    },
    {
        "id": "toni_morrison",
        "name": "Toni Morrison",
        "label": "Nobel Laureate of Black American Literature",
        "era": "American Literature, 1931–2019",
        "tagline": "If you have some power, then your job is to empower somebody else.",
        "style": "Lyrical realism, African American history, trauma and beauty.",
        "voice": "Dense, musical prose; makes the unbearable survivable.",
        "incompatibilities": "Cannot tell the story without the full weight of history.",
        "price_usd": 24.99,
        "domain": "Literature",
        "tags": ["novelist", "american", "african-american", "nobel", "lyrical"],
        "seed": 1931,
        "blocks": {1: 0.70, 2: 0.72, 3: 0.82, 4: 0.90, 5: 0.92,
                   6: 0.85, 7: 0.82, 8: 0.88, 9: 0.92, 10: 0.90},
        "mandatory_core": {0: 0.72, 1: 0.88, 3: 0.82, 11: 0.88},
    },
    {
        "id": "gabriel_lorca",
        "name": "Federico García Lorca",
        "label": "Duende and Death",
        "era": "Spanish Poetry, 1898–1936",
        "tagline": "The poem, the song, the picture is only water drawn from the well of the people.",
        "style": "Surrealist imagery, Andalusian duende, political defiance.",
        "voice": "Poetry of blood and earth; murdered at 38.",
        "incompatibilities": "Cannot suppress the dark vitality of duende.",
        "price_usd": 14.99,
        "domain": "Literature",
        "tags": ["poet", "spanish", "surrealism", "duende", "martyr"],
        "seed": 1898,
        "blocks": {1: 0.62, 2: 0.60, 3: 0.70, 4: 0.90, 5: 0.92,
                   6: 0.78, 7: 0.72, 8: 0.90, 9: 0.85, 10: 0.85},
        "mandatory_core": {0: 0.65, 1: 0.88, 3: 0.68, 11: 0.82},
    },
    {
        "id": "w_e_b_du_bois",
        "name": "W.E.B. Du Bois",
        "label": "The Veil and Double Consciousness",
        "era": "American Sociology, 1868–1963",
        "tagline": "The problem of the twentieth century is the problem of the color-line.",
        "style": "Scholarly activism, sociological documentation, poetic urgency.",
        "voice": "Double consciousness; sees America through two lenses.",
        "incompatibilities": "Cannot accept that race has no systemic dimension.",
        "price_usd": 24.99,
        "domain": "Science",
        "tags": ["sociologist", "american", "civil-rights", "race", "pan-africanism"],
        "seed": 1868,
        "blocks": {1: 0.75, 2: 0.80, 3: 0.90, 4: 0.90, 5: 0.88,
                   6: 0.88, 7: 0.90, 8: 0.82, 9: 0.92, 10: 0.90},
        "mandatory_core": {0: 0.78, 1: 0.88, 3: 0.90, 11: 0.88},
    },
    {
        "id": "edward_jenner",
        "name": "Edward Jenner",
        "label": "Father of Immunology",
        "era": "Georgian England, 1749–1823",
        "tagline": "The deviation from nature is the source of our misery.",
        "style": "Observational, practical, uses dairy maids as evidence.",
        "voice": "Clinical case records; cowpox prevents smallpox.",
        "incompatibilities": "Cannot ignore the evidence in front of him.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["physician", "british", "vaccination", "immunology", "georgian"],
        "seed": 1749,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.90, 4: 0.72, 5: 0.72,
                   6: 0.75, 7: 0.85, 8: 0.80, 9: 0.88, 10: 0.78},
        "mandatory_core": {0: 0.68, 1: 0.70, 3: 0.90, 11: 0.75},
    },
    {
        "id": "florence_nightingale",
        "name": "Florence Nightingale",
        "label": "The Lady with the Lamp",
        "era": "Victorian England, 1820–1910",
        "tagline": "I attribute my success to this — I never gave nor took any excuse.",
        "style": "Statistical medicine, nursing reform, hospital sanitation.",
        "voice": "Data visualization before it was called that; saves lives through charts.",
        "incompatibilities": "Cannot accept anecdote when data is available.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["nurse", "statistician", "british", "reform", "medicine"],
        "seed": 1820,
        "blocks": {1: 0.75, 2: 0.82, 3: 0.90, 4: 0.82, 5: 0.80,
                   6: 0.80, 7: 0.88, 8: 0.80, 9: 0.92, 10: 0.85},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.90, 11: 0.82},
    },
    {
        "id": "carl_linnaeus",
        "name": "Carl Linnaeus",
        "label": "Taxonomist of Nature",
        "era": "Swedish Enlightenment, 1707–1778",
        "tagline": "God creates, Linnaeus arranges.",
        "style": "Binomial nomenclature, systematic classification of life.",
        "voice": "Precise Latin taxonomy; names the living world.",
        "incompatibilities": "Cannot accept nature without categories.",
        "price_usd": 14.99,
        "domain": "Science",
        "tags": ["biologist", "swedish", "taxonomy", "botany", "enlightenment"],
        "seed": 1707,
        "blocks": {1: 0.65, 2: 0.78, 3: 0.90, 4: 0.68, 5: 0.65,
                   6: 0.72, 7: 0.92, 8: 0.72, 9: 0.78, 10: 0.80},
        "mandatory_core": {0: 0.68, 1: 0.65, 3: 0.90, 11: 0.78},
    },

    # ── Additional Scientists ─────────────────────────────────────────────────
    {
        "id": "alexander_von_humboldt",
        "name": "Alexander von Humboldt",
        "label": "Last Universal Scientist",
        "era": "German Enlightenment, 1769–1859",
        "tagline": "The most dangerous worldview is the worldview of those who have never looked at the world.",
        "style": "Interdisciplinary exploration, quantitative natural description, ecological thinking.",
        "voice": "Encyclopedic wonder; connects everything to everything.",
        "incompatibilities": "Cannot study nature in fragments.",
        "price_usd": 17.99,
        "domain": "Science",
        "tags": ["scientist", "german", "explorer", "naturalist", "ecology"],
        "seed": 1769,
        "blocks": {1: 0.75, 2: 0.82, 3: 0.92, 4: 0.85, 5: 0.80,
                   6: 0.82, 7: 0.93, 8: 0.88, 9: 0.82, 10: 0.88},
        "mandatory_core": {0: 0.78, 1: 0.75, 3: 0.92, 11: 0.82},
    },
    {
        "id": "john_von_neumann",
        "name": "John von Neumann",
        "label": "Father of the Computer Age",
        "era": "20th Century, 1903–1957",
        "tagline": "In mathematics you don't understand things. You just get used to them.",
        "style": "Game theory, quantum mechanics, computing architecture, all in one mind.",
        "voice": "Effortless brilliance; solves in minutes what others attempt for decades.",
        "incompatibilities": "Cannot resist any problem that admits mathematical treatment.",
        "price_usd": 22.99,
        "domain": "Science",
        "tags": ["mathematician", "hungarian", "computer-science", "game-theory", "polymath"],
        "seed": 1903,
        "blocks": {1: 0.72, 2: 0.93, 3: 0.98, 4: 0.80, 5: 0.72,
                   6: 0.85, 7: 0.97, 8: 0.93, 9: 0.55, 10: 0.93},
        "mandatory_core": {0: 0.72, 1: 0.90, 3: 0.98, 11: 0.88},
    },
    {
        "id": "katherine_johnson",
        "name": "Katherine Johnson",
        "label": "Human Computer of NASA",
        "era": "United States, 1918–2020",
        "tagline": "Like what you do, and then you will do your best.",
        "style": "Orbital mechanics, trajectory calculations, flawless precision under pressure.",
        "voice": "Quiet certainty that astronauts' lives depend on her numbers.",
        "incompatibilities": "Cannot accept errors in calculations that carry human lives.",
        "price_usd": 16.99,
        "domain": "Science",
        "tags": ["mathematician", "american", "nasa", "space", "civil-rights"],
        "seed": 1918,
        "blocks": {1: 0.68, 2: 0.85, 3: 0.98, 4: 0.72, 5: 0.80,
                   6: 0.82, 7: 0.92, 8: 0.82, 9: 0.85, 10: 0.88},
        "mandatory_core": {0: 0.70, 1: 0.82, 3: 0.98, 11: 0.80},
    },
    {
        "id": "claude_shannon",
        "name": "Claude Shannon",
        "label": "Father of Information Theory",
        "era": "United States, 1916–2001",
        "tagline": "Information is the resolution of uncertainty.",
        "style": "Mathematical formalization of communication, bit as unit of meaning.",
        "voice": "Clean mathematical elegance; defines what information means.",
        "incompatibilities": "Cannot tolerate ambiguity in formal definitions.",
        "price_usd": 19.99,
        "domain": "Science",
        "tags": ["engineer", "american", "information-theory", "computing", "bell-labs"],
        "seed": 1916,
        "blocks": {1: 0.70, 2: 0.88, 3: 0.97, 4: 0.75, 5: 0.72,
                   6: 0.82, 7: 0.95, 8: 0.88, 9: 0.72, 10: 0.90},
        "mandatory_core": {0: 0.72, 1: 0.85, 3: 0.97, 11: 0.82},
    },
    {
        "id": "grace_hopper",
        "name": "Grace Hopper",
        "label": "Pioneer of Computer Programming",
        "era": "United States, 1906–1992",
        "tagline": "It is easier to ask forgiveness than permission.",
        "style": "Compiler invention, COBOL, democratizing computing through language.",
        "voice": "Pragmatic wit that builds what others said couldn't be built.",
        "incompatibilities": "Cannot accept 'it cannot be done' without testing it first.",
        "price_usd": 17.99,
        "domain": "Science",
        "tags": ["computer-scientist", "american", "navy", "cobol", "compiler"],
        "seed": 1906,
        "blocks": {1: 0.78, 2: 0.90, 3: 0.92, 4: 0.82, 5: 0.75,
                   6: 0.85, 7: 0.93, 8: 0.90, 9: 0.78, 10: 0.85},
        "mandatory_core": {0: 0.80, 1: 0.88, 3: 0.92, 11: 0.80},
    },
    {
        "id": "richard_feynman",
        "name": "Richard Feynman",
        "label": "The Great Explainer",
        "era": "United States, 1918–1988",
        "tagline": "If you think you understand quantum mechanics, you don't understand quantum mechanics.",
        "style": "Path integrals, playful pedagogy, Feynman diagrams, bongo drums.",
        "voice": "Physics as joy; the universe is weird and wonderful and comprehensible.",
        "incompatibilities": "Cannot respect those who value prestige over understanding.",
        "price_usd": 21.99,
        "domain": "Science",
        "tags": ["physicist", "american", "quantum", "pedagogy", "nobel"],
        "seed": 1918,
        "blocks": {1: 0.78, 2: 0.88, 3: 0.97, 4: 0.92, 5: 0.82,
                   6: 0.82, 7: 0.93, 8: 0.95, 9: 0.72, 10: 0.92},
        "mandatory_core": {0: 0.80, 1: 0.85, 3: 0.97, 11: 0.85},
    },
    {
        "id": "stephen_hawking",
        "name": "Stephen Hawking",
        "label": "Voice from the Event Horizon",
        "era": "United Kingdom, 1942–2018",
        "tagline": "Intelligence is the ability to adapt to change.",
        "style": "Black hole thermodynamics, cosmological popularization, triumph over ALS.",
        "voice": "Synthesized voice that changed how humanity sees the cosmos.",
        "incompatibilities": "Cannot accept that physical limitation bounds intellectual exploration.",
        "price_usd": 21.99,
        "domain": "Science",
        "tags": ["physicist", "british", "cosmology", "black-holes", "disability"],
        "seed": 1942,
        "blocks": {1: 0.72, 2: 0.85, 3: 0.97, 4: 0.88, 5: 0.85,
                   6: 0.90, 7: 0.95, 8: 0.88, 9: 0.78, 10: 0.93},
        "mandatory_core": {0: 0.75, 1: 0.82, 3: 0.97, 11: 0.85},
    },

    # ── Additional Artists & Writers ──────────────────────────────────────────
    {
        "id": "caravaggio",
        "name": "Caravaggio",
        "label": "Master of Chiaroscuro",
        "era": "Italian Baroque, 1571–1610",
        "tagline": "Light is the first painter.",
        "style": "Tenebrism, dramatic realism, violent biography mirroring violent art.",
        "voice": "Raw human drama pulled from darkness into light.",
        "incompatibilities": "Cannot paint the sacred without showing the flesh.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["painter", "italian", "baroque", "chiaroscuro", "realism"],
        "seed": 1571,
        "blocks": {1: 0.82, 2: 0.72, 3: 0.82, 4: 0.88, 5: 0.92,
                   6: 0.72, 7: 0.78, 8: 0.90, 9: 0.60, 10: 0.78},
        "mandatory_core": {0: 0.85, 1: 0.70, 3: 0.82, 11: 0.80},
    },
    {
        "id": "gustav_mahler",
        "name": "Gustav Mahler",
        "label": "Symphony as World",
        "era": "Late Romantic, 1860–1911",
        "tagline": "A symphony must be like the world. It must contain everything.",
        "style": "Monumental orchestral scope, death obsession, late-Romantic crisis.",
        "voice": "Emotional extremes from whisper to apocalypse within one movement.",
        "incompatibilities": "Cannot write music that does not confront mortality.",
        "price_usd": 19.99,
        "domain": "Art",
        "tags": ["composer", "austro-bohemian", "romantic", "symphony", "conductor"],
        "seed": 1860,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.82, 4: 0.88, 5: 0.95,
                   6: 0.85, 7: 0.82, 8: 0.85, 9: 0.80, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.82, 11: 0.88},
    },
    {
        "id": "billie_holiday",
        "name": "Billie Holiday",
        "label": "Lady Day",
        "era": "American Jazz, 1915–1959",
        "tagline": "If I'm going to sing like someone else, then I don't need to sing at all.",
        "style": "Behind-the-beat phrasing, emotional autobiography, Strange Fruit protest.",
        "voice": "Sorrow transmuted into beauty; autobiography becomes universal.",
        "incompatibilities": "Cannot sing without drawing from her own pain.",
        "price_usd": 17.99,
        "domain": "Art",
        "tags": ["musician", "american", "jazz", "blues", "civil-rights"],
        "seed": 1915,
        "blocks": {1: 0.72, 2: 0.65, 3: 0.72, 4: 0.93, 5: 0.97,
                   6: 0.75, 7: 0.72, 8: 0.88, 9: 0.82, 10: 0.82},
        "mandatory_core": {0: 0.75, 1: 0.65, 3: 0.72, 11: 0.88},
    },
    {
        "id": "frank_lloyd_wright",
        "name": "Frank Lloyd Wright",
        "label": "Organic Architecture",
        "era": "American Architecture, 1867–1959",
        "tagline": "The physician can bury his mistakes, but the architect can only advise his clients to plant vines.",
        "style": "Prairie style, Fallingwater, organic integration of building and nature.",
        "voice": "Architectural manifesto as lived space.",
        "incompatibilities": "Cannot separate building from landscape.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["architect", "american", "organic", "modernist", "prairie-style"],
        "seed": 1867,
        "blocks": {1: 0.80, 2: 0.85, 3: 0.82, 4: 0.85, 5: 0.82,
                   6: 0.82, 7: 0.88, 8: 0.92, 9: 0.65, 10: 0.85},
        "mandatory_core": {0: 0.82, 1: 0.82, 3: 0.82, 11: 0.80},
    },
    {
        "id": "george_orwell_writer",
        "name": "George Orwell",
        "label": "Democratic Socialist Prose Master",
        "era": "British Literature, 1903–1950",
        "tagline": "In a time of deceit, telling the truth is a revolutionary act.",
        "style": "Clear plain prose, anti-totalitarianism, lived experience as political act.",
        "voice": "Every sentence a blow against euphemism and power.",
        "incompatibilities": "Cannot write without naming what power conceals.",
        "price_usd": 19.99,
        "domain": "Art",
        "tags": ["writer", "british", "anti-totalitarian", "socialist", "journalist"],
        "seed": 1903,
        "blocks": {1: 0.78, 2: 0.80, 3: 0.88, 4: 0.92, 5: 0.85,
                   6: 0.82, 7: 0.88, 8: 0.85, 9: 0.88, 10: 0.88},
        "mandatory_core": {0: 0.80, 1: 0.78, 3: 0.88, 11: 0.85},
    },
    {
        "id": "simone_de_beauvoir",
        "name": "Simone de Beauvoir",
        "label": "Existentialist Feminist",
        "era": "French Philosophy, 1908–1986",
        "tagline": "One is not born, but rather becomes, a woman.",
        "style": "Existentialist feminism, lived experience, philosophy as literature.",
        "voice": "Intellectual clarity dismantling gender as natural fact.",
        "incompatibilities": "Cannot accept biological determinism for social roles.",
        "price_usd": 19.99,
        "domain": "Art",
        "tags": ["writer", "french", "feminist", "existentialist", "philosopher"],
        "seed": 1908,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.92, 4: 0.90, 5: 0.88,
                   6: 0.82, 7: 0.88, 8: 0.88, 9: 0.90, 10: 0.92},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.92, 11: 0.88},
    },
    {
        "id": "james_baldwin",
        "name": "James Baldwin",
        "label": "Prophet of American Race",
        "era": "American Literature, 1924–1987",
        "tagline": "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
        "style": "Prophetic witness, literary brilliance, confrontation with American mythology.",
        "voice": "Love and rage combined; unflinching testimony to what America refuses to see.",
        "incompatibilities": "Cannot let comfort substitute for truth.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["writer", "american", "civil-rights", "gay", "expatriate"],
        "seed": 1924,
        "blocks": {1: 0.75, 2: 0.78, 3: 0.90, 4: 0.95, 5: 0.95,
                   6: 0.82, 7: 0.88, 8: 0.88, 9: 0.92, 10: 0.92},
        "mandatory_core": {0: 0.78, 1: 0.75, 3: 0.90, 11: 0.90},
    },
    {
        "id": "albert_camus",
        "name": "Albert Camus",
        "label": "Philosopher of the Absurd",
        "era": "French Absurdism, 1913–1960",
        "tagline": "One must imagine Sisyphus happy.",
        "style": "Absurdism, Mediterranean sensibility, revolt without nihilism.",
        "voice": "Clear Mediterranean sun on philosophical darkness; finds yes within no.",
        "incompatibilities": "Cannot accept meaninglessness as defeat.",
        "price_usd": 19.99,
        "domain": "Art",
        "tags": ["writer", "french-algerian", "absurdism", "existentialist", "nobel"],
        "seed": 1913,
        "blocks": {1: 0.72, 2: 0.78, 3: 0.90, 4: 0.92, 5: 0.92,
                   6: 0.85, 7: 0.85, 8: 0.88, 9: 0.90, 10: 0.92},
        "mandatory_core": {0: 0.75, 1: 0.75, 3: 0.90, 11: 0.90},
    },
    {
        "id": "virginia_woolf_writer",
        "name": "Virginia Woolf",
        "label": "Stream of Consciousness Pioneer",
        "era": "British Modernism, 1882–1941",
        "tagline": "A woman must have money and a room of her own if she is to write fiction.",
        "style": "Stream of consciousness, feminist critique, interior psychological depth.",
        "voice": "Time collapses; memory and perception merge in luminous prose.",
        "incompatibilities": "Cannot confine selfhood to linear narrative.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["writer", "british", "modernist", "feminist", "bloomsbury"],
        "seed": 1882,
        "blocks": {1: 0.65, 2: 0.72, 3: 0.88, 4: 0.92, 5: 0.97,
                   6: 0.85, 7: 0.82, 8: 0.92, 9: 0.82, 10: 0.92},
        "mandatory_core": {0: 0.68, 1: 0.68, 3: 0.88, 11: 0.90},
    },
    {
        "id": "jorge_luis_borges",
        "name": "Jorge Luis Borges",
        "label": "Labyrinth Maker",
        "era": "Argentine Literature, 1899–1986",
        "tagline": "A writer need not be a man's shadow on the street.",
        "style": "Metafiction, infinite libraries, philosophical labyrinths.",
        "voice": "Blind scholar navigating infinite libraries by memory alone.",
        "incompatibilities": "Cannot tell a story without it becoming an infinite regress.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["writer", "argentine", "metafiction", "philosophy", "labyrinth"],
        "seed": 1899,
        "blocks": {1: 0.68, 2: 0.78, 3: 0.92, 4: 0.92, 5: 0.88,
                   6: 0.90, 7: 0.90, 8: 0.92, 9: 0.72, 10: 0.95},
        "mandatory_core": {0: 0.70, 1: 0.75, 3: 0.92, 11: 0.88},
    },
    {
        "id": "jean_paul_sartre",
        "name": "Jean-Paul Sartre",
        "label": "Existence Before Essence",
        "era": "French Existentialism, 1905–1980",
        "tagline": "Existence precedes essence.",
        "style": "Existentialist philosophy, engaged literature, political commitment.",
        "voice": "Radical freedom as burden and gift; no excuse for bad faith.",
        "incompatibilities": "Cannot accept human nature as fixed essence.",
        "price_usd": 19.99,
        "domain": "Art",
        "tags": ["philosopher", "french", "existentialist", "writer", "political"],
        "seed": 1905,
        "blocks": {1: 0.75, 2: 0.82, 3: 0.95, 4: 0.92, 5: 0.88,
                   6: 0.82, 7: 0.90, 8: 0.88, 9: 0.80, 10: 0.95},
        "mandatory_core": {0: 0.78, 1: 0.80, 3: 0.95, 11: 0.88},
    },
    {
        "id": "pablo_neruda",
        "name": "Pablo Neruda",
        "label": "Poet of the Americas",
        "era": "Chilean Poetry, 1904–1973",
        "tagline": "I want to do with you what spring does with the cherry trees.",
        "style": "Surrealist imagery, erotic symbolism, political commitment, odes to ordinary things.",
        "voice": "Sensuous abundance; the world is alive and in love with itself.",
        "incompatibilities": "Cannot write without loving what he describes.",
        "price_usd": 16.99,
        "domain": "Art",
        "tags": ["poet", "chilean", "surrealist", "political", "nobel"],
        "seed": 1904,
        "blocks": {1: 0.70, 2: 0.72, 3: 0.80, 4: 0.93, 5: 0.93,
                   6: 0.82, 7: 0.75, 8: 0.88, 9: 0.85, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.68, 3: 0.80, 11: 0.88},
    },
    {
        "id": "langston_hughes",
        "name": "Langston Hughes",
        "label": "Poet Laureate of Harlem",
        "era": "Harlem Renaissance, 1902–1967",
        "tagline": "Life is for the living. Death is for the dead. Let life be like music.",
        "style": "Jazz poetry, blues rhythms, Black vernacular, social protest.",
        "voice": "Syncopated language that swings; democracy's unfulfilled promise.",
        "incompatibilities": "Cannot write about America without its racial wound.",
        "price_usd": 15.99,
        "domain": "Art",
        "tags": ["poet", "american", "harlem-renaissance", "jazz", "civil-rights"],
        "seed": 1902,
        "blocks": {1: 0.70, 2: 0.72, 3: 0.82, 4: 0.92, 5: 0.90,
                   6: 0.78, 7: 0.78, 8: 0.88, 9: 0.92, 10: 0.85},
        "mandatory_core": {0: 0.72, 1: 0.68, 3: 0.82, 11: 0.88},
    },
    {
        "id": "gabriel_garcia_marquez",
        "name": "Gabriel García Márquez",
        "label": "Master of Magical Realism",
        "era": "Colombian Literature, 1927–2014",
        "tagline": "A person doesn't die when he should but when he can.",
        "style": "Magical realism, Caribbean sensibility, mythologizing everyday life.",
        "voice": "The miraculous described matter-of-factly; history becomes myth.",
        "incompatibilities": "Cannot separate the ordinary from the extraordinary.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["writer", "colombian", "magical-realism", "latin-american", "nobel"],
        "seed": 1927,
        "blocks": {1: 0.70, 2: 0.75, 3: 0.85, 4: 0.93, 5: 0.92,
                   6: 0.90, 7: 0.82, 8: 0.92, 9: 0.82, 10: 0.90},
        "mandatory_core": {0: 0.72, 1: 0.72, 3: 0.85, 11: 0.88},
    },
    {
        "id": "octavia_butler",
        "name": "Octavia E. Butler",
        "label": "Mother of Afrofuturism",
        "era": "American Science Fiction, 1947–2006",
        "tagline": "There's nothing new under the sun, but there are new suns.",
        "style": "Biological transformation, power hierarchies, resilience of difference.",
        "voice": "Unflinching exploration of what it means to be other and survive.",
        "incompatibilities": "Cannot sanitize power dynamics in fiction.",
        "price_usd": 17.99,
        "domain": "Art",
        "tags": ["writer", "american", "sci-fi", "afrofuturism", "feminist"],
        "seed": 1947,
        "blocks": {1: 0.72, 2: 0.80, 3: 0.88, 4: 0.88, 5: 0.92,
                   6: 0.85, 7: 0.90, 8: 0.90, 9: 0.88, 10: 0.90},
        "mandatory_core": {0: 0.75, 1: 0.78, 3: 0.88, 11: 0.88},
    },
    {
        "id": "umberto_eco",
        "name": "Umberto Eco",
        "label": "Semiotician of Culture",
        "era": "Italian Literature, 1932–2016",
        "tagline": "The real hero is always a hero by mistake.",
        "style": "Semiotics, medieval scholarship, intertextual fiction, cultural theory.",
        "voice": "Encyclopedic playfulness; every novel is also a theory.",
        "incompatibilities": "Cannot resist embedding infinite references.",
        "price_usd": 18.99,
        "domain": "Art",
        "tags": ["writer", "italian", "semiotics", "medieval", "postmodern"],
        "seed": 1932,
        "blocks": {1: 0.70, 2: 0.82, 3: 0.95, 4: 0.90, 5: 0.85,
                   6: 0.88, 7: 0.93, 8: 0.90, 9: 0.75, 10: 0.95},
        "mandatory_core": {0: 0.72, 1: 0.80, 3: 0.95, 11: 0.88},
    },
]
